<!--
 var comp1 = [
{type:'info',text:'Nodes: 358.0: Density: 0.02'},
{type:'demography',text:'Donald J. Bogue: 0.14'},
{type:'famplan',text:'Ronald Freedman: 0.13'},
{type:'demography',text:'Philip M. Hauser: 0.11'},
{type:'famplan',text:'Joseph D. Beasley: 0.09'},
{type:'demography',text:'Edwin D. Driver: 0.08'},
{type:'pubh',text:'Elliot Liebow: 0.08'},
{type:'pubh',text:'G. Franklin Edwards: 0.08'},
{type:'demography',text:'Mindel C. Sheps: 0.08'},
{type:'demography',text:'Reynolds Farley: 0.08'},
{type:'pubh',text:'Daniel C. Thompson: 0.08'},
{type:'famplan',text:'Charles F. Westoff: 0.07'},
{type:'pubh',text:'James E. Teele: 0.07'},
{type:'demography',text:'Daniel O. Price: 0.07'},
{type:'pubh',text:'Paul C. Glick: 0.07'},
{type:'pubh',text:'Preston Valien: 0.07'},
{type:'famplan',text:'Norman B. Ryder: 0.07'},
{type:'demography',text:'Frank W. Notestein: 0.07'},
{type:'sociology',text:'Karl E. Taeuber: 0.07'},
{type:'pubh',text:'Irene B. Taeuber: 0.07'},
{type:'pubh',text:'J. Mayone Stycos: 0.06'},
{type:'famplan',text:'Arthur A. Campbell: 0.06'},
{type:'pubh',text:'Christopher Tietze: 0.06'},
{type:'famplan',text:'Charles B. Arnold: 0.06'},
{type:'pubh',text:'Jessie S. Bernard: 0.06'},
{type:'pubh',text:'C. V. Willie: 0.06'},
{type:'pubh',text:'M-F. Hall: 0.06'},
{type:'famplan',text:'Robert G. Potter: 0.06'},
{type:'pubh',text:'C. R. Lawrence: 0.05'},
{type:'pubh',text:'A. H. Neiva: 0.05'},
{type:'demography',text:'Everett S. Lee: 0.05'},
{type:'demography',text:'Carmen Miro: 0.05'},
{type:'pubh',text:'Karl A. Smith: 0.05'},
{type:'pubh',text:'W. Parker Mauldin: 0.05'},
{type:'pubh',text:'Paul R. Williams: 0.05'},
{type:'pubh',text:'Joseph S. Himes: 0.05'},
{type:'demography',text:'Carl L. Harter: 0.05'},
{type:'pubh',text:'T. K. Burch: 0.04'},
{type:'pubh',text:'J. Arias: 0.04'},
{type:'demography',text:'John A. Ross: 0.04'},
{type:'pubh',text:'R. O. Carleton: 0.04'},
{type:'general',text:'Frederick S. Jaffe: 0.04'},
{type:'pubh',text:'James A. Jones: 0.04'},
{type:'pubh',text:'Clyde V. Kiser: 0.04'},
{type:'pubh',text:'R. Puffer: 0.04'},
{type:'pubh',text:'F. E. Linder: 0.04'},
{type:'demography',text:'Wilson H. Grabill: 0.03'},
{type:'pubh',text:'G. PéRez: 0.03'},
{type:'pubh',text:'Ferdinand Rath: 0.03'},
{type:'demography',text:'Rowland V. Rider: 0.03'},
{type:'pubh',text:'Harriet B. Presser: 0.03'},
{type:'demography',text:'Tan Boon Ann: 0.03'},
{type:'pubh',text:'D. S. Thomas: 0.03'},
{type:'general',text:'John D. Durand: 0.03'},
{type:'famplan',text:'Allan G. Rosenfield: 0.03'},
{type:'pubh',text:'R. Delgado: 0.03'},
{type:'pubh',text:'F. Rath: 0.03'},
{type:'famplan',text:'George P. Cernada: 0.03'},
{type:'pubh',text:'O. Mendoza: 0.03'},
{type:'demography',text:'T. H. Sun: 0.03'},
{type:'pubh',text:'J. C. Elizaga: 0.03'},
{type:'pubh',text:'Paul B. Cornely: 0.03'},
{type:'famplan',text:'Paul A. Harper: 0.03'},
{type:'famplan',text:'David M. Heer: 0.03'},
{type:'famplan',text:'S. M. Keeny: 0.03'},
{type:'famplan',text:'Ralph F. Frankowski: 0.03'},
{type:'famplan',text:'L. P. Chow: 0.03'},
{type:'famplan',text:'Dae Woo Han: 0.02'},
{type:'demography',text:'T. C. Hsu: 0.02'},
{type:'demography',text:'J. Oscar Alers: 0.02'},
{type:'pubh',text:'P. B. Cornely: 0.02'},
{type:'famplan',text:'Thomas K. Burch: 0.02'},
{type:'general',text:'Judith Blake: 0.02'},
{type:'pubh',text:'Gwendolyn Z. Johnson: 0.02'},
{type:'general',text:'Richard Reynolds: 0.02'},
{type:'famplan',text:'James A. Palmore: 0.02'},
{type:'sociology',text:'Walter B. Watson: 0.02'},
{type:'pubh',text:'M. C. Chang: 0.02'},
{type:'demography',text:'Gavin Jones: 0.02'},
{type:'pubh',text:'Ansley J. Coale: 0.02'},
{type:'pubh',text:'John E. Gordon: 0.02'},
{type:'famplan',text:'Winich Asavasena: 0.02'},
{type:'pubh',text:'Gino Germani: 0.02'},
{type:'demography',text:'Ariffin Bin Marzuki: 0.02'},
{type:'demography',text:'Lolagene C. Coombs: 0.02'},
{type:'pubh',text:'John B. Wyon: 0.02'},
{type:'famplan',text:'Joy G. Dryfoos: 0.02'},
{type:'famplan',text:'Miriam OrdoñEz: 0.02'},
{type:'pubh',text:'William M. Schmidt: 0.02'},
{type:'pubh',text:'Carlos Ferrero: 0.02'},
{type:'demography',text:'Sook Bang: 0.02'},
{type:'pubh',text:'Rubens M. Marques: 0.02'},
{type:'famplan',text:'Gustavo Perez: 0.02'},
{type:'famplan',text:'Gail A. Shea: 0.02'},
{type:'famplan',text:'Joseph Van Kemanade: 0.02'},
{type:'famplan',text:'Jan Hutjes: 0.02'},
{type:'pubh',text:'Elza S. Berquo: 0.02'},
{type:'pubh',text:'Tegualda Monreal: 0.02'},
{type:'pubh',text:'Eunice Pinho: 0.02'},
{type:'pubh',text:'Jose S. Martins: 0.02'},
{type:'pubh',text:'Imre Simon: 0.02'},
{type:'famplan',text:'Andre E. Hellegers: 0.02'},
{type:'demography',text:'John Y. Takeshita: 0.02'},
{type:'famplan',text:'J. Gilbert Hardee: 0.02'},
{type:'pubh',text:'Maria L. Milanesi: 0.02'},
{type:'demography',text:'Murray Gendell: 0.02'},
{type:'famplan',text:'J. Y. Peng: 0.02'},
{type:'famplan',text:'Somsak Varakamin: 0.01'},
{type:'demography',text:'Alvaro Lopez: 0.01'},
{type:'general',text:'Dudley Kirk: 0.01'},
{type:'demography',text:'Oscar Harkavy: 0.01'},
{type:'famplan',text:'John Knodel: 0.01'},
{type:'general',text:'Lewis C. Frank Jr.: 0.01'},
{type:'pubh',text:'Rolando Armijo: 0.01'},
{type:'famplan',text:'A. Rasheed Ghazi: 0.01'},
{type:'pubh',text:'Louis J. Ducoff: 0.01'},
{type:'pubh',text:'John Crawford: 0.01'},
{type:'pubh',text:'L. Baumgartner: 0.01'},
{type:'pubh',text:'Dorothy Myer: 0.01'},
{type:'pubh',text:'Elisabeth Schach: 0.01'},
{type:'general',text:'Willard Johnson: 0.01'},
{type:'famplan',text:'Chitt Hemachudha: 0.01'},
{type:'pubh',text:'Robert H. Weller: 0.01'},
{type:'pubh',text:'Alan Ross: 0.01'},
{type:'famplan',text:'John C. Cobb: 0.01'},
{type:'demography',text:'G. S. Masnick: 0.01'},
{type:'famplan',text:'Shamsuddin Bin Abdul Rahman: 0.01'},
{type:'demography',text:'Harry M. Raulet: 0.01'},
{type:'pubh',text:'Anrudh K. Jain: 0.01'},
{type:'famplan',text:'Paul White: 0.01'},
{type:'pubh',text:'David L. Rabin: 0.01'},
{type:'pubh',text:'CéSar PeláEz: 0.01'},
{type:'pubh',text:'B. Mariano Requena: 0.01'},
{type:'famplan',text:'Daniel R. Weintraub: 0.01'},
{type:'general',text:'Ruth Barnhouse-Beuscher: 0.01'},
{type:'famplan',text:'George Worth: 0.01'},
{type:'general',text:'Myrna M. Weissman: 0.01'},
{type:'pubh',text:'Leslie Corsa Jr.: 0.01'},
{type:'pubh',text:'A. Peter Ruderman: 0.01'},
{type:'famplan',text:'Chaichana Suvanavejh: 0.01'},
{type:'pubh',text:'H. Jack Geiger: 0.01'},
{type:'sociology',text:'Albert I. Hermalin: 0.01'},
{type:'famplan',text:'Roger Avery: 0.01'},
{type:'demography',text:'Habib R. Siddiqui: 0.01'},
{type:'pubh',text:'M. Requena B.: 0.01'},
{type:'famplan',text:'Carita Jo Bernsohn: 0.01'},
{type:'demography',text:'Ronald Rindfuss: 0.01'},
{type:'general',text:'Larry Bumpass: 0.01'},
{type:'famplan',text:'Paul Demeny: 0.01'},
{type:'demography',text:'Samuel B. Hopkins: 0.01'},
{type:'pubh',text:'Frank Lorimer: 0.01'},
{type:'pubh',text:'John J. Macisco Jr.: 0.01'},
{type:'pubh',text:'Salvador Diaz: 0.01'},
{type:'famplan',text:'Jean P. Cobb: 0.01'},
{type:'pubh',text:'Reginaldo Zaccara De Campos: 0.01'},
{type:'demography',text:'Donald W. Helbig: 0.01'},
{type:'demography',text:'Stephen L. Finner: 0.01'},
{type:'demography',text:'Omer R. Galle: 0.01'},
{type:'famplan',text:'Yusof Bakar: 0.01'},
{type:'economics',text:'Dorothy Nortman: 0.01'},
{type:'general',text:'Lien-Ping Chow: 0.01'},
{type:'famplan',text:'Loh Sow Khin: 0.01'},
{type:'famplan',text:'O. D. Finnigan: 0.01'},
{type:'economics',text:'Etienne Van De Walle: 0.01'},
{type:'demography',text:'Nadipuram R. Parthasarathy: 0.01'},
{type:'pubh',text:'Jane A. Menken: 0.01'},
{type:'demography',text:'Lyle Saunders: 0.01'},
{type:'famplan',text:'M. Subbiah: 0.01'},
{type:'demography',text:'Kingsley Davis: 0.01'},
{type:'general',text:'Edith Fein: 0.01'},
{type:'pubh',text:'Mary L. New: 0.01'},
{type:'demography',text:'Sarah Lewit: 0.01'},
{type:'demography',text:'Visid Prachuabmoh: 0.01'},
{type:'famplan',text:'Ann R. Sauls: 0.01'},
{type:'famplan',text:'Oliver D. Finnigan Iii: 0.01'},
{type:'demography',text:'Raymond W. Carlaw: 0.01'},
{type:'famplan',text:'Patricia G. Steinhoff: 0.01'},
{type:'demography',text:'Myung Ho Kim: 0.01'},
{type:'famplan',text:'Hew Wai Sin: 0.01'},
{type:'famplan',text:'Alvaro Cuadros: 0.01'},
{type:'famplan',text:'George C. Worth: 0.01'},
{type:'famplan',text:'Lee-Jay Cho: 0.01'},
{type:'pubh',text:'Leon F. Bouvier: 0.01'},
{type:'pubh',text:'C. V. Kiser: 0.01'},
{type:'pubh',text:'A. Lopez: 0.01'},
{type:'famplan',text:'Phyllis Coghlan: 0.01'},
{type:'demography',text:'Jae Mo Yang: 0.01'},
{type:'pubh',text:'R. Armijo: 0.01'},
{type:'demography',text:'Lawrence W. Green: 0.01'},
{type:'general',text:'Edgar R. Chasteen: 0.01'},
{type:'demography',text:'P. Vela: 0.01'},
{type:'famplan',text:'Ming-Cheng Chang: 0.01'},
{type:'famplan',text:'Roger Rochat: 0.01'},
{type:'famplan',text:'Alan Margolis: 0.01'},
{type:'demography',text:'Jae-Mo Yang: 0.01'},
{type:'demography',text:'Doris P. Slesinger: 0.01'},
{type:'demography',text:'A. Perez: 0.01'},
{type:'demography',text:'A. Adlakha: 0.01'},
{type:'pubh',text:'M-FrançOise Hall: 0.01'},
{type:'demography',text:'Helen Abbey: 0.01'},
{type:'general',text:'Judith S. Weis: 0.01'},
{type:'famplan',text:'S.M. Keeny: 0.01'},
{type:'famplan',text:'Te-Hsiung Sun: 0.01'},
{type:'sociology',text:'Judith Friedman: 0.01'},
{type:'demography',text:'K. C. Chan: 0.01'},
{type:'pubh',text:'Lien-Pin Chow: 0.01'},
{type:'sociology',text:'Otis Dudley Duncan: 0.01'},
{type:'famplan',text:'Silvia Pedraza: 0.01'},
{type:'demography',text:'J. Michael Coble: 0.01'},
{type:'demography',text:'Robert O. Carleton: 0.01'},
{type:'famplan',text:'Millard B. Bethel: 0.01'},
{type:'demography',text:'Mo-Im Kim: 0.01'},
{type:'famplan',text:'Roy G. Smith: 0.01'},
{type:'pubh',text:'F. Osborn: 0.01'},
{type:'demography',text:'N. I. Khan: 0.01'},
{type:'famplan',text:'Linda Atkinson: 0.01'},
{type:'demography',text:'D. N. Namboothiri: 0.01'},
{type:'famplan',text:'Robert Castadot: 0.01'},
{type:'famplan',text:'Kyung Shik Chang: 0.01'},
{type:'demography',text:'Man Gap Lee: 0.01'},
{type:'famplan',text:'Milton Diamond: 0.01'},
{type:'famplan',text:'Peter H. Michael: 0.01'},
{type:'sociology',text:'William F. Pratt: 0.01'},
{type:'demography',text:'Margaret Parker: 0.01'},
{type:'pubh',text:'Vasilios Valaoras: 0.01'},
{type:'famplan',text:'F. L. Chen: 0.01'},
{type:'pubh',text:'Jeanne Clare Ridley: 0.01'},
{type:'pubh',text:'Joan W. Lingner: 0.01'},
{type:'famplan',text:'Sylvain Fribourg: 0.01'},
{type:'pubh',text:'Dorothy G. Wiehl: 0.01'},
{type:'demography',text:'Jorge L. Somoza: 0.01'},
{type:'demography',text:'Juan C. Elizaga: 0.01'},
{type:'sociology',text:'Larry L. Bumpass: 0.01'},
{type:'famplan',text:'Lois M. Verbrugge: 0.01'},
{type:'sociology',text:'Walter Gove: 0.01'},
{type:'pubh',text:'T. H. Liu: 0.01'},
{type:'famplan',text:'George Cernada: 0.01'},
{type:'pubh',text:'Steven Polgar: 0.01'},
{type:'demography',text:'Paul Gingrich: 0.01'},
{type:'demography',text:'J. M. Sakoda: 0.01'},
{type:'famplan',text:'Frank F. Furstenberg Jr.: 0.01'},
{type:'famplan',text:'Susan A. Ricketts: 0.01'},
{type:'demography',text:'B. Mccann: 0.01'},
{type:'pubh',text:'H. William Mooney: 0.01'},
{type:'history',text:'Edward Shorter: 0.01'},
{type:'demography',text:'Philip C. Kreitner: 0.01'},
{type:'general',text:'Samuel M. Wishik: 0.01'},
{type:'pubh',text:'Barbara Mc Cann: 0.01'},
{type:'pubh',text:'James M. Sakoda: 0.01'},
{type:'famplan',text:'Tae Ryong Kim: 0.01'},
{type:'famplan',text:'Sang Whan Song: 0.01'},
{type:'demography',text:'Annette P. Radick: 0.01'},
{type:'demography',text:'Peng-Tu Liu: 0.01'},
{type:'pubh',text:'Emily C. Moore: 0.01'},
{type:'demography',text:'Maria Nydia Maraviglia: 0.01'},
{type:'demography',text:'G. Stephan Masnick: 0.01'},
{type:'sociology',text:'Lolagene Coombs: 0.01'},
{type:'famplan',text:'Ming-Chen Chang: 0.01'},
{type:'demography',text:'George R. Martine: 0.01'},
{type:'demography',text:'David Goldberg: 0.01'},
{type:'demography',text:'Enver Adil: 0.01'},
{type:'demography',text:'Ann Fischer: 0.01'},
{type:'pubh',text:'C. Morton Hawkins: 0.01'},
{type:'demography',text:'Halliman H. Winsborough: 0.01'},
{type:'demography',text:'P. S. K. Chi: 0.01'},
{type:'famplan',text:'Frederick F. Stephen: 0.01'},
{type:'sociology',text:'Douglas Carnahan: 0.01'},
{type:'demography',text:'Oliver D. Finnigan: 0.01'},
{type:'demography',text:'Robert J. Lapham: 0.01'},
{type:'demography',text:'Arthur J. Norton: 0.01'},
{type:'famplan',text:'Sidney H. Newman: 0.01'},
{type:'demography',text:'D. Narayanan Namboothiri: 0.01'},
{type:'pubh',text:'Martha Jane Renzi: 0.01'},
{type:'demography',text:'Leslie Corsa: 0.01'},
{type:'famplan',text:'Nafis Sadik: 0.01'},
{type:'demography',text:'J. Timothy Johnson: 0.01'},
{type:'demography',text:'Raymond H. Potvin: 0.01'},
{type:'demography',text:'Anna L. Southam: 0.01'},
{type:'pubh',text:'Beatrice R. Pollack: 0.01'},
{type:'demography',text:'Sarah Hobbs: 0.01'},
{type:'famplan',text:'Mildred B. Beck: 0.01'},
{type:'demography',text:'A. K. Jain: 0.01'},
{type:'famplan',text:'David P. Smith: 0.01'},
{type:'famplan',text:'James A. Sweet: 0.01'},
{type:'famplan',text:'Chi Hoon Choi: 0.01'},
{type:'demography',text:'Walter Mertens: 0.01'},
{type:'famplan',text:'Jumroon Mikhanorn: 0.01'},
{type:'famplan',text:'Marsha Corey: 0.01'},
{type:'famplan',text:'Chi I-Cheng: 0.01'},
{type:'sociology',text:'Robert E. Klein: 0.01'},
{type:'demography',text:'Paul M. Hirsch: 0.01'},
{type:'famplan',text:'George Varky: 0.01'},
{type:'demography',text:'H. Majumdar: 0.0'},
{type:'pubh',text:'Jose Donayre: 0.0'},
{type:'demography',text:'Maria Davidson: 0.0'},
{type:'famplan',text:'Sasichan Vimuktanon: 0.0'},
{type:'demography',text:'Max W. Williams: 0.0'},
{type:'demography',text:'Prithwis Das Gupta: 0.0'},
{type:'pubh',text:'Alberto Gonzalez-Quiroga: 0.0'},
{type:'demography',text:'Man Jun Hahm: 0.0'},
{type:'famplan',text:'John Maier: 0.0'},
{type:'demography',text:'Hugh Loebner: 0.0'},
{type:'demography',text:'Hilary Page: 0.0'},
{type:'famplan',text:'Walter Watson: 0.0'},
{type:'demography',text:'Allan G. Feldt: 0.0'},
{type:'demography',text:'Amos H. Hawley: 0.0'},
{type:'general',text:'Ronald R. Rindfuss: 0.0'},
{type:'pubh',text:'Farida K. Shah: 0.0'},
{type:'demography',text:'Dean O. Smith: 0.0'},
{type:'pubh',text:'Jorge Somoza: 0.0'},
{type:'famplan',text:'Susan B. Wald: 0.0'},
{type:'demography',text:'Sarah Betsy Cohen: 0.0'},
{type:'demography',text:'Hugh Carter: 0.0'},
{type:'demography',text:'Robert O. Grymes: 0.0'},
{type:'famplan',text:'Ten Love: 0.0'},
{type:'sociology',text:'Ernest A. T. Barth: 0.0'},
{type:'famplan',text:'Charlotte F. Muller: 0.0'},
{type:'demography',text:'Arjun L. Adlakha: 0.0'},
{type:'demography',text:'Norfleet W. Rives Jr.: 0.0'},
{type:'pubh',text:'Myrna E. Frank: 0.0'},
{type:'demography',text:'Robert Parke Jr.: 0.0'},
{type:'demography',text:'Vestal W. Parrish Jr.: 0.0'},
{type:'pubh',text:'Mariano Requena: 0.0'},
{type:'famplan',text:'Peter J. Donaldson: 0.0'},
{type:'famplan',text:'Pichit Pitaktepsombati: 0.0'},
{type:'pubh',text:'Eduardo E. Arriaga: 0.0'},
{type:'pubh',text:'Hernan Mendoza-Hoyos: 0.0'},
{type:'famplan',text:'Sarah Lewitt: 0.0'},
{type:'demography',text:'Judith G. Bryden: 0.0'},
{type:'sociology',text:'Parker G. Marden: 0.0'},
{type:'demography',text:'Joanna Muller: 0.0'},
{type:'statistics',text:'D. R. Mcneil: 0.0'},
{type:'famplan',text:'Gerald Zatuchni: 0.0'},
{type:'demography',text:'Louise Kantrow: 0.0'},
{type:'demography',text:'Arjun Adlakha: 0.0'},
{type:'demography',text:'Virginia A. Hiday: 0.0'},
{type:'pubh',text:'Janice Roussel: 0.0'},
{type:'demography',text:'P. T. Liu: 0.0'},
{type:'famplan',text:'Steven Sieverts: 0.0'},
{type:'eugenics',text:'Evelyn M. Kitagawa: 0.0'},
{type:'demography',text:'Elsa S. Turner: 0.0'},
{type:'demography',text:'David A. May: 0.0'},
{type:'famplan',text:'John P. Wells: 0.0'},
{type:'famplan',text:'Howard C. Taylor: 0.0'},
{type:'demography',text:'Jean Van Der Tak: 0.0'},
{type:'demography',text:'Lee Jay Cho: 0.0'},
{type:'famplan',text:'Evelyne Lapierre-Adamcyk: 0.0'},
{type:'demography',text:'Walt Saveland: 0.0'},
{type:'demography',text:'Alma F. Taeuber: 0.0'},
{type:'demography',text:'T. Paul Schultz: 0.0'},
{type:'famplan',text:'Tessie Huang: 0.0'},
{type:'eugenics',text:'Edward B. Perrin: 0.0'},
{type:'demography',text:'Thomas P. Monahan: 0.0'},
{type:'pubh',text:'Frederick W. Osborn: 0.0'},
{type:'demography',text:'George S. Masnick: 0.0'},
{type:'famplan',text:'Gavin W. Jones: 0.0'},
{type:'famplan',text:'Laura P. Lu: 0.0'},
{type:'demography',text:'Bernard Berelson: 0.0'},
{type:'famplan',text:'N. Iskandar: 0.0'}
];
var comps = [
{type:'info',text:'Nodes: 13.0: Density: 0.38'},
{type:'demography',text:'John F. Kantner: 0.75'},
{type:'demography',text:'Merlin B. Brinkerhoff: 0.58'},
{type:'demography',text:'Clark E. Vincent: 0.5'},
{type:'demography',text:'C. Allen Haney: 0.5'},
{type:'demography',text:'Carl M. Cochrane: 0.5'},
{type:'demography',text:'Melvin Zelnik: 0.5'},
{type:'demography',text:'Philip R. Kunz: 0.5'},
{type:'demography',text:'Phillip R. Kunz: 0.25'},
{type:'demography',text:'T. R. Balakrishnan: 0.25'},
{type:'demography',text:'Evan T. Peterson: 0.17'},
{type:'demography',text:'Brian L. Pitcher: 0.17'},
{type:'demography',text:'J. D. Allingham: 0.17'},
{type:'demography',text:'John D. Allingham: 0.17'},
{type:'info',text:'Nodes: 10.0: Density: 0.42'},
{type:'pubh',text:'J. Richard Udry: 1.0'},
{type:'pubh',text:'Robert G. Burnight: 0.44'},
{type:'general',text:'Donald O. Cowgill: 0.44'},
{type:'pubh',text:'Srisomang Keovichit: 0.44'},
{type:'pubh',text:'Charas Yamarat: 0.44'},
{type:'demography',text:'Charles L. Chase: 0.44'},
{type:'famplan',text:'Lydia T. Clark: 0.33'},
{type:'famplan',text:'Marvin Levy: 0.33'},
{type:'demography',text:'Karl E. Bauman: 0.22'},
{type:'demography',text:'Fred W. Reed: 0.11'},
{type:'info',text:'Nodes: 5.0: Density: 0.5'},
{type:'demography',text:'G. Edward Ebanks: 0.75'},
{type:'sociology',text:'Charles E. Nobbe: 0.75'},
{type:'demography',text:'P. M. George: 0.5'},
{type:'demography',text:'Carl F. Grindstaff: 0.25'},
{type:'sociology',text:'Calvin F. Schmid: 0.25'},
{type:'info',text:'Nodes: 5.0: Density: 0.4'},
{type:'sociology',text:'Calvin Goldscheider: 0.75'},
{type:'pubh',text:'Sidney Goldstein: 0.5'},
{type:'demography',text:'Peter R. Uhlenberg: 0.25'},
{type:'demography',text:'Kurt B. Mayer: 0.25'},
{type:'demography',text:'Basil G. Zimmer: 0.25'},
{type:'info',text:'Nodes: 5.0: Density: 0.5'},
{type:'statistics',text:'Nathan Keyfitz: 0.75'},
{type:'statistics',text:'Dhruva Nagnur: 0.5'},
{type:'statistics',text:'Divakar Sharma: 0.5'},
{type:'eugenics',text:'Edmund M. Murphy: 0.5'},
{type:'demography',text:'Dhruva N. Nagnur: 0.25'},
{type:'info',text:'Nodes: 3.0: Density: 0.67'},
{type:'demography',text:'Donald S. Akers: 1.0'},
{type:'demography',text:'Ellen Linna Jamison: 0.5'},
{type:'demography',text:'Jacob S. Siegel: 0.5'},
{type:'info',text:'Nodes: 3.0: Density: 0.67'},
{type:'sociology',text:'Charles B. Nam: 1.0'},
{type:'sociology',text:'Henry S. Shryock Jr.: 0.5'},
{type:'famplan',text:'Susan O. Gustavus: 0.5'},
{type:'info',text:'Nodes: 3.0: Density: 0.67'},
{type:'demography',text:'Verne E. Nelson: 1.0'},
{type:'statistics',text:'Samuel H. Preston: 0.5'},
{type:'demography',text:'Robert Schoen: 0.5'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'sociology',text:'Judah Matras: 1.0'},
{type:'demography',text:'Charles Hirschman: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'economics',text:'Joseph J. Spengler: 1.0'},
{type:'history',text:'Richard Sutch: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'sociology',text:'C. Horace Hamilton: 1.0'},
{type:'sociology',text:'Elizabeth M. Suval: 1.0'},
{type:'info',text:'Unconnected:'},
{type:'general',text:'Conrad Taeuber'},
{type:'demography',text:'George J. Stolnitz'},
{type:'demography',text:'Ronald Lee'},
{type:'famplan',text:'Garrett Hardin'}
];
var authors = 415;
 var density = 0.01;
 var components = 12;
-->