<!--
 var comp1 = [
{type:'info',text:'Nodes: 1567.0: Density: 0.0'},
{type:'famplan',text:'Charlotte Ellertson: 0.02'},
{type:'general',text:'Beverly Winikoff: 0.02'},
{type:'general',text:'James W. Vaupel: 0.02'},
{type:'demography',text:'Robert J. Magnani: 0.02'},
{type:'famplan',text:'John S. Santelli: 0.01'},
{type:'sociology',text:'Douglas S. Massey: 0.01'},
{type:'famplan',text:'Susheela Singh: 0.01'},
{type:'sociology',text:'Ronald R. Rindfuss: 0.01'},
{type:'sociology',text:'Robert A. Hummer: 0.01'},
{type:'sociology',text:'S. Philip Morgan: 0.01'},
{type:'famplan',text:'Karen Hardee: 0.01'},
{type:'general',text:'Kaare Christensen: 0.01'},
{type:'famplan',text:'John Knodel: 0.01'},
{type:'sociology',text:'W. Parker Frisbie: 0.01'},
{type:'economics',text:'David K. Guilkey: 0.01'},
{type:'famplan',text:'Xiao Bilian: 0.01'},
{type:'demography',text:'Barkat-E-Khuda: 0.01'},
{type:'general',text:'Kenneth G. Manton: 0.01'},
{type:'demography',text:'James F. Phillips: 0.01'},
{type:'famplan',text:'Heidi Jones: 0.01'},
{type:'general',text:'James R. Carey: 0.01'},
{type:'famplan',text:'Jacqueline E. Darroch: 0.01'},
{type:'famplan',text:'Margarita Diaz: 0.01'},
{type:'general',text:'Pablo Liedo: 0.01'},
{type:'famplan',text:'Ruth Simmons: 0.01'},
{type:'famplan',text:'Frank F. Furstenberg Jr.: 0.01'},
{type:'general',text:'Yi Zeng: 0.01'},
{type:'demography',text:'Hans-Peter Kohler: 0.01'},
{type:'famplan',text:'Juan Diaz: 0.01'},
{type:'famplan',text:'Stanley K. Henshaw: 0.01'},
{type:'general',text:'Wolfgang Lutz: 0.01'},
{type:'demography',text:'Anatoli I. Yashin: 0.01'},
{type:'demography',text:'Alexia Prskawetz: 0.01'},
{type:'famplan',text:'Elizabeth Armstrong: 0.01'},
{type:'sociology',text:'Irma T. Elo: 0.01'},
{type:'demography',text:'Frans Van Poppel: 0.01'},
{type:'demography',text:'John R. Logan: 0.01'},
{type:'famplan',text:'Evert Ketting: 0.01'},
{type:'demography',text:'Ian Diamond: 0.01'},
{type:'sociology',text:'Michael S. Rendall: 0.01'},
{type:'famplan',text:'Leo Morris: 0.01'},
{type:'general',text:'James W. Curtsinger: 0.01'},
{type:'famplan',text:'Jane T. Bertrand: 0.01'},
{type:'demography',text:'Michael A. Koenig: 0.01'},
{type:'demography',text:'Barbara S. Mensch: 0.01'},
{type:'general',text:'Ivan A. Iachine: 0.01'},
{type:'famplan',text:'Do Trong Hieu: 0.01'},
{type:'general',text:'Thomas E. Johnson: 0.01'},
{type:'famplan',text:'Irving Sivin: 0.01'},
{type:'demography',text:'Linda G. Martin: 0.01'},
{type:'general',text:'Aziz A. Khazaeli: 0.01'},
{type:'general',text:'Valter D. Longo: 0.01'},
{type:'general',text:'Leonid A. Gavrilov: 0.01'},
{type:'general',text:'Natalia S. Gavrilova: 0.01'},
{type:'general',text:'VäInö Kannisto: 0.01'},
{type:'demography',text:'Shelley Clark: 0.01'},
{type:'famplan',text:'Barbara Entwisle: 0.01'},
{type:'general',text:'Niels V. Holm: 0.01'},
{type:'sociology',text:'Richard G. Rogers: 0.01'},
{type:'sociology',text:'William G. Axinn: 0.01'},
{type:'eugenics',text:'Noreen Goldman: 0.01'},
{type:'famplan',text:'Barbara Janowitz: 0.01'},
{type:'demography',text:'John A. Ross: 0.01'},
{type:'economics',text:'Michael J. White: 0.01'},
{type:'eugenics',text:'Alberto Palloni: 0.01'},
{type:'famplan',text:'Ilene S. Speizer: 0.01'},
{type:'history',text:'Aart C. Liefbroer: 0.01'},
{type:'demography',text:'Robert F. Schoeni: 0.01'},
{type:'demography',text:'James Lubitz: 0.01'},
{type:'sociology',text:'Thomas J. Espenshade: 0.01'},
{type:'famplan',text:'V. T. Palan: 0.01'},
{type:'demography',text:'Kenneth Land: 0.01'},
{type:'general',text:'S. Jay Olshansky: 0.01'},
{type:'demography',text:'Kenneth Manton: 0.01'},
{type:'demography',text:'Diane Shinberg: 0.01'},
{type:'famplan',text:'Grace Delano: 0.01'},
{type:'demography',text:'Richard D. Alba: 0.01'},
{type:'demography',text:'Hakan Aykan: 0.01'},
{type:'famplan',text:'Anna Glasier: 0.01'},
{type:'demography',text:'Timothy Waidmann: 0.01'},
{type:'famplan',text:'Susheel Kaur: 0.01'},
{type:'demography',text:'Stan Becker: 0.01'},
{type:'demography',text:'Ellen Kramarow: 0.01'},
{type:'demography',text:'Brenda C. Spillman: 0.01'},
{type:'famplan',text:'Lesley Browne: 0.01'},
{type:'famplan',text:'L. Vasquez Estrada: 0.01'},
{type:'famplan',text:'Grace Faoye: 0.01'},
{type:'famplan',text:'Susan Cotts Watkins: 0.01'},
{type:'demography',text:'Eileen Crimmins: 0.01'},
{type:'famplan',text:'Josue Garza-Flores: 0.01'},
{type:'sociology',text:'Lingxin Hao: 0.01'},
{type:'demography',text:'Vaughn Call: 0.01'},
{type:'demography',text:'Vicki A. Freedman: 0.01'},
{type:'demography',text:'Zeng Yi: 0.01'},
{type:'famplan',text:'Fiona Steele: 0.01'},
{type:'demography',text:'Lori M. Hunter: 0.01'},
{type:'famplan',text:'Ulla Larsen: 0.01'},
{type:'demography',text:'Haishan Fu: 0.01'},
{type:'famplan',text:'Laurie Schwab Zabin: 0.01'},
{type:'demography',text:'Irwin Garfinkel: 0.01'},
{type:'sociology',text:'Robert Schoen: 0.01'},
{type:'demography',text:'J. Edward Taylor: 0.01'},
{type:'famplan',text:'John B. Casterline: 0.01'},
{type:'demography',text:'David Serwadda: 0.01'},
{type:'demography',text:'Maria J. Wawer: 0.01'},
{type:'famplan',text:'Patricia Akweongo: 0.01'},
{type:'general',text:'Bruce A. Carnes: 0.01'},
{type:'sociology',text:'Nancy S. Landale: 0.01'},
{type:'famplan',text:'Elizabeth Frankenberg: 0.01'},
{type:'sociology',text:'Dennis P. Hogan: 0.01'},
{type:'demography',text:'Bruce Caldwell: 0.01'},
{type:'sociology',text:'Kenneth C. Land: 0.01'},
{type:'demography',text:'Thomas Lutalo: 0.01'},
{type:'sociology',text:'Susan E. Short: 0.01'},
{type:'famplan',text:'Du Ming-Kun: 0.01'},
{type:'famplan',text:'Dale Huntington: 0.01'},
{type:'famplan',text:'Usha R. Krishna: 0.01'},
{type:'demography',text:'David Bishai: 0.01'},
{type:'famplan',text:'Gu Sujuan: 0.01'},
{type:'famplan',text:'Evelio Cabezas: 0.01'},
{type:'demography',text:'Sara R. Curran: 0.01'},
{type:'general',text:'Sergei Scherbov: 0.01'},
{type:'famplan',text:'Naomi Rutenberg: 0.01'},
{type:'famplan',text:'Kurus J. Coyaji: 0.01'},
{type:'demography',text:'Laura Duberstein Lindberg: 0.01'},
{type:'famplan',text:'Pierre Ngom: 0.01'},
{type:'famplan',text:'Christopher Elias: 0.01'},
{type:'famplan',text:'Fariyal F. Fikree: 0.01'},
{type:'demography',text:'Ann E. Biddlecom: 0.01'},
{type:'sociology',text:'Frank D. Bean: 0.01'},
{type:'famplan',text:'T. K. Roy: 0.01'},
{type:'demography',text:'H. Gilman Mccann: 0.01'},
{type:'famplan',text:'Andrea Eschen: 0.01'},
{type:'famplan',text:'Elizabeth F. Jackson: 0.01'},
{type:'famplan',text:'Dawn M. Upchurch: 0.01'},
{type:'general',text:'John R. Wilmoth: 0.01'},
{type:'demography',text:'Mary Arends-Kuenning: 0.01'},
{type:'sociology',text:'Kathleen Mullan Harris: 0.01'},
{type:'sociology',text:'Samuel H. Preston: 0.01'},
{type:'sociology',text:'Sara S. Mclanahan: 0.01'},
{type:'demography',text:'Jeffrey A. Burr: 0.01'},
{type:'famplan',text:'Nguyen Thi Nhu Ngoc: 0.01'},
{type:'famplan',text:'Albert I. Hermalin: 0.01'},
{type:'economics',text:'Ronald Lee: 0.01'},
{type:'demography',text:'Alan Booth: 0.01'},
{type:'famplan',text:'Aurora E. Perez: 0.01'},
{type:'demography',text:'Jennifer Van Hook: 0.01'},
{type:'famplan',text:'Sajeda Amin: 0.01'},
{type:'general',text:'Stephen J. Walsh: 0.01'},
{type:'demography',text:'James P. Smith: 0.01'},
{type:'eugenics',text:'Natalia N. Evdokushkina: 0.01'},
{type:'demography',text:'Thomas A. Mroz: 0.01'},
{type:'famplan',text:'John C. Caldwell: 0.01'},
{type:'sociology',text:'Starling G. Pullum: 0.01'},
{type:'eugenics',text:'Vyacheslav N. Kroutko: 0.01'},
{type:'eugenics',text:'Anna L. Gavrilova: 0.01'},
{type:'geography',text:'Graeme Hugo: 0.01'},
{type:'demography',text:'Yu Xie: 0.01'},
{type:'eugenics',text:'Ayaga Agula Bawah: 0.01'},
{type:'famplan',text:'David Hubacher: 0.01'},
{type:'eugenics',text:'Cornelius Debpuur: 0.01'},
{type:'eugenics',text:'Yulia E. Kushnareva: 0.01'},
{type:'eugenics',text:'Galina N. Evdokushkina: 0.01'},
{type:'demography',text:'Myron P. Gutmann: 0.01'},
{type:'eugenics',text:'Victoria G. Semyonova: 0.01'},
{type:'famplan',text:'F. Nii-Amoo Dodoo: 0.01'},
{type:'famplan',text:'Leighton Ku: 0.01'},
{type:'sociology',text:'Linda J. Waite: 0.01'},
{type:'famplan',text:'Freya L. Sonenstein: 0.01'},
{type:'demography',text:'James Trussell: 0.01'},
{type:'eugenics',text:'Alexander Yu. Andreyev: 0.01'},
{type:'famplan',text:'Kenneth Hill: 0.01'},
{type:'demography',text:'Gordon F. De Jong: 0.01'},
{type:'demography',text:'Annabel S. Erulkar: 0.01'},
{type:'eugenics',text:'Maxine Weinstein: 0.01'},
{type:'famplan',text:'Dianne F. Harrison: 0.0'},
{type:'demography',text:'Charles F. Westoff: 0.0'},
{type:'famplan',text:'Koray Tanfer: 0.0'},
{type:'famplan',text:'Lloyd J. Kolbe: 0.0'},
{type:'famplan',text:'Laila Nawar: 0.0'},
{type:'demography',text:'Aphichat Chamratrithirong: 0.0'},
{type:'famplan',text:'Herbert L. Smith: 0.0'},
{type:'demography',text:'Sian L. Curtis: 0.0'},
{type:'eugenics',text:'Robert D. Retherford: 0.0'},
{type:'demography',text:'Thomas C. Edwards Jr.: 0.0'},
{type:'demography',text:'Laura Porter: 0.0'},
{type:'demography',text:'Daniel A. Powers: 0.0'},
{type:'famplan',text:'Wendy D. Manning: 0.0'},
{type:'demography',text:'Nalini Ranjit: 0.0'},
{type:'famplan',text:'Yvette P. Cuca: 0.0'},
{type:'general',text:'Vinod Mishra: 0.0'},
{type:'famplan',text:'Anrudh Jain: 0.0'},
{type:'sociology',text:'Nan Marie Astone: 0.0'},
{type:'demography',text:'Richard Alba: 0.0'},
{type:'famplan',text:'Saumya Ramarao: 0.0'},
{type:'famplan',text:'Lawanda G. Burwell: 0.0'},
{type:'sociology',text:'Eileen M. Crimmins: 0.0'},
{type:'famplan',text:'Janet L. Collins: 0.0'},
{type:'eugenics',text:'Francesco C. Billari: 0.0'},
{type:'famplan',text:'John Bongaarts: 0.0'},
{type:'demography',text:'Matt Stevenson: 0.0'},
{type:'demography',text:'Manuel De J. Gonzalez G.: 0.0'},
{type:'famplan',text:'Larry L. Bumpass: 0.0'},
{type:'famplan',text:'Fred Binka: 0.0'},
{type:'demography',text:'Mary Cablk: 0.0'},
{type:'famplan',text:'David D. Celentano: 0.0'},
{type:'demography',text:'Georgia Verropoulou: 0.0'},
{type:'famplan',text:'Laura Kann: 0.0'},
{type:'famplan',text:'Ezzeldin Osman Hassan: 0.0'},
{type:'famplan',text:'Guy Stecklov: 0.0'},
{type:'demography',text:'Glen H. Elder Jr.: 0.0'},
{type:'demography',text:'Nancy Luke: 0.0'},
{type:'famplan',text:'Sherry A. Everett: 0.0'},
{type:'famplan',text:'Sandra L. Hofferth: 0.0'},
{type:'demography',text:'Robert J. Lilieholm: 0.0'},
{type:'famplan',text:'Cynthia B. Lloyd: 0.0'},
{type:'sociology',text:'Mark D. Hayward: 0.0'},
{type:'famplan',text:'Carol Cassell: 0.0'},
{type:'demography',text:'I-Fen Lin: 0.0'},
{type:'demography',text:'Kimberly S. Karish: 0.0'},
{type:'demography',text:'Mian Bazle Hossain: 0.0'},
{type:'famplan',text:'Charles W. Warren: 0.0'},
{type:'sociology',text:'Michael Spittel: 0.0'},
{type:'famplan',text:'David F. Sly: 0.0'},
{type:'demography',text:'Karen A. Woodrow-Lafield: 0.0'},
{type:'famplan',text:'David Quadagno: 0.0'},
{type:'demography',text:'Clea Sucoff Mcneely: 0.0'},
{type:'eugenics',text:'Jenny De Jong Gierveld: 0.0'},
{type:'demography',text:'Richard Toth: 0.0'},
{type:'famplan',text:'Martin L. Levin: 0.0'},
{type:'sociology',text:'Jay Teachman: 0.0'},
{type:'famplan',text:'Deborah S. Degraff: 0.0'},
{type:'demography',text:'Ronald Gray: 0.0'},
{type:'demography',text:'David R. Hotchkiss: 0.0'},
{type:'demography',text:'Isaac W. Eberstein: 0.0'},
{type:'demography',text:'The Rakai Project Team: 0.0'},
{type:'sociology',text:'Young J. Kim: 0.0'},
{type:'famplan',text:'Eric E. Seiber: 0.0'},
{type:'famplan',text:'Carol E. Kaufman: 0.0'},
{type:'demography',text:'Kim S. Miller: 0.0'},
{type:'demography',text:'Christopher Prinz: 0.0'},
{type:'demography',text:'Tomas Frejka: 0.0'},
{type:'famplan',text:'Scott Boggess: 0.0'},
{type:'general',text:'Kenneth W. Wachter: 0.0'},
{type:'famplan',text:'Harry Cross: 0.0'},
{type:'famplan',text:'Peggy C. Giordano: 0.0'},
{type:'famplan',text:'Wesley H. Clark: 0.0'},
{type:'demography',text:'Charles Hirschman: 0.0'},
{type:'eugenics',text:'Jean-Marie Robine: 0.0'},
{type:'famplan',text:'Kenneth A. Bollen: 0.0'},
{type:'sociology',text:'Marta Tienda: 0.0'},
{type:'sociology',text:'Henriette Engelhardt: 0.0'},
{type:'famplan',text:'John E. Anderson: 0.0'},
{type:'famplan',text:'David P. Lindstrom: 0.0'},
{type:'famplan',text:'Carolyn H. Bradner: 0.0'},
{type:'sociology',text:'Moshe Semyonov: 0.0'},
{type:'demography',text:'Joseph Lee Rodgers: 0.0'},
{type:'demography',text:'Robert Black: 0.0'},
{type:'demography',text:'K. A. S. Wickrama: 0.0'},
{type:'demography',text:'Jan M. Hoem: 0.0'},
{type:'famplan',text:'Evam Kofi Glover: 0.0'},
{type:'famplan',text:'Alex Nazzar: 0.0'},
{type:'sociology',text:'Monique Biegler: 0.0'},
{type:'demography',text:'Scott Rozelle: 0.0'},
{type:'sociology',text:'Andrew J. Cherlin: 0.0'},
{type:'demography',text:'Mark R. Montgomery: 0.0'},
{type:'famplan',text:'Eugene Weiss: 0.0'},
{type:'sociology',text:'Jennifer S. Barber: 0.0'},
{type:'demography',text:'Steven M. Lewis: 0.0'},
{type:'famplan',text:'Kokila Agarwal: 0.0'},
{type:'famplan',text:'Batya Elul: 0.0'},
{type:'demography',text:'Christopher G. Ellison: 0.0'},
{type:'famplan',text:'Joana Nerquaye-Tetteh: 0.0'},
{type:'demography',text:'Pat Caldwell: 0.0'},
{type:'demography',text:'Karen Carver: 0.0'},
{type:'famplan',text:'Eliya Msiyaphazi Zulu: 0.0'},
{type:'economics',text:'Leslie A. Whittington: 0.0'},
{type:'famplan',text:'Robert Miller: 0.0'},
{type:'demography',text:'Duncan Thomas: 0.0'},
{type:'famplan',text:'Brian Wells Pence: 0.0'},
{type:'sociology',text:'Minja Kim Choe: 0.0'},
{type:'demography',text:'Sara Mclanahan: 0.0'},
{type:'famplan',text:'Angela Bannerman: 0.0'},
{type:'famplan',text:'Fred N. Binka: 0.0'},
{type:'sociology',text:'Peter B. De Turk: 0.0'},
{type:'eugenics',text:'Monica Das Gupta: 0.0'},
{type:'demography',text:'Min Zhou: 0.0'},
{type:'demography',text:'Ann K. Blanc: 0.0'},
{type:'famplan',text:'Karin L. Brewster: 0.0'},
{type:'sociology',text:'Ying Hong: 0.0'},
{type:'demography',text:'R. Burciaga Valdez: 0.0'},
{type:'eugenics',text:'Douglas A. Wolf: 0.0'},
{type:'famplan',text:'Barbara S. Okun: 0.0'},
{type:'sociology',text:'Neil G. Bennett: 0.0'},
{type:'famplan',text:'Ellen Wilson: 0.0'},
{type:'general',text:'Joseph J. Strout: 0.0'},
{type:'demography',text:'Reeve Vanneman: 0.0'},
{type:'famplan',text:'Marguerite Farrell: 0.0'},
{type:'famplan',text:'Frank L. Mott: 0.0'},
{type:'sociology',text:'Lee A. Lillard: 0.0'},
{type:'famplan',text:'Elizabeth Thomson: 0.0'},
{type:'demography',text:'David R. Johnson: 0.0'},
{type:'demography',text:'Rand D. Conger: 0.0'},
{type:'famplan',text:'Margaret Pendzich: 0.0'},
{type:'demography',text:'Zachary Zimmer: 0.0'},
{type:'sociology',text:'Douglas Forbes: 0.0'},
{type:'demography',text:'Evert Van Imhoff: 0.0'},
{type:'famplan',text:'Khong Ngoc Am: 0.0'},
{type:'famplan',text:'Joyce Abma: 0.0'},
{type:'sociology',text:'Alejandro Portes: 0.0'},
{type:'famplan',text:'Taylor Haas: 0.0'},
{type:'general',text:'Christine Cassel: 0.0'},
{type:'demography',text:'Elizabeth C. Cooksey: 0.0'},
{type:'famplan',text:'Carol S. Aneshensel: 0.0'},
{type:'eugenics',text:'Zoe Matthews: 0.0'},
{type:'famplan',text:'Marlina Lacuesta: 0.0'},
{type:'demography',text:'Frederick O. Lorenz: 0.0'},
{type:'famplan',text:'Phan Thi Lien: 0.0'},
{type:'famplan',text:'Nancy L. Sloan: 0.0'},
{type:'famplan',text:'Abraham Hodgson: 0.0'},
{type:'demography',text:'JoaquíN Arango: 0.0'},
{type:'demography',text:'Lynn White: 0.0'},
{type:'famplan',text:'Jennifer Wagman: 0.0'},
{type:'famplan',text:'Varja Lipovsek: 0.0'},
{type:'famplan',text:'Lynne Gaffikin: 0.0'},
{type:'famplan',text:'Tom Lutalo: 0.0'},
{type:'sociology',text:'Patricia L. Mccall: 0.0'},
{type:'sociology',text:'R. Kelly Raley: 0.0'},
{type:'demography',text:'Anne K. Driscoll: 0.0'},
{type:'economics',text:'B. Lindsay Lowell: 0.0'},
{type:'demography',text:'Akinrinola Bankole: 0.0'},
{type:'economics',text:'Zai Liang: 0.0'},
{type:'famplan',text:'Richard Lowry: 0.0'},
{type:'demography',text:'Brian J. Stults: 0.0'},
{type:'history',text:'Michael R. Haines: 0.0'},
{type:'famplan',text:'Laura Ghiron: 0.0'},
{type:'famplan',text:'Mohamed Naguib: 0.0'},
{type:'famplan',text:'Nancy D. Brener: 0.0'},
{type:'famplan',text:'Luis Guilherme Penteado: 0.0'},
{type:'famplan',text:'Catherine A. Hagen: 0.0'},
{type:'famplan',text:'Nabil Attallah: 0.0'},
{type:'sociology',text:'Greg J. Duncan: 0.0'},
{type:'demography',text:'Yothin Sawangdee: 0.0'},
{type:'famplan',text:'Medi Kidugavu: 0.0'},
{type:'demography',text:'Sidney Goldstein: 0.0'},
{type:'eugenics',text:'Marieke Blommesteijn: 0.0'},
{type:'famplan',text:'Michele Polacsek: 0.0'},
{type:'sociology',text:'Arland Thornton: 0.0'},
{type:'demography',text:'Scott J. South: 0.0'},
{type:'general',text:'Xiaohe Xu: 0.0'},
{type:'famplan',text:'Evelyn Sakeah: 0.0'},
{type:'eugenics',text:'Ingrid Esveldt: 0.0'},
{type:'demography',text:'Gustav Feichtinger: 0.0'},
{type:'famplan',text:'Roberto Santiso Galvez: 0.0'},
{type:'famplan',text:'Francisco Cabral: 0.0'},
{type:'demography',text:'Michele Gragnolati: 0.0'},
{type:'demography',text:'Ian Askew: 0.0'},
{type:'famplan',text:'Joseph H. Pleck: 0.0'},
{type:'demography',text:'Adela Pellegrino: 0.0'},
{type:'eugenics',text:'KÈNe Henkens: 0.0'},
{type:'general',text:'Susan Hanson: 0.0'},
{type:'famplan',text:'Bui Thi Chi: 0.0'},
{type:'demography',text:'Constance A. Nathanson: 0.0'},
{type:'demography',text:'Cem Mete: 0.0'},
{type:'famplan',text:'Isaac F. Adewole: 0.0'},
{type:'general',text:'William B. Capra: 0.0'},
{type:'famplan',text:'Pinar Senlet: 0.0'},
{type:'famplan',text:'Boniface A. Oye-Adeniran: 0.0'},
{type:'famplan',text:'Marilou Costello: 0.0'},
{type:'famplan',text:'Matthew Holtman: 0.0'},
{type:'famplan',text:'Laurie F. Derose: 0.0'},
{type:'eugenics',text:'Helga De Valk: 0.0'},
{type:'famplan',text:'Zheng Wu: 0.0'},
{type:'demography',text:'Teresa Seeman: 0.0'},
{type:'demography',text:'Barbara W. Sugland: 0.0'},
{type:'eugenics',text:'Ming-Cheng Chang: 0.0'},
{type:'famplan',text:'Anne Terborgh: 0.0'},
{type:'famplan',text:'P. N. Mari Bhat: 0.0'},
{type:'famplan',text:'Maria Yolanda Makuch: 0.0'},
{type:'eugenics',text:'Hein Moors: 0.0'},
{type:'famplan',text:'Donald R. Hoover: 0.0'},
{type:'sociology',text:'Reynolds Farley: 0.0'},
{type:'demography',text:'Lisa Greenwell: 0.0'},
{type:'demography',text:'Simon Szreter: 0.0'},
{type:'demography',text:'Elizabeth G. Menaghan: 0.0'},
{type:'demography',text:'Emilio A. Parrado: 0.0'},
{type:'famplan',text:'William D. Mosher: 0.0'},
{type:'demography',text:'Yu-Hsuan Lin: 0.0'},
{type:'demography',text:'Bridget K. Gorman: 0.0'},
{type:'demography',text:'H. Elizabeth Peters: 0.0'},
{type:'famplan',text:'Arnstein Aassve: 0.0'},
{type:'general',text:'B. L. Turner Ii: 0.0'},
{type:'famplan',text:'Debora Bossemeyer: 0.0'},
{type:'eugenics',text:'Ewa Tabeau: 0.0'},
{type:'demography',text:'Kyle D. Crowder: 0.0'},
{type:'famplan',text:'Nahid Toubia: 0.0'},
{type:'demography',text:'Elwood Carlson: 0.0'},
{type:'famplan',text:'Ngozi Iwere: 0.0'},
{type:'demography',text:'Cynthia K. Miller: 0.0'},
{type:'demography',text:'Dang Nguyen Anh: 0.0'},
{type:'demography',text:'Mary C. Daly: 0.0'},
{type:'demography',text:'Julie Davanzo: 0.0'},
{type:'demography',text:'Laknath Peiris: 0.0'},
{type:'famplan',text:'Nguyen Hua Phuc: 0.0'},
{type:'famplan',text:'Ronald H. Gray: 0.0'},
{type:'general',text:'Jefferson Fox: 0.0'},
{type:'famplan',text:'Indrani Pieris: 0.0'},
{type:'famplan',text:'Estela Maria Leao De Aquino: 0.0'},
{type:'famplan',text:'Fred Nalugoda: 0.0'},
{type:'general',text:'Fernando Rajulton: 0.0'},
{type:'famplan',text:'Peter Hall: 0.0'},
{type:'famplan',text:'Sheana E. Bull: 0.0'},
{type:'famplan',text:'Maria Jose Osis: 0.0'},
{type:'sociology',text:'P. Lindsay Chase-Lansdale: 0.0'},
{type:'demography',text:'Tristan Gorrindo: 0.0'},
{type:'sociology',text:'Charles B. Nam: 0.0'},
{type:'demography',text:'Kristin A. Moore: 0.0'},
{type:'demography',text:'Gesine K. Hearn: 0.0'},
{type:'general',text:'Ronald D. Lee: 0.0'},
{type:'famplan',text:'William R. Grady: 0.0'},
{type:'famplan',text:'Nguyen Thi Loi: 0.0'},
{type:'famplan',text:'Ron Gray: 0.0'},
{type:'demography',text:'Saifuddin Ahmed: 0.0'},
{type:'famplan',text:'Maria De Conceicao Chagas Almeida: 0.0'},
{type:'demography',text:'Tom P. Evans: 0.0'},
{type:'famplan',text:'Laura D. Lindberg: 0.0'},
{type:'famplan',text:'Laurie S. Zabin: 0.0'},
{type:'famplan',text:'Hosanna Soler: 0.0'},
{type:'famplan',text:'Carlos Gonzalez: 0.0'},
{type:'demography',text:'Lora Ebert Wallace: 0.0'},
{type:'famplan',text:'Willy Terceros: 0.0'},
{type:'famplan',text:'Anthony C. Kouzis: 0.0'},
{type:'famplan',text:'Jill Mathis: 0.0'},
{type:'demography',text:'Heather Joshi: 0.0'},
{type:'sociology',text:'Pamela J. Smock: 0.0'},
{type:'famplan',text:'Peter Fajans: 0.0'},
{type:'demography',text:'V. Jeffery Evans: 0.0'},
{type:'famplan',text:'Iryna Zablotska: 0.0'},
{type:'famplan',text:'Loren Galvao: 0.0'},
{type:'demography',text:'Anne Goujon: 0.0'},
{type:'demography',text:'Reanne Frank: 0.0'},
{type:'famplan',text:'Daniel T. Lichter: 0.0'},
{type:'famplan',text:'Kara S. Riehman: 0.0'},
{type:'famplan',text:'Barbara Mensch: 0.0'},
{type:'demography',text:'John Hobcraft: 0.0'},
{type:'demography',text:'Lynda Clarke: 0.0'},
{type:'general',text:'Julian May: 0.0'},
{type:'sociology',text:'Ira Rosenwaike: 0.0'},
{type:'sociology',text:'Jason D. Boardman: 0.0'},
{type:'famplan',text:'Rofina Asuru: 0.0'},
{type:'famplan',text:'Zhai Fengying: 0.0'},
{type:'famplan',text:'Michelle Gardner: 0.0'},
{type:'demography',text:'Ali Kouaouci: 0.0'},
{type:'demography',text:'Peter J. Donaldson: 0.0'},
{type:'famplan',text:'James E. Rosen: 0.0'},
{type:'demography',text:'Gunnar Almgren: 0.0'},
{type:'demography',text:'Marcia Carlson: 0.0'},
{type:'famplan',text:'Jay Satia: 0.0'},
{type:'economics',text:'Minhaj Ul Haque: 0.0'},
{type:'famplan',text:'Jayanti Tuladhar: 0.0'},
{type:'famplan',text:'Nizamuddin Khan: 0.0'},
{type:'famplan',text:'Michael Resnick: 0.0'},
{type:'sociology',text:'Lisa D. Pearce: 0.0'},
{type:'general',text:'Robert J. Sampson: 0.0'},
{type:'famplan',text:'Kathryn Kost: 0.0'},
{type:'demography',text:'Amson Sibanda: 0.0'},
{type:'famplan',text:'Michele T. Villinski: 0.0'},
{type:'demography',text:'Brian Karl Finch: 0.0'},
{type:'famplan',text:'Altaf Hossain: 0.0'},
{type:'famplan',text:'Patricia M. Dietz: 0.0'},
{type:'famplan',text:'Olivia P. Mcdonald: 0.0'},
{type:'demography',text:'Gert G. Wagner: 0.0'},
{type:'famplan',text:'Amy Ong Tsui: 0.0'},
{type:'famplan',text:'Josefina V. Cabigon: 0.0'},
{type:'demography',text:'Duolao Wang: 0.0'},
{type:'demography',text:'Avery M. Guest: 0.0'},
{type:'eugenics',text:'Thomas K. Burch: 0.0'},
{type:'famplan',text:'Uma Saha: 0.0'},
{type:'demography',text:'Mary Rogers Gillmore: 0.0'},
{type:'sociology',text:'Gilbert Marzan: 0.0'},
{type:'demography',text:'Dirk J. Van De Kaa: 0.0'},
{type:'famplan',text:'Fredrick K. Nyagah: 0.0'},
{type:'famplan',text:'Maureen Clyde: 0.0'},
{type:'economics',text:'Janet Currie: 0.0'},
{type:'demography',text:'Nagwa Khallaf: 0.0'},
{type:'famplan',text:'Blesilda Pangolibay: 0.0'},
{type:'demography',text:'Miloslav Macura: 0.0'},
{type:'famplan',text:'Yvonne Stedman: 0.0'},
{type:'sociology',text:'Brenda Marsteller Kowalewski: 0.0'},
{type:'famplan',text:'Melissa M. Adams: 0.0'},
{type:'famplan',text:'Andrew Thompson: 0.0'},
{type:'famplan',text:'Paulina Makinwa-Adebusoye: 0.0'},
{type:'demography',text:'Barry M. Popkin: 0.0'},
{type:'famplan',text:'Robert Hanenberg: 0.0'},
{type:'famplan',text:'Mohammad H. Rahbar: 0.0'},
{type:'demography',text:'Diane S. Lauderdale: 0.0'},
{type:'famplan',text:'Philip B. Adongo: 0.0'},
{type:'general',text:'Burton H. Singer: 0.0'},
{type:'demography',text:'Jennifer E. Glick: 0.0'},
{type:'demography',text:'Ronald Mincy: 0.0'},
{type:'demography',text:'Thomas A. Diprete: 0.0'},
{type:'demography',text:'Graciela Teruel: 0.0'},
{type:'demography',text:'Michael J. Brien: 0.0'},
{type:'sociology',text:'Felicia B. Leclere: 0.0'},
{type:'famplan',text:'Haidary Kamal: 0.0'},
{type:'famplan',text:'T. Stephen Jones: 0.0'},
{type:'demography',text:'Michael S. Spencer: 0.0'},
{type:'demography',text:'Stacy J. Rogers: 0.0'},
{type:'famplan',text:'Shameem Ahmed: 0.0'},
{type:'demography',text:'Magali Barbieri: 0.0'},
{type:'demography',text:'Steven P. Swinford: 0.0'},
{type:'famplan',text:'Dao Quang Vinh: 0.0'},
{type:'sociology',text:'Jay D. Teachman: 0.0'},
{type:'famplan',text:'Christa Coggins: 0.0'},
{type:'famplan',text:'Kristen Nelson: 0.0'},
{type:'famplan',text:'Paul N. Hu: 0.0'},
{type:'demography',text:'Rodolfo Tuiran: 0.0'},
{type:'famplan',text:'Felicia Stewart: 0.0'},
{type:'sociology',text:'William Kandel: 0.0'},
{type:'general',text:'Teresa E. Seeman: 0.0'},
{type:'demography',text:'Shelah S. Bloom: 0.0'},
{type:'famplan',text:'Hala Youssef: 0.0'},
{type:'demography',text:'R. S. Oropesa: 0.0'},
{type:'sociology',text:'Miguel Ceballos: 0.0'},
{type:'famplan',text:'David Sokal: 0.0'},
{type:'demography',text:'Francesco Billari: 0.0'},
{type:'economics',text:'Betemariam Berhanu: 0.0'},
{type:'eugenics',text:'Cecilia Tomassini: 0.0'},
{type:'demography',text:'Victor Nee: 0.0'},
{type:'famplan',text:'Parveen Nangia: 0.0'},
{type:'famplan',text:'Wilma Bailey: 0.0'},
{type:'general',text:'Brian C. Oneill: 0.0'},
{type:'sociology',text:'David A. Cotter: 0.0'},
{type:'demography',text:'Jere R. Behrman: 0.0'},
{type:'demography',text:'Youssef Waheeb: 0.0'},
{type:'demography',text:'Ruchira T. Naved: 0.0'},
{type:'eugenics',text:'Dilip C. Nath: 0.0'},
{type:'demography',text:'Jason Fields: 0.0'},
{type:'famplan',text:'Pramilla Senanayake: 0.0'},
{type:'famplan',text:'Aria Davis Crump: 0.0'},
{type:'famplan',text:'Fazilatun Nessa: 0.0'},
{type:'sociology',text:'Kyle Crowder: 0.0'},
{type:'general',text:'Marcus W. Feldman: 0.0'},
{type:'demography',text:'Xiao Zhenyu: 0.0'},
{type:'demography',text:'Randal Day: 0.0'},
{type:'demography',text:'Yolanda C. Padilla: 0.0'},
{type:'eugenics',text:'Frans Willekens: 0.0'},
{type:'famplan',text:'Trinh Huu Vach: 0.0'},
{type:'famplan',text:'Kara Riehman: 0.0'},
{type:'economics',text:'Robert J. Willis: 0.0'},
{type:'famplan',text:'Mary Davis: 0.0'},
{type:'famplan',text:'Daniel H. Klepinger: 0.0'},
{type:'demography',text:'Martin Brockerhoff: 0.0'},
{type:'famplan',text:'Amanullah Khan: 0.0'},
{type:'demography',text:'Toni P. Miles: 0.0'},
{type:'famplan',text:'Deirdre Wulf: 0.0'},
{type:'famplan',text:'Gregorio Perez-Palacios: 0.0'},
{type:'demography',text:'Stephen A. Cernkovich: 0.0'},
{type:'famplan',text:'Martin Vessey: 0.0'},
{type:'demography',text:'Liu Yuzhi: 0.0'},
{type:'sociology',text:'Douglas S. Massey: 0.0'},
{type:'famplan',text:'Bruce K. Caldwell: 0.0'},
{type:'demography',text:'C. Shannon Stokes: 0.0'},
{type:'demography',text:'Truong Si Anh: 0.0'},
{type:'famplan',text:'Peggy Barker: 0.0'},
{type:'economics',text:'Naohiro Ogawa: 0.0'},
{type:'demography',text:'Wang Zhenglian: 0.0'},
{type:'general',text:'Julien O. Teitler: 0.0'},
{type:'famplan',text:'Lynda Doll: 0.0'},
{type:'demography',text:'Noah Lewin-Epstein: 0.0'},
{type:'famplan',text:'Janet C. Rice: 0.0'},
{type:'general',text:'Jane-Ling Wang: 0.0'},
{type:'famplan',text:'Lisanne F. Brown: 0.0'},
{type:'famplan',text:'Alison M. Spitz: 0.0'},
{type:'general',text:'Hans-Georg Muller: 0.0'},
{type:'sociology',text:'Joshua R. Goldstein: 0.0'},
{type:'sociology',text:'Kristin Espinosa: 0.0'},
{type:'famplan',text:'Michelle M. Fondell: 0.0'},
{type:'famplan',text:'Daniel J. Whitaker: 0.0'},
{type:'famplan',text:'Helen Doll: 0.0'},
{type:'demography',text:'M. D. Pugh: 0.0'},
{type:'demography',text:'Jed Friedman: 0.0'},
{type:'famplan',text:'Ronald Wilson: 0.0'},
{type:'demography',text:'Amy Lutz: 0.0'},
{type:'demography',text:'Bert Kestenbaum: 0.0'},
{type:'demography',text:'Renata Forste: 0.0'},
{type:'famplan',text:'Amita Bhatt: 0.0'},
{type:'demography',text:'Rachelle D. White: 0.0'},
{type:'demography',text:'Alessandro Rosina: 0.0'},
{type:'famplan',text:'Anne Webb: 0.0'},
{type:'economics',text:'Mark R. Rosenzweig: 0.0'},
{type:'famplan',text:'Philip Adongo: 0.0'},
{type:'demography',text:'William H. Frey: 0.0'},
{type:'demography',text:'Lucky M. Tedrow: 0.0'},
{type:'famplan',text:'Mark Vanlandingham: 0.0'},
{type:'general',text:'David E. Bloom: 0.0'},
{type:'famplan',text:'Fatima Sajan: 0.0'},
{type:'famplan',text:'W. Parker Mauldin: 0.0'},
{type:'famplan',text:'Muhammad Masood Kadir: 0.0'},
{type:'sociology',text:'Wenquan Zhang: 0.0'},
{type:'demography',text:'Jan E. Mutchler: 0.0'},
{type:'famplan',text:'Miriam Fuentes: 0.0'},
{type:'famplan',text:'Phan Thuc Anh: 0.0'},
{type:'famplan',text:'Sharon Camp: 0.0'},
{type:'famplan',text:'Indrani Haque: 0.0'},
{type:'demography',text:'Rodolfo Corona: 0.0'},
{type:'demography',text:'Saul D. Hoffman: 0.0'},
{type:'demography',text:'Jason M. Fields: 0.0'},
{type:'demography',text:'Nico Keilman: 0.0'},
{type:'famplan',text:'Charles Onoka: 0.0'},
{type:'general',text:'Mary Beth Ofstedal: 0.0'},
{type:'demography',text:'Curtis S. Florence: 0.0'},
{type:'famplan',text:'Alfred Adewuyi: 0.0'},
{type:'sociology',text:'Kendra Rothert: 0.0'},
{type:'demography',text:'M. Giovanna Merli: 0.0'},
{type:'sociology',text:'Nicola J. Standish: 0.0'},
{type:'famplan',text:'F. Ram: 0.0'},
{type:'demography',text:'Frances K. Goldscheider: 0.0'},
{type:'demography',text:'Arleen Leibowitz: 0.0'},
{type:'demography',text:'Kathleen Beegle: 0.0'},
{type:'sociology',text:'Joann Defiore: 0.0'},
{type:'demography',text:'Paula England: 0.0'},
{type:'demography',text:'Joachim R. Frick: 0.0'},
{type:'famplan',text:'Rick Homan: 0.0'},
{type:'eugenics',text:'Ruth Mace: 0.0'},
{type:'demography',text:'Emily Grundy: 0.0'},
{type:'famplan',text:'Maria Rosa Garate: 0.0'},
{type:'famplan',text:'John Kekovole: 0.0'},
{type:'famplan',text:'Christopher H. Johnson: 0.0'},
{type:'famplan',text:'Jane Chege: 0.0'},
{type:'demography',text:'Wendell Primus: 0.0'},
{type:'demography',text:'Kathleen Paasch: 0.0'},
{type:'famplan',text:'Lori Kowaleski-Jones: 0.0'},
{type:'sociology',text:'Joan M. Hermsen: 0.0'},
{type:'famplan',text:'Nahla Abdel-Tawab: 0.0'},
{type:'demography',text:'Zvi Eisenbach: 0.0'},
{type:'famplan',text:'Brian Hubbard: 0.0'},
{type:'demography',text:'Maria Dworak: 0.0'},
{type:'famplan',text:'Alex Muyonga: 0.0'},
{type:'famplan',text:'Isaac Eberstein: 0.0'},
{type:'demography',text:'Lindy Williams: 0.0'},
{type:'demography',text:'Bothaina El-Deeb: 0.0'},
{type:'famplan',text:'Linus I. A. Ettyang: 0.0'},
{type:'famplan',text:'Jennifer A. Strickler: 0.0'},
{type:'demography',text:'Zhang Chunyuan: 0.0'},
{type:'demography',text:'H. Theodore Groat: 0.0'},
{type:'demography',text:'Sunita Kishor: 0.0'},
{type:'demography',text:'Marcia J. Carlson: 0.0'},
{type:'sociology',text:'Clea A. Sucoff: 0.0'},
{type:'famplan',text:'Anju Malhotra: 0.0'},
{type:'famplan',text:'Adul Barkat: 0.0'},
{type:'demography',text:'Mary Jane Lohr: 0.0'},
{type:'famplan',text:'Nicole Haberland: 0.0'},
{type:'famplan',text:'Renee Samara: 0.0'},
{type:'demography',text:'Dwayne Benjamin: 0.0'},
{type:'demography',text:'Parfait M. Eloundou-Enyegue: 0.0'},
{type:'famplan',text:'Gladys Martinez: 0.0'},
{type:'demography',text:'F. Allan Hubbell: 0.0'},
{type:'famplan',text:'Alex C. Ezeh: 0.0'},
{type:'famplan',text:'Paul Stupp: 0.0'},
{type:'demography',text:'Nicholas A. Christakis: 0.0'},
{type:'famplan',text:'David J. Landry: 0.0'},
{type:'demography',text:'Rossarin Soottipong Gray: 0.0'},
{type:'demography',text:'Susan L. Brown: 0.0'},
{type:'general',text:'Hwa Young Lee: 0.0'},
{type:'demography',text:'Yi-Li Chuang: 0.0'},
{type:'famplan',text:'Stacy W. Mcdonald: 0.0'},
{type:'famplan',text:'Irina Alekseevna Zhirova: 0.0'},
{type:'demography',text:'Rebeca Raijman: 0.0'},
{type:'demography',text:'Liz Middleton: 0.0'},
{type:'famplan',text:'Jamil H. Chowdhury: 0.0'},
{type:'famplan',text:'Sabu S. Padmadas: 0.0'},
{type:'general',text:'Jeffrey D. Morenoff: 0.0'},
{type:'demography',text:'Peter Ekamper: 0.0'},
{type:'general',text:'Bruce S. Mcewen: 0.0'},
{type:'economics',text:'Robert A. Moffitt: 0.0'},
{type:'economics',text:'Xuguang Guo: 0.0'},
{type:'general',text:'Samuli Helle: 0.0'},
{type:'famplan',text:'Marco Pinel: 0.0'},
{type:'general',text:'Zenaida R. Ravaneral: 0.0'},
{type:'famplan',text:'Quan Le Nga: 0.0'},
{type:'demography',text:'Jennifer V. W. Van Hook: 0.0'},
{type:'demography',text:'Kathleen E. Kiernan: 0.0'},
{type:'demography',text:'Irena Kogan: 0.0'},
{type:'demography',text:'Netra B. Chhetri: 0.0'},
{type:'sociology',text:'Avery Guest: 0.0'},
{type:'famplan',text:'John Stover: 0.0'},
{type:'demography',text:'Brian Fisher: 0.0'},
{type:'famplan',text:'Genevieve M. Kenney: 0.0'},
{type:'famplan',text:'Leigh Anne Shafer: 0.0'},
{type:'demography',text:'Susan Sprecher: 0.0'},
{type:'eugenics',text:'Gebre-Egziabher Kiros: 0.0'},
{type:'demography',text:'David Lam: 0.0'},
{type:'famplan',text:'Leslie F. Clark: 0.0'},
{type:'demography',text:'Rachel Connelly: 0.0'},
{type:'famplan',text:'Afroze Sherali: 0.0'},
{type:'demography',text:'Mark Hereward: 0.0'},
{type:'famplan',text:'Davy M. Chikamata: 0.0'},
{type:'demography',text:'Prem Bhandari: 0.0'},
{type:'statistics',text:'Adrian E. Raftery: 0.0'},
{type:'demography',text:'David J. Lunn: 0.0'},
{type:'demography',text:'Stephen M. Sosler: 0.0'},
{type:'demography',text:'Brian Roe: 0.0'},
{type:'demography',text:'Thomas Kersen: 0.0'},
{type:'demography',text:'Christine M. Schaeffer: 0.0'},
{type:'sociology',text:'Amy Dunger: 0.0'},
{type:'famplan',text:'Ntsiki Manzini: 0.0'},
{type:'economics',text:'Jonathan Gruber: 0.0'},
{type:'demography',text:'Guido Pinto Aguirre: 0.0'},
{type:'economics',text:'Fengying Zhai: 0.0'},
{type:'demography',text:'Dennis A. Ahlburg: 0.0'},
{type:'demography',text:'Leo R. Chavez: 0.0'},
{type:'demography',text:'A. B. M. Khorshed Alam Mozumder: 0.0'},
{type:'demography',text:'Sara Beck Fein: 0.0'},
{type:'demography',text:'Corina Huisman: 0.0'},
{type:'demography',text:'Feinian Chen: 0.0'},
{type:'famplan',text:'Leah Robin: 0.0'},
{type:'famplan',text:'Jean Jackson: 0.0'},
{type:'demography',text:'Joshua Goldstein: 0.0'},
{type:'famplan',text:'Stanley Terrell: 0.0'},
{type:'demography',text:'Cassio M. Turra: 0.0'},
{type:'famplan',text:'Jacqueline Koenig: 0.0'},
{type:'demography',text:'Mario F. Teisl: 0.0'},
{type:'demography',text:'Elena Dolkigh: 0.0'},
{type:'demography',text:'Mary Casey Jacob: 0.0'},
{type:'famplan',text:'Andrew A. Fisher: 0.0'},
{type:'demography',text:'Arthur L. Greil: 0.0'},
{type:'famplan',text:'Alan Gray: 0.0'},
{type:'demography',text:'Sharon Stash: 0.0'},
{type:'demography',text:'Hilke Kayser: 0.0'},
{type:'demography',text:'Jon M. Hussey: 0.0'},
{type:'demography',text:'Mark E. Hill: 0.0'},
{type:'demography',text:'Jeroen K. Vermunt: 0.0'},
{type:'sociology',text:'Indra Chaudhury: 0.0'},
{type:'famplan',text:'Dorina Vereau: 0.0'},
{type:'demography',text:'Richard A. Wanner: 0.0'},
{type:'famplan',text:'Yukolsiri Surasrang: 0.0'},
{type:'general',text:'Virpi Lummaa: 0.0'},
{type:'famplan',text:'Florina Serbanescu: 0.0'},
{type:'sociology',text:'Patrick M. Krueger: 0.0'},
{type:'demography',text:'Dominic J. Mancini: 0.0'},
{type:'demography',text:'German Rodriguez: 0.0'},
{type:'demography',text:'Richard E. Bilsborrow: 0.0'},
{type:'famplan',text:'Lene Levy-Storms: 0.0'},
{type:'famplan',text:'Laura M. Johnson: 0.0'},
{type:'demography',text:'Daniel S. Gaylin: 0.0'},
{type:'demography',text:'Amon Ergashev: 0.0'},
{type:'famplan',text:'Fauzia Hoodbhoy: 0.0'},
{type:'sociology',text:'George Immerwahr: 0.0'},
{type:'demography',text:'E. A. Hammel: 0.0'},
{type:'demography',text:'Rebecca Kim: 0.0'},
{type:'demography',text:'Ma Zhongdong: 0.0'},
{type:'famplan',text:'Margarita Suazo: 0.0'},
{type:'demography',text:'Guang Guo: 0.0'},
{type:'famplan',text:'Elizabeth Kolb: 0.0'},
{type:'famplan',text:'Truong Viet Dung: 0.0'},
{type:'famplan',text:'Diane K. Mclaughlin: 0.0'},
{type:'demography',text:'David A. Swanson: 0.0'},
{type:'demography',text:'Seung-Eun Song: 0.0'},
{type:'demography',text:'Valarie King: 0.0'},
{type:'demography',text:'Tom Mcnulty: 0.0'},
{type:'demography',text:'Warren C. Sanderson: 0.0'},
{type:'famplan',text:'Kathryn M. Yount: 0.0'},
{type:'famplan',text:'R. Hasan M. Hoesni: 0.0'},
{type:'demography',text:'Xian Liu: 0.0'},
{type:'demography',text:'Nigar Nargis: 0.0'},
{type:'sociology',text:'CristóBal Ridao-Cano: 0.0'},
{type:'famplan',text:'Dao Xuan Vinh: 0.0'},
{type:'demography',text:'B. Reneé Ferguson: 0.0'},
{type:'demography',text:'Sara Peracca: 0.0'},
{type:'general',text:'Richard A. Easterlin: 0.0'},
{type:'demography',text:'Cecilia Menjivar: 0.0'},
{type:'sociology',text:'Mary C. Brinton: 0.0'},
{type:'demography',text:'Fei Guo: 0.0'},
{type:'demography',text:'Edmundo Paredes: 0.0'},
{type:'demography',text:'Jyoti Mudgal: 0.0'},
{type:'history',text:'Thomas W. Pullum: 0.0'},
{type:'demography',text:'Chen Chunjun: 0.0'},
{type:'demography',text:'Michael White: 0.0'},
{type:'sociology',text:'William L. Parish: 0.0'},
{type:'eugenics',text:'Albert Hermalin: 0.0'},
{type:'famplan',text:'Julide Ergin: 0.0'},
{type:'eugenics',text:'Gijs Beets: 0.0'},
{type:'famplan',text:'Kanta Jamil: 0.0'},
{type:'sociology',text:'Ross M. Stolzenberg: 0.0'},
{type:'demography',text:'Paul A. Nakonezny: 0.0'},
{type:'demography',text:'Edward J. Castronova: 0.0'},
{type:'sociology',text:'Michael P. Massagli: 0.0'},
{type:'demography',text:'Ellen Kruse: 0.0'},
{type:'famplan',text:'Karen R. Katz: 0.0'},
{type:'sociology',text:'David J. Eggebeen: 0.0'},
{type:'demography',text:'Mark Hill: 0.0'},
{type:'famplan',text:'Marcia A. Angle: 0.0'},
{type:'famplan',text:'David C. Ribar: 0.0'},
{type:'demography',text:'Tu Ping: 0.0'},
{type:'demography',text:'Richard V. Burkhauser: 0.0'},
{type:'famplan',text:'Lynne Maziarz Geitz: 0.0'},
{type:'demography',text:'Andres Vikat: 0.0'},
{type:'famplan',text:'Elizabeth Eggleston: 0.0'},
{type:'famplan',text:'Alin Stanescu: 0.0'},
{type:'demography',text:'Andrew Hinde: 0.0'},
{type:'demography',text:'Bunnak Poch: 0.0'},
{type:'demography',text:'John Logan: 0.0'},
{type:'demography',text:'Rebecca Sear: 0.0'},
{type:'economics',text:'Jona Schellekens: 0.0'},
{type:'demography',text:'Jeungil Oh: 0.0'},
{type:'demography',text:'Guillermina Jasso: 0.0'},
{type:'demography',text:'Lilach Lion Elmakias: 0.0'},
{type:'famplan',text:'Sherrine Eid: 0.0'},
{type:'famplan',text:'Levent Cagatay: 0.0'},
{type:'demography',text:'Jeannette Sutton: 0.0'},
{type:'famplan',text:'Daniel Bagah: 0.0'},
{type:'famplan',text:'Ly Thai Loc: 0.0'},
{type:'famplan',text:'Oliver Chinganya: 0.0'},
{type:'famplan',text:'Tom O. Owuor: 0.0'},
{type:'demography',text:'Shelly Lundberg: 0.0'},
{type:'sociology',text:'Monica A. Longmore: 0.0'},
{type:'demography',text:'Michael Dill: 0.0'},
{type:'general',text:'Byung-Yup Cho: 0.0'},
{type:'famplan',text:'Nafissatou Diop: 0.0'},
{type:'demography',text:'Dov Friedlander: 0.0'},
{type:'demography',text:'Theodore J. Iwashyna: 0.0'},
{type:'general',text:'Vicki L. Lamb: 0.0'},
{type:'demography',text:'K. Stephen Blanchard: 0.0'},
{type:'demography',text:'Thomas L. Hanson: 0.0'},
{type:'famplan',text:'Han Raggers: 0.0'},
{type:'demography',text:'Nancy A. Denton: 0.0'},
{type:'famplan',text:'Vanessa E. Cullins: 0.0'},
{type:'famplan',text:'Mai Van Cam: 0.0'},
{type:'demography',text:'Porntip Sriwatcharin: 0.0'},
{type:'sociology',text:'Xu Siyuan: 0.0'},
{type:'famplan',text:'John Stoeckel: 0.0'},
{type:'general',text:'Angelique Chan: 0.0'},
{type:'famplan',text:'Lawrence B. Finer: 0.0'},
{type:'demography',text:'Monica Boyd: 0.0'},
{type:'demography',text:'Patrick R. Galloway: 0.0'},
{type:'famplan',text:'Vipan Prachuabmoh Ruffolo: 0.0'},
{type:'demography',text:'Mike Murphy: 0.0'},
{type:'famplan',text:'Pakamas Ratanalangkarn: 0.0'},
{type:'eugenics',text:'Daniel D. Greenfield: 0.0'},
{type:'demography',text:'Brian Stults: 0.0'},
{type:'demography',text:'Anil Deolalikar: 0.0'},
{type:'famplan',text:'Jennifer Lincoln-Hanson: 0.0'},
{type:'economics',text:'Cynthia B. Lloyd: 0.0'},
{type:'demography',text:'Hana Pacalova: 0.0'},
{type:'sociology',text:'Alfred Demaris: 0.0'},
{type:'demography',text:'Kirsten Ohm Kyvik: 0.0'},
{type:'demography',text:'Shiraz I. Mishra: 0.0'},
{type:'sociology',text:'Noriko O. Tsuya: 0.0'},
{type:'demography',text:'Hsien-Hen Lu: 0.0'},
{type:'demography',text:'Ivan Light: 0.0'},
{type:'famplan',text:'Tatiana Mikhailovna Astakhova: 0.0'},
{type:'sociology',text:'Yu Yang: 0.0'},
{type:'demography',text:'Jani S. Little: 0.0'},
{type:'famplan',text:'George R. Huggins: 0.0'},
{type:'demography',text:'Akbar Aghajanian: 0.0'},
{type:'demography',text:'Kathleen A. Burke: 0.0'},
{type:'general',text:'John W. Rowe: 0.0'},
{type:'demography',text:'Shu-Yin J. Leung: 0.0'},
{type:'general',text:'Felton Earls: 0.0'},
{type:'famplan',text:'Nguyen Van Phai: 0.0'},
{type:'demography',text:'F. Landis Mackellar: 0.0'},
{type:'demography',text:'Wendy Post: 0.0'},
{type:'demography',text:'James X. Zhang: 0.0'},
{type:'demography',text:'Bui The Cuong: 0.0'},
{type:'demography',text:'Gary D. Sandefur: 0.0'},
{type:'demography',text:'Jianping Huang: 0.0'},
{type:'demography',text:'Evelyn L. Lehrer: 0.0'},
{type:'sociology',text:'Yang Mingliang: 0.0'},
{type:'famplan',text:'Jennifer J. Frost: 0.0'},
{type:'demography',text:'Youngtae Cho: 0.0'},
{type:'famplan',text:'Emily Zielinski Gutierrez: 0.0'},
{type:'famplan',text:'Hoang Ti Van: 0.0'},
{type:'demography',text:'Rosalind Berkowitz King: 0.0'},
{type:'demography',text:'Annababette Wils: 0.0'},
{type:'economics',text:'William Darity Jr.: 0.0'},
{type:'sociology',text:'Susan Gurung: 0.0'},
{type:'demography',text:'Nikolai Botev: 0.0'},
{type:'demography',text:'Martha S. Hill: 0.0'},
{type:'demography',text:'Ian A. Mcgregor: 0.0'},
{type:'demography',text:'Julia Mcquillan: 0.0'},
{type:'demography',text:'Fred Arnold: 0.0'},
{type:'demography',text:'S. Irudaya Rajan: 0.0'},
{type:'demography',text:'Jorge Durand: 0.0'},
{type:'famplan',text:'Barbara L. Ibrahim: 0.0'},
{type:'general',text:'Jukka Jokela: 0.0'},
{type:'demography',text:'Andrew J. Houtenville: 0.0'},
{type:'demography',text:'Chien-Chung Huang: 0.0'},
{type:'demography',text:'Anne H. Gauthier: 0.0'},
{type:'famplan',text:'Kua Wongboonsin: 0.0'},
{type:'demography',text:'Barbara Vaughan: 0.0'},
{type:'famplan',text:'Ali Ashraf: 0.0'},
{type:'sociology',text:'Daniel Llanes: 0.0'},
{type:'famplan',text:'Subrata Routh: 0.0'},
{type:'demography',text:'Alice Goldstein: 0.0'},
{type:'sociology',text:'Amy M. Pienta: 0.0'},
{type:'sociology',text:'Daniel S. Nagin: 0.0'},
{type:'famplan',text:'Bakutuvwidi Makani: 0.0'},
{type:'demography',text:'Ann Branaman: 0.0'},
{type:'demography',text:'Ganesh P. Shivakoti: 0.0'},
{type:'demography',text:'Andrew Foster: 0.0'},
{type:'demography',text:'Gary R. Lee: 0.0'},
{type:'sociology',text:'Gayle Kaufman: 0.0'},
{type:'eugenics',text:'Nico Van Nimwegen: 0.0'},
{type:'demography',text:'Paul R. Amato: 0.0'},
{type:'famplan',text:'Inoussa Kabore: 0.0'},
{type:'famplan',text:'David C. May: 0.0'},
{type:'economics',text:'John F. Stewart: 0.0'},
{type:'famplan',text:'Susan M. Lee: 0.0'},
{type:'sociology',text:'Marilyn Espitia: 0.0'},
{type:'demography',text:'Stephen N. Simpson: 0.0'},
{type:'famplan',text:'John O. G. Billy: 0.0'},
{type:'demography',text:'Robyn Iredale: 0.0'},
{type:'famplan',text:'Christine Panchaud: 0.0'},
{type:'demography',text:'Renbao Chen: 0.0'},
{type:'eugenics',text:'Bernard Jeune: 0.0'},
{type:'demography',text:'Karen Oppenheim Mason: 0.0'},
{type:'economics',text:'Zeba A. Sathar: 0.0'},
{type:'famplan',text:'Christopher C. Weiss: 0.0'},
{type:'famplan',text:'Omaima El-Gibaly: 0.0'},
{type:'famplan',text:'Alex Chika Ezeh: 0.0'},
{type:'famplan',text:'Ahmed Al-Sabir: 0.0'},
{type:'general',text:'Nan Li: 0.0'},
{type:'eugenics',text:'Zhenglian Wang: 0.0'},
{type:'sociology',text:'Yanjie Bian: 0.0'},
{type:'demography',text:'Eugene A. Hammel: 0.0'},
{type:'statistics',text:'Shripad Tuljapurkar: 0.0'},
{type:'sociology',text:'Kimberley Peters: 0.0'},
{type:'famplan',text:'Linda J. Piccinino: 0.0'},
{type:'demography',text:'Lené Levy-Storms: 0.0'},
{type:'demography',text:'Julie A. Street: 0.0'},
{type:'demography',text:'Philip Kasinitz: 0.0'},
{type:'eugenics',text:'Zewdu Woubalem: 0.0'},
{type:'famplan',text:'SiâN L. Curtis: 0.0'},
{type:'famplan',text:'Olga Grigorievna Frolova: 0.0'},
{type:'famplan',text:'Hoang Xuyen: 0.0'},
{type:'famplan',text:'José Miguel Carranza: 0.0'},
{type:'demography',text:'Alain Blum: 0.0'},
{type:'famplan',text:'B. Oleko Tambashe: 0.0'},
{type:'demography',text:'Alan Sica: 0.0'},
{type:'economics',text:'Diane J. Macunovich: 0.0'},
{type:'famplan',text:'Margaret Newby: 0.0'},
{type:'famplan',text:'Elizabeth Mumford: 0.0'},
{type:'demography',text:'Alinda Bosch: 0.0'},
{type:'history',text:'Cheryl Elman: 0.0'},
{type:'demography',text:'Kao-Lee Liaw: 0.0'},
{type:'general',text:'Aline DéSesquelles: 0.0'},
{type:'famplan',text:'Joedo Prihartono: 0.0'},
{type:'famplan',text:'Mark R. Emerson: 0.0'},
{type:'demography',text:'Wilma Smeenk: 0.0'},
{type:'famplan',text:'Dina Feivelson: 0.0'},
{type:'eugenics',text:'A.C. Liefbroer: 0.0'},
{type:'demography',text:'Shigesato Takahashi: 0.0'},
{type:'demography',text:'Romana Peronaci: 0.0'},
{type:'demography',text:'Satomi Sakamoto: 0.0'},
{type:'famplan',text:'Noureddine Abderrahim: 0.0'},
{type:'eugenics',text:'Carol Jagger: 0.0'},
{type:'eugenics',text:'Paul Lichtenstein: 0.0'},
{type:'famplan',text:'Victoria Adeyemi: 0.0'},
{type:'famplan',text:'Jeanne Noble: 0.0'},
{type:'history',text:'Erik Beekink: 0.0'},
{type:'famplan',text:'Robert Brackbill: 0.0'},
{type:'sociology',text:'Robert M. Adelman: 0.0'},
{type:'economics',text:'Alan De Brauw: 0.0'},
{type:'economics',text:'Alan Debrauw: 0.0'},
{type:'famplan',text:'K. Navaneetham: 0.0'},
{type:'demography',text:'Rob Stephenson: 0.0'},
{type:'demography',text:'Tanya Koropeckyj-Cox: 0.0'},
{type:'sociology',text:'Deanna L. Pagnini: 0.0'},
{type:'economics',text:'Anthony P. Carnevale: 0.0'},
{type:'demography',text:'Emily Rosenbaum: 0.0'},
{type:'demography',text:'Julie A. Phillips: 0.0'},
{type:'demography',text:'Xiaoyi Jin: 0.0'},
{type:'demography',text:'Elaina Rose: 0.0'},
{type:'demography',text:'Constantijn W.A. Panis: 0.0'},
{type:'famplan',text:'Laila O. El-Zeini: 0.0'},
{type:'famplan',text:'Zhenming Xie: 0.0'},
{type:'famplan',text:'Wayan Suriastini: 0.0'},
{type:'demography',text:'E. Michael Foster: 0.0'},
{type:'economics',text:'Jere Behrman: 0.0'},
{type:'general',text:'Annareth Stols: 0.0'},
{type:'demography',text:'Maitreyi Das: 0.0'},
{type:'famplan',text:'Edward Abel: 0.0'},
{type:'demography',text:'Ann Berrington: 0.0'},
{type:'famplan',text:'Robert D. Plotnick: 0.0'},
{type:'demography',text:'Joseph L. Rodgers: 0.0'},
{type:'demography',text:'Liana C. Sayer: 0.0'},
{type:'demography',text:'Jacqueline A. Carrigan: 0.0'},
{type:'sociology',text:'William J. Haller: 0.0'},
{type:'demography',text:'Margaret L. Usdansky: 0.0'},
{type:'economics',text:'Deborah Levison: 0.0'},
{type:'demography',text:'Paul Hewett: 0.0'},
{type:'demography',text:'Simon Burgess: 0.0'},
{type:'demography',text:'Evelina Panayotova: 0.0'},
{type:'demography',text:'Anne S. Johansen: 0.0'},
{type:'demography',text:'Gabriele Doblhammer-Reiter: 0.0'},
{type:'economics',text:'Nancy Birdsall: 0.0'},
{type:'statistics',text:'Gustavo Angeles: 0.0'},
{type:'demography',text:'Marcela Cerrutti: 0.0'},
{type:'demography',text:'Eileen Diaz Mcconnell: 0.0'},
{type:'sociology',text:'Rodney Stark: 0.0'},
{type:'famplan',text:'Susan Wierzbicki: 0.0'},
{type:'demography',text:'Timothy M. Smeedeng: 0.0'},
{type:'sociology',text:'Donald W. Matteson: 0.0'},
{type:'famplan',text:'Inge Hutter: 0.0'},
{type:'demography',text:'Ma Linmao: 0.0'},
{type:'demography',text:'Tanya Kenkre: 0.0'},
{type:'demography',text:'Theresa Heintze: 0.0'},
{type:'demography',text:'Vegard Skirbekk: 0.0'},
{type:'demography',text:'Shiva S. Halli: 0.0'},
{type:'demography',text:'Silvia Giorguli Saucedo: 0.0'},
{type:'demography',text:'Quynh-Giang Tran: 0.0'},
{type:'eugenics',text:'Isabelle Romieu: 0.0'},
{type:'demography',text:'James A. Sweet: 0.0'},
{type:'famplan',text:'Jonathan Stadler: 0.0'},
{type:'famplan',text:'Diana Measham: 0.0'},
{type:'famplan',text:'Kate Miller: 0.0'},
{type:'famplan',text:'Sandra G. Garcia: 0.0'},
{type:'demography',text:'Bert Jan Flim: 0.0'},
{type:'famplan',text:'Nancy E. Reichman: 0.0'},
{type:'demography',text:'Lorenzo Moreno: 0.0'},
{type:'demography',text:'Zhongren Jing: 0.0'},
{type:'demography',text:'Gregory A. Huber: 0.0'},
{type:'demography',text:'Sami M. Huovilainen: 0.0'},
{type:'famplan',text:'Eric Seiber: 0.0'},
{type:'famplan',text:'Suzette Audam: 0.0'},
{type:'famplan',text:'Ketan Joshi: 0.0'},
{type:'demography',text:'Susan Harris: 0.0'},
{type:'demography',text:'William A. Vega: 0.0'},
{type:'demography',text:'Guo Zhigang: 0.0'},
{type:'demography',text:'José Antonio Ortega: 0.0'},
{type:'demography',text:'Anh Dang: 0.0'},
{type:'demography',text:'Josh Dewind: 0.0'},
{type:'demography',text:'Jacqueline L. Angel: 0.0'},
{type:'demography',text:'Richard B. Bernard: 0.0'},
{type:'sociology',text:'Sigal Alon: 0.0'},
{type:'demography',text:'Susan D. Stewart: 0.0'},
{type:'famplan',text:'Nyovani Janet Madise: 0.0'},
{type:'demography',text:'J. Ties Boerma: 0.0'},
{type:'famplan',text:'Karen Stein: 0.0'},
{type:'sociology',text:'William Haller: 0.0'},
{type:'famplan',text:'Davida Becker: 0.0'},
{type:'demography',text:'Hanna Van Solinge: 0.0'},
{type:'general',text:'Susan De Vos: 0.0'},
{type:'demography',text:'Gregory E. Loya: 0.0'},
{type:'demography',text:'Anne R. Pebley: 0.0'},
{type:'demography',text:'Douglas A. Granger: 0.0'},
{type:'demography',text:'Elena Vesselinov: 0.0'},
{type:'demography',text:'Audrey Singer: 0.0'},
{type:'demography',text:'Jeffrey M. Timberlake: 0.0'},
{type:'eugenics',text:'Kaushlendra K. Singh: 0.0'},
{type:'demography',text:'Rachel Willis: 0.0'},
{type:'demography',text:'Holly E. Heard: 0.0'},
{type:'demography',text:'Andrew L. Kavee: 0.0'},
{type:'general',text:'Thildé Stevens: 0.0'},
{type:'demography',text:'Emmanuelle Cambois: 0.0'},
{type:'demography',text:'Dana Glei: 0.0'},
{type:'sociology',text:'Fuqin Bian: 0.0'},
{type:'demography',text:'Chang Y. Chung: 0.0'},
{type:'demography',text:'Quincy Stewart: 0.0'},
{type:'demography',text:'John V. Pepper: 0.0'},
{type:'sociology',text:'Yuval Elmelech: 0.0'},
{type:'demography',text:'Gavin W. Jones: 0.0'},
{type:'demography',text:'Yuanreng Hu: 0.0'},
{type:'eugenics',text:'Susan A. Murphy: 0.0'},
{type:'economics',text:'Barney Cohen: 0.0'},
{type:'demography',text:'Pepper Schwartz: 0.0'},
{type:'sociology',text:'Luis Eduardo Guarnizo: 0.0'},
{type:'famplan',text:'Janet S. Moore: 0.0'},
{type:'demography',text:'Gijs C. N. Beets: 0.0'},
{type:'famplan',text:'Xiping Xu: 0.0'},
{type:'demography',text:'Anne E. Winkler: 0.0'},
{type:'demography',text:'Tomas KöGel: 0.0'},
{type:'demography',text:'Anthony Champion: 0.0'},
{type:'demography',text:'Rex Forehand: 0.0'},
{type:'demography',text:'Felix BüChel: 0.0'},
{type:'economics',text:'Richard A. Fry: 0.0'},
{type:'demography',text:'Larry Corder: 0.0'},
{type:'famplan',text:'Lori Reid: 0.0'},
{type:'demography',text:'Monica Akinyi Magadi: 0.0'},
{type:'famplan',text:'Stephen A. Norton: 0.0'},
{type:'demography',text:'Stephen Stanhope: 0.0'},
{type:'sociology',text:'Francis G. Caro: 0.0'},
{type:'demography',text:'Thomas K. Legrand: 0.0'},
{type:'famplan',text:'Maxine Whittaker: 0.0'},
{type:'famplan',text:'Linda Lacey: 0.0'},
{type:'demography',text:'Kate Offutt: 0.0'},
{type:'demography',text:'Martine Corijn: 0.0'},
{type:'demography',text:'Hugh Davies: 0.0'},
{type:'demography',text:'Gunter Steinmann: 0.0'},
{type:'famplan',text:'Laura Katzive: 0.0'},
{type:'sociology',text:'Christine Mcrae: 0.0'},
{type:'demography',text:'Stewart E. Tolnay: 0.0'},
{type:'demography',text:'Susan C. Watkins: 0.0'},
{type:'famplan',text:'Joan Leitch: 0.0'},
{type:'famplan',text:'Betsy Payn: 0.0'},
{type:'eugenics',text:'Yanyi K. Djamba: 0.0'},
{type:'demography',text:'Gretchen T. Cornwell: 0.0'},
{type:'demography',text:'Gerda Neyer: 0.0'},
{type:'sociology',text:'Yean-Ju Lee: 0.0'},
{type:'demography',text:'Alaka Malwade Basu: 0.0'},
{type:'demography',text:'Samuel Echevarria: 0.0'},
{type:'demography',text:'Michael S. Pollard: 0.0'},
{type:'demography',text:'Juan Carlos Guzman: 0.0'},
{type:'economics',text:'Antonio Yunez-Naude: 0.0'},
{type:'sociology',text:'Elizabeth Fussell: 0.0'},
{type:'famplan',text:'Wayne J. Millar: 0.0'},
{type:'famplan',text:'Anika Rahman: 0.0'},
{type:'demography',text:'Julie Jefferies: 0.0'},
{type:'demography',text:'Dirgha J. Ghimire: 0.0'},
{type:'demography',text:'Patricio Solis: 0.0'},
{type:'demography',text:'John M. Fitzgerald: 0.0'},
{type:'sociology',text:'Debra Donahoe: 0.0'},
{type:'famplan',text:'Frederick A. D. Kaona: 0.0'},
{type:'demography',text:'Samantha Friedman: 0.0'},
{type:'history',text:'Robert A. Nye: 0.0'},
{type:'demography',text:'Mary C. Waters: 0.0'},
{type:'famplan',text:'James A. Hanley: 0.0'},
{type:'demography',text:'Eric Stallard: 0.0'},
{type:'famplan',text:'Daniel Goodkind: 0.0'},
{type:'general',text:'Elizabeth Arias: 0.0'},
{type:'sociology',text:'Thomas Wells: 0.0'},
{type:'demography',text:'Zenaida R. Ravanera: 0.0'},
{type:'demography',text:'Michael Bracher: 0.0'},
{type:'demography',text:'Mary Grace Kovar: 0.0'},
{type:'economics',text:'Jason Dietrich: 0.0'},
{type:'demography',text:'Anne C. Case: 0.0'},
{type:'famplan',text:'Lori Bollinger: 0.0'},
{type:'demography',text:'Wendy Sigle: 0.0'},
{type:'famplan',text:'Teresa Sobieszczyk: 0.0'},
{type:'demography',text:'Alejandro N. Herrin: 0.0'},
{type:'demography',text:'Andrew Mason: 0.0'},
{type:'general',text:'David Canning: 0.0'},
{type:'eugenics',text:'Aat C. Liefbroer: 0.0'},
{type:'demography',text:'Carol Propper: 0.0'},
{type:'famplan',text:'Bondan Sikoki: 0.0'},
{type:'famplan',text:'Zeinab Khadr: 0.0'},
{type:'famplan',text:'Kale Feyisetan: 0.0'},
{type:'demography',text:'John C. Henretta: 0.0'},
{type:'famplan',text:'Joseph Brown: 0.0'},
{type:'demography',text:'Toby L. Parcel: 0.0'},
{type:'famplan',text:'Karungari Kiragu: 0.0'},
{type:'demography',text:'Karen Glaser: 0.0'},
{type:'demography',text:'Paul C. Hewett: 0.0'},
{type:'economics',text:'Timothy Miller: 0.0'},
{type:'demography',text:'I. O. Orubuloye: 0.0'},
{type:'demography',text:'Paul Winters: 0.0'},
{type:'famplan',text:'Minja Choe: 0.0'},
{type:'sociology',text:'Johanne Boisjoly: 0.0'},
{type:'famplan',text:'Brent Wolff: 0.0'},
{type:'demography',text:'Maria Rita Testa: 0.0'},
{type:'demography',text:'Mehrab Ali Khan: 0.0'},
{type:'demography',text:'Jeralynn S. Cossman: 0.0'},
{type:'demography',text:'Jennifer L. Glanville: 0.0'},
{type:'demography',text:'John Mollenkopf: 0.0'},
{type:'famplan',text:'Maureen J. Graham: 0.0'},
{type:'sociology',text:'Scott Sernau: 0.0'},
{type:'economics',text:'Michael Fischer: 0.0'},
{type:'demography',text:'Jacob Brody: 0.0'},
{type:'demography',text:'Yu Wentao: 0.0'},
{type:'demography',text:'Maxwell Ndigume Kwenda: 0.0'},
{type:'demography',text:'Jessica L. Baraka: 0.0'},
{type:'demography',text:'Karen Benjamin Guzzo: 0.0'},
{type:'demography',text:'Benjamin Davis: 0.0'},
{type:'demography',text:'Wei-Jun J. Yeung: 0.0'},
{type:'famplan',text:'Vincent C. Miller: 0.0'},
{type:'demography',text:'Mark S. Handcock: 0.0'},
{type:'eugenics',text:'C. Depbuur: 0.0'},
{type:'famplan',text:'John G. Haaga: 0.0'},
{type:'general',text:'Patrick Heuveline: 0.0'},
{type:'famplan',text:'Katharine Cooper-Arnold: 0.0'},
{type:'eugenics',text:'Laura Lecchini: 0.0'},
{type:'demography',text:'Stefan Hrafn Jonsson: 0.0'},
{type:'demography',text:'Hallie J. Kintner: 0.0'},
{type:'sociology',text:'Kimberley D. Peters: 0.0'},
{type:'demography',text:'Pia N. Malaney: 0.0'},
{type:'demography',text:'Jihong Liu: 0.0'},
{type:'demography',text:'Zeba A. Sathar: 0.0'},
{type:'famplan',text:'Gigi Santow: 0.0'},
{type:'demography',text:'John P. Bartkowski: 0.0'},
{type:'demography',text:'Jitka Rychtarikova: 0.0'},
{type:'eugenics',text:'Jerry J. Maples: 0.0'},
{type:'general',text:'Stephen W. Raudenbush: 0.0'},
{type:'famplan',text:'Lucky Tedrow: 0.0'},
{type:'demography',text:'Kathleen A. Lamb: 0.0'},
{type:'demography',text:'Grace Wyshak: 0.0'},
{type:'famplan',text:'Selene Oslak: 0.0'},
{type:'demography',text:'Samuel Preston: 0.0'},
{type:'famplan',text:'Assefa Hailemariam: 0.0'},
{type:'famplan',text:'Katherine Abel: 0.0'},
{type:'eugenics',text:'Theo Van Tilburg: 0.0'},
{type:'famplan',text:'Thea De Wet: 0.0'},
{type:'sociology',text:'Jimy Sanders: 0.0'},
{type:'demography',text:'Troy C. Blanchard: 0.0'},
{type:'demography',text:'Barrie Margetts: 0.0'},
{type:'history',text:'Lee A. Craig: 0.0'},
{type:'history',text:'David I. Kertzer: 0.0'},
{type:'demography',text:'Marcia K. Meyers: 0.0'},
{type:'demography',text:'Robert Ssengonzi: 0.0'},
{type:'demography',text:'Peter Uhlenberg: 0.0'},
{type:'demography',text:'Lisa S. Matthews: 0.0'},
{type:'demography',text:'Nyovani J. Madise: 0.0'},
{type:'famplan',text:'Freya Sonenstein: 0.0'},
{type:'demography',text:'Douglas Grahn: 0.0'},
{type:'history',text:'Thomas Weiss: 0.0'},
{type:'demography',text:'James Mcnally: 0.0'},
{type:'demography',text:'Robert D. Shull: 0.0'},
{type:'sociology',text:'Mary Elizabeth Hughes: 0.0'},
{type:'history',text:'Sara M. Pullum-PiñóN: 0.0'},
{type:'demography',text:'Jamie Mihoko Doyle: 0.0'},
{type:'famplan',text:'Gabriela Escudero: 0.0'},
{type:'demography',text:'Paula Griffiths: 0.0'},
{type:'sociology',text:'Dalton Conley: 0.0'},
{type:'demography',text:'Sara R. Millman: 0.0'},
{type:'demography',text:'Luis Eduardo Guarnizo: 0.0'},
{type:'famplan',text:'Cynthia Stanton: 0.0'},
{type:'demography',text:'Robert Reville: 0.0'},
{type:'famplan',text:'Gillian H.C. Foo: 0.0'},
{type:'famplan',text:'Surinder Wadhera: 0.0'},
{type:'sociology',text:'Roger Finke: 0.0'},
{type:'demography',text:'Shenyang Guo: 0.0'},
{type:'general',text:'Sarah Kahler Mustillo: 0.0'},
{type:'demography',text:'Kenneth A. Couch: 0.0'},
{type:'demography',text:'Rikiya Matsukura: 0.0'},
{type:'demography',text:'J. William Leasure: 0.0'},
{type:'demography',text:'Lee Lillard: 0.0'},
{type:'famplan',text:'Baochang Gu: 0.0'},
{type:'demography',text:'Lynette F. Hoelter: 0.0'},
{type:'general',text:'Griffith Feeney: 0.0'},
{type:'sociology',text:'Ruth R. Berg: 0.0'},
{type:'famplan',text:'Marilyn Rymer Ellwood: 0.0'},
{type:'famplan',text:'Fatma El-Zanaty: 0.0'},
{type:'famplan',text:'Simon-Pierre Tegang: 0.0'},
{type:'economics',text:'Jacob Alex Klerman: 0.0'},
{type:'economics',text:'J. Edward Taylor: 0.0'},
{type:'eugenics',text:'Elsbeth Van Dam: 0.0'},
{type:'demography',text:'Beth A. Kotchick: 0.0'},
{type:'famplan',text:'John Ssekamatte-Ssebuliba: 0.0'},
{type:'demography',text:'Younghwan Song: 0.0'},
{type:'eugenics',text:'Andreas Wienke: 0.0'},
{type:'sociology',text:'John T. Hartman: 0.0'},
{type:'famplan',text:'Trevor N. Croft: 0.0'},
{type:'demography',text:'Jean-Pierre Gonnot: 0.0'},
{type:'economics',text:'George Dyer: 0.0'},
{type:'famplan',text:'Kaushalendra K. Singh: 0.0'},
{type:'famplan',text:'Joseph Stanford: 0.0'},
{type:'demography',text:'Elizabeth Holt: 0.0'},
{type:'demography',text:'Gu Danan: 0.0'},
{type:'famplan',text:'Maletela Tuoane: 0.0'},
{type:'demography',text:'Ye Luo: 0.0'},
{type:'demography',text:'Shuzhuo Li: 0.0'},
{type:'demography',text:'Pimonpan Isarabhakdi: 0.0'},
{type:'demography',text:'Vu Manh Loi: 0.0'},
{type:'demography',text:'Shoshana Grossbard-Shechtman: 0.0'},
{type:'sociology',text:'Mary Blair-Loy: 0.0'},
{type:'demography',text:'Alfredo Lattes: 0.0'},
{type:'demography',text:'Jeremy K. Marmer: 0.0'},
{type:'demography',text:'Kerry Richter: 0.0'},
{type:'demography',text:'Debarun Majumdar: 0.0'},
{type:'demography',text:'Sanjiv Gupta: 0.0'},
{type:'demography',text:'Pau BaizáN: 0.0'},
{type:'demography',text:'Andreas Diekmann: 0.0'},
{type:'famplan',text:'Christine A. Bachrach: 0.0'},
{type:'demography',text:'Lisa A. Gennetian: 0.0'},
{type:'demography',text:'Laura Shrestha: 0.0'},
{type:'demography',text:'Alex Chika-Ezeh: 0.0'},
{type:'demography',text:'Loren Brandt: 0.0'},
{type:'demography',text:'Cynthia J. Buckley: 0.0'},
{type:'demography',text:'George C. Myers: 0.0'},
{type:'demography',text:'Brian K. Finch: 0.0'},
{type:'demography',text:'Rebecca Reddick: 0.0'},
{type:'demography',text:'John E. Knodel: 0.0'},
{type:'demography',text:'Kristen Harknett: 0.0'},
{type:'famplan',text:'Tesfaye Shiferaw: 0.0'},
{type:'sociology',text:'Marin Clarkberg: 0.0'},
{type:'famplan',text:'Anjanette Nelson-Wally: 0.0'},
{type:'famplan',text:'Amy L. Godecker: 0.0'},
{type:'demography',text:'Damon Jones: 0.0'},
{type:'sociology',text:'Lincoln H. Day: 0.0'},
{type:'demography',text:'Robert E. Jones: 0.0'},
{type:'demography',text:'Woojin Chung: 0.0'},
{type:'demography',text:'David Wypij: 0.0'},
{type:'famplan',text:'Ray Langsten: 0.0'},
{type:'demography',text:'Stephanie A. Bohon: 0.0'},
{type:'demography',text:'Yvonne Brandreth: 0.0'},
{type:'famplan',text:'Nafissatou Diop-Sidibé: 0.0'},
{type:'demography',text:'Yukio Kawano: 0.0'},
{type:'demography',text:'Nguyen Huu Minh: 0.0'},
{type:'demography',text:'Miguel N. Rivera: 0.0'},
{type:'demography',text:'Yih-Jin Young: 0.0'},
{type:'economics',text:'Jessica Gordon Nembhard: 0.0'},
{type:'demography',text:'Padma Srinivasan: 0.0'},
{type:'demography',text:'Grace Kao: 0.0'},
{type:'demography',text:'Kermyt G. Anderson: 0.0'},
{type:'demography',text:'Li-Shou Yang: 0.0'},
{type:'demography',text:'Richard W. Johnson: 0.0'},
{type:'demography',text:'Aaron Gullickson: 0.0'},
{type:'economics',text:'Yiu Por Chen: 0.0'},
{type:'famplan',text:'William L. Winfrey: 0.0'},
{type:'demography',text:'Richard Fry: 0.0'},
{type:'demography',text:'Eilidh Garrett: 0.0'},
{type:'demography',text:'Philip Guest: 0.0'},
{type:'demography',text:'Greta Gilbertson: 0.0'},
{type:'demography',text:'SiâN Curtis: 0.0'},
{type:'sociology',text:'Xiaoling Shu: 0.0'},
{type:'demography',text:'Andres Peri: 0.0'},
{type:'famplan',text:'Linda S. Peterson: 0.0'},
{type:'demography',text:'Rodolfo A. Bulatao: 0.0'},
{type:'history',text:'Sharon Sassler: 0.0'},
{type:'demography',text:'Kelly Stamper Balistreri: 0.0'},
{type:'demography',text:'Markos Ezra: 0.0'},
{type:'demography',text:'Robert E. Black: 0.0'},
{type:'demography',text:'Carol L. Roan: 0.0'},
{type:'demography',text:'Naomi Ito: 0.0'},
{type:'demography',text:'Abdolmohammed Kazemipur: 0.0'},
{type:'famplan',text:'Hantamalala Rafalimanana: 0.0'},
{type:'famplan',text:'Ndugga Baker Maggwa: 0.0'},
{type:'demography',text:'Adam Davey: 0.0'},
{type:'demography',text:'Nolan Malone: 0.0'},
{type:'demography',text:'Dimiter Philipov: 0.0'},
{type:'demography',text:'Duncan D. Chaplin: 0.0'},
{type:'demography',text:'DȧVid C. Ribar: 0.0'},
{type:'demography',text:'Akim J. Mturi: 0.0'},
{type:'demography',text:'Xiushi Yang: 0.0'},
{type:'demography',text:'Iliana Kohler: 0.0'},
{type:'famplan',text:'Bamikale Feyisetan: 0.0'},
{type:'demography',text:'Gerard Calot: 0.0'},
{type:'history',text:'Sara M. Pullum: 0.0'},
{type:'eugenics',text:'Giti Goswami: 0.0'},
{type:'famplan',text:'Victor De Silva: 0.0'},
{type:'demography',text:'Voon Chin Phua: 0.0'},
{type:'demography',text:'Steven W. Sinding: 0.0'},
{type:'demography',text:'Lei Li: 0.0'},
{type:'demography',text:'Emilio F. Moran: 0.0'},
{type:'eugenics',text:'Norman Y. Luther: 0.0'},
{type:'demography',text:'Yasuhiko Saito: 0.0'},
{type:'demography',text:'Julia Kwong: 0.0'},
{type:'demography',text:'Estela Rivero-Fuentes: 0.0'},
{type:'demography',text:'W. Henry Mosley: 0.0'},
{type:'famplan',text:'Monica A. Magadi: 0.0'},
{type:'demography',text:'Dinh Quang Pham: 0.0'},
{type:'famplan',text:'Nguyen Minh Thang: 0.0'},
{type:'demography',text:'Bussarawan Teerawichitchainan: 0.0'},
{type:'famplan',text:'Rezina Mita: 0.0'},
{type:'demography',text:'Jodi R. Sandfort: 0.0'},
{type:'demography',text:'Kimberlee A. Shauman: 0.0'},
{type:'sociology',text:'Catherine T. Kenney: 0.0'},
{type:'economics',text:'Philip L. Martin: 0.0'},
{type:'demography',text:'Eric P. Baumer: 0.0'},
{type:'demography',text:'Irene Padavic: 0.0'},
{type:'demography',text:'Alex De Sherbinin: 0.0'},
{type:'demography',text:'Joan R. Kahn: 0.0'},
{type:'demography',text:'T. Paul Schultz: 0.0'},
{type:'demography',text:'Eric R. Jensen: 0.0'},
{type:'demography',text:'Kurt Schmidheiny: 0.0'},
{type:'demography',text:'José Itzigsohn: 0.0'},
{type:'famplan',text:'Amy Kaler: 0.0'},
{type:'demography',text:'Emily M. Agree: 0.0'},
{type:'demography',text:'Hantamala Rafalimanana: 0.0'},
{type:'demography',text:'Susan M. Hauan: 0.0'},
{type:'demography',text:'Luis Rosero-Bixby: 0.0'},
{type:'eugenics',text:'D. Narayana: 0.0'},
{type:'general',text:'Gabriele Doblhammer: 0.0'},
{type:'famplan',text:'Ashraf Lasee: 0.0'},
{type:'demography',text:'Dumitru Sandu: 0.0'},
{type:'demography',text:'Raynard Kington: 0.0'},
{type:'demography',text:'Andrew S. London: 0.0'},
{type:'demography',text:'Christine Fox: 0.0'},
{type:'demography',text:'F. Scott Christopher: 0.0'},
{type:'famplan',text:'Francis Zavier: 0.0'},
{type:'sociology',text:'Elizabeth Stearns: 0.0'},
{type:'sociology',text:'Robert B. Avery: 0.0'},
{type:'sociology',text:'Jimy M. Sanders: 0.0'},
{type:'demography',text:'Michele Steinmetz: 0.0'},
{type:'famplan',text:'Anthony Pramualratana: 0.0'},
{type:'famplan',text:'Polina Kozyreva: 0.0'},
{type:'demography',text:'Anastasia Gorodzeisky: 0.0'},
{type:'sociology',text:'Rebecca Miles-Doan: 0.0'},
{type:'demography',text:'Kevin M. White: 0.0'},
{type:'demography',text:'Christophe Z. Guilmoto: 0.0'},
{type:'demography',text:'Amelie Constant: 0.0'},
{type:'demography',text:'Katherine Trent: 0.0'},
{type:'demography',text:'David Shapiro: 0.0'},
{type:'demography',text:'Laurie K. Scheuble: 0.0'},
{type:'famplan',text:'Megumi Omori: 0.0'},
{type:'demography',text:'Betsy GuzmáN: 0.0'},
{type:'eugenics',text:'Barthelemy Kuate Defo: 0.0'},
{type:'demography',text:'Harrie Van Vianen: 0.0'},
{type:'demography',text:'Magnus Lofstrom: 0.0'},
{type:'famplan',text:'Julie Morgan: 0.0'},
{type:'statistics',text:'Narayan Sastry: 0.0'},
{type:'demography',text:'Deborah Roempke Graefe: 0.0'},
{type:'sociology',text:'Susan G. Singley: 0.0'},
{type:'demography',text:'Kathleen Mcgarry: 0.0'},
{type:'demography',text:'Andrew J. Yates: 0.0'},
{type:'sociology',text:'Darren E. Sherkat: 0.0'},
{type:'demography',text:'Leora Lawton: 0.0'},
{type:'demography',text:'Linda Young-Demarco: 0.0'},
{type:'famplan',text:'Bolaji M. Fapohunda: 0.0'},
{type:'economics',text:'Paul Gertler: 0.0'},
{type:'history',text:'Hugo RöLing: 0.0'},
{type:'demography',text:'Raisa A. Bahchieva: 0.0'},
{type:'history',text:'Graham Mooney: 0.0'},
{type:'demography',text:'Antoine Bommier: 0.0'},
{type:'sociology',text:'Michael B. Aguilera: 0.0'},
{type:'sociology',text:'Ge Lin: 0.0'},
{type:'demography',text:'Andrew Fisher: 0.0'},
{type:'demography',text:'Chris Knoester: 0.0'},
{type:'famplan',text:'Pavalavalli Govindasamy: 0.0'},
{type:'economics',text:'Robert L. Clark: 0.0'},
{type:'economics',text:'William J. House: 0.0'},
{type:'demography',text:'Kristin E. Espinosa: 0.0'},
{type:'eugenics',text:'Michel Guillot: 0.0'},
{type:'demography',text:'Loraine West: 0.0'},
{type:'demography',text:'AméLie Quesnel-ValléE: 0.0'},
{type:'demography',text:'Fengyu Zhang: 0.0'},
{type:'demography',text:'Adriana Kemp: 0.0'},
{type:'demography',text:'Nathanael Lauster: 0.0'},
{type:'famplan',text:'Belay Biratu: 0.0'},
{type:'demography',text:'Nicola Standish: 0.0'},
{type:'demography',text:'Ilana Redstone: 0.0'},
{type:'demography',text:'Mignon R. Moore: 0.0'},
{type:'demography',text:'Derrick Thomas: 0.0'},
{type:'economics',text:'Rosemary Hyson: 0.0'},
{type:'sociology',text:'James M. Raymo: 0.0'},
{type:'demography',text:'Arnold Peters: 0.0'},
{type:'history',text:'Kenneth H. Fliess: 0.0'},
{type:'demography',text:'Christine Himes: 0.0'},
{type:'famplan',text:'Vicki Lamb: 0.0'},
{type:'demography',text:'Leslie F. Stone: 0.0'},
{type:'famplan',text:'A. Dharmalingam: 0.0'},
{type:'demography',text:'Wu Deqing: 0.0'},
{type:'demography',text:'Margaret E. Greene: 0.0'},
{type:'general',text:'Nancy Folbre: 0.0'},
{type:'demography',text:'Ellen Brennan: 0.0'},
{type:'demography',text:'John Hartman: 0.0'},
{type:'demography',text:'Glenn Deane: 0.0'},
{type:'demography',text:'Anna Wils: 0.0'},
{type:'famplan',text:'Elizabeth Costenbader: 0.0'},
{type:'economics',text:'Andrew D. Foster: 0.0'},
{type:'famplan',text:'Susan Chen: 0.0'},
{type:'demography',text:'Ahmet IçDuygu: 0.0'},
{type:'famplan',text:'Judith Bruce: 0.0'},
{type:'demography',text:'Vladimir Canudas Romo: 0.0'},
{type:'demography',text:'Gary Sandefur: 0.0'},
{type:'general',text:'Thomas D. Cook: 0.0'},
{type:'sociology',text:'Laura E. Geschwender: 0.0'},
{type:'famplan',text:'Kelly Martin: 0.0'},
{type:'demography',text:'Danielle W. Toussaint: 0.0'},
{type:'famplan',text:'Ann A. Way: 0.0'},
{type:'demography',text:'Dolores Acevedo: 0.0'},
{type:'demography',text:'Elizabeth Wildsmith: 0.0'},
{type:'famplan',text:'Susan Newcomer: 0.0'},
{type:'demography',text:'Ulf Christian Ewert: 0.0'},
{type:'demography',text:'René M. Zenteno: 0.0'},
{type:'demography',text:'Wilhelm Schlag: 0.0'},
{type:'sociology',text:'Ted Mouw: 0.0'},
{type:'demography',text:'Antonio Mcdaniel: 0.0'},
{type:'demography',text:'Robert Crosnoe: 0.0'},
{type:'demography',text:'Hans LundströM: 0.0'},
{type:'demography',text:'Virginia Knox: 0.0'},
{type:'demography',text:'Megan M. Sweeney: 0.0'},
{type:'demography',text:'Binyamin Gshur: 0.0'},
{type:'demography',text:'Bhanu B. Niraula: 0.0'},
{type:'famplan',text:'Rushikesh M. Maru: 0.0'},
{type:'demography',text:'Naomi Lacy: 0.0'},
{type:'demography',text:'Carl L. Bankston Iii: 0.0'},
{type:'sociology',text:'Ethan Michelson: 0.0'},
{type:'demography',text:'Namvar Zohoori: 0.0'},
{type:'sociology',text:'John H. Laub: 0.0'},
{type:'demography',text:'Eva M. Bernhardt: 0.0'},
{type:'statistics',text:'Hans-Georg MüLler: 0.0'},
{type:'demography',text:'Nagah H. Al-Bassusi: 0.0'},
{type:'famplan',text:'Dina J. Feivelson: 0.0'},
{type:'demography',text:'Zhongdong Ma: 0.0'},
{type:'famplan',text:'Thomas Schindlmayr: 0.0'},
{type:'demography',text:'James C. Witte: 0.0'},
{type:'sociology',text:'David Spener: 0.0'},
{type:'demography',text:'Georgina Binstock: 0.0'},
{type:'famplan',text:'Gereltuya Altankhuyag: 0.0'},
{type:'demography',text:'Chiara Capoferro: 0.0'},
{type:'eugenics',text:'Mhairi Gibson: 0.0'},
{type:'famplan',text:'Margaret M. Schulte: 0.0'},
{type:'demography',text:'Susan Jayne: 0.0'},
{type:'famplan',text:'Ruth E. Bessinger: 0.0'},
{type:'economics',text:'Michael Baker: 0.0'},
{type:'demography',text:'Mary E. Corcoran: 0.0'},
{type:'demography',text:'A. J. Francis Zavier: 0.0'},
{type:'demography',text:'Belinda S. Chen: 0.0'},
{type:'demography',text:'Dennis Hodgson: 0.0'},
{type:'general',text:'Tukufu Zuberi: 0.0'},
{type:'demography',text:'Sunita Bose: 0.0'},
{type:'sociology',text:'Emily Hannum: 0.0'},
{type:'sociology',text:'Kristen W. Springer: 0.0'},
{type:'demography',text:'Iqbal Alam: 0.0'},
{type:'sociology',text:'Leah K. Vanwey: 0.0'},
{type:'demography',text:'Toni Zhang: 0.0'},
{type:'famplan',text:'Michele Bolzan: 0.0'},
{type:'demography',text:'Alden Speare Jr.: 0.0'},
{type:'economics',text:'David C. Stapleton: 0.0'},
{type:'demography',text:'Louis G. Pol: 0.0'},
{type:'demography',text:'Paula Fomby: 0.0'},
{type:'famplan',text:'Lea Trujillo: 0.0'},
{type:'demography',text:'T. R. Balakrishman: 0.0'},
{type:'famplan',text:'Gora Mboup: 0.0'},
{type:'demography',text:'Roxane Silberman: 0.0'},
{type:'economics',text:'Frances Vavrus: 0.0'},
{type:'demography',text:'Randy Hart: 0.0'},
{type:'demography',text:'Katherine Hempstead: 0.0'},
{type:'demography',text:'Larry Bumpass: 0.0'},
{type:'demography',text:'James Cherng-Tay Hsueh: 0.0'},
{type:'demography',text:'Melonie Heron: 0.0'},
{type:'demography',text:'Susan H. Jayne: 0.0'},
{type:'demography',text:'Rene Zenteno: 0.0'},
{type:'sociology',text:'Patricia A. Mcmanus: 0.0'},
{type:'economics',text:'Susan H. Cochrane: 0.0'},
{type:'general',text:'Wendy R. Ewart: 0.0'},
{type:'demography',text:'Donna Ruane Morrison: 0.0'},
{type:'general',text:'Jim Oeppen: 0.0'},
{type:'famplan',text:'Amir H. Merhyar: 0.0'},
{type:'eugenics',text:'Mariana Mourgova: 0.0'},
{type:'demography',text:'Regina M. Bures: 0.0'},
{type:'demography',text:'Karen L. Kramer: 0.0'},
{type:'eugenics',text:'Tarun K. Roy: 0.0'},
{type:'demography',text:'Michael Murphy: 0.0'},
{type:'demography',text:'Sarah Avellar: 0.0'},
{type:'famplan',text:'Joseph J. Murphy: 0.0'},
{type:'sociology',text:'Dana L. Haynie: 0.0'},
{type:'demography',text:'Stuart R. Gaffin: 0.0'},
{type:'demography',text:'Carolyn A. Liebler: 0.0'},
{type:'famplan',text:'Cynthia Harper: 0.0'},
{type:'eugenics',text:'Sharon Yan: 0.0'},
{type:'demography',text:'Elizabeth M. Grieco: 0.0'},
{type:'demography',text:'Maria Krysan: 0.0'},
{type:'demography',text:'S. Karthick Ramakrishnan: 0.0'},
{type:'demography',text:'Patricia H. Craig: 0.0'},
{type:'demography',text:'Leonid Darsky: 0.0'},
{type:'famplan',text:'Jacqueline Darroch Forrest: 0.0'},
{type:'demography',text:'Debra S. Judge: 0.0'},
{type:'famplan',text:'Elof Johansson: 0.0'},
{type:'demography',text:'Shiro Horiuchi: 0.0'},
{type:'sociology',text:'Deborah Barrett: 0.0'},
{type:'demography',text:'Quanhe Yang: 0.0'},
{type:'demography',text:'James C. Knowles: 0.0'},
{type:'demography',text:'Nimfa B. Ogena: 0.0'},
{type:'demography',text:'Jose Antonio Ortega Osona: 0.0'},
{type:'demography',text:'Ansley J. Coale: 0.0'},
{type:'demography',text:'Rachel A. Gordon: 0.0'},
{type:'demography',text:'Judith Banister: 0.0'},
{type:'general',text:'Rene M. Zenteno: 0.0'},
{type:'demography',text:'Constantijn W. A. Panis: 0.0'},
{type:'demography',text:'M. A. Lee: 0.0'},
{type:'demography',text:'Wendy Sigle-Rushton: 0.0'},
{type:'sociology',text:'Michelle J. Budig: 0.0'},
{type:'demography',text:'Stephanie A. Bond Huie: 0.0'},
{type:'demography',text:'John F. Sandberg: 0.0'},
{type:'demography',text:'Laura Stark: 0.0'},
{type:'eugenics',text:'Labananda Choudhury: 0.0'},
{type:'demography',text:'Berna Miller Torr: 0.0'},
{type:'demography',text:'Michael Anderson: 0.0'},
{type:'demography',text:'Paula Tufis: 0.0'},
{type:'sociology',text:'Kim M. Lloyd: 0.0'},
{type:'famplan',text:'Gilda Sedgh: 0.0'},
{type:'history',text:'Kate Fisher: 0.0'},
{type:'economics',text:'John Strauss: 0.0'},
{type:'demography',text:'Allan M. Parnell: 0.0'},
{type:'sociology',text:'R.S. Oropesa: 0.0'}
];
var comps = [
{type:'info',text:'Nodes: 25.0: Density: 0.46'},
{type:'economics',text:'Paul R. Ehrlich: 0.79'},
{type:'general',text:'Karl-GöRan MäLer: 0.63'},
{type:'general',text:'Partha Dasgupta: 0.63'},
{type:'general',text:'Jacques Du Guerny: 0.63'},
{type:'general',text:'Bengt-Owe Jansson: 0.63'},
{type:'general',text:'Ann Kinzig: 0.63'},
{type:'general',text:'Domenico Siniscalco: 0.63'},
{type:'general',text:'Gretchen Daily: 0.63'},
{type:'general',text:'Carl Folke: 0.63'},
{type:'general',text:'Brian Walker: 0.63'},
{type:'general',text:'Per Pinstrup-Andersen: 0.63'},
{type:'general',text:'Ann Mari Jansson: 0.63'},
{type:'general',text:'Simon Levin: 0.63'},
{type:'general',text:'Nils Kautsky: 0.63'},
{type:'general',text:'Pierre Crosson: 0.63'},
{type:'general',text:'Bert Bolin: 0.63'},
{type:'demography',text:'Jianguo Liu: 0.29'},
{type:'demography',text:'Zhiyun Ouyang: 0.17'},
{type:'demography',text:'Yingchun Tan: 0.17'},
{type:'demography',text:'Heming Zhang: 0.17'},
{type:'demography',text:'Jian Yang: 0.17'},
{type:'demography',text:'Angela G. Mertig: 0.08'},
{type:'demography',text:'Li An: 0.08'},
{type:'economics',text:'Jian-Guo Zhong: 0.04'},
{type:'demography',text:'Gretchen C. Daily: 0.04'},
{type:'info',text:'Nodes: 4.0: Density: 1.0'},
{type:'famplan',text:'J. Richard Udry: 1.0'},
{type:'famplan',text:'Pamela J. Schwingl: 1.0'},
{type:'famplan',text:'Bea J. Van Den Berg: 1.0'},
{type:'famplan',text:'Monica Gaughan: 1.0'},
{type:'info',text:'Nodes: 3.0: Density: 0.67'},
{type:'famplan',text:'Harriet B. Presser: 1.0'},
{type:'eugenics',text:'Maitreyi Bordia Das: 0.5'},
{type:'famplan',text:'Jane Lawler Dye: 0.5'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'famplan',text:'Bernard Pillet: 1.0'},
{type:'famplan',text:'Dudley Kirk: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'demography',text:'Suzanne M. Bianchi: 1.0'},
{type:'demography',text:'Kei M. Nomaguchi: 1.0'},
{type:'info',text:'Unconnected:'},
{type:'demography',text:'Kingsley Davis'},
{type:'famplan',text:'Ronald Freedman'},
{type:'demography',text:'Nathan Keyfitz'},
{type:'demography',text:'Norman B. Ryder'},
{type:'demography',text:'Paul Demeny'}
];
var authors = 1608;
 var density = 0.0;
 var components = 6;
-->