<!--
 var comp1 = [
{type:'info',text:'Nodes: 555.0: Density: 0.01'},
{type:'demography',text:'James Trussell: 0.05'},
{type:'demography',text:'James A. Palmore: 0.04'},
{type:'pubh',text:'Roger W. Rochat: 0.03'},
{type:'demography',text:'Charles F. Westoff: 0.03'},
{type:'famplan',text:'Leo Morris: 0.03'},
{type:'famplan',text:'Robert G. Potter: 0.03'},
{type:'pubh',text:'John E. Anderson: 0.03'},
{type:'famplan',text:'T. James Trussell: 0.03'},
{type:'famplan',text:'James F. Phillips: 0.03'},
{type:'sociology',text:'Ronald R. Rindfuss: 0.03'},
{type:'demography',text:'J. Chakraborty: 0.03'},
{type:'demography',text:'Anthony R. Measham: 0.03'},
{type:'demography',text:'John Knodel: 0.03'},
{type:'demography',text:'Ronald Freedman: 0.03'},
{type:'famplan',text:'Lincoln C. Chen: 0.02'},
{type:'famplan',text:'Noreen Goldman: 0.02'},
{type:'demography',text:'Atiqur Rahman Khan: 0.02'},
{type:'famplan',text:'Somsak Varakamin: 0.02'},
{type:'demography',text:'Jane Menken: 0.02'},
{type:'demography',text:'Albert I. Hermalin: 0.02'},
{type:'demography',text:'Jane T. Bertrand: 0.02'},
{type:'demography',text:'Anne R. Pebley: 0.02'},
{type:'demography',text:'Barbara Janowitz: 0.02'},
{type:'demography',text:'Phillips Cutright: 0.02'},
{type:'pubh',text:'Willard Cates Jr.: 0.02'},
{type:'demography',text:'Jacqueline Darroch Forrest: 0.02'},
{type:'history',text:'Stanley L. Engerman: 0.02'},
{type:'pubh',text:'Ruth Simmons: 0.02'},
{type:'famplan',text:'Haryono Suyono: 0.02'},
{type:'general',text:'Kenneth W. Wachter: 0.02'},
{type:'economics',text:'Dorothy Fernandez: 0.02'},
{type:'history',text:'Robert W. Fogel: 0.02'},
{type:'famplan',text:'Alan Keller: 0.02'},
{type:'famplan',text:'Makhlisur Rahman: 0.02'},
{type:'history',text:'Kenneth Sokoloff: 0.02'},
{type:'demography',text:'John A. Ross: 0.02'},
{type:'famplan',text:'Roger C. Avery: 0.02'},
{type:'famplan',text:'Christopher Tietze: 0.02'},
{type:'demography',text:'Douglas L. Anderton: 0.02'},
{type:'history',text:'Gerald Friedman: 0.02'},
{type:'demography',text:'Nasra M. Shah: 0.02'},
{type:'sociology',text:'Dennis P. Hogan: 0.02'},
{type:'demography',text:'Robert W. Gardner: 0.02'},
{type:'famplan',text:'Jack C. Smith: 0.02'},
{type:'famplan',text:'George B. Simmons: 0.02'},
{type:'history',text:'Georgia Villaflor: 0.02'},
{type:'statistics',text:'Samuel H. Preston: 0.02'},
{type:'famplan',text:'Felix Mascarin: 0.02'},
{type:'famplan',text:'Jerald Bailey: 0.02'},
{type:'history',text:'Roderick Floud: 0.02'},
{type:'general',text:'A. K. M. Alauddin Chowdhury: 0.02'},
{type:'history',text:'Richard H. Steckel: 0.02'},
{type:'general',text:'Ansley J. Coale: 0.02'},
{type:'famplan',text:'Roy G. Smith: 0.02'},
{type:'famplan',text:'Suraiya Jabeen: 0.02'},
{type:'history',text:'Robert A. Margo: 0.02'},
{type:'famplan',text:'Michael J. Rosenberg: 0.02'},
{type:'famplan',text:'Jay D. Teachman: 0.02'},
{type:'famplan',text:'Arland Thornton: 0.01'},
{type:'pubh',text:'Charles W. Warren: 0.01'},
{type:'demography',text:'James Mccarthy: 0.01'},
{type:'famplan',text:'Irving Sivin: 0.01'},
{type:'sociology',text:'Charles Hirschman: 0.01'},
{type:'famplan',text:'B. D. Misra: 0.01'},
{type:'famplan',text:'Te-Hsiung Sun: 0.01'},
{type:'demography',text:'John Bongaarts: 0.01'},
{type:'famplan',text:'Shushum Bhatia: 0.01'},
{type:'famplan',text:'Sandra L. Huffman: 0.01'},
{type:'famplan',text:'Stanley K. Henshaw: 0.01'},
{type:'demography',text:'James T. Fawcett: 0.01'},
{type:'famplan',text:'Barbara Vaughan: 0.01'},
{type:'famplan',text:'Jose Garcia-Nunez: 0.01'},
{type:'famplan',text:'Jacqueline D. Forrest: 0.01'},
{type:'demography',text:'Siew-Ean Khoo: 0.01'},
{type:'famplan',text:'Tony Bennett: 0.01'},
{type:'famplan',text:'Allan Rosenfield: 0.01'},
{type:'famplan',text:'Aida Torres: 0.01'},
{type:'demography',text:'H. Bond: 0.01'},
{type:'general',text:'Rose E. Frisch: 0.01'},
{type:'famplan',text:'Dale N. Robertson: 0.01'},
{type:'demography',text:'Fred Arnold: 0.01'},
{type:'eugenics',text:'Tan Boon Ann: 0.01'},
{type:'demography',text:'N. L. Aziz: 0.01'},
{type:'famplan',text:'Stan Dsouza: 0.01'},
{type:'famplan',text:'Suwardjono Surjaningrat: 0.01'},
{type:'famplan',text:'Jalaluddin Akbar: 0.01'},
{type:'demography',text:'Elise F. Jones: 0.01'},
{type:'famplan',text:'Richard Lincoln: 0.01'},
{type:'famplan',text:'Ming-Cheng Chang: 0.01'},
{type:'famplan',text:'Elsimar Coutinho: 0.01'},
{type:'famplan',text:'Marilyn B. Hirsch: 0.01'},
{type:'famplan',text:'G. Roberto Santiso: 0.01'},
{type:'famplan',text:'Gerry E. Hendershot: 0.01'},
{type:'famplan',text:'Olivia Mcdonald: 0.01'},
{type:'demography',text:'Robert M. Hauser: 0.01'},
{type:'famplan',text:'Richard S. Monteith: 0.01'},
{type:'famplan',text:'Pentti Holma: 0.01'},
{type:'famplan',text:'Frederick S. Jaffe: 0.01'},
{type:'famplan',text:'Francisco Alvarez-Sanchez: 0.01'},
{type:'general',text:'W. Henry Mosley: 0.01'},
{type:'famplan',text:'Barbara L. Lindheim: 0.01'},
{type:'famplan',text:'Peter C. Miller: 0.01'},
{type:'famplan',text:'W. H. Mosley: 0.01'},
{type:'famplan',text:'Patricia G. Steinhoff: 0.01'},
{type:'demography',text:'L. Corsa: 0.01'},
{type:'general',text:'Gordon F. De Jong: 0.01'},
{type:'demography',text:'J. T. Johnson: 0.01'},
{type:'famplan',text:'Soledad Diaz: 0.01'},
{type:'demography',text:'Young J. Kim: 0.01'},
{type:'demography',text:'Mary Chamie: 0.01'},
{type:'famplan',text:'Lolagene C. Coombs: 0.01'},
{type:'famplan',text:'A. I. Chowdhury: 0.01'},
{type:'demography',text:'Peerasit Kamnuansilpa: 0.01'},
{type:'demography',text:'R. Chander: 0.01'},
{type:'famplan',text:'William R. Grady: 0.01'},
{type:'famplan',text:'Hasina Banu: 0.01'},
{type:'pubh',text:'Stan Bernstein: 0.01'},
{type:'demography',text:'B. A. Tan: 0.01'},
{type:'famplan',text:'Larry L. Bumpass: 0.01'},
{type:'famplan',text:'Mark C. E. Cheng: 0.01'},
{type:'famplan',text:'Susan E. Holck: 0.01'},
{type:'demography',text:'J. Mayone Stycos: 0.01'},
{type:'famplan',text:'Nicholas H. Wright: 0.01'},
{type:'famplan',text:'Odon Frutos: 0.01'},
{type:'famplan',text:'Roberto Kriskovich: 0.01'},
{type:'demography',text:'Linda G. Martin: 0.01'},
{type:'famplan',text:'Larry Bumpass: 0.01'},
{type:'famplan',text:'Kenneth F. Schulz: 0.01'},
{type:'famplan',text:'Atef M. Khalifa: 0.01'},
{type:'demography',text:'Kari Pitkanen: 0.01'},
{type:'famplan',text:'Walter Rodrigues: 0.01'},
{type:'demography',text:'Geraldine P. Mineau: 0.01'},
{type:'famplan',text:'Hussein Abdel-Aziz Sayed: 0.01'},
{type:'demography',text:'Mary Beth Weinberger: 0.01'},
{type:'famplan',text:'John B. Casterline: 0.01'},
{type:'famplan',text:'Juan Schoemaker: 0.01'},
{type:'eugenics',text:'Aldur W. Eriksson: 0.01'},
{type:'eugenics',text:'P. Gene Trapp: 0.01'},
{type:'famplan',text:'M. Obaidullah: 0.01'},
{type:'famplan',text:'S. Bruce Schearer: 0.01'},
{type:'famplan',text:'Ann Way: 0.01'},
{type:'demography',text:'Carmen Miro: 0.01'},
{type:'sociology',text:'Craig St. John: 0.01'},
{type:'demography',text:'Samuel Preston: 0.01'},
{type:'famplan',text:'John Hobcraft: 0.01'},
{type:'eugenics',text:'James H. Mielke: 0.01'},
{type:'demography',text:'J. Trussell: 0.01'},
{type:'famplan',text:'Aziz Bindary: 0.01'},
{type:'eugenics',text:'Lynn B. Jorde: 0.01'},
{type:'demography',text:'Benjamin V. Carino: 0.01'},
{type:'demography',text:'Ricardo G. Abad: 0.01'},
{type:'famplan',text:'Susan Eisman: 0.01'},
{type:'famplan',text:'Martin E. Gorosh: 0.01'},
{type:'famplan',text:'Atiqur R. Khan: 0.01'},
{type:'demography',text:'Bernard Berelson: 0.01'},
{type:'famplan',text:'Tongplaew Narkavonnakit: 0.01'},
{type:'demography',text:'W. Rodrigues: 0.01'},
{type:'demography',text:'Neil G. Bennett: 0.01'},
{type:'demography',text:'W. Parker Mauldin: 0.01'},
{type:'demography',text:'Mercedes Concepcion: 0.01'},
{type:'famplan',text:'Robert D. Retherford: 0.01'},
{type:'famplan',text:'Charles H. C. Chen: 0.01'},
{type:'famplan',text:'Deirdre Wulf: 0.01'},
{type:'famplan',text:'Aurora Rabago De Rodriguez: 0.01'},
{type:'sociology',text:'S. Philip Morgan: 0.01'},
{type:'famplan',text:'Wayne S. Stinson: 0.01'},
{type:'famplan',text:'Frances E. Kobrin: 0.01'},
{type:'famplan',text:'Lee-Jay Cho: 0.01'},
{type:'famplan',text:'John Cleland: 0.01'},
{type:'famplan',text:'Laurie S. Zabin: 0.01'},
{type:'demography',text:'Susheela Singh: 0.01'},
{type:'famplan',text:'S. Elizabeth Kelly: 0.01'},
{type:'famplan',text:'James E. Higgins: 0.01'},
{type:'famplan',text:'Attaher H. Toure: 0.01'},
{type:'famplan',text:'C. S. Chung: 0.01'},
{type:'famplan',text:'Loh Sow Khin: 0.01'},
{type:'famplan',text:'Jorge Martinez-Manautou: 0.01'},
{type:'famplan',text:'Insook Han Park: 0.01'},
{type:'famplan',text:'Margaret Terry Orr: 0.01'},
{type:'famplan',text:'Janet B. Hardy: 0.01'},
{type:'famplan',text:'Ali Ashraf: 0.01'},
{type:'famplan',text:'Nancy J. Binkin: 0.01'},
{type:'famplan',text:'Susan M. Rogers: 0.01'},
{type:'famplan',text:'Michael J. Furlong: 0.01'},
{type:'famplan',text:'Jay S. Friedman: 0.01'},
{type:'famplan',text:'Sriani Basnayake: 0.01'},
{type:'demography',text:'A. M. T. Thome: 0.01'},
{type:'famplan',text:'J. S. Parsons: 0.01'},
{type:'famplan',text:'Donald E. Morisky: 0.01'},
{type:'demography',text:'J. Dennis Willigan: 0.01'},
{type:'sociology',text:'Andrew Cherlin: 0.01'},
{type:'famplan',text:'Rosa Judith Cisneros: 0.01'},
{type:'famplan',text:'Francis X. Buchmeier: 0.01'},
{type:'demography',text:'Byoung Mohk Choi: 0.01'},
{type:'famplan',text:'A. M. Sardar: 0.01'},
{type:'demography',text:'Karen Oppenheim Mason: 0.01'},
{type:'famplan',text:'Laura M. Souder: 0.01'},
{type:'famplan',text:'Yusof Bakar: 0.01'},
{type:'famplan',text:'Brigitte Doring-Bradley: 0.01'},
{type:'famplan',text:'Chin S. Chung: 0.01'},
{type:'famplan',text:'Ricardo Aparico Jimenez: 0.01'},
{type:'demography',text:'L. Morris: 0.01'},
{type:'general',text:'Janet W. Mcarthur: 0.01'},
{type:'famplan',text:'German Rodriguez: 0.01'},
{type:'famplan',text:'Prayoon Klinshom: 0.01'},
{type:'famplan',text:'Robert J. Lapham: 0.01'},
{type:'famplan',text:'Varaporn Devaphalin: 0.01'},
{type:'demography',text:'Etienne Van De Walle: 0.01'},
{type:'famplan',text:'Milton Diamond: 0.01'},
{type:'demography',text:'Lee L. Bean: 0.01'},
{type:'demography',text:'H. I. Goldberg: 0.01'},
{type:'demography',text:'Gary H. Mcclelland: 0.01'},
{type:'famplan',text:'Patricia Steinhoff: 0.01'},
{type:'famplan',text:'M. Subbiah: 0.01'},
{type:'famplan',text:'Nadine N. Burton: 0.01'},
{type:'famplan',text:'Shamsuddin Bin Abdul Rahman: 0.01'},
{type:'famplan',text:'M. Lamine Traore: 0.01'},
{type:'economics',text:'Barbara Entwisle: 0.01'},
{type:'general',text:'William E. Bertrand: 0.01'},
{type:'demography',text:'J. N. Hobcraft: 0.01'},
{type:'famplan',text:'Ronald J. Pion: 0.01'},
{type:'famplan',text:'Juan Guillermo Figueroa: 0.01'},
{type:'famplan',text:'Joaquim Barreto Fonseca: 0.01'},
{type:'famplan',text:'Milton S. Nakamura: 0.01'},
{type:'famplan',text:'Calvin Goldscheider: 0.01'},
{type:'famplan',text:'George F. Brown: 0.01'},
{type:'famplan',text:'Sam Taylor: 0.01'},
{type:'demography',text:'Katherine A. Lynch: 0.01'},
{type:'famplan',text:'Ellen Sullivan: 0.01'},
{type:'sociology',text:'John N. Koffel: 0.01'},
{type:'demography',text:'Hernan Delgado: 0.01'},
{type:'famplan',text:'Oscar Harkavy: 0.01'},
{type:'famplan',text:'Laurie Schwab Zabin: 0.01'},
{type:'famplan',text:'Deborah L. Covington: 0.01'},
{type:'famplan',text:'Minja Kim Choe: 0.01'},
{type:'famplan',text:'Lois E. Paul: 0.01'},
{type:'famplan',text:'Peter Patta Sumbung: 0.01'},
{type:'sociology',text:'Robert W. Hodge: 0.01'},
{type:'demography',text:'Celeste M. Smucker: 0.01'},
{type:'famplan',text:'A. S. G. Faruque: 0.01'},
{type:'famplan',text:'Farquhar Stirling: 0.01'},
{type:'famplan',text:'Nancy Piet: 0.01'},
{type:'famplan',text:'Anthony Bennett: 0.01'},
{type:'demography',text:'Carlos Welti-Chanes: 0.01'},
{type:'famplan',text:'M. Soedarmadi: 0.01'},
{type:'famplan',text:'David A. Grimes: 0.01'},
{type:'demography',text:'Amy Ong Tsui: 0.01'},
{type:'famplan',text:'Rohadi: 0.01'},
{type:'demography',text:'Apichat Chamratrithirong: 0.01'},
{type:'demography',text:'V. C. Chidambaram: 0.01'},
{type:'sociology',text:'Harry P. Travis: 0.01'},
{type:'famplan',text:'Jose Maria Arruda: 0.01'},
{type:'demography',text:'Debra Stempel: 0.01'},
{type:'famplan',text:'Kabamba Nkamany: 0.01'},
{type:'demography',text:'Baron Moots: 0.01'},
{type:'demography',text:'Stephen J. Williams: 0.01'},
{type:'demography',text:'Ozer Babakol: 0.01'},
{type:'famplan',text:'James W. Brackett: 0.01'},
{type:'demography',text:'Gary S. Littman: 0.01'},
{type:'famplan',text:'A. Hartoadi: 0.01'},
{type:'famplan',text:'Jane S. Delung: 0.01'},
{type:'famplan',text:'Jeremiah Sullivan: 0.01'},
{type:'famplan',text:'Maureen A. Cotterill: 0.01'},
{type:'famplan',text:'Douglas H. Huber: 0.01'},
{type:'famplan',text:'Hazel Ashurst: 0.01'},
{type:'demography',text:'Charles J. Mode: 0.01'},
{type:'demography',text:'Anrudh K. Jain: 0.01'},
{type:'demography',text:'Maxine Weinstein: 0.01'},
{type:'demography',text:'K. Hill: 0.01'},
{type:'demography',text:'Eric Jensen: 0.01'},
{type:'demography',text:'Charles Hammerslough: 0.01'},
{type:'general',text:'David Knoke: 0.01'},
{type:'famplan',text:'Donald Lauro: 0.01'},
{type:'demography',text:'Allan G. Hill: 0.01'},
{type:'demography',text:'John F. Kantner: 0.01'},
{type:'famplan',text:'Nelma Keen: 0.01'},
{type:'famplan',text:'J. M. Tuladhar: 0.01'},
{type:'famplan',text:'Tze-Hwa Fan: 0.01'},
{type:'demography',text:'Wendy C. Wolf: 0.01'},
{type:'demography',text:'George W. Barclay: 0.01'},
{type:'sociology',text:'Peter J. Dickinson: 0.01'},
{type:'demography',text:'Michael A. Stoto: 0.01'},
{type:'famplan',text:'S. S. Ratnam: 0.01'},
{type:'famplan',text:'Jose Antonio Solis: 0.01'},
{type:'famplan',text:'Angela M. De Mendoza: 0.01'},
{type:'famplan',text:'Sergio Correu Azcona: 0.01'},
{type:'demography',text:'J. A. Ross: 0.01'},
{type:'famplan',text:'Linda Atkinson: 0.01'},
{type:'famplan',text:'Md. Yunus: 0.01'},
{type:'famplan',text:'Sou-Pen Wei: 0.01'},
{type:'eugenics',text:'V. T. Palan: 0.01'},
{type:'famplan',text:'Y. M. Wong: 0.01'},
{type:'famplan',text:'Carl W. Tyler Jr.: 0.01'},
{type:'demography',text:'Celeste Smucker: 0.01'},
{type:'famplan',text:'Chusie Sujpluem: 0.01'},
{type:'demography',text:'Michael R. Haines: 0.01'},
{type:'demography',text:'Thomas W. Pullum: 0.01'},
{type:'famplan',text:'Jorge Garcia Pena: 0.01'},
{type:'famplan',text:'Christine E. Colven: 0.01'},
{type:'famplan',text:'Allan G. Rosenfield: 0.01'},
{type:'demography',text:'Michael K. Salemi: 0.01'},
{type:'pubh',text:'James D. Shelton: 0.01'},
{type:'demography',text:'Michael Hout: 0.01'},
{type:'famplan',text:'George Simmons: 0.01'},
{type:'famplan',text:'R. Henry Pardoko: 0.01'},
{type:'famplan',text:'Samuel D. Clark Jr.: 0.01'},
{type:'famplan',text:'Joaquin A. Nunez: 0.01'},
{type:'famplan',text:'Jorge Campos Cordero: 0.01'},
{type:'demography',text:'Zenas M. Sykes: 0.01'},
{type:'famplan',text:'Melvin Zelnik: 0.01'},
{type:'general',text:'John Shelton Reed: 0.01'},
{type:'history',text:'Donald J. Bogue: 0.01'},
{type:'famplan',text:'William R. Kelly: 0.01'},
{type:'famplan',text:'Wongsokusumo Bahrawi: 0.01'},
{type:'demography',text:'Florentina Reyes Salvail: 0.01'},
{type:'famplan',text:'Ricardo Castaneda Rugamas: 0.01'},
{type:'famplan',text:'Donald W. Maccorquodale: 0.01'},
{type:'demography',text:'William H. Frey: 0.01'},
{type:'demography',text:'William D. Mosher: 0.01'},
{type:'famplan',text:'Allen L. Schirm: 0.01'},
{type:'famplan',text:'Edward A. Smith: 0.01'},
{type:'famplan',text:'Alfredo Gallegos: 0.01'},
{type:'famplan',text:'Raul Rodriguez-Barocio: 0.01'},
{type:'famplan',text:'Manuel Urbina-Fuentes: 0.01'},
{type:'famplan',text:'Bruce Schearer: 0.0'},
{type:'demography',text:'S. O. Rutstein: 0.0'},
{type:'famplan',text:'Carol Measham: 0.0'},
{type:'famplan',text:'Miguel Gomez Barrantes: 0.0'},
{type:'sociology',text:'Sara Arber: 0.0'},
{type:'famplan',text:'Linda E. Atkinson: 0.0'},
{type:'statistics',text:'Stan Becker: 0.0'},
{type:'demography',text:'K. Ford: 0.0'},
{type:'famplan',text:'Lillian Tao: 0.0'},
{type:'demography',text:'John Stoeckel: 0.0'},
{type:'famplan',text:'Kanchana Kanchanasinith: 0.0'},
{type:'famplan',text:'John C. Chao: 0.0'},
{type:'demography',text:'J. W. Mcdonald: 0.0'},
{type:'economics',text:'Harvey A. Garn: 0.0'},
{type:'demography',text:'Andrew Mason: 0.0'},
{type:'famplan',text:'Roy O. Greep: 0.0'},
{type:'famplan',text:'Hui-Sheng Lin: 0.0'},
{type:'demography',text:'Michael A. Strong: 0.0'},
{type:'eugenics',text:'David E. Bloom: 0.0'},
{type:'demography',text:'Carol A. Nickerson: 0.0'},
{type:'famplan',text:'Melita Gesche: 0.0'},
{type:'famplan',text:'Napaporn Chayovan: 0.0'},
{type:'demography',text:'David Hittle: 0.0'},
{type:'demography',text:'Shea Rutstein: 0.0'},
{type:'famplan',text:'Maria Antonieta Pineda: 0.0'},
{type:'famplan',text:'Makhdoom A. Shah: 0.0'},
{type:'famplan',text:'Wan Fook-Kee: 0.0'},
{type:'famplan',text:'Raymond L. Langsten: 0.0'},
{type:'demography',text:'W. E. Bertrand: 0.0'},
{type:'sociology',text:'David R. Johnson: 0.0'},
{type:'famplan',text:'Andrew D. Foster: 0.0'},
{type:'famplan',text:'James Allman: 0.0'},
{type:'famplan',text:'Suthon Panyadilok: 0.0'},
{type:'demography',text:'Ron Lesthaeghe: 0.0'},
{type:'famplan',text:'Nancy Binkin: 0.0'},
{type:'famplan',text:'Chai Bin Park: 0.0'},
{type:'demography',text:'R. T. Ravenholt: 0.0'},
{type:'demography',text:'Maurice M. Macdonald: 0.0'},
{type:'demography',text:'G. Myriam OrdóñEz: 0.0'},
{type:'demography',text:'Peter C. Smith: 0.0'},
{type:'famplan',text:'Kwanchai Thaithong: 0.0'},
{type:'famplan',text:'Gerard Calot: 0.0'},
{type:'history',text:'Myron P. Gutmann: 0.0'},
{type:'demography',text:'Sayed Babur Hussain: 0.0'},
{type:'demography',text:'Miatudila Malonga: 0.0'},
{type:'sociology',text:'Moshe Semyonov: 0.0'},
{type:'history',text:'Susan Watkins: 0.0'},
{type:'famplan',text:'Aphichat Chamratrithirong: 0.0'},
{type:'famplan',text:'Ellen Blaine: 0.0'},
{type:'famplan',text:'Evelyn Folch-Lyon: 0.0'},
{type:'famplan',text:'S. Y. S. B. Herath: 0.0'},
{type:'general',text:'William H. Sewell: 0.0'},
{type:'economics',text:'Harbans Singh: 0.0'},
{type:'demography',text:'John C. Turner: 0.0'},
{type:'famplan',text:'Walter RodríGues: 0.0'},
{type:'demography',text:'Donald R. Mcneil: 0.0'},
{type:'demography',text:'Napaporn Havanon: 0.0'},
{type:'demography',text:'Gretchen Berggren: 0.0'},
{type:'famplan',text:'Zenas Sykes: 0.0'},
{type:'demography',text:'T. R. Balakrishnan: 0.0'},
{type:'famplan',text:'Deborah Maine: 0.0'},
{type:'famplan',text:'Antonio Marcio Tavares Thome: 0.0'},
{type:'famplan',text:'Ricardo Aparicio Jimenez: 0.0'},
{type:'economics',text:'Amos H. Hawley: 0.0'},
{type:'famplan',text:'Nlandu Mangani: 0.0'},
{type:'famplan',text:'Matondo Mansilu: 0.0'},
{type:'demography',text:'Dov Friedlander: 0.0'},
{type:'demography',text:'A. Fisher: 0.0'},
{type:'famplan',text:'Nibhon Debavalya: 0.0'},
{type:'famplan',text:'Nancy Yinger: 0.0'},
{type:'demography',text:'George T. Curlin: 0.0'},
{type:'famplan',text:'Suvanee Satayapan: 0.0'},
{type:'sociology',text:'John L. Czajka: 0.0'},
{type:'demography',text:'Jeanne Griffith: 0.0'},
{type:'famplan',text:'Joy G. Dryfoos: 0.0'},
{type:'famplan',text:'Albert J. Fernando: 0.0'},
{type:'demography',text:'Elena Brineman: 0.0'},
{type:'demography',text:'Emdadul Huq: 0.0'},
{type:'demography',text:'Zvi Eisenbach: 0.0'},
{type:'famplan',text:'Antonio G. Cisneros: 0.0'},
{type:'famplan',text:'Hervé Gauthier: 0.0'},
{type:'famplan',text:'Warren C. Robinson: 0.0'},
{type:'famplan',text:'John Laing: 0.0'},
{type:'famplan',text:'Asta M. Kenney: 0.0'},
{type:'famplan',text:'Carol J. Rowland Hogue: 0.0'},
{type:'famplan',text:'Somphong Shevasunt: 0.0'},
{type:'demography',text:'C. Gray Swicegood: 0.0'},
{type:'eugenics',text:'Ira Rosenwaike: 0.0'},
{type:'famplan',text:'Mizanur Rahman: 0.0'},
{type:'eugenics',text:'J. Timothy Johnson: 0.0'},
{type:'demography',text:'Graham Lord: 0.0'},
{type:'famplan',text:'Julian Gold: 0.0'},
{type:'famplan',text:'Lynn C. Landman: 0.0'},
{type:'history',text:'Janet Rothenberg Pack: 0.0'},
{type:'famplan',text:'A. A. Armar: 0.0'},
{type:'famplan',text:'Elena Brinemann: 0.0'},
{type:'famplan',text:'William F. Pratt: 0.0'},
{type:'demography',text:'Joseph Conaty: 0.0'},
{type:'demography',text:'Richard B. Janosik: 0.0'},
{type:'demography',text:'Anthony Pramualratana: 0.0'},
{type:'demography',text:'Nam-Il Kim: 0.0'},
{type:'famplan',text:'James R. Beniger: 0.0'},
{type:'famplan',text:'Maria Umana: 0.0'},
{type:'demography',text:'Allan Parnell: 0.0'},
{type:'famplan',text:'Peters D. Willson: 0.0'},
{type:'demography',text:'Deborah S. Freedman: 0.0'},
{type:'demography',text:'B. Moots: 0.0'},
{type:'famplan',text:'Lois Paul: 0.0'},
{type:'demography',text:'M. A. Koenig: 0.0'},
{type:'demography',text:'Kathy R. Widmer: 0.0'},
{type:'famplan',text:'Marjorie A. Koblinsky: 0.0'},
{type:'demography',text:'Clyde H. Coombs: 0.0'},
{type:'demography',text:'G. B. Simmons: 0.0'},
{type:'demography',text:'Gayl D. Ness: 0.0'},
{type:'demography',text:'T. J. Trussell: 0.0'},
{type:'demography',text:'John W. Mcdonald: 0.0'},
{type:'famplan',text:'Howard W. Ory: 0.0'},
{type:'sociology',text:'Andrea Tyree: 0.0'},
{type:'demography',text:'J. Stoeckel: 0.0'},
{type:'famplan',text:'Bondan Supraptilah: 0.0'},
{type:'famplan',text:'Edward A. Brann: 0.0'},
{type:'famplan',text:'Luise De La Macorra: 0.0'},
{type:'demography',text:'Nirmala Murthy: 0.0'},
{type:'demography',text:'Odile Frank: 0.0'},
{type:'famplan',text:'Anibal Faundes-Latham: 0.0'},
{type:'demography',text:'Deborah Freedman: 0.0'},
{type:'famplan',text:'Magdalena Leon De Leal: 0.0'},
{type:'statistics',text:'Paul A. Tukey: 0.0'},
{type:'famplan',text:'Sara R. Millman: 0.0'},
{type:'famplan',text:'Ahrudh K. Jain: 0.0'},
{type:'famplan',text:'Robert H. Haveman: 0.0'},
{type:'famplan',text:'Sri Poedjastoeti: 0.0'},
{type:'famplan',text:'Visid Prachuabmoh: 0.0'},
{type:'demography',text:'Eleanor Brown: 0.0'},
{type:'demography',text:'Ralph R. Sell: 0.0'},
{type:'demography',text:'Carin Celebuski: 0.0'},
{type:'demography',text:'Judith Banister: 0.0'},
{type:'demography',text:'Hallie Kintner: 0.0'},
{type:'general',text:'Constance Henry: 0.0'},
{type:'sociology',text:'David Snyder: 0.0'},
{type:'pubh',text:'Albert K. Schoenbucher: 0.0'},
{type:'demography',text:'Donna M. Strobino: 0.0'},
{type:'famplan',text:'Ruth S. Simmons: 0.0'},
{type:'famplan',text:'Elizabeth Q. Bulatao: 0.0'},
{type:'demography',text:'Susan G. Janssen: 0.0'},
{type:'demography',text:'Marilyn Butler: 0.0'},
{type:'demography',text:'Jonathan Lieberson: 0.0'},
{type:'sociology',text:'Ronald Rindfuss: 0.0'},
{type:'eugenics',text:'Gek-Ching Thai: 0.0'},
{type:'sociology',text:'Pamela K. Hecht: 0.0'},
{type:'history',text:'Richard Steckel: 0.0'},
{type:'famplan',text:'Sallie Craig Huber: 0.0'},
{type:'famplan',text:'Kevin Oreilly: 0.0'},
{type:'sociology',text:'Kiyosi Hirosima: 0.0'},
{type:'demography',text:'F. E. Kobrin: 0.0'},
{type:'demography',text:'P. N. Mari Bhat: 0.0'},
{type:'famplan',text:'Roger Rochat: 0.0'},
{type:'demography',text:'Morrison G. Wong: 0.0'},
{type:'famplan',text:'Zhong-Hui Feng: 0.0'},
{type:'famplan',text:'Juan M. Flavier: 0.0'},
{type:'famplan',text:'Jeff A. Borders: 0.0'},
{type:'pubh',text:'Warner S. Tillack: 0.0'},
{type:'demography',text:'Deborah Oakley: 0.0'},
{type:'demography',text:'Amy O. Tsui: 0.0'},
{type:'history',text:'Herbert S. Klein: 0.0'},
{type:'famplan',text:'Walter B. Watson: 0.0'},
{type:'pubh',text:'Kenneth W. Eckhardt: 0.0'},
{type:'sociology',text:'Michele Pazul: 0.0'},
{type:'demography',text:'S. Horiuchi: 0.0'},
{type:'demography',text:'Randall Olsen: 0.0'},
{type:'demography',text:'T. W. Pullum: 0.0'},
{type:'famplan',text:'Lyle Peter Groeneveld: 0.0'},
{type:'famplan',text:'Sung-Bong Hong: 0.0'},
{type:'economics',text:'C. R. Winegarden: 0.0'},
{type:'famplan',text:'Robert A. Hatcher: 0.0'},
{type:'statistics',text:'John Mcdonald: 0.0'},
{type:'demography',text:'Rafiqul Huda Chaudhury: 0.0'},
{type:'history',text:'Claudia Goldin: 0.0'},
{type:'famplan',text:'Juan Correa: 0.0'},
{type:'famplan',text:'Pichit Pitaktepsombati: 0.0'},
{type:'sociology',text:'Baron L. Moots: 0.0'},
{type:'famplan',text:'Marc B. Glassman: 0.0'},
{type:'demography',text:'Shiro Horiuchi: 0.0'},
{type:'history',text:'Susan Cotts Watkins: 0.0'},
{type:'famplan',text:'Pudjo Rahardjo: 0.0'},
{type:'demography',text:'Dorothy Nortman: 0.0'},
{type:'demography',text:'Nancy J. Davis: 0.0'},
{type:'demography',text:'Suzanne Culter: 0.0'},
{type:'famplan',text:'John G. Cleland: 0.0'},
{type:'pubh',text:'Stephanie J. Ventura: 0.0'},
{type:'demography',text:'Arjun L. Adlakha: 0.0'},
{type:'famplan',text:'Mercedes B. Concepcion: 0.0'},
{type:'demography',text:'Larry Freshnock: 0.0'},
{type:'famplan',text:'Kathleen Ford: 0.0'},
{type:'demography',text:'[Robert Lapham]: 0.0'},
{type:'demography',text:'D. E. Bloom: 0.0'},
{type:'famplan',text:'Norman B. Ryder: 0.0'},
{type:'demography',text:'Paul D. Frenzen: 0.0'},
{type:'general',text:'Arnold Levine: 0.0'},
{type:'demography',text:'Barbara Von Elm: 0.0'},
{type:'demography',text:'Abbas Bhuiya: 0.0'},
{type:'demography',text:'Barbara Logue: 0.0'},
{type:'sociology',text:'Karen A. Polonko: 0.0'},
{type:'demography',text:'G. Rodriguez: 0.0'},
{type:'sociology',text:'Kim Blankenship: 0.0'},
{type:'demography',text:'Barbara B. Lamphere: 0.0'},
{type:'famplan',text:'Tauseef Ahmed: 0.0'},
{type:'demography',text:'Alan Thomas Richards: 0.0'},
{type:'sociology',text:'David L. Featherman: 0.0'},
{type:'demography',text:'Shantha Madhavan: 0.0'},
{type:'famplan',text:'S. R. Millman: 0.0'},
{type:'demography',text:'Nancy J. Mcgirr: 0.0'},
{type:'famplan',text:'Judith Bourne Rooks: 0.0'},
{type:'history',text:'Rene Leboutte: 0.0'},
{type:'famplan',text:'Rachel Benson Gold: 0.0'},
{type:'demography',text:'James A. Sweet: 0.0'},
{type:'famplan',text:'Maylin Simpson-Herbert: 0.0'},
{type:'demography',text:'Abdul-Aziz Farah: 0.0'},
{type:'demography',text:'Lea Keil Garson: 0.0'},
{type:'sociology',text:'Randall Thomson: 0.0'},
{type:'famplan',text:'Peter J. Davies: 0.0'},
{type:'famplan',text:'Sauvaluck Piampiti: 0.0'},
{type:'history',text:'Edward Shorter: 0.0'},
{type:'famplan',text:'M. Ataur Rahman: 0.0'},
{type:'demography',text:'G. Feeney: 0.0'},
{type:'pubh',text:'Haydee Rondon De Nova: 0.0'},
{type:'demography',text:'R. E. Lightbourne: 0.0'},
{type:'demography',text:'Lowell Hargens: 0.0'},
{type:'demography',text:'John May: 0.0'},
{type:'demography',text:'P. M. Kulkarni: 0.0'},
{type:'demography',text:'S. Preston: 0.0'}
];
var comps = [
{type:'info',text:'Nodes: 25.0: Density: 0.1'},
{type:'sociology',text:'Frank D. Bean: 0.54'},
{type:'demography',text:'W. Parker Frisbie: 0.29'},
{type:'sociology',text:'Dudley L. Poston Jr.: 0.17'},
{type:'statistics',text:'Jeffrey S. Passel: 0.17'},
{type:'demography',text:'Isaac W. Eberstein: 0.13'},
{type:'demography',text:'Gilbert CáRdenas: 0.08'},
{type:'demography',text:'Allan G. King: 0.08'},
{type:'demography',text:'Russell L. Curtis Jr.: 0.08'},
{type:'demography',text:'John P. Marcum: 0.08'},
{type:'demography',text:'Harley L. Browning: 0.08'},
{type:'demography',text:'Antonio Ugalde: 0.08'},
{type:'demography',text:'Charles H. Wood: 0.08'},
{type:'sociology',text:'Lisa Neidert: 0.04'},
{type:'demography',text:'Joachim Singelmann: 0.04'},
{type:'demography',text:'Jan Reese Parker: 0.04'},
{type:'demography',text:'Susan H. Cochrane: 0.04'},
{type:'sociology',text:'Clifford J. Clarke: 0.04'},
{type:'demography',text:'Karen A. Woodrow: 0.04'},
{type:'demography',text:'Benjamin S. Bradshaw: 0.04'},
{type:'demography',text:'Ralph White: 0.04'},
{type:'demography',text:'Walter T. Martin: 0.04'},
{type:'sociology',text:'Gray Swicegood: 0.04'},
{type:'demography',text:'Jose Alberto M. De Carvalho: 0.04'},
{type:'demography',text:'Linda H. Aiken: 0.04'},
{type:'demography',text:'Jacob S. Siegel: 0.04'},
{type:'info',text:'Nodes: 17.0: Density: 0.16'},
{type:'eugenics',text:'J. Richard Udry: 0.69'},
{type:'demography',text:'C. M. Suchindran: 0.38'},
{type:'eugenics',text:'Naomi M. Morris: 0.19'},
{type:'demography',text:'Helen P. Koo: 0.19'},
{type:'demography',text:'Maxine Ruppert: 0.13'},
{type:'demography',text:'Fred W. Reed: 0.13'},
{type:'demography',text:'Charles Teddlie: 0.13'},
{type:'demography',text:'Sandra Lynn Hofferth: 0.13'},
{type:'demography',text:'Ellen Shapiro Fried: 0.13'},
{type:'demography',text:'Karl E. Bauman: 0.13'},
{type:'demography',text:'Janet D. Griffith: 0.13'},
{type:'eugenics',text:'John D. Palmer: 0.13'},
{type:'demography',text:'R. L. Cliquet: 0.06'},
{type:'demography',text:'El-Sayed Nour: 0.06'},
{type:'demography',text:'P. A. Lachenbruch: 0.06'},
{type:'demography',text:'Barbara K. Janowitz: 0.06'},
{type:'demography',text:'Susan F. Newcomer: 0.06'},
{type:'info',text:'Nodes: 14.0: Density: 0.18'},
{type:'demography',text:'Robert L. Bach: 0.38'},
{type:'demography',text:'Alejandro Portes: 0.31'},
{type:'demography',text:'Joel Smith: 0.23'},
{type:'famplan',text:'Marta Tienda: 0.23'},
{type:'sociology',text:'Robert Nash Parker: 0.23'},
{type:'sociology',text:'Kenneth L. Wilson: 0.15'},
{type:'sociology',text:'Kenneth Manton: 0.15'},
{type:'sociology',text:'José A. Cobas: 0.15'},
{type:'sociology',text:'David Bromley: 0.15'},
{type:'demography',text:'Leif Jensen: 0.15'},
{type:'sociology',text:'W. Allen Martin: 0.08'},
{type:'demography',text:'Lisa A. Schraml: 0.08'},
{type:'sociology',text:'M. Dwayne Smith: 0.08'},
{type:'sociology',text:'Ronald Angel: 0.08'},
{type:'info',text:'Nodes: 7.0: Density: 0.29'},
{type:'sociology',text:'Kristin A. Moore: 0.67'},
{type:'demography',text:'Linda J. Waite: 0.5'},
{type:'famplan',text:'Richard F. Wertheimer: 0.17'},
{type:'famplan',text:'Steven B. Caldwell: 0.17'},
{type:'sociology',text:'Sandra L. Hofferth: 0.17'},
{type:'demography',text:'Glenna D. Spitze: 0.17'},
{type:'demography',text:'Ross M. Stolzenberg: 0.17'},
{type:'info',text:'Nodes: 7.0: Density: 0.29'},
{type:'sociology',text:'Douglas S. Massey: 0.83'},
{type:'demography',text:'Lucky M. Tedrow: 0.33'},
{type:'demography',text:'Kathleen M. Schnabel: 0.17'},
{type:'demography',text:'Josh Reichert: 0.17'},
{type:'demography',text:'Brendan P. Mullan: 0.17'},
{type:'demography',text:'Joshua S. Reichert: 0.17'},
{type:'demography',text:'David A. Swanson: 0.17'},
{type:'info',text:'Nodes: 5.0: Density: 0.6'},
{type:'sociology',text:'Charles B. Nam: 1.0'},
{type:'demography',text:'Larry W. Isaac: 0.5'},
{type:'demography',text:'Norman L. Weatherby: 0.5'},
{type:'demography',text:'Morgan Lyons: 0.5'},
{type:'demography',text:'Kathleen A. Ockay: 0.5'},
{type:'info',text:'Nodes: 3.0: Density: 0.67'},
{type:'economics',text:'Nathan Keyfitz: 1.0'},
{type:'eugenics',text:'Antonio Golini: 0.5'},
{type:'demography',text:'G. Littman: 0.5'},
{type:'info',text:'Nodes: 3.0: Density: 0.67'},
{type:'demography',text:'Judith Blake: 1.0'},
{type:'demography',text:'Jorge H. Del Pinal: 0.5'},
{type:'statistics',text:'Prithwis Das Gupta: 0.5'},
{type:'info',text:'Nodes: 3.0: Density: 0.67'},
{type:'sociology',text:'Wendy Baldwin: 1.0'},
{type:'famplan',text:'Virginia S. Cain: 0.5'},
{type:'sociology',text:'Harriet B. Presser: 0.5'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'demography',text:'Kingsley Davis: 1.0'},
{type:'demography',text:'Pietronella Van Den Oever: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'economics',text:'Dudley Kirk: 1.0'},
{type:'economics',text:'Frank Wm. Oechsli: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'history',text:'Alice Goldstein: 1.0'},
{type:'general',text:'Sidney Goldstein: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'demography',text:'Suzanne M. Bianchi: 1.0'},
{type:'sociology',text:'Reynolds Farley: 1.0'},
{type:'info',text:'Unconnected:'},
{type:'demography',text:'Frank W. Notestein'},
{type:'demography',text:'John D. Durand'},
{type:'general',text:'Everett S. Lee'},
{type:'general',text:'Arthur A. Campbell'},
{type:'demography',text:'George J. Stolnitz'},
{type:'sociology',text:'Jane A. Menken'},
{type:'demography',text:'Paul Demeny'},
{type:'statistics',text:'Ronald Lee'},
{type:'demography',text:'Alberto Palloni'},
{type:'sociology',text:'David Goldberg'}
];
var authors = 657;
 var density = 0.01;
 var components = 14;
-->