<!--
 var comp1 = [
{type:'info',text:'Nodes: 23.0: Density: 0.1'},
{type:'general',text:'Irene B. Taeuber: 0.32'},
{type:'general',text:'Hope T. Eldridge: 0.27'},
{type:'sociology',text:'Jacob S. Siegel: 0.23'},
{type:'statistics',text:'Frank W. Notestein: 0.18'},
{type:'statistics',text:'Henry S. Shryock Jr.: 0.18'},
{type:'statistics',text:'P. V. Cardon: 0.09'},
{type:'pubh',text:'Halbert L. Dunn: 0.09'},
{type:'general',text:'Ernest Jurkat: 0.09'},
{type:'sociology',text:'Benjamin Greenberg: 0.09'},
{type:'demography',text:'Philip M. Hauser: 0.09'},
{type:'sociology',text:'Margaret J. Hagood: 0.09'},
{type:'general',text:'Nora P. Powell: 0.09'},
{type:'economics',text:'Joseph S. Davis: 0.09'},
{type:'demography',text:'Chungnim C. Han: 0.05'},
{type:'demography',text:'George W. Barclay: 0.05'},
{type:'sociology',text:'Louis J. Ducoff: 0.05'},
{type:'sociology',text:'C. Horace Hamilton: 0.05'},
{type:'statistics',text:'Norman Lawrence: 0.05'},
{type:'general',text:'Louise K. Kiser: 0.05'},
{type:'sociology',text:'Conrad Taeuber: 0.05'},
{type:'demography',text:'Felix E. Moore: 0.05'},
{type:'general',text:'Edwin G. Beal: 0.05'},
{type:'demography',text:'Chia-Lin Pan: 0.05'}
];
var comps = [
{type:'info',text:'Nodes: 13.0: Density: 0.21'},
{type:'demography',text:'Clyde V. Kiser: 0.58'},
{type:'sociology',text:'Pascal K. Whelpton: 0.42'},
{type:'sociology',text:'Charles F. Westoff: 0.33'},
{type:'demography',text:'Ronald Freedman: 0.33'},
{type:'pubh',text:'Lee F. Herrera: 0.25'},
{type:'pubh',text:'John F. Kantner: 0.17'},
{type:'pubh',text:'Jeanne E. Clare: 0.08'},
{type:'pubh',text:'Edgar F. Borgatta: 0.08'},
{type:'statistics',text:'Amos H. Hawley: 0.08'},
{type:'demography',text:'George F. Mair: 0.08'},
{type:'pubh',text:'Nathalie L. Schacter: 0.08'},
{type:'pubh',text:'Marianne Degraff Swain: 0.08'},
{type:'demography',text:'Harry Sharp: 0.08'},
{type:'info',text:'Nodes: 5.0: Density: 0.4'},
{type:'general',text:'Kingsley Davis: 1.0'},
{type:'demography',text:'Jerry W. Combs Jr.: 0.25'},
{type:'general',text:'Clarence Senior: 0.25'},
{type:'pubh',text:'Ana Casis: 0.25'},
{type:'economics',text:'Hilda Hertz Golden: 0.25'},
{type:'info',text:'Nodes: 3.0: Density: 0.67'},
{type:'sociology',text:'W. Parker Mauldin: 1.0'},
{type:'demography',text:'Calvin L. Beale: 0.5'},
{type:'sociology',text:'Eli S. Marks: 0.5'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'demography',text:'George J. Stolnitz: 1.0'},
{type:'demography',text:'Norman B. Ryder: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'sociology',text:'Nathan Keyfitz: 1.0'},
{type:'demography',text:'H. L. Robinson: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'general',text:'Edward P. Hutchinson: 1.0'},
{type:'demography',text:'Wilbert E. Moore: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'general',text:'Louis I. Dublin: 1.0'},
{type:'general',text:'Alfred J. Lotka: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'sociology',text:'Dorothy S. Thomas: 1.0'},
{type:'sociology',text:'George Sabagh: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'sociology',text:'Earl Huyck: 1.0'},
{type:'general',text:'Dudley Kirk: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'sociology',text:'Manzer John Griswold: 1.0'},
{type:'sociology',text:'Calvin F. Schmid: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'general',text:'Warren S. Thompson: 1.0'},
{type:'statistics',text:'Donald J. Bogue: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'sociology',text:'Anne S. Lee: 1.0'},
{type:'sociology',text:'Everett S. Lee: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'demography',text:'Otis Dudley Duncan: 1.0'},
{type:'demography',text:'Vincent Heath Whitney: 1.0'},
{type:'info',text:'Unconnected:'},
{type:'general',text:'Henry Pratt Fairchild'},
{type:'general',text:'Frank Lorimer'},
{type:'history',text:'Joseph J. Spengler'},
{type:'pubh',text:'Harold F. Dorn'},
{type:'general',text:'John D. Durand'},
{type:'sociology',text:'Sidney Goldstein'}
];
var authors = 70;
 var density = 0.02;
 var components = 14;
-->