<!--
 var comp1 = [
{type:'info',text:'Nodes: 1422.0: Density: 0.0'},
{type:'famplan',text:'Barbara Janowitz: 0.03'},
{type:'demography',text:'James Trussell: 0.02'},
{type:'pubh',text:'Leo Morris: 0.02'},
{type:'general',text:'James W. Vaupel: 0.02'},
{type:'demography',text:'Charles W. Warren: 0.02'},
{type:'general',text:'J. W. Curtsinger: 0.02'},
{type:'sociology',text:'Ronald R. Rindfuss: 0.02'},
{type:'sociology',text:'S. Philip Morgan: 0.02'},
{type:'famplan',text:'Jack C. Smith: 0.02'},
{type:'famplan',text:'Jane T. Bertrand: 0.01'},
{type:'demography',text:'Stan Becker: 0.01'},
{type:'famplan',text:'Robert G. Potter: 0.01'},
{type:'famplan',text:'John E. Anderson: 0.01'},
{type:'famplan',text:'Young-Mi Kim: 0.01'},
{type:'demography',text:'Douglas S. Massey: 0.01'},
{type:'famplan',text:'Stanley K. Henshaw: 0.01'},
{type:'pubh',text:'James S. Marks: 0.01'},
{type:'demography',text:'Shyam Thapa: 0.01'},
{type:'pubh',text:'Lloyd J. Kolbe: 0.01'},
{type:'demography',text:'Frank F. Furstenberg Jr.: 0.01'},
{type:'demography',text:'James F. Phillips: 0.01'},
{type:'famplan',text:'Charles F. Westoff: 0.01'},
{type:'famplan',text:'Dale Huntington: 0.01'},
{type:'famplan',text:'Carol J. R. Hogue: 0.01'},
{type:'famplan',text:'D. Lawrence Kincaid: 0.01'},
{type:'demography',text:'Jacqueline Darroch Forrest: 0.01'},
{type:'demography',text:'Roger W. Rochat: 0.01'},
{type:'sociology',text:'Samuel H. Preston: 0.01'},
{type:'general',text:'Ansley J. Coale: 0.01'},
{type:'famplan',text:'Phyllis T. Piotrow: 0.01'},
{type:'demography',text:'Vincent Fauveau: 0.01'},
{type:'general',text:'James R. Carey: 0.01'},
{type:'pubh',text:'Sevgi O. Aral: 0.01'},
{type:'famplan',text:'Laura Kann: 0.01'},
{type:'demography',text:'Michael A. Koenig: 0.01'},
{type:'general',text:'J. W. Vaupel: 0.01'},
{type:'general',text:'J. R. Carey: 0.01'},
{type:'famplan',text:'Nancy J. Binkin: 0.01'},
{type:'demography',text:'Linda J. Waite: 0.01'},
{type:'pubh',text:'Howard I. Goldberg: 0.01'},
{type:'pubh',text:'Joel C. Kleinman: 0.01'},
{type:'famplan',text:'Andrew A. Fisher: 0.01'},
{type:'sociology',text:'J. Richard Udry: 0.01'},
{type:'eugenics',text:'Zeng Yi: 0.01'},
{type:'famplan',text:'Deborah L. Covington: 0.01'},
{type:'pubh',text:'Janet Collins: 0.01'},
{type:'famplan',text:'Thomas T. Kane: 0.01'},
{type:'economics',text:'John S. Akin: 0.01'},
{type:'pubh',text:'G. Stephen Bowen: 0.01'},
{type:'sociology',text:'Joan R. Kahn: 0.01'},
{type:'demography',text:'Anne R. Pebley: 0.01'},
{type:'famplan',text:'Ian Askew: 0.01'},
{type:'pubh',text:'Lloyd Kolbe: 0.01'},
{type:'general',text:'Thomas E. Johnson: 0.01'},
{type:'famplan',text:'J. Chakraborty: 0.01'},
{type:'economics',text:'David K. Guilkey: 0.01'},
{type:'demography',text:'Frank D. Bean: 0.01'},
{type:'demography',text:'Minja Kim Choe: 0.01'},
{type:'demography',text:'Malcolm Potts: 0.01'},
{type:'famplan',text:'Noreen Goldman: 0.01'},
{type:'pubh',text:'Laurie S. Zabin: 0.01'},
{type:'general',text:'Gordon J. Lithgow: 0.01'},
{type:'famplan',text:'Michelle J. Hindin: 0.01'},
{type:'famplan',text:'Wilma Lynn: 0.01'},
{type:'famplan',text:'Alex Zinanga: 0.01'},
{type:'general',text:'S. Jay Olshansky: 0.01'},
{type:'famplan',text:'Opia Mensah Kumah: 0.01'},
{type:'famplan',text:'Florence Chikara: 0.01'},
{type:'famplan',text:'Carmen Miro: 0.01'},
{type:'demography',text:'Donald J. Adamchak: 0.01'},
{type:'famplan',text:'Innocent Kuseka: 0.01'},
{type:'sociology',text:'Julie Davanzo: 0.01'},
{type:'pubh',text:'James W. Buehler: 0.01'},
{type:'famplan',text:'Cheryl L. Lettenmaier: 0.01'},
{type:'demography',text:'William R. Grady: 0.01'},
{type:'famplan',text:'Young J. Kim: 0.01'},
{type:'pubh',text:'Sandra Smith: 0.01'},
{type:'eugenics',text:'Michael T. Mbizvo: 0.01'},
{type:'general',text:'Bruce A. Carnes: 0.01'},
{type:'demography',text:'Joan M. Herold: 0.01'},
{type:'famplan',text:'Terry Silberman: 0.01'},
{type:'famplan',text:'John Stanback: 0.01'},
{type:'demography',text:'Maxine Weinstein: 0.01'},
{type:'famplan',text:'John Knodel: 0.01'},
{type:'demography',text:'Richard S. Monteith: 0.01'},
{type:'famplan',text:'Carol S. Weisman: 0.01'},
{type:'general',text:'Joseph L. Graves: 0.01'},
{type:'sociology',text:'Arland Thornton: 0.01'},
{type:'general',text:'H. H. Fukui: 0.01'},
{type:'famplan',text:'Douglas Nichols: 0.01'},
{type:'general',text:'S. Pletcher: 0.01'},
{type:'general',text:'William B. Capra: 0.01'},
{type:'famplan',text:'Pat Caldwell: 0.01'},
{type:'pubh',text:'William D. Mosher: 0.01'},
{type:'sociology',text:'Michael J. White: 0.01'},
{type:'demography',text:'Aphichat Chamratrithirong: 0.01'},
{type:'demography',text:'Ming-Cheng Chang: 0.01'},
{type:'sociology',text:'John B. Casterline: 0.01'},
{type:'general',text:'Christine K. Cassel: 0.01'},
{type:'general',text:'Jane-Ling Wang: 0.01'},
{type:'famplan',text:'Kim Winnard: 0.01'},
{type:'general',text:'Leonid A. Gavrilov: 0.01'},
{type:'general',text:'Hans-Georg Muller: 0.01'},
{type:'general',text:'Natalia S. Gavrilova: 0.01'},
{type:'sociology',text:'Nancy S. Landale: 0.01'},
{type:'general',text:'Theodore J. Nusbaum: 0.01'},
{type:'economics',text:'Barry M. Popkin: 0.01'},
{type:'general',text:'A. Khazaeli: 0.01'},
{type:'general',text:'Laurence D. Mueller: 0.01'},
{type:'general',text:'L. Xiu: 0.01'},
{type:'demography',text:'Daniel T. Lichter: 0.01'},
{type:'general',text:'Michael R. Rose: 0.01'},
{type:'general',text:'John H. Gagnon: 0.01'},
{type:'demography',text:'Henry P. David: 0.01'},
{type:'pubh',text:'Aulikki Nissinen: 0.01'},
{type:'famplan',text:'E. O. Otolorin: 0.01'},
{type:'pubh',text:'Geng Guanyi: 0.01'},
{type:'famplan',text:'Thomas J. Espenshade: 0.01'},
{type:'famplan',text:'John M. Paxman: 0.01'},
{type:'sociology',text:'Jay D. Teachman: 0.01'},
{type:'pubh',text:'Guo Ze-Yu: 0.01'},
{type:'demography',text:'Constance A. Nathanson: 0.01'},
{type:'demography',text:'K. H. W. Gaminiratne: 0.01'},
{type:'famplan',text:'Aida Torres: 0.01'},
{type:'pubh',text:'Erkki Vartiainen: 0.01'},
{type:'pubh',text:'Jacob J. Feldman: 0.01'},
{type:'famplan',text:'Kanchana Kanchanasinith: 0.01'},
{type:'demography',text:'James Mccarthy: 0.01'},
{type:'famplan',text:'Marcel Vekemans: 0.01'},
{type:'pubh',text:'David Williamson: 0.01'},
{type:'pubh',text:'We Guang-Lin: 0.01'},
{type:'famplan',text:'Ronald Freedman: 0.01'},
{type:'eugenics',text:'James W. Wood: 0.01'},
{type:'famplan',text:'Joseph A. Catania: 0.01'},
{type:'demography',text:'Elise F. Jones: 0.01'},
{type:'sociology',text:'David E. Bloom: 0.01'},
{type:'famplan',text:'Dudley L. Poston Jr.: 0.01'},
{type:'pubh',text:'Heikki Korhonen: 0.01'},
{type:'demography',text:'Barbara Mensch: 0.01'},
{type:'pubh',text:'Pirjo Pietinen: 0.01'},
{type:'pubh',text:'Jeffrey P. Koplan: 0.01'},
{type:'demography',text:'Saneya Saleh: 0.01'},
{type:'eugenics',text:'Chai Podhisita: 0.01'},
{type:'pubh',text:'Du Dianjun: 0.01'},
{type:'famplan',text:'Mark D. Hayward: 0.01'},
{type:'demography',text:'Karen G. Foreit: 0.01'},
{type:'demography',text:'Kenneth Manton: 0.01'},
{type:'pubh',text:'Lilo T. Strauss: 0.01'},
{type:'demography',text:'Kenneth G. Manton: 0.01'},
{type:'sociology',text:'Katherine Trent: 0.01'},
{type:'demography',text:'Mark W. Oberle: 0.01'},
{type:'demography',text:'Robert Schoen: 0.01'},
{type:'famplan',text:'Deirdre Wulf: 0.01'},
{type:'demography',text:'Graziella Caselli: 0.01'},
{type:'famplan',text:'Lawrence J. Severy: 0.01'},
{type:'famplan',text:'Ruth Simmons: 0.01'},
{type:'famplan',text:'Maria J. Wawer: 0.01'},
{type:'famplan',text:'M. Margaret Dolcini: 0.01'},
{type:'famplan',text:'Richard Lincoln: 0.01'},
{type:'general',text:'Donna Ruane Morrison: 0.01'},
{type:'sociology',text:'John O. G. Billy: 0.01'},
{type:'demography',text:'Sandra L. Huffman: 0.01'},
{type:'pubh',text:'Mark L. Rosenberg: 0.01'},
{type:'demography',text:'Susheela Singh: 0.01'},
{type:'pubh',text:'Gary R. Noble: 0.01'},
{type:'famplan',text:'Robert D. Retherford: 0.01'},
{type:'famplan',text:'Rodney Phillips: 0.01'},
{type:'famplan',text:'Wendy J. Graham: 0.01'},
{type:'famplan',text:'Kathy I. Kennedy: 0.01'},
{type:'pubh',text:'Brent Miller: 0.01'},
{type:'demography',text:'Li Bohua: 0.01'},
{type:'sociology',text:'Marta Tienda: 0.01'},
{type:'pubh',text:'Fanchon F. Finucane: 0.01'},
{type:'pubh',text:'Wendy Baldwin: 0.01'},
{type:'famplan',text:'Masuma Mamdani: 0.01'},
{type:'famplan',text:'J. Lynne Davies: 0.01'},
{type:'demography',text:'Luis Rosero-Bixby: 0.01'},
{type:'famplan',text:'Federico Leon: 0.01'},
{type:'pubh',text:'Joan Cornoni-Huntley: 0.01'},
{type:'pubh',text:'Jennifer H. Madans: 0.01'},
{type:'demography',text:'Richard E. Bilsborrow: 0.01'},
{type:'famplan',text:'Willard Cates Jr.: 0.01'},
{type:'famplan',text:'Margarita Suazo: 0.01'},
{type:'famplan',text:'Halima Maidouka: 0.01'},
{type:'famplan',text:'Patricia Bailey: 0.01'},
{type:'famplan',text:'Anna Flynn: 0.01'},
{type:'famplan',text:'Ruhul Amin: 0.01'},
{type:'famplan',text:'Sharon Weir: 0.01'},
{type:'pubh',text:'Helen E. Barbano: 0.01'},
{type:'pubh',text:'Mary Grace Kovar: 0.01'},
{type:'famplan',text:'James R. Foreit: 0.01'},
{type:'famplan',text:'Robert A. Miller: 0.01'},
{type:'famplan',text:'Nahid F. Toubia: 0.01'},
{type:'economics',text:'J. Edward Taylor: 0.01'},
{type:'famplan',text:'Virginia C. Orense: 0.01'},
{type:'pubh',text:'Freya Sonenstein: 0.01'},
{type:'pubh',text:'Deborah Rugg: 0.01'},
{type:'famplan',text:'Harin W. Perera: 0.01'},
{type:'statistics',text:'William M. Mason: 0.01'},
{type:'pubh',text:'Lynn Short: 0.01'},
{type:'demography',text:'Kusol Soonthorndhada: 0.01'},
{type:'famplan',text:'Oona M. R. Campbell: 0.01'},
{type:'pubh',text:'Ray Yip: 0.01'},
{type:'famplan',text:'Cleone I. F. Rooney: 0.01'},
{type:'demography',text:'Dennis P. Hogan: 0.01'},
{type:'general',text:'Griffith Feeney: 0.01'},
{type:'demography',text:'Judith A. Fortney: 0.01'},
{type:'famplan',text:'Veronique G. A. Filippi: 0.01'},
{type:'demography',text:'Soma De Silva: 0.01'},
{type:'famplan',text:'Robert Snowden: 0.01'},
{type:'eugenics',text:'Anatoli I. Yashin: 0.01'},
{type:'famplan',text:'Amy O. Tsui: 0.01'},
{type:'pubh',text:'Gary A. Chase: 0.01'},
{type:'famplan',text:'Thalia Barreto: 0.01'},
{type:'demography',text:'Jeffrey A. Burr: 0.01'},
{type:'pubh',text:'Marion Howard: 0.01'},
{type:'pubh',text:'Douglas Kirby: 0.01'},
{type:'pubh',text:'Christine S. Cox: 0.01'},
{type:'famplan',text:'Kathryn Kost: 0.0'},
{type:'famplan',text:'Deborah S. Gates: 0.0'},
{type:'eugenics',text:'Prasit Leepreecha: 0.0'},
{type:'demography',text:'Koray Tanfer: 0.0'},
{type:'eugenics',text:'William J. Serow: 0.0'},
{type:'sociology',text:'Charles Hirschman: 0.0'},
{type:'demography',text:'James A. Palmore: 0.0'},
{type:'famplan',text:'Noriko O. Tsuya: 0.0'},
{type:'demography',text:'Te-Hsiung Sun: 0.0'},
{type:'eugenics',text:'Sally Lennington Kunstadter: 0.0'},
{type:'demography',text:'John Caldwell: 0.0'},
{type:'famplan',text:'Lynne R. Wilkens: 0.0'},
{type:'demography',text:'Janet B. Hardy: 0.0'},
{type:'pubh',text:'Jack Habib: 0.0'},
{type:'eugenics',text:'Norman Y. Luther: 0.0'},
{type:'demography',text:'Wilhelm Flieger: 0.0'},
{type:'famplan',text:'Alfredo Brazzoduro: 0.0'},
{type:'general',text:'Philip L. Martin: 0.0'},
{type:'famplan',text:'Richard A. Easterlin: 0.0'},
{type:'famplan',text:'Greg J. Duncan: 0.0'},
{type:'sociology',text:'Nan Marie Astone: 0.0'},
{type:'pubh',text:'Bruce Cohen: 0.0'},
{type:'famplan',text:'Leopoldo Nunez: 0.0'},
{type:'pubh',text:'Richard Suzman: 0.0'},
{type:'famplan',text:'I.V. Mako: 0.0'},
{type:'famplan',text:'Elizabeth Hervey Stephen: 0.0'},
{type:'pubh',text:'Jonathan R. Sugarman: 0.0'},
{type:'famplan',text:'Mechai Viravaidya: 0.0'},
{type:'famplan',text:'John A. Ross: 0.0'},
{type:'demography',text:'Kathleen Ford: 0.0'},
{type:'general',text:'Philip K. Robins: 0.0'},
{type:'famplan',text:'Regina Mcnamara: 0.0'},
{type:'eugenics',text:'K. Vaninadha Rao: 0.0'},
{type:'demography',text:'Saad Gadalla: 0.0'},
{type:'pubh',text:'S. J. Olshansky: 0.0'},
{type:'eugenics',text:'Rasamee Sae Thao: 0.0'},
{type:'pubh',text:'D. Peter Drotman: 0.0'},
{type:'demography',text:'Eric Stallard: 0.0'},
{type:'demography',text:'Tu Ping: 0.0'},
{type:'famplan',text:'Stella Babalola: 0.0'},
{type:'pubh',text:'Paula Van Ness: 0.0'},
{type:'pubh',text:'James O. Mason: 0.0'},
{type:'sociology',text:'John N. Edwards: 0.0'},
{type:'general',text:'Alberto Palloni: 0.0'},
{type:'demography',text:'Larry C. Deeb: 0.0'},
{type:'famplan',text:'Carol Corso: 0.0'},
{type:'pubh',text:'Diane Makuc: 0.0'},
{type:'famplan',text:'Sebioniga Lawal: 0.0'},
{type:'eugenics',text:'Wirachon Sae Yang: 0.0'},
{type:'pubh',text:'David Danon: 0.0'},
{type:'famplan',text:'Lewis Ndhlovu: 0.0'},
{type:'eugenics',text:'Cheng Sae Thao: 0.0'},
{type:'pubh',text:'Bryan K. Lindsey: 0.0'},
{type:'famplan',text:'Jeannie I. Rosoff: 0.0'},
{type:'famplan',text:'Alison Spitz: 0.0'},
{type:'pubh',text:'J. E. Dowd: 0.0'},
{type:'demography',text:'Bruce Caldwell: 0.0'},
{type:'famplan',text:'France Donnay: 0.0'},
{type:'pubh',text:'David Galinsky: 0.0'},
{type:'famplan',text:'Therese Mcginn: 0.0'},
{type:'eugenics',text:'Peter Kunstadter: 0.0'},
{type:'demography',text:'Gretchen A. Condran: 0.0'},
{type:'famplan',text:'Lance M. Pollack: 0.0'},
{type:'sociology',text:'Isaac W. Eberstein: 0.0'},
{type:'famplan',text:'Jose Rimon: 0.0'},
{type:'eugenics',text:'Mai Laoyang: 0.0'},
{type:'general',text:'Wang Feng: 0.0'},
{type:'famplan',text:'D. S. Gates: 0.0'},
{type:'famplan',text:'Ron Stall: 0.0'},
{type:'general',text:'Linda G. Martin: 0.0'},
{type:'general',text:'Jane Menken: 0.0'},
{type:'famplan',text:'Mark Robbins: 0.0'},
{type:'demography',text:'Wolfgang Opitz: 0.0'},
{type:'general',text:'Kathleen E. Kiernan: 0.0'},
{type:'famplan',text:'Gigi Santow: 0.0'},
{type:'demography',text:'Albert I. Hermalin: 0.0'},
{type:'pubh',text:'Philip H. Rhodes: 0.0'},
{type:'general',text:'Axel Kowald: 0.0'},
{type:'general',text:'K. Ritchie: 0.0'},
{type:'demography',text:'Naomi Rutenberg: 0.0'},
{type:'famplan',text:'Cheryl Lettenmaier: 0.0'},
{type:'famplan',text:'O. A. Ladipo: 0.0'},
{type:'famplan',text:'Roberto Santiso: 0.0'},
{type:'general',text:'Andrew J. Cherlin: 0.0'},
{type:'famplan',text:'Nanda Weeraratne: 0.0'},
{type:'pubh',text:'Cheryl S. Alexander: 0.0'},
{type:'famplan',text:'Suvathana Vibulsresth: 0.0'},
{type:'pubh',text:'Lisa Daily: 0.0'},
{type:'famplan',text:'Pichit Pitaktepsombati: 0.0'},
{type:'sociology',text:'Susan Cotts Watkins: 0.0'},
{type:'famplan',text:'Donald Lauro: 0.0'},
{type:'demography',text:'Jere R. Behrman: 0.0'},
{type:'famplan',text:'Cecilia Ndeti: 0.0'},
{type:'sociology',text:'James L. Peterson: 0.0'},
{type:'pubh',text:'John R. Moore: 0.0'},
{type:'famplan',text:'Patricia E. Bailey: 0.0'},
{type:'sociology',text:'Tim B. Heaton: 0.0'},
{type:'famplan',text:'Larry L. Bumpass: 0.0'},
{type:'demography',text:'Sara Mclanahan: 0.0'},
{type:'famplan',text:'Esther S. Hudes: 0.0'},
{type:'sociology',text:'Margaret E. Ensminger: 0.0'},
{type:'pubh',text:'Michael Dalmat: 0.0'},
{type:'famplan',text:'Thomas J. Coates: 0.0'},
{type:'famplan',text:'Maria Antonieta Pineda: 0.0'},
{type:'famplan',text:'Lawrence S. Magder: 0.0'},
{type:'statistics',text:'Toni Richards: 0.0'},
{type:'pubh',text:'Steven D. Helgerson: 0.0'},
{type:'general',text:'Julien O. Teitler: 0.0'},
{type:'famplan',text:'Mehrab Ali Khan: 0.0'},
{type:'general',text:'Thomas B. L. Kirkwood: 0.0'},
{type:'demography',text:'Marilyn B. Hirsch: 0.0'},
{type:'demography',text:'Karen Hardee-Cleaveland: 0.0'},
{type:'famplan',text:'F. Y. Mohamed Ali: 0.0'},
{type:'demography',text:'J. Timothy Johnson: 0.0'},
{type:'famplan',text:'Deborah S. Reed: 0.0'},
{type:'sociology',text:'Barbara Entwisle: 0.0'},
{type:'economics',text:'Alden Speare Jr.: 0.0'},
{type:'statistics',text:'Gary D. Sandefur: 0.0'},
{type:'pubh',text:'Dixie E. Snider Jr.: 0.0'},
{type:'demography',text:'W. Parker Mauldin: 0.0'},
{type:'pubh',text:'Benedict I. Truman: 0.0'},
{type:'famplan',text:'John W. Mcdonald: 0.0'},
{type:'famplan',text:'Barbara S. Mensch: 0.0'},
{type:'sociology',text:'Elizabeth Thomson: 0.0'},
{type:'famplan',text:'Padmini Silva: 0.0'},
{type:'pubh',text:'William M. Rokaw: 0.0'},
{type:'famplan',text:'Pierre Buekens: 0.0'},
{type:'famplan',text:'Robert A. Hatcher: 0.0'},
{type:'pubh',text:'Andrew Friede: 0.0'},
{type:'demography',text:'Sara S. Mclanahan: 0.0'},
{type:'famplan',text:'Nelson Keyonzo: 0.0'},
{type:'demography',text:'Steven D. Mclaughlin: 0.0'},
{type:'general',text:'J. M. Robine: 0.0'},
{type:'famplan',text:'Pattaka Piyapinyo: 0.0'},
{type:'famplan',text:'John Mwita: 0.0'},
{type:'general',text:'P. Lindsay Chase-Linsdale: 0.0'},
{type:'demography',text:'Jeffrey R. Harris: 0.0'},
{type:'demography',text:'Adela Pellegrino: 0.0'},
{type:'demography',text:'Ali Kouaouci: 0.0'},
{type:'famplan',text:'J. Courtland Robinson: 0.0'},
{type:'famplan',text:'Linda D. Winges: 0.0'},
{type:'famplan',text:'Marvin Hage: 0.0'},
{type:'pubh',text:'Rueben C. Warren: 0.0'},
{type:'demography',text:'C. Gray Swicegood: 0.0'},
{type:'demography',text:'Katherine Fennelly: 0.0'},
{type:'pubh',text:'Lee Fleshood: 0.0'},
{type:'pubh',text:'Kate Prager: 0.0'},
{type:'demography',text:'Inne Susanti: 0.0'},
{type:'famplan',text:'Mouhamadou Gueye: 0.0'},
{type:'famplan',text:'Pornsinee Amornwichet: 0.0'},
{type:'famplan',text:'Nlandu Mangani: 0.0'},
{type:'famplan',text:'Matondo Mansilu: 0.0'},
{type:'famplan',text:'Felix Guillen: 0.0'},
{type:'famplan',text:'Yu-De Chen: 0.0'},
{type:'famplan',text:'Robert Hanenberg: 0.0'},
{type:'pubh',text:'Sandra S. Smith: 0.0'},
{type:'famplan',text:'Dennis Hapugalle: 0.0'},
{type:'famplan',text:'B. Jill Smith: 0.0'},
{type:'famplan',text:'Adel A. El-Kady: 0.0'},
{type:'economics',text:'Oded Stark: 0.0'},
{type:'eugenics',text:'Linda S. Adair: 0.0'},
{type:'famplan',text:'Juan Maria Carron: 0.0'},
{type:'demography',text:'Peerasit Kamnuansilpa: 0.0'},
{type:'demography',text:'Joaquin Arango: 0.0'},
{type:'famplan',text:'Alvaro Conde: 0.0'},
{type:'famplan',text:'Susan Arday: 0.0'},
{type:'pubh',text:'Jim Ross: 0.0'},
{type:'famplan',text:'Sharon S. Weir: 0.0'},
{type:'pubh',text:'Frederick L. Trowbridge: 0.0'},
{type:'famplan',text:'Charles H. C. Chen: 0.0'},
{type:'demography',text:'Laurie Schwab Zabin: 0.0'},
{type:'famplan',text:'Maria Rosa Garate: 0.0'},
{type:'famplan',text:'Shari C. Wasser: 0.0'},
{type:'famplan',text:'Nadine N. Burton: 0.0'},
{type:'demography',text:'Barrett A. Lee: 0.0'},
{type:'famplan',text:'Margaret Ensminger: 0.0'},
{type:'demography',text:'Robert Feldman: 0.0'},
{type:'famplan',text:'Dario Castagnino: 0.0'},
{type:'demography',text:'Susan M. Rogers: 0.0'},
{type:'statistics',text:'Mark R. Montgomery: 0.0'},
{type:'famplan',text:'Sushil Kumar: 0.0'},
{type:'statistics',text:'John P. Creason: 0.0'},
{type:'pubh',text:'Janet L. Collins: 0.0'},
{type:'famplan',text:'Ruth Pinedo: 0.0'},
{type:'pubh',text:'Thomas C. Spillman: 0.0'},
{type:'famplan',text:'John Bongaarts: 0.0'},
{type:'demography',text:'Diane K. Mclaughlin: 0.0'},
{type:'famplan',text:'Maria Mercedes Melian: 0.0'},
{type:'sociology',text:'Irwin Garfinkel: 0.0'},
{type:'economics',text:'Theodore D. Fuller: 0.0'},
{type:'famplan',text:'Ruth Martinez: 0.0'},
{type:'famplan',text:'Peter Miller: 0.0'},
{type:'famplan',text:'Deborah Holtzman: 0.0'},
{type:'famplan',text:'Cathy Dratman: 0.0'},
{type:'famplan',text:'Nancy Dittes: 0.0'},
{type:'famplan',text:'Paulina Suarez: 0.0'},
{type:'statistics',text:'Wilson B. Riggan: 0.0'},
{type:'demography',text:'Thomas W. Pullum: 0.0'},
{type:'demography',text:'Gray Swicegood: 0.0'},
{type:'demography',text:'William L. Parish: 0.0'},
{type:'famplan',text:'Nanta Auamkul: 0.0'},
{type:'famplan',text:'Johnny Madrigal-Pana: 0.0'},
{type:'demography',text:'Deborah S. Degraff: 0.0'},
{type:'famplan',text:'David J. Eggebeen: 0.0'},
{type:'famplan',text:'Jose G. Rimon: 0.0'},
{type:'demography',text:'Frances Goldscheider: 0.0'},
{type:'famplan',text:'Marta Perez-Gonzales: 0.0'},
{type:'famplan',text:'Shaoxian Wang: 0.0'},
{type:'demography',text:'Clifford C. Clogg: 0.0'},
{type:'famplan',text:'Salif Ndiaye: 0.0'},
{type:'demography',text:'Graeme Hugo: 0.0'},
{type:'demography',text:'Kathryn A. London: 0.0'},
{type:'pubh',text:'Beth Collins: 0.0'},
{type:'famplan',text:'Gustavo Castellanos: 0.0'},
{type:'sociology',text:'Sonalde Desai: 0.0'},
{type:'famplan',text:'Eugenia Monterroso: 0.0'},
{type:'demography',text:'Jo Ann Jones: 0.0'},
{type:'demography',text:'Li Yongpiing: 0.0'},
{type:'famplan',text:'S. Firoza Begum: 0.0'},
{type:'demography',text:'Kristin A. Moore: 0.0'},
{type:'famplan',text:'T. R. Balakrishnan: 0.0'},
{type:'pubh',text:'Wick Warren: 0.0'},
{type:'demography',text:'Linda Adair: 0.0'},
{type:'famplan',text:'Rowland V. Rider: 0.0'},
{type:'famplan',text:'Diego Berrio: 0.0'},
{type:'famplan',text:'German Rodriguez: 0.0'},
{type:'statistics',text:'Alvin C. Pellom: 0.0'},
{type:'sociology',text:'Jeanne Brooks-Gunn: 0.0'},
{type:'famplan',text:'Karin E. Johnson: 0.0'},
{type:'famplan',text:'Zandra Castaneda: 0.0'},
{type:'famplan',text:'Robert T. Michael: 0.0'},
{type:'famplan',text:'Sandra L. Hofferth: 0.0'},
{type:'sociology',text:'Charles B. Nam: 0.0'},
{type:'pubh',text:'Marjorie C. Horn: 0.0'},
{type:'demography',text:'Brent C. Miller: 0.0'},
{type:'famplan',text:'Peter R. Lamptey: 0.0'},
{type:'famplan',text:'Lamine Gueye: 0.0'},
{type:'general',text:'Douglas A. Wolf: 0.0'},
{type:'demography',text:'Xu Yi: 0.0'},
{type:'famplan',text:'Anne Whatley: 0.0'},
{type:'demography',text:'Darryl J. Holman: 0.0'},
{type:'demography',text:'Mercedes Concepcion: 0.0'},
{type:'famplan',text:'Doris Sosa: 0.0'},
{type:'pubh',text:'Kathleen Turczyn: 0.0'},
{type:'sociology',text:'Shenyang Guo: 0.0'},
{type:'famplan',text:'Antonio Serrano Zavala: 0.0'},
{type:'famplan',text:'Martha A. Teitelbaum: 0.0'},
{type:'pubh',text:'Arline T. Geronimus: 0.0'},
{type:'demography',text:'Raymond J. Peterson: 0.0'},
{type:'economics',text:'Rebeca Wong: 0.0'},
{type:'famplan',text:'Mildred Vera: 0.0'},
{type:'famplan',text:'Anameli Monroy De Velasco: 0.0'},
{type:'demography',text:'Datin Noor Laily Bt. Dato Abu Bakar: 0.0'},
{type:'demography',text:'Jacques Vallin: 0.0'},
{type:'famplan',text:'Esther Boohene: 0.0'},
{type:'famplan',text:'Julie Convisser: 0.0'},
{type:'economics',text:'Arleen Leibowitz: 0.0'},
{type:'statistics',text:'Max A. Woodbury: 0.0'},
{type:'famplan',text:'Lynne Wilkens: 0.0'},
{type:'demography',text:'John F. Stewart: 0.0'},
{type:'pubh',text:'David P. Johnson: 0.0'},
{type:'demography',text:'Ian Diamond: 0.0'},
{type:'pubh',text:'Faye L. Wong: 0.0'},
{type:'eugenics',text:'Karen Oppenheim Mason: 0.0'},
{type:'famplan',text:'Flor Cardoso Suarez: 0.0'},
{type:'demography',text:'Gu Baochang: 0.0'},
{type:'famplan',text:'Asta M. Kenney: 0.0'},
{type:'famplan',text:'Michael Welsh: 0.0'},
{type:'famplan',text:'Susan Wright: 0.0'},
{type:'famplan',text:'L. P. Chow: 0.0'},
{type:'sociology',text:'Douglas L. Anderton: 0.0'},
{type:'demography',text:'Christine A. Bachrach: 0.0'},
{type:'famplan',text:'Alexander E. Omu: 0.0'},
{type:'famplan',text:'Stacey Plichta: 0.0'},
{type:'famplan',text:'Ben Truman: 0.0'},
{type:'famplan',text:'Nadine Burton: 0.0'},
{type:'eugenics',text:'Kenneth L. Campbell: 0.0'},
{type:'famplan',text:'Lawrence J. Dolan: 0.0'},
{type:'demography',text:'Mark R. Emerson: 0.0'},
{type:'famplan',text:'Celene Aluvihare: 0.0'},
{type:'famplan',text:'Anne R. Cross: 0.0'},
{type:'famplan',text:'Mark E. Mcbride: 0.0'},
{type:'demography',text:'Marvin Eisen: 0.0'},
{type:'demography',text:'Roger Avery: 0.0'},
{type:'pubh',text:'Thomas A. Peterman: 0.0'},
{type:'famplan',text:'Hui-Sheng Lin: 0.0'},
{type:'famplan',text:'Abdallah M. Abdel-Aziz: 0.0'},
{type:'famplan',text:'Ariawan Soejoenoes: 0.0'},
{type:'demography',text:'Daniel Kraushaar: 0.0'},
{type:'famplan',text:'Kathy Kennedy: 0.0'},
{type:'famplan',text:'Varda Soskolne: 0.0'},
{type:'eugenics',text:'A. Meredith John: 0.0'},
{type:'demography',text:'Gugulethu Gule: 0.0'},
{type:'famplan',text:'Birgitte Jensen: 0.0'},
{type:'pubh',text:'Bruce C. Campbell: 0.0'},
{type:'famplan',text:'Karen Johnson Lassner: 0.0'},
{type:'pubh',text:'Loretta E. Wolfe: 0.0'},
{type:'famplan',text:'Angela Spinelli: 0.0'},
{type:'famplan',text:'Yankuba Dibba: 0.0'},
{type:'famplan',text:'Lynne Gaffikin: 0.0'},
{type:'famplan',text:'Simonetta Landucci Tosi: 0.0'},
{type:'famplan',text:'Bradford A. Kay: 0.0'},
{type:'famplan',text:'Marcial Solis: 0.0'},
{type:'famplan',text:'John C. Caldwell: 0.0'},
{type:'demography',text:'Yasuhiko Saito: 0.0'},
{type:'demography',text:'Vicente Paqueo: 0.0'},
{type:'demography',text:'Ephraim Hlophe: 0.0'},
{type:'famplan',text:'Borhan Shrydeh: 0.0'},
{type:'famplan',text:'Felicia Hance Stewart: 0.0'},
{type:'demography',text:'B. Lindsay Lowell: 0.0'},
{type:'pubh',text:'Dwain Wilcox: 0.0'},
{type:'famplan',text:'Nellie Mathu: 0.0'},
{type:'demography',text:'Jane A. Menken: 0.0'},
{type:'famplan',text:'Anrudh Jain: 0.0'},
{type:'famplan',text:'Joseph Dwyer: 0.0'},
{type:'pubh',text:'Myron J. Frank: 0.0'},
{type:'pubh',text:'Joan H. Salim: 0.0'},
{type:'famplan',text:'Niels K. Rasmussen: 0.0'},
{type:'famplan',text:'Jean Jackson: 0.0'},
{type:'famplan',text:'John Chombo: 0.0'},
{type:'famplan',text:'Janine M. Morgall: 0.0'},
{type:'famplan',text:'John H. Bratt: 0.0'},
{type:'famplan',text:'Pansy Hamilton: 0.0'},
{type:'sociology',text:'Katharine M. Donato: 0.0'},
{type:'sociology',text:'Scott J. South: 0.0'},
{type:'famplan',text:'Grace Wambwa: 0.0'},
{type:'famplan',text:'Daniel B. Fried: 0.0'},
{type:'demography',text:'David R. Williams: 0.0'},
{type:'demography',text:'Ann P. Riley: 0.0'},
{type:'famplan',text:'Voahangi Ravao: 0.0'},
{type:'demography',text:'R. S. Oropesa: 0.0'},
{type:'pubh',text:'Donna M. Strobino: 0.0'},
{type:'demography',text:'Peter Mcdonald: 0.0'},
{type:'famplan',text:'Martha Ann Teitelbaum: 0.0'},
{type:'famplan',text:'Elizabeth Wollast: 0.0'},
{type:'pubh',text:'Barbara E. Crawley: 0.0'},
{type:'famplan',text:'Fahad Hiyari: 0.0'},
{type:'general',text:'Omer R. Galle: 0.0'},
{type:'famplan',text:'Paul Shumba: 0.0'},
{type:'famplan',text:'Tom Turk: 0.0'},
{type:'famplan',text:'Jacqueline D. Forrest: 0.0'},
{type:'famplan',text:'Kevin R. Oreilly: 0.0'},
{type:'demography',text:'Robert H. Weller: 0.0'},
{type:'famplan',text:'Mary V. Wonga: 0.0'},
{type:'famplan',text:'Ching-Ching Chen Cernada: 0.0'},
{type:'demography',text:'Eileen M. Crimmins: 0.0'},
{type:'famplan',text:'Eugene Weiss: 0.0'},
{type:'history',text:'Sidney Goldstein: 0.0'},
{type:'famplan',text:'Michele E. Grandolfo: 0.0'},
{type:'famplan',text:'Anne Verougstraete: 0.0'},
{type:'famplan',text:'Patricia Donovan: 0.0'},
{type:'famplan',text:'Tunde Taylor-Thomas: 0.0'},
{type:'famplan',text:'John Cleland: 0.0'},
{type:'demography',text:'Yean-Ju Lee: 0.0'},
{type:'famplan',text:'Michel Boutsen: 0.0'},
{type:'pubh',text:'Donna F. Stroup: 0.0'},
{type:'famplan',text:'Thomas Dow: 0.0'},
{type:'demography',text:'Mizanur Rahman: 0.0'},
{type:'pubh',text:'Phillip Nieburg: 0.0'},
{type:'famplan',text:'George P. Cernada: 0.0'},
{type:'demography',text:'Edward A. Smith: 0.0'},
{type:'famplan',text:'A. I. Chowdhury: 0.0'},
{type:'pubh',text:'William C. Jenkins: 0.0'},
{type:'pubh',text:'George Brenneman: 0.0'},
{type:'famplan',text:'Rachel Benson Gold: 0.0'},
{type:'demography',text:'Iqbal H. Shah: 0.0'},
{type:'demography',text:'Leslie A. Whittington: 0.0'},
{type:'demography',text:'Hubert Allen: 0.0'},
{type:'famplan',text:'Susan Harlap: 0.0'},
{type:'general',text:'Judith N. Wasserheit: 0.0'},
{type:'pubh',text:'R. J. Berry: 0.0'},
{type:'pubh',text:'Linda Washington: 0.0'},
{type:'famplan',text:'Jane Silverman: 0.0'},
{type:'famplan',text:'Nancy C. Baughman: 0.0'},
{type:'famplan',text:'Rose De Buysscher: 0.0'},
{type:'pubh',text:'Ernest H. Kimball: 0.0'},
{type:'demography',text:'Liang Zhiwu: 0.0'},
{type:'pubh',text:'Helene D. Gayle: 0.0'},
{type:'demography',text:'Francine Van De Walle: 0.0'},
{type:'demography',text:'Gillian Stevens: 0.0'},
{type:'demography',text:'Liu Li: 0.0'},
{type:'demography',text:'Rachel A. Rosenfeld: 0.0'},
{type:'famplan',text:'Jeffrey L. Tharp: 0.0'},
{type:'demography',text:'Thomas E. Dow Jr.: 0.0'},
{type:'famplan',text:'Young Mi Kim: 0.0'},
{type:'demography',text:'Thomas M. Mcdevitt: 0.0'},
{type:'famplan',text:'Patsy Leemans: 0.0'},
{type:'pubh',text:'John S. Moran: 0.0'},
{type:'famplan',text:'Momodou Jeng: 0.0'},
{type:'famplan',text:'Peter Lamptey: 0.0'},
{type:'famplan',text:'Benedict Dhlodhlo: 0.0'},
{type:'famplan',text:'Kadi Traore: 0.0'},
{type:'famplan',text:'Margaret Thuo: 0.0'},
{type:'famplan',text:'Angelique Bregentzer: 0.0'},
{type:'demography',text:'Elena S. H. Yu: 0.0'},
{type:'famplan',text:'Bruno Dujardin: 0.0'},
{type:'famplan',text:'Philip G. Lampe: 0.0'},
{type:'demography',text:'Allan Parnell: 0.0'},
{type:'pubh',text:'William Laroque: 0.0'},
{type:'famplan',text:'Tamara Smith: 0.0'},
{type:'famplan',text:'G. Ebun Delano: 0.0'},
{type:'sociology',text:'Ann Klimas Blanc: 0.0'},
{type:'famplan',text:'Djunghu Balowa: 0.0'},
{type:'famplan',text:'Joseph T. Taylor-Thomas: 0.0'},
{type:'famplan',text:'Mark Oberle: 0.0'},
{type:'famplan',text:'John Stoeckel: 0.0'},
{type:'famplan',text:'Bonnie Faigeles: 0.0'},
{type:'famplan',text:'William Glass: 0.0'},
{type:'demography',text:'Napaporn Chayovan: 0.0'},
{type:'famplan',text:'Niki Cotten: 0.0'},
{type:'famplan',text:'Kua Wongboonsin: 0.0'},
{type:'famplan',text:'Harbandinah Pietojo: 0.0'},
{type:'demography',text:'A.K.M.A. Chowdhury: 0.0'},
{type:'demography',text:'Evelyne Lapierre-Adamcyk: 0.0'},
{type:'famplan',text:'Mike Machuca: 0.0'},
{type:'famplan',text:'Jennifer Macias: 0.0'},
{type:'famplan',text:'Thomas W. Valente: 0.0'},
{type:'sociology',text:'George Kephart: 0.0'},
{type:'pubh',text:'Paul Z. Siegel: 0.0'},
{type:'demography',text:'Mohamed Bailey: 0.0'},
{type:'demography',text:'Stan L. Albrecht: 0.0'},
{type:'demography',text:'Frances Kobrin Goldscheider: 0.0'},
{type:'famplan',text:'Karen J. Mason: 0.0'},
{type:'demography',text:'Shanyisa Khasiani: 0.0'},
{type:'pubh',text:'Adele L. Franks: 0.0'},
{type:'demography',text:'Karin L. Brewster: 0.0'},
{type:'famplan',text:'Theodore M. King: 0.0'},
{type:'demography',text:'Robin M. Weinick: 0.0'},
{type:'pubh',text:'Isolde L. Alexander: 0.0'},
{type:'famplan',text:'Abdallah Abdel-Aziz: 0.0'},
{type:'famplan',text:'June Tsodzai: 0.0'},
{type:'demography',text:'Michael A. Stoto: 0.0'},
{type:'famplan',text:'Ubaidur Rob: 0.0'},
{type:'famplan',text:'Mogens Osler: 0.0'},
{type:'famplan',text:'Chirhamolekwa Chirwisa: 0.0'},
{type:'pubh',text:'Robert A. Hahn: 0.0'},
{type:'famplan',text:'Farida Akhter Jahan: 0.0'},
{type:'eugenics',text:'Vladimir Shkolnikov: 0.0'},
{type:'famplan',text:'Azara Bamba: 0.0'},
{type:'general',text:'Alan H. Bittles: 0.0'},
{type:'statistics',text:'Karen A. Woodrow: 0.0'},
{type:'demography',text:'Mark A. Fossett: 0.0'},
{type:'famplan',text:'Rosalie Streett: 0.0'},
{type:'famplan',text:'Atiqur Rahman Khan: 0.0'},
{type:'famplan',text:'Dorian Powell: 0.0'},
{type:'demography',text:'Dorie G. Williams: 0.0'},
{type:'famplan',text:'M. A. Khan: 0.0'},
{type:'famplan',text:'Linda B. Williams: 0.0'},
{type:'famplan',text:'Alberto Rizo: 0.0'},
{type:'pubh',text:'E. Russell Alexander: 0.0'},
{type:'famplan',text:'Phyllis Wingo: 0.0'},
{type:'famplan',text:'Evelyn G. Landry: 0.0'},
{type:'famplan',text:'Phyllis A. Wingo: 0.0'},
{type:'famplan',text:'Chibalonza Kashwantale: 0.0'},
{type:'general',text:'James W. Curtsinger: 0.0'},
{type:'famplan',text:'Katya Masnyk: 0.0'},
{type:'sociology',text:'David J. Landry: 0.0'},
{type:'general',text:'Jennifer Greene: 0.0'},
{type:'general',text:'Nancy E. Riley: 0.0'},
{type:'famplan',text:'Donald Weeden: 0.0'},
{type:'famplan',text:'Ruth S. Simmons: 0.0'},
{type:'demography',text:'Ellen Percy Kraly: 0.0'},
{type:'demography',text:'Nazli Baydar: 0.0'},
{type:'demography',text:'Sanders D. Korenman: 0.0'},
{type:'sociology',text:'Glenn V. Fuguitt: 0.0'},
{type:'sociology',text:'Alan Booth: 0.0'},
{type:'sociology',text:'William G. Axinn: 0.0'},
{type:'demography',text:'Melissa A. Hardy: 0.0'},
{type:'famplan',text:'Stacey B. Plichta: 0.0'},
{type:'demography',text:'A. K. M. Alauddin Chowdhury: 0.0'},
{type:'pubh',text:'Sharon Ramirez: 0.0'},
{type:'famplan',text:'Philip Guest: 0.0'},
{type:'famplan',text:'Emily Rosenbaum: 0.0'},
{type:'famplan',text:'Delia Haustein: 0.0'},
{type:'famplan',text:'Janice Miller: 0.0'},
{type:'demography',text:'Cameron Campbell: 0.0'},
{type:'demography',text:'Geraldine P. Mineau: 0.0'},
{type:'demography',text:'Terrance D. Olson: 0.0'},
{type:'demography',text:'J. Kelly Mccoy: 0.0'},
{type:'demography',text:'Robert Higginson: 0.0'},
{type:'demography',text:'Jens Lauritsen: 0.0'},
{type:'demography',text:'Denise B. Kandel: 0.0'},
{type:'famplan',text:'Jooean Tan: 0.0'},
{type:'famplan',text:'Kitty Hsu Dana: 0.0'},
{type:'demography',text:'Alan L. Ginsburg: 0.0'},
{type:'pubh',text:'Jeffrey Lancashire: 0.0'},
{type:'eugenics',text:'Vaino Kannisto: 0.0'},
{type:'general',text:'Susan Greenhalgh: 0.0'},
{type:'general',text:'Lin Fu De: 0.0'},
{type:'demography',text:'W. P. Butz: 0.0'},
{type:'demography',text:'Bhakta B. Gubhaju: 0.0'},
{type:'famplan',text:'Nancy Birdsall: 0.0'},
{type:'demography',text:'Kerry Richter: 0.0'},
{type:'demography',text:'Sherrie Kossoudji: 0.0'},
{type:'demography',text:'Sairudee Vorakitphokatorn: 0.0'},
{type:'general',text:'Albert D. Klassen: 0.0'},
{type:'famplan',text:'Jose Ochoa: 0.0'},
{type:'famplan',text:'Joaquin Nunez: 0.0'},
{type:'demography',text:'A. Roger Thatcher: 0.0'},
{type:'demography',text:'Lee L. Bean: 0.0'},
{type:'famplan',text:'John L. Peterson: 0.0'},
{type:'famplan',text:'Brian J. Mccarthy: 0.0'},
{type:'famplan',text:'Emile T. Woods: 0.0'},
{type:'famplan',text:'Zhang Ruyue: 0.0'},
{type:'famplan',text:'Anne K. Duggan: 0.0'},
{type:'eugenics',text:'Teresa Castro Martin: 0.0'},
{type:'famplan',text:'Lucinda H. Glover: 0.0'},
{type:'famplan',text:'Christine Colven: 0.0'},
{type:'general',text:'Kathryn M. Neckerman: 0.0'},
{type:'demography',text:'Peter A. Morrison: 0.0'},
{type:'pubh',text:'Ruth L. Berkelman: 0.0'},
{type:'sociology',text:'Naomi Sealand: 0.0'},
{type:'pubh',text:'Cynthia Mobley: 0.0'},
{type:'famplan',text:'Felicia Stewart: 0.0'},
{type:'demography',text:'Christine L. Himes: 0.0'},
{type:'economics',text:'Susan De Vos: 0.0'},
{type:'economics',text:'Elizabeth Briody: 0.0'},
{type:'demography',text:'Allan M. Parnell: 0.0'},
{type:'general',text:'N. Appaji Rao: 0.0'},
{type:'famplan',text:'Syeda Feroza Begum: 0.0'},
{type:'demography',text:'Christina Witsberger: 0.0'},
{type:'famplan',text:'Jalaluddin Akbar: 0.0'},
{type:'demography',text:'Stan Dsouza: 0.0'},
{type:'famplan',text:'Laura Brown: 0.0'},
{type:'famplan',text:'Felicia Guest: 0.0'},
{type:'economics',text:'Harley L. Browning: 0.0'},
{type:'general',text:'Charles F. Turner: 0.0'},
{type:'demography',text:'Peter O. Way: 0.0'},
{type:'famplan',text:'Rachita Na Pattalung: 0.0'},
{type:'famplan',text:'Tessa M. Wardlaw: 0.0'},
{type:'famplan',text:'Pascaline Sebgo: 0.0'},
{type:'famplan',text:'Charlotte Hord: 0.0'},
{type:'famplan',text:'Thomas Fenn: 0.0'},
{type:'famplan',text:'Janie Benson: 0.0'},
{type:'demography',text:'Karol J. Krotki: 0.0'},
{type:'general',text:'Ulla Larsen: 0.0'},
{type:'famplan',text:'Diane Binson: 0.0'},
{type:'famplan',text:'Merrill Wolf: 0.0'},
{type:'famplan',text:'Laila Baqee: 0.0'},
{type:'demography',text:'Mingkun Zhou: 0.0'},
{type:'pubh',text:'George J. Halpin: 0.0'},
{type:'demography',text:'Stewart E. Tolnay: 0.0'},
{type:'statistics',text:'Guang Guo: 0.0'},
{type:'demography',text:'E. Walter Terrie: 0.0'},
{type:'sociology',text:'Andrew T. Miller: 0.0'},
{type:'famplan',text:'Andrew Fisher: 0.0'},
{type:'famplan',text:'Roberta Herceg-Baron: 0.0'},
{type:'demography',text:'John Baj: 0.0'},
{type:'economics',text:'Charles C. Griffin: 0.0'},
{type:'famplan',text:'Leah T. Marangu: 0.0'},
{type:'demography',text:'Xiao Zhenyu: 0.0'},
{type:'demography',text:'Richard Fuller: 0.0'},
{type:'demography',text:'Baoyu Xiao: 0.0'},
{type:'demography',text:'David R. Johnson: 0.0'},
{type:'famplan',text:'Gloria Lagos: 0.0'},
{type:'demography',text:'Hubert A. Allen Jr.: 0.0'},
{type:'demography',text:'Ken R. Smith: 0.0'},
{type:'demography',text:'Robert L. Clark: 0.0'},
{type:'demography',text:'Santhat Sermsri: 0.0'},
{type:'demography',text:'David H. Demo: 0.0'},
{type:'history',text:'Timothy W. Guinnane: 0.0'},
{type:'demography',text:'John Kekovole: 0.0'},
{type:'pubh',text:'Lonnie Bristow: 0.0'},
{type:'demography',text:'Kathleen Paasch: 0.0'},
{type:'economics',text:'P. H. Reddy: 0.0'},
{type:'sociology',text:'David E. Kanouse: 0.0'},
{type:'famplan',text:'Daniel H. Klepinger: 0.0'},
{type:'sociology',text:'Tim Futing Liao: 0.0'},
{type:'famplan',text:'Michael Bracher: 0.0'},
{type:'demography',text:'Jean-Pierre Habicht: 0.0'},
{type:'demography',text:'J.-P. Habicht: 0.0'},
{type:'famplan',text:'Kim Streatfield: 0.0'},
{type:'famplan',text:'Haidary Kamal: 0.0'},
{type:'famplan',text:'Sawon Hong: 0.0'},
{type:'demography',text:'Linda Archer: 0.0'},
{type:'general',text:'Hidenori H. Fukui: 0.0'},
{type:'famplan',text:'Mian Bazle Hossain: 0.0'},
{type:'famplan',text:'Jane E. Miller: 0.0'},
{type:'famplan',text:'Naohiro Ogawa: 0.0'},
{type:'demography',text:'Sanders Korenman: 0.0'},
{type:'pubh',text:'Stuart M. Berman: 0.0'},
{type:'demography',text:'Ozer Babakol: 0.0'},
{type:'famplan',text:'Ellen Blaine: 0.0'},
{type:'demography',text:'P. W. Stupp: 0.0'},
{type:'eugenics',text:'Ila A. Maslar: 0.0'},
{type:'famplan',text:'Dorace A. Trottier: 0.0'},
{type:'statistics',text:'Charles F. Manski: 0.0'},
{type:'famplan',text:'Douglas H. Huber: 0.0'},
{type:'demography',text:'Antonio Mcdaniel: 0.0'},
{type:'demography',text:'Ann K. Blanc: 0.0'},
{type:'general',text:'Jeffrey S. Passel: 0.0'},
{type:'famplan',text:'Saul D. Hoffman: 0.0'},
{type:'pubh',text:'Douglas N. Klaucke: 0.0'},
{type:'famplan',text:'Stephen H. Linder: 0.0'},
{type:'demography',text:'Daniel D. Greenfield: 0.0'},
{type:'statistics',text:'Daniel Powers: 0.0'},
{type:'sociology',text:'William Lavely: 0.0'},
{type:'pubh',text:'James A. Mercy: 0.0'},
{type:'general',text:'David R. Townsend: 0.0'},
{type:'famplan',text:'G.M. Kamal: 0.0'},
{type:'famplan',text:'Etienne Van De Walle: 0.0'},
{type:'famplan',text:'Wu Jianming: 0.0'},
{type:'demography',text:'Napaporn Havanon: 0.0'},
{type:'sociology',text:'Lynn K. White: 0.0'},
{type:'statistics',text:'Prithwis Das Gupta: 0.0'},
{type:'famplan',text:'Kim Sturgen: 0.0'},
{type:'demography',text:'Feng Wang: 0.0'},
{type:'pubh',text:'Lisa Giles: 0.0'},
{type:'famplan',text:'Judy Shea: 0.0'},
{type:'famplan',text:'Guo Fei: 0.0'},
{type:'demography',text:'Cynthia B. Lloyd: 0.0'},
{type:'economics',text:'David M. Blau: 0.0'},
{type:'pubh',text:'Liz Greeley: 0.0'},
{type:'pubh',text:'Charles Deam: 0.0'},
{type:'sociology',text:'Pamela Kato Klebanov: 0.0'},
{type:'sociology',text:'Kathleen Mullan Harris: 0.0'},
{type:'famplan',text:'David M. Heer: 0.0'},
{type:'demography',text:'Xie Ying: 0.0'},
{type:'demography',text:'Mark Vanlandingham: 0.0'},
{type:'demography',text:'David Sommers: 0.0'},
{type:'eugenics',text:'Stephen J. Kunitz: 0.0'},
{type:'famplan',text:'Alemayehu G. Mariam: 0.0'},
{type:'statistics',text:'Neil G. Bennett: 0.0'},
{type:'demography',text:'Dorothy L. Nortman: 0.0'},
{type:'demography',text:'Sandra L. Hanson: 0.0'},
{type:'demography',text:'Laurence Grummer-Strawn: 0.0'},
{type:'famplan',text:'Jason B. Smith: 0.0'},
{type:'famplan',text:'A.H. Guinena: 0.0'},
{type:'famplan',text:'Shafiqur R. Choudhuri: 0.0'},
{type:'demography',text:'Indra Gajanayake: 0.0'},
{type:'demography',text:'Siriwan Siriboon: 0.0'},
{type:'sociology',text:'Jorge Durand: 0.0'},
{type:'demography',text:'William Urton: 0.0'},
{type:'famplan',text:'Carol Pearson: 0.0'},
{type:'famplan',text:'Calvin Goldscheider: 0.0'},
{type:'sociology',text:'Larry Bumpass: 0.0'},
{type:'famplan',text:'Wilma Medica: 0.0'},
{type:'general',text:'Mark Testa: 0.0'},
{type:'demography',text:'Barbara Vaughan: 0.0'},
{type:'famplan',text:'Rosalie Dominik: 0.0'},
{type:'demography',text:'Anatoli Yashin: 0.0'},
{type:'demography',text:'Alice Goldstein: 0.0'},
{type:'famplan',text:'Max Winterhalter: 0.0'},
{type:'eugenics',text:'Anton De Craen: 0.0'},
{type:'pubh',text:'Elizabeth Shapiro: 0.0'},
{type:'general',text:'Marilyn Krogh: 0.0'},
{type:'eugenics',text:'David F. Sly: 0.0'},
{type:'pubh',text:'Lois A. Fingerhut: 0.0'},
{type:'demography',text:'Karen Woodrow: 0.0'},
{type:'pubh',text:'Michael H. Malloy: 0.0'},
{type:'famplan',text:'Ann A. Way: 0.0'},
{type:'famplan',text:'Anthony Bennett: 0.0'},
{type:'general',text:'Pablo Liedo: 0.0'},
{type:'demography',text:'Charles Simkins: 0.0'},
{type:'general',text:'Robert E. Fay: 0.0'},
{type:'famplan',text:'Barbara A. Taylor: 0.0'},
{type:'demography',text:'Linda Meyers: 0.0'},
{type:'eugenics',text:'Patricia L. Johnson: 0.0'},
{type:'demography',text:'Peter Streble: 0.0'},
{type:'demography',text:'Paul P. L. Cheung: 0.0'},
{type:'eugenics',text:'Ric Streatfield: 0.0'},
{type:'statistics',text:'J. Gregory Robinson: 0.0'},
{type:'famplan',text:'Jeanne Cushing: 0.0'},
{type:'famplan',text:'Joyce Sherman: 0.0'},
{type:'demography',text:'Guo Liu: 0.0'},
{type:'demography',text:'Judith Banister: 0.0'},
{type:'demography',text:'Oona M. Campbell: 0.0'},
{type:'demography',text:'Lindy Williams: 0.0'},
{type:'general',text:'Michel Garenne: 0.0'},
{type:'famplan',text:'Beverly Winikoff: 0.0'},
{type:'famplan',text:'Ayorinde Ajayi: 0.0'},
{type:'famplan',text:'Fadel Diadhiou: 0.0'},
{type:'famplan',text:'Alfredo Guzman: 0.0'},
{type:'famplan',text:'Ernesto La Mata: 0.0'},
{type:'demography',text:'Bashir Ahmed: 0.0'},
{type:'famplan',text:'Doris E. Tirado: 0.0'},
{type:'general',text:'Dina Orozco: 0.0'},
{type:'famplan',text:'Jennifer Strickler: 0.0'},
{type:'famplan',text:'Ayo A. Ajayi: 0.0'},
{type:'famplan',text:'Margaret M. Gachara: 0.0'},
{type:'famplan',text:'Elizabeth C. Cooksey: 0.0'},
{type:'demography',text:'Amy Ong Tsui: 0.0'},
{type:'famplan',text:'Maurice D. Van Arsdol Jr.: 0.0'},
{type:'sociology',text:'William R. Kelly: 0.0'},
{type:'demography',text:'E. Michael Foster: 0.0'},
{type:'demography',text:'Masri Singarimbun: 0.0'},
{type:'demography',text:'Dawn M. Upchurch: 0.0'},
{type:'pubh',text:'Selma Taffel: 0.0'},
{type:'pubh',text:'H. Frank Andersen: 0.0'},
{type:'pubh',text:'Robert L. Davis: 0.0'},
{type:'famplan',text:'Marjorie A. Koblinsky: 0.0'},
{type:'demography',text:'Marianne M. Hillemeier: 0.0'},
{type:'famplan',text:'James M. Harper: 0.0'},
{type:'famplan',text:'Christine Winquist Nord: 0.0'},
{type:'demography',text:'Donna B. Sulak: 0.0'},
{type:'famplan',text:'Sriani Basnayake: 0.0'},
{type:'famplan',text:'Thomas E. Freese: 0.0'},
{type:'demography',text:'Deanna L. Pagnini: 0.0'},
{type:'famplan',text:'Chirwisa Chirhamolekwa: 0.0'},
{type:'famplan',text:'Cecelia Maria Bessa Rodrigues: 0.0'},
{type:'famplan',text:'Allan F. Abrahamse: 0.0'},
{type:'demography',text:'Naomi M. Morris: 0.0'},
{type:'famplan',text:'Ann L. Coker: 0.0'},
{type:'famplan',text:'V. C. Chidambaram: 0.0'},
{type:'famplan',text:'Jay S. Friedman: 0.0'},
{type:'demography',text:'J. Michael Wrigley: 0.0'},
{type:'demography',text:'Robert N. Anderson: 0.0'},
{type:'famplan',text:'Mary Beth Weinberger: 0.0'},
{type:'economics',text:'James Alm: 0.0'},
{type:'famplan',text:'Diane L. Manninen: 0.0'},
{type:'demography',text:'Russell K. Adair: 0.0'},
{type:'demography',text:'David T. Takeuchi: 0.0'},
{type:'famplan',text:'Herbert L. Smith: 0.0'},
{type:'demography',text:'H. Dennis Tolley: 0.0'},
{type:'sociology',text:'Gus Haggstrom: 0.0'},
{type:'famplan',text:'Claire I. Viadro: 0.0'},
{type:'demography',text:'Sian L. Curtis: 0.0'},
{type:'famplan',text:'M. Kathryn Stewart: 0.0'},
{type:'demography',text:'Gary M. Fournier: 0.0'},
{type:'famplan',text:'Victor De Silva: 0.0'},
{type:'famplan',text:'Prem J. Thapa: 0.0'},
{type:'demography',text:'Barbara Laslett: 0.0'},
{type:'famplan',text:'Steven W. Sinding: 0.0'},
{type:'pubh',text:'Patti Waller: 0.0'},
{type:'famplan',text:'Walter Obungu: 0.0'},
{type:'demography',text:'Li Nan: 0.0'},
{type:'demography',text:'P. Lindsay Chase-Lansdale: 0.0'},
{type:'demography',text:'Marin E. Clarkberg: 0.0'},
{type:'demography',text:'Robert J. Lapham: 0.0'},
{type:'demography',text:'Ruth Marinshaw: 0.0'},
{type:'famplan',text:'Rezina Mita: 0.0'},
{type:'demography',text:'Paula Lantz: 0.0'},
{type:'sociology',text:'Hussein A.-A. Sayed: 0.0'},
{type:'demography',text:'Robert Warren: 0.0'},
{type:'demography',text:'Karen A. Polonko: 0.0'},
{type:'demography',text:'Abdel Fattah E. Ismail: 0.0'},
{type:'demography',text:'Luther M. Talbert: 0.0'},
{type:'famplan',text:'Daya Abeywickrema: 0.0'},
{type:'demography',text:'Christine M. Schaeffer: 0.0'},
{type:'sociology',text:'Felicia B. Leclere: 0.0'},
{type:'eugenics',text:'William F. Pratt: 0.0'},
{type:'famplan',text:'Francisco Puac: 0.0'},
{type:'demography',text:'Lorenzo Moreno: 0.0'},
{type:'famplan',text:'Laura A. Brown: 0.0'},
{type:'demography',text:'Robin C. Sickles: 0.0'},
{type:'sociology',text:'Andrew B. Gross: 0.0'},
{type:'sociology',text:'Diane N. Lye: 0.0'},
{type:'demography',text:'Jerald R. Herting: 0.0'},
{type:'demography',text:'Sara Millman: 0.0'},
{type:'demography',text:'Zhu Chuzhu: 0.0'},
{type:'demography',text:'Hans Ullmann: 0.0'},
{type:'demography',text:'Willard L. Rodgers: 0.0'},
{type:'famplan',text:'Marcia A. Angle: 0.0'},
{type:'demography',text:'Jeffrey Thomas: 0.0'},
{type:'demography',text:'James Lee: 0.0'},
{type:'demography',text:'Robert A. Hummer: 0.0'},
{type:'demography',text:'Linda A. Valleroy: 0.0'},
{type:'famplan',text:'Lynne Casper: 0.0'},
{type:'sociology',text:'Gus W. Haggstrom: 0.0'},
{type:'famplan',text:'Michael D. Bracher: 0.0'},
{type:'pubh',text:'Kate Prayer: 0.0'},
{type:'general',text:'Stephen H. Saul: 0.0'},
{type:'demography',text:'Lora G. Myers: 0.0'},
{type:'demography',text:'Thomas K. Martin: 0.0'},
{type:'demography',text:'France Meslé: 0.0'},
{type:'pubh',text:'Charles R. Hammerslough: 0.0'},
{type:'history',text:'Gu Shengzu: 0.0'},
{type:'demography',text:'Elmar HöNekopp: 0.0'},
{type:'demography',text:'Penelope L. Maza: 0.0'},
{type:'famplan',text:'Malcolm Mcneil: 0.0'},
{type:'eugenics',text:'T.R. Balakrishnan: 0.0'},
{type:'demography',text:'James M. White: 0.0'},
{type:'demography',text:'Pat Quiggin: 0.0'},
{type:'demography',text:'Jochen Fleischhacker: 0.0'},
{type:'famplan',text:'Pravin Visaria: 0.0'},
{type:'demography',text:'Ron Lesthaeghe: 0.0'},
{type:'demography',text:'Suet Lim: 0.0'},
{type:'demography',text:'Lisa G. Cope: 0.0'},
{type:'demography',text:'David Neumark: 0.0'},
{type:'famplan',text:'Kristin Anderson Moore: 0.0'},
{type:'famplan',text:'Nancy Dole: 0.0'},
{type:'demography',text:'David Simcox: 0.0'},
{type:'demography',text:'Jennifer Glass: 0.0'},
{type:'sociology',text:'Daniel H. Hill: 0.0'},
{type:'famplan',text:'Maria Solange Valenzuela: 0.0'},
{type:'demography',text:'Kazuo Yamaguchi: 0.0'},
{type:'demography',text:'Gail M. Johnston: 0.0'},
{type:'demography',text:'Mitchell Eggers: 0.0'},
{type:'famplan',text:'Aurora Rabago: 0.0'},
{type:'general',text:'Andrew Cherlin: 0.0'},
{type:'demography',text:'Debra J. Umberson: 0.0'},
{type:'demography',text:'Roger A. Wojtkiewicz: 0.0'},
{type:'demography',text:'Melissa Partin: 0.0'},
{type:'demography',text:'Michael Xinxiang Mao: 0.0'},
{type:'demography',text:'Kul T. Wadhwa: 0.0'},
{type:'famplan',text:'Lisa J. Crockett: 0.0'},
{type:'famplan',text:'Kashwantale Chibalonza: 0.0'},
{type:'demography',text:'Karen Price Carver: 0.0'},
{type:'demography',text:'Linda Young-Demarco: 0.0'},
{type:'general',text:'Philip Hedrick: 0.0'},
{type:'famplan',text:'Beatriz B. Collere Hanff: 0.0'},
{type:'demography',text:'David E. Myers: 0.0'},
{type:'demography',text:'M. Omar Rahman: 0.0'},
{type:'famplan',text:'Jose David Araya Zelaya: 0.0'},
{type:'famplan',text:'Judith A. Levine: 0.0'},
{type:'eugenics',text:'Zheng Wu: 0.0'},
{type:'demography',text:'Weimin Zhang: 0.0'},
{type:'famplan',text:'Karl E. Bauman: 0.0'},
{type:'eugenics',text:'Anatoly G. Vishnevsky: 0.0'},
{type:'famplan',text:'Fabio Sabogal: 0.0'},
{type:'famplan',text:'Junichi Yagi: 0.0'},
{type:'famplan',text:'Anastasia J. Gage-Brandon: 0.0'},
{type:'famplan',text:'Victoria M. Ward: 0.0'},
{type:'demography',text:'James W. Kanan: 0.0'},
{type:'famplan',text:'Robert B. Hill: 0.0'},
{type:'famplan',text:'Alan J. Hawkins: 0.0'},
{type:'demography',text:'Avery M. Guest: 0.0'},
{type:'famplan',text:'Widad Kidane-Mariam: 0.0'},
{type:'demography',text:'Reynolds Farley: 0.0'},
{type:'eugenics',text:'Aden I. Shirwa: 0.0'},
{type:'famplan',text:'Isaac Obeng-Quaidoo: 0.0'},
{type:'demography',text:'Werasit Sittitrai: 0.0'},
{type:'sociology',text:'Patricia H. Craig: 0.0'},
{type:'pubh',text:'Kathi A. Santini: 0.0'},
{type:'economics',text:'Robert J. Willis: 0.0'},
{type:'famplan',text:'Francesca A. Florey: 0.0'},
{type:'famplan',text:'Michael Klitsch: 0.0'},
{type:'demography',text:'Christine Himes: 0.0'},
{type:'demography',text:'Leslie L. Clarke: 0.0'},
{type:'demography',text:'Gary Thompson: 0.0'},
{type:'demography',text:'Leon F. Bouvier: 0.0'},
{type:'general',text:'Isabel V. Sawhill: 0.0'},
{type:'sociology',text:'Kumiko Shibuya: 0.0'},
{type:'economics',text:'H. Elizabeth Peters: 0.0'},
{type:'demography',text:'Alauddin Chowdhury: 0.0'},
{type:'demography',text:'Edward E. Telles: 0.0'},
{type:'sociology',text:'Lynne M. Casper: 0.0'},
{type:'demography',text:'Kevin Wieser: 0.0'},
{type:'demography',text:'J. Mayone Stycos: 0.0'},
{type:'demography',text:'Burton Singer: 0.0'},
{type:'famplan',text:'Dominique Meekers: 0.0'},
{type:'famplan',text:'Paul W. Stupp: 0.0'},
{type:'famplan',text:'Moise Balma: 0.0'},
{type:'demography',text:'S. Victor De Silva: 0.0'},
{type:'famplan',text:'Paul Kizito: 0.0'},
{type:'famplan',text:'Nahid Toubia: 0.0'},
{type:'demography',text:'Michael K Miller: 0.0'},
{type:'demography',text:'Mei-Yu Yu: 0.0'},
{type:'demography',text:'Vilma Ortiz: 0.0'},
{type:'famplan',text:'Jennifer Frost: 0.0'},
{type:'famplan',text:'Linda E. Atkinson: 0.0'},
{type:'demography',text:'Elaine Mcdonald: 0.0'},
{type:'pubh',text:'Patricia Golden: 0.0'},
{type:'demography',text:'Paul Taubman: 0.0'},
{type:'famplan',text:'Judith Bruce: 0.0'},
{type:'sociology',text:'Ann E. Biddlecom: 0.0'},
{type:'demography',text:'I. O. Orubuloye: 0.0'},
{type:'demography',text:'Bogdan Wojtyniak: 0.0'},
{type:'eugenics',text:'Wang Zhenglian: 0.0'},
{type:'demography',text:'Kristi L. Hoffman: 0.0'},
{type:'demography',text:'Myron P. Gutmann: 0.0'},
{type:'famplan',text:'Chanpen Saengtienchai: 0.0'},
{type:'demography',text:'Lucky M. Tedrow: 0.0'},
{type:'economics',text:'Peter Berman: 0.0'},
{type:'famplan',text:'Siti Pariani: 0.0'},
{type:'sociology',text:'Thomas L. Hanson: 0.0'},
{type:'demography',text:'Lowell J. Taylor: 0.0'},
{type:'demography',text:'Nancy A. Denton: 0.0'},
{type:'demography',text:'Daphne Spain: 0.0'},
{type:'famplan',text:'Alfred L. Mcalister: 0.0'},
{type:'demography',text:'Charlotte Hohn: 0.0'},
{type:'famplan',text:'John F. May: 0.0'},
{type:'famplan',text:'Sandor A. Balogh: 0.0'},
{type:'pubh',text:'Risa Lavizzo-Mourey: 0.0'},
{type:'pubh',text:'Priscilla B. Holman: 0.0'},
{type:'famplan',text:'Jose Maria Arruda: 0.0'},
{type:'eugenics',text:'Tod A. Ragsdale: 0.0'},
{type:'demography',text:'David W. Rasmussen: 0.0'},
{type:'famplan',text:'Neera Shrestha: 0.0'},
{type:'pubh',text:'Robert J. Weinzimer: 0.0'},
{type:'general',text:'Henry J. Voss: 0.0'},
{type:'demography',text:'David E. Moore: 0.0'},
{type:'demography',text:'Ricardo Amon: 0.0'},
{type:'famplan',text:'Karol Krotki: 0.0'},
{type:'pubh',text:'Louis Salinas: 0.0'},
{type:'demography',text:'William D. Kalsbeek: 0.0'},
{type:'famplan',text:'Marcos Paulo P. De Castro: 0.0'},
{type:'famplan',text:'Gustavo Quiroz: 0.0'},
{type:'eugenics',text:'Loredana Cerbara: 0.0'},
{type:'sociology',text:'Luin Goldring: 0.0'},
{type:'sociology',text:'Evelyn M. Kitagawa: 0.0'},
{type:'famplan',text:'Luis Hernando Ochoa: 0.0'},
{type:'demography',text:'Mckinley L. Blackburn: 0.0'},
{type:'pubh',text:'Glenn A. Flinchum: 0.0'},
{type:'famplan',text:'Jorge Halvas: 0.0'},
{type:'famplan',text:'Gail L. Zellman: 0.0'},
{type:'demography',text:'Lois Paul: 0.0'},
{type:'demography',text:'Henri Leridon: 0.0'},
{type:'famplan',text:'Stephen L. Isaacs: 0.0'},
{type:'demography',text:'J. G. Cleland: 0.0'},
{type:'famplan',text:'Bethany Young: 0.0'},
{type:'demography',text:'P. Sankara Sarma: 0.0'},
{type:'sociology',text:'William H. Frey: 0.0'},
{type:'famplan',text:'Vasantha Kandiah: 0.0'},
{type:'famplan',text:'Jyotsnamoy Chakraborty: 0.0'},
{type:'pubh',text:'Paula Summerour: 0.0'},
{type:'demography',text:'Barbara S. Okun: 0.0'},
{type:'demography',text:'Dominique Ingegneri: 0.0'},
{type:'famplan',text:'Federico R. Leon: 0.0'},
{type:'general',text:'Ronald B. Mincy: 0.0'},
{type:'famplan',text:'Karin Gleiter: 0.0'},
{type:'famplan',text:'Barbara E. Kwast: 0.0'},
{type:'general',text:'Anne Brooks: 0.0'},
{type:'eugenics',text:'Giuseppe Leti: 0.0'},
{type:'demography',text:'David N. Hamill: 0.0'},
{type:'demography',text:'Lisa Berkman: 0.0'},
{type:'demography',text:'Cathleen D. Zick: 0.0'},
{type:'demography',text:'Barbara L. Wolfe: 0.0'},
{type:'demography',text:'Lois E. Paul: 0.0'},
{type:'famplan',text:'Edward O. Laumann: 0.0'},
{type:'eugenics',text:'Paul W. Leslie: 0.0'},
{type:'famplan',text:'Lisa M. Koonin: 0.0'},
{type:'famplan',text:'Cynthia Lloyd: 0.0'},
{type:'famplan',text:'Mohamed Aly Ahmed: 0.0'},
{type:'demography',text:'Jan E. Mutchler: 0.0'},
{type:'demography',text:'Ian D. Diamond: 0.0'},
{type:'famplan',text:'Julia N. Pennbridge: 0.0'},
{type:'sociology',text:'Hussein A. A. Sayed: 0.0'},
{type:'famplan',text:'Alfred Adewuyi: 0.0'},
{type:'eugenics',text:'Michael A. Little: 0.0'},
{type:'famplan',text:'Leela Visaria: 0.0'},
{type:'famplan',text:'Gretchen Cornwell: 0.0'},
{type:'eugenics',text:'Ahmad Alachkar: 0.0'},
{type:'pubh',text:'John Bound: 0.0'},
{type:'demography',text:'Frank F. Furstenberg: 0.0'},
{type:'pubh',text:'Gloria D. Kelly: 0.0'},
{type:'famplan',text:'Octavio Mojarro: 0.0'},
{type:'famplan',text:'Monique Mukamanzi: 0.0'},
{type:'demography',text:'Hussein Abdel-Aziz Sayed: 0.0'},
{type:'famplan',text:'Eliane F. Duarte Franco: 0.0'},
{type:'demography',text:'Frances K. Goldscheider: 0.0'},
{type:'sociology',text:'Geoffrey K. Leigh: 0.0'},
{type:'economics',text:'Paul Lightfoot: 0.0'},
{type:'famplan',text:'John Laing: 0.0'},
{type:'demography',text:'Dennis De Tray: 0.0'},
{type:'famplan',text:'Allan G. Rosenfield: 0.0'},
{type:'demography',text:'James Sweet: 0.0'},
{type:'sociology',text:'Hector Cordero-GuzmáN: 0.0'},
{type:'pubh',text:'Anita Powell: 0.0'},
{type:'statistics',text:'Henry I. Braun: 0.0'},
{type:'demography',text:'Lingxin Hao: 0.0'},
{type:'demography',text:'James C. Knowles: 0.0'},
{type:'pubh',text:'William C. Parra: 0.0'},
{type:'demography',text:'Alan C. Acock: 0.0'},
{type:'famplan',text:'Fara G. Mbodji: 0.0'},
{type:'pubh',text:'Stephanie J. Ventura: 0.0'},
{type:'famplan',text:'Kathy Shepherd Stolley: 0.0'},
{type:'famplan',text:'J. Brooks-Gunn: 0.0'},
{type:'eugenics',text:'Sergei A. Vassin: 0.0'},
{type:'famplan',text:'Cheri Pies: 0.0'},
{type:'famplan',text:'Lisa Kaeser: 0.0'},
{type:'demography',text:'Richard E. Barrett: 0.0'},
{type:'sociology',text:'James C. Mccann: 0.0'},
{type:'economics',text:'Daniel G. Sisler: 0.0'},
{type:'demography',text:'Winston K. Chow: 0.0'},
{type:'demography',text:'Diane J. Macunovich: 0.0'},
{type:'demography',text:'Anthony Pramualratana: 0.0'},
{type:'sociology',text:'Lisa A. Cubbins: 0.0'},
{type:'famplan',text:'Gaston Farr: 0.0'},
{type:'sociology',text:'Ling-Xin Hao: 0.0'},
{type:'general',text:'Christine Cassel: 0.0'},
{type:'demography',text:'J. B. Casterline: 0.0'},
{type:'economics',text:'Richard B. Freeman: 0.0'},
{type:'famplan',text:'Valerie Sedivy: 0.0'},
{type:'famplan',text:'Jamir Chowdhury: 0.0'},
{type:'famplan',text:'Oona Campbell: 0.0'},
{type:'history',text:'Caroline Hoppe: 0.0'},
{type:'demography',text:'Donald Camburn: 0.0'},
{type:'famplan',text:'Renee Samara: 0.0'},
{type:'sociology',text:'C. Matthew Snipp: 0.0'},
{type:'famplan',text:'Howard Wineberg: 0.0'},
{type:'demography',text:'Abate Mammo: 0.0'},
{type:'demography',text:'Riccardo Capocaccia: 0.0'},
{type:'demography',text:'Saad M. Gadalla: 0.0'},
{type:'demography',text:'Paula Goldman: 0.0'},
{type:'demography',text:'John Wooldredge: 0.0'},
{type:'demography',text:'Yuan Jianhua: 0.0'},
{type:'famplan',text:'Katherine M. Stone: 0.0'},
{type:'famplan',text:'Karungari Kiragu: 0.0'},
{type:'demography',text:'Tom Fricke: 0.0'},
{type:'eugenics',text:'Bart Holland: 0.0'},
{type:'demography',text:'Joseph P. Murphy: 0.0'},
{type:'sociology',text:'Mitchell L. Eggers: 0.0'},
{type:'demography',text:'Richard B. Miller: 0.0'},
{type:'general',text:'Vlatko Silobrc̄Ić: 0.0'},
{type:'demography',text:'Donald Huddle: 0.0'},
{type:'demography',text:'Jan F. Brazzell: 0.0'},
{type:'famplan',text:'Deborah Maine: 0.0'},
{type:'demography',text:'Jose Gomez De Leon: 0.0'},
{type:'famplan',text:'Bamikale Feyisetan: 0.0'},
{type:'sociology',text:'Nancy O. Snyder: 0.0'},
{type:'economics',text:'Anil B. Deolalikar: 0.0'},
{type:'demography',text:'Shea O. Rutstein: 0.0'},
{type:'demography',text:'Diana B. Winchie: 0.0'},
{type:'demography',text:'Zai Liang: 0.0'},
{type:'demography',text:'Emilio Parrado: 0.0'},
{type:'demography',text:'Lita J. Domingo: 0.0'},
{type:'economics',text:'Richard Anker: 0.0'},
{type:'sociology',text:'Julia Adams: 0.0'},
{type:'demography',text:'Deborah Whithear: 0.0'},
{type:'demography',text:'Nancy Brandon Tuma: 0.0'},
{type:'demography',text:'Basil G. Zimmer: 0.0'},
{type:'pubh',text:'Sabra Lloyd: 0.0'},
{type:'famplan',text:'Christopher Elias: 0.0'},
{type:'economics',text:'Ruth E. Levine: 0.0'},
{type:'demography',text:'Dennis A. Ahlburg: 0.0'},
{type:'famplan',text:'Serguey Ivanov: 0.0'},
{type:'demography',text:'Haya Stier: 0.0'},
{type:'demography',text:'Laurie Scheuble: 0.0'},
{type:'demography',text:'Francisco Alba: 0.0'},
{type:'demography',text:'Kim M. Lloyd: 0.0'},
{type:'famplan',text:'James A. Sweet: 0.0'},
{type:'demography',text:'Malathi Ram: 0.0'},
{type:'demography',text:'Susan M. Hauan: 0.0'},
{type:'demography',text:'Lanny Thompson: 0.0'},
{type:'sociology',text:'Lisa J. Neidert: 0.0'},
{type:'geography',text:'Judith W. Meyer: 0.0'},
{type:'demography',text:'Yoshie Imai: 0.0'},
{type:'demography',text:'Alan D. Lopez: 0.0'},
{type:'demography',text:'Ann Bowman Jannetta: 0.0'},
{type:'demography',text:'Ellen Eliason Kisker: 0.0'},
{type:'demography',text:'Daniel Alex Heckert: 0.0'},
{type:'demography',text:'Patricia J. Glynn: 0.0'},
{type:'history',text:'Andrew S. London: 0.0'},
{type:'eugenics',text:'Chintana Pejaranonda: 0.0'},
{type:'demography',text:'Irma T. Elo: 0.0'},
{type:'sociology',text:'Lauren J. Krivo: 0.0'},
{type:'demography',text:'Devaki Jain: 0.0'},
{type:'demography',text:'Karen Booth: 0.0'},
{type:'sociology',text:'Toni Falbo: 0.0'},
{type:'pubh',text:'Jacqueline P. Davis: 0.0'},
{type:'demography',text:'Arthur Sakamoto: 0.0'},
{type:'demography',text:'Paul T. Schollaert: 0.0'},
{type:'famplan',text:'Apichat Chamratrithirong: 0.0'},
{type:'famplan',text:'A. R. Khan: 0.0'},
{type:'eugenics',text:'Aykut Toros: 0.0'},
{type:'famplan',text:'Julia A. Walsh: 0.0'},
{type:'economics',text:'Horacio Soberon-Ferrer: 0.0'},
{type:'demography',text:'Alex Heckert: 0.0'},
{type:'demography',text:'Yuanreng Hu: 0.0'},
{type:'demography',text:'Christine E. Peterson: 0.0'},
{type:'demography',text:'Christopher Wilson: 0.0'},
{type:'demography',text:'Peter R. Mueser: 0.0'},
{type:'demography',text:'Beth J. Soldo: 0.0'},
{type:'demography',text:'Eric S. Rothman: 0.0'},
{type:'sociology',text:'Ellen P. Kraly: 0.0'},
{type:'general',text:'Mark J. Miller: 0.0'},
{type:'demography',text:'Barbara Thomas: 0.0'},
{type:'eugenics',text:'Anne Babette Wils: 0.0'},
{type:'demography',text:'Deborah A. Phillips: 0.0'},
{type:'demography',text:'Sara Mc Lanahan: 0.0'},
{type:'demography',text:'Pradip K. Muhuri: 0.0'},
{type:'demography',text:'Zhongren Jing: 0.0'},
{type:'famplan',text:'Abdul Razzaque Rukanuddin: 0.0'},
{type:'famplan',text:'Mariam Maiga: 0.0'},
{type:'demography',text:'Pamela F. Delargy: 0.0'},
{type:'demography',text:'Jeffrey Kallan: 0.0'},
{type:'demography',text:'Jennifer Lauby: 0.0'},
{type:'demography',text:'Jeroen Van Ginneken: 0.0'},
{type:'demography',text:'Pavalavalli Govindasamy: 0.0'},
{type:'history',text:'E. M. Beck: 0.0'},
{type:'statistics',text:'Larry S. Corder: 0.0'},
{type:'demography',text:'Xian Liu: 0.0'},
{type:'demography',text:'Norman J. Waitzman: 0.0'},
{type:'demography',text:'Charles A. Calhoun: 0.0'},
{type:'general',text:'Felipe GarcíA EspañA: 0.0'},
{type:'demography',text:'Audrey Vandenheuvel: 0.0'},
{type:'famplan',text:'Gail Savina: 0.0'},
{type:'demography',text:'Dianne G. Goodwin: 0.0'},
{type:'demography',text:'Renata Forste: 0.0'},
{type:'demography',text:'K. Jill Kiecolt: 0.0'},
{type:'famplan',text:'Virginia Hight Laukaran: 0.0'},
{type:'demography',text:'Donald Oellerich: 0.0'},
{type:'demography',text:'Denise Kandel: 0.0'},
{type:'demography',text:'D. J. Macunovich: 0.0'},
{type:'demography',text:'Jiwon Jeon: 0.0'},
{type:'famplan',text:'Terry Sollom: 0.0'},
{type:'demography',text:'Kenneth H. Fliess: 0.0'},
{type:'economics',text:'Robert A. Pollak: 0.0'},
{type:'demography',text:'William A. V. Clark: 0.0'},
{type:'demography',text:'Todd P. Steen: 0.0'},
{type:'demography',text:'Arne L. Kalleberg: 0.0'},
{type:'demography',text:'Benjamin P. Givens: 0.0'},
{type:'famplan',text:'Evelyn Landry: 0.0'},
{type:'demography',text:'Lee-Jay Cho: 0.0'},
{type:'pubh',text:'Lynne S. Wilcox: 0.0'},
{type:'demography',text:'Xiushi Yang: 0.0'},
{type:'famplan',text:'Kevin Mckillop: 0.0'},
{type:'demography',text:'J. R. Rele: 0.0'},
{type:'demography',text:'Laurence M. Grummer-Strawn: 0.0'},
{type:'demography',text:'John Ermisch: 0.0'},
{type:'demography',text:'Karen Holden: 0.0'},
{type:'demography',text:'Jingyuan Yu: 0.0'},
{type:'demography',text:'Tim F. Liao: 0.0'},
{type:'famplan',text:'Maureen Sullivan: 0.0'},
{type:'demography',text:'Anju Malhotra Taj: 0.0'},
{type:'demography',text:'Dolores Acevedo: 0.0'},
{type:'sociology',text:'Scott C. Harrison: 0.0'},
{type:'demography',text:'Susan Newcomer: 0.0'},
{type:'famplan',text:'Jennifer Van Vort: 0.0'},
{type:'famplan',text:'Lynn P. Freedman: 0.0'},
{type:'sociology',text:'Brooks Bitterman: 0.0'},
{type:'demography',text:'Hyunju Kim: 0.0'},
{type:'history',text:'Ellen A. Kramarow: 0.0'},
{type:'demography',text:'Richard Williams: 0.0'},
{type:'demography',text:'R. Stephen Cantrell: 0.0'},
{type:'eugenics',text:'Arpad Szakolczai: 0.0'},
{type:'sociology',text:'Eric Fong: 0.0'},
{type:'demography',text:'Angelique Chan: 0.0'},
{type:'demography',text:'Oded Galor: 0.0'},
{type:'demography',text:'Agnes Riedmann: 0.0'},
{type:'demography',text:'Jing Shu: 0.0'},
{type:'sociology',text:'Yooshik Gong: 0.0'},
{type:'demography',text:'Franklin D. Wilson: 0.0'},
{type:'demography',text:'Alfred Demaris: 0.0'},
{type:'demography',text:'William T. Liu: 0.0'},
{type:'demography',text:'Peter B. Wood: 0.0'},
{type:'demography',text:'Graham Lord: 0.0'},
{type:'demography',text:'Michael Fix: 0.0'},
{type:'sociology',text:'Rebecca Jean Emigh: 0.0'},
{type:'demography',text:'Wayne A. Cornelius: 0.0'},
{type:'demography',text:'Mei-Yuyu: 0.0'},
{type:'demography',text:'Laura Spencer Loomis: 0.0'},
{type:'demography',text:'S. R. Millman: 0.0'},
{type:'demography',text:'David L. Brown: 0.0'},
{type:'sociology',text:'Scott R. Eliason: 0.0'},
{type:'famplan',text:'Laura Roper: 0.0'},
{type:'demography',text:'Michael A. Boozer: 0.0'},
{type:'demography',text:'David I. Kertzer: 0.0'},
{type:'demography',text:'Glenna Spitze: 0.0'},
{type:'demography',text:'Karen Stanecki: 0.0'},
{type:'famplan',text:'Nassour Ouaidou: 0.0'},
{type:'sociology',text:'Maxine Seaborn Thompson: 0.0'},
{type:'economics',text:'J. Brad Schwartz: 0.0'},
{type:'statistics',text:'Allen L. Schirm: 0.0'},
{type:'demography',text:'Virginia S. Cain: 0.0'},
{type:'demography',text:'Jane S. Durch: 0.0'},
{type:'pubh',text:'Ann C. Klassen: 0.0'},
{type:'pubh',text:'Edward L. Hunter: 0.0'},
{type:'famplan',text:'Richard R. Fordyce: 0.0'},
{type:'famplan',text:'Sara R. Millman: 0.0'},
{type:'demography',text:'Johan Surkyn: 0.0'},
{type:'famplan',text:'Jean Baker: 0.0'},
{type:'demography',text:'Joseph J. Minarik: 0.0'},
{type:'economics',text:'M. Louise Fox: 0.0'},
{type:'famplan',text:'James W. Mcnally: 0.0'},
{type:'eugenics',text:'Viviana Egidi: 0.0'},
{type:'sociology',text:'Ding-Tzann Lii: 0.0'},
{type:'famplan',text:'Shea Rutstein: 0.0'},
{type:'demography',text:'Young-Hee Yoon: 0.0'},
{type:'demography',text:'Baochang Gu: 0.0'},
{type:'demography',text:'Carla Makhlouf Obermeyer: 0.0'},
{type:'demography',text:'Lee A. Lillard: 0.0'},
{type:'famplan',text:'Margaret Terry Orr: 0.0'},
{type:'demography',text:'Karen Kuhlthau: 0.0'},
{type:'general',text:'Morrison G. Wong: 0.0'},
{type:'economics',text:'Jacob Alex Klerman: 0.0'},
{type:'economics',text:'John Harris: 0.0'},
{type:'demography',text:'A. I. Abdelrahman: 0.0'},
{type:'demography',text:'Gbolahan A. Oni: 0.0'},
{type:'demography',text:'Mckinley Blackburn: 0.0'},
{type:'demography',text:'Shaomin Li: 0.0'},
{type:'demography',text:'Glenn D. Deane: 0.0'},
{type:'famplan',text:'Aristide Aplogan: 0.0'},
{type:'demography',text:'Eve Powell-Griner: 0.0'},
{type:'demography',text:'Renbao Chen: 0.0'},
{type:'famplan',text:'Futing Liao: 0.0'},
{type:'economics',text:'Robert E. B. Lucas: 0.0'},
{type:'pubh',text:'Marcy Cynamon: 0.0'},
{type:'general',text:'Shiro Horiuchi: 0.0'},
{type:'famplan',text:'Ruth Roemer: 0.0'},
{type:'demography',text:'Young Kim: 0.0'},
{type:'economics',text:'George J. Borjas: 0.0'},
{type:'demography',text:'Nicholas Eberstadt: 0.0'},
{type:'demography',text:'W. Brian Arthur: 0.0'},
{type:'famplan',text:'Susan F. Newcomer: 0.0'},
{type:'famplan',text:'Sheldon J. Segal: 0.0'},
{type:'demography',text:'Abbas Bhuiya: 0.0'},
{type:'pubh',text:'Farrell Wolfson: 0.0'},
{type:'sociology',text:'Adam Bickford: 0.0'},
{type:'famplan',text:'Anna Titkow: 0.0'},
{type:'demography',text:'Malinee Wongsith: 0.0'},
{type:'famplan',text:'Phillips Cutright: 0.0'},
{type:'sociology',text:'Zhenchao Qian: 0.0'},
{type:'demography',text:'Juxin Di: 0.0'},
{type:'demography',text:'C. Raymond Bingham: 0.0'},
{type:'demography',text:'George C. Myers: 0.0'},
{type:'demography',text:'Kay E. Anderson: 0.0'},
{type:'famplan',text:'Philip Kestelman: 0.0'},
{type:'demography',text:'James W. Shockey: 0.0'},
{type:'famplan',text:'Lauren A. Chester: 0.0'},
{type:'demography',text:'K. S. Gnanasekaran: 0.0'},
{type:'famplan',text:'Elisabeth A. Ferraz: 0.0'},
{type:'statistics',text:'George Y. Wong: 0.0'}
];
var comps = [
{type:'info',text:'Nodes: 3.0: Density: 1.0'},
{type:'demography',text:'Donald J. Bogue: 1.0'},
{type:'famplan',text:'Deborah Oakley: 1.0'},
{type:'famplan',text:'Susan Sereika: 1.0'},
{type:'info',text:'Nodes: 3.0: Density: 1.0'},
{type:'demography',text:'Jennifer Bhattacharya: 1.0'},
{type:'demography',text:'Barbra Richardson: 1.0'},
{type:'sociology',text:'Judith Blake: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'general',text:'Ronald Lee: 1.0'},
{type:'general',text:'Tim Miller: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'demography',text:'W. Parker Frisbie: 1.0'},
{type:'demography',text:'Douglas Forbes: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'demography',text:'Harriet B. Presser: 1.0'},
{type:'demography',text:'Sunita Kishor: 1.0'},
{type:'info',text:'Unconnected:'},
{type:'demography',text:'Joseph J. Spengler'},
{type:'demography',text:'Kingsley Davis'},
{type:'demography',text:'Nathan Keyfitz'},
{type:'famplan',text:'Norman B. Ryder'},
{type:'famplan',text:'Paul Demeny'},
{type:'demography',text:'Walter Willcox'},
{type:'famplan',text:'Bernard Berelson'},
{type:'famplan',text:'Oscar Harkavy'},
{type:'demography',text:'Garrett Hardin'}
];
var authors = 1443;
 var density = 0.0;
 var components = 6;
-->