<!--
 var comp1 = [
{type:'info',text:'Nodes: 104.0: Density: 0.06'},
{type:'pubh',text:'Ronald Freedman: 0.26'},
{type:'eugenics',text:'J. Mayone Stycos: 0.24'},
{type:'pubh',text:'R. R. Puffer: 0.2'},
{type:'pubh',text:'C. A. Miró: 0.2'},
{type:'pubh',text:'J. V. Grauman: 0.18'},
{type:'demography',text:'Nathan Keyfitz: 0.17'},
{type:'economics',text:'Kingsley Davis: 0.17'},
{type:'pubh',text:'Lowell J. Reed: 0.16'},
{type:'pubh',text:'T. H. Montenegro: 0.15'},
{type:'sociology',text:'Pascal K. Whelpton: 0.14'},
{type:'pubh',text:'A. Arca-Parró: 0.14'},
{type:'pubh',text:'I. B. Taeuber: 0.14'},
{type:'pubh',text:'D. Kirk: 0.13'},
{type:'pubh',text:'H. Behm: 0.13'},
{type:'pubh',text:'F. E. Linder: 0.13'},
{type:'pubh',text:'G. Rosen: 0.12'},
{type:'pubh',text:'Donald J. Bogue: 0.12'},
{type:'demography',text:'G. W. Roberts: 0.12'},
{type:'pubh',text:'Frank Lorimer: 0.11'},
{type:'pubh',text:'J. W. Morse: 0.1'},
{type:'pubh',text:'A. Robertson: 0.1'},
{type:'pubh',text:'G. Llanos: 0.1'},
{type:'pubh',text:'G. A. Silver: 0.1'},
{type:'pubh',text:'J. Amador-Guevara: 0.1'},
{type:'pubh',text:'Adolfo Gaete-Darbó: 0.09'},
{type:'pubh',text:'Charles F. Westoff: 0.08'},
{type:'demography',text:'Clyde V. Kiser: 0.08'},
{type:'pubh',text:'Giorgio Mortara: 0.07'},
{type:'demography',text:'George C. Myers: 0.07'},
{type:'pubh',text:'George W. Roberts: 0.07'},
{type:'pubh',text:'L. Van Nort: 0.07'},
{type:'pubh',text:'David Goldberg: 0.06'},
{type:'pubh',text:'Robert G. Potter: 0.06'},
{type:'pubh',text:'Reuben Hill: 0.06'},
{type:'pubh',text:'Rodolfo Stavenhagen: 0.05'},
{type:'sociology',text:'Maurice D. Van Arsdol Jr.: 0.05'},
{type:'pubh',text:'Jorge Somoza: 0.05'},
{type:'demography',text:'Beverly Duncan: 0.05'},
{type:'pubh',text:'M. Weissman: 0.05'},
{type:'pubh',text:'E. Arriaga: 0.05'},
{type:'pubh',text:'L. Baumgartner: 0.05'},
{type:'pubh',text:'Allan G. Feldt: 0.04'},
{type:'sociology',text:'Harry Sharp: 0.04'},
{type:'pubh',text:'O. Harkavy: 0.04'},
{type:'demography',text:'Calvin F. Schmid: 0.04'},
{type:'demography',text:'Carmen Miro: 0.04'},
{type:'pubh',text:'F. W. Notestein: 0.04'},
{type:'demography',text:'Elliot G. Mishler: 0.04'},
{type:'demography',text:'Doris Slesinger: 0.03'},
{type:'pubh',text:'Joseph Schachter: 0.03'},
{type:'statistics',text:'Leo F. Schnore: 0.03'},
{type:'pubh',text:'Hugo Behm: 0.03'},
{type:'geography',text:'Jack P. Gibbs: 0.03'},
{type:'sociology',text:'E. Lowell Kelly: 0.03'},
{type:'demography',text:'T. H. Sun: 0.03'},
{type:'demography',text:'John Y. Takeshita: 0.03'},
{type:'demography',text:'Morris Axelrod: 0.03'},
{type:'pubh',text:'Hector Gutierrez: 0.03'},
{type:'pubh',text:'Georges Sabagh: 0.03'},
{type:'sociology',text:'Leonard Broom: 0.03'},
{type:'sociology',text:'Kurt W. Back: 0.03'},
{type:'pubh',text:'Paul C. Glick: 0.03'},
{type:'demography',text:'J. Y. Peng: 0.03'},
{type:'sociology',text:'Philip C. Sagi: 0.03'},
{type:'sociology',text:'John R. Walker: 0.02'},
{type:'demography',text:'Bhaskar D. Misra: 0.02'},
{type:'pubh',text:'Erwin S. Solomon: 0.02'},
{type:'demography',text:'Amos H. Hawley: 0.02'},
{type:'demography',text:'D. P. Dandekar: 0.02'},
{type:'pubh',text:'Wilson H. Grabill: 0.02'},
{type:'sociology',text:'Sarah Lewit: 0.02'},
{type:'sociology',text:'Earle H. Maccannell: 0.02'},
{type:'sociology',text:'Santo F. Camilleri: 0.02'},
{type:'demography',text:'Martin Bolte: 0.02'},
{type:'economics',text:'Deborah S. Freedman: 0.02'},
{type:'sociology',text:'Virginia Harris: 0.02'},
{type:'pubh',text:'Kurt Back: 0.02'},
{type:'sociology',text:'Helen P. Beem: 0.02'},
{type:'sociology',text:'Hugh Carter: 0.02'},
{type:'pubh',text:'Jeanne E. Clare: 0.02'},
{type:'eugenics',text:'Edgar F. Borgatta: 0.02'},
{type:'sociology',text:'Warren E. Kalbach: 0.02'},
{type:'demography',text:'Gerhard Baumert: 0.02'},
{type:'sociology',text:'John W. Smit: 0.02'},
{type:'pubh',text:'Deward E. Waggoner: 0.02'},
{type:'pubh',text:'Lois Pratt: 0.01'},
{type:'eugenics',text:'Jeffrey K. Hadden: 0.01'},
{type:'demography',text:'Kiyoshi Tagashira: 0.01'},
{type:'pubh',text:'Charles Windle: 0.01'},
{type:'statistics',text:'Otis Dudley Duncan: 0.01'},
{type:'eugenics',text:'Clarence Senior: 0.01'},
{type:'eugenics',text:'Alvin M. Katz: 0.01'},
{type:'demography',text:'Doris P. Slesinger: 0.01'},
{type:'pubh',text:'John F. Kantner: 0.01'},
{type:'general',text:'Gene B. Petersen: 0.01'},
{type:'demography',text:'M. P. Parker: 0.01'},
{type:'demography',text:'H. V. Muhsam: 0.01'},
{type:'sociology',text:'Allan Feldt: 0.01'},
{type:'demography',text:'L. Braithwaite: 0.01'},
{type:'sociology',text:'Walter T. Martin: 0.01'},
{type:'demography',text:'Judith Blake: 0.01'},
{type:'pubh',text:'Benedict J. Duffy: 0.01'},
{type:'demography',text:'James A. Palmore: 0.01'},
{type:'eugenics',text:'William A. Lessa: 0.01'}
];
var comps = [
{type:'info',text:'Nodes: 8.0: Density: 0.29'},
{type:'sociology',text:'Charles B. Nam: 0.43'},
{type:'eugenics',text:'Thomas R. Ford: 0.43'},
{type:'eugenics',text:'John K. Folger: 0.43'},
{type:'pubh',text:'C. A. Mcmahan: 0.29'},
{type:'statistics',text:'Lillian Guralnick: 0.29'},
{type:'sociology',text:'Edward G. Stockwell: 0.14'},
{type:'sociology',text:'Gordon F. Dejong: 0.14'},
{type:'statistics',text:'Elizabeth J. Coulter: 0.14'},
{type:'info',text:'Nodes: 7.0: Density: 0.43'},
{type:'demography',text:'Morris H. Hansen: 0.67'},
{type:'statistics',text:'Harold Nisselson: 0.5'},
{type:'statistics',text:'William N. Hurwitz: 0.5'},
{type:'statistics',text:'Joseph Steinberg: 0.5'},
{type:'eugenics',text:'Conrad Taeuber: 0.33'},
{type:'pubh',text:'Irene B. Taeuber: 0.33'},
{type:'demography',text:'Leo A. Orleans: 0.17'},
{type:'info',text:'Nodes: 4.0: Density: 1.0'},
{type:'sociology',text:'John D. Durand: 1.0'},
{type:'pubh',text:'M. Romero G.: 1.0'},
{type:'pubh',text:'G. Mario Romero: 1.0'},
{type:'pubh',text:'R. Pacheco A.: 1.0'},
{type:'info',text:'Nodes: 4.0: Density: 0.67'},
{type:'demography',text:'C. Horace Hamilton: 1.0'},
{type:'sociology',text:'Selz C. Mayo: 0.67'},
{type:'sociology',text:'Charles W. Pettus: 0.67'},
{type:'sociology',text:'Josef Perry: 0.33'},
{type:'info',text:'Nodes: 4.0: Density: 1.0'},
{type:'economics',text:'Douglass C. North: 1.0'},
{type:'economics',text:'Paul Demeny: 1.0'},
{type:'economics',text:'Irma Adelman: 1.0'},
{type:'economics',text:'William N. Parker: 1.0'},
{type:'info',text:'Nodes: 3.0: Density: 0.67'},
{type:'statistics',text:'Ansley J. Coale: 1.0'},
{type:'statistics',text:'Frederick F. Stephan: 0.5'},
{type:'pubh',text:'C. Y. Tye: 0.5'},
{type:'info',text:'Nodes: 3.0: Density: 1.0'},
{type:'demography',text:'Bernard Berelson: 1.0'},
{type:'eugenics',text:'W. Parker Mauldin: 1.0'},
{type:'famplan',text:'James Hardy: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'pubh',text:'Everett S. Lee: 1.0'},
{type:'statistics',text:'Anne S. Lee: 1.0'},
{type:'info',text:'Nodes: 2.0: Density: 1.0'},
{type:'statistics',text:'Sidney Goldstein: 1.0'},
{type:'history',text:'Kurt Mayer: 1.0'},
{type:'info',text:'Unconnected:'},
{type:'demography',text:'Frederick Osborn'},
{type:'sociology',text:'Philip M. Hauser'},
{type:'demography',text:'Joseph J. Spengler'},
{type:'pubh',text:'Harold F. Dorn'},
{type:'demography',text:'Dorothy S. Thomas'},
{type:'general',text:'Dudley Kirk'},
{type:'general',text:'Norman B. Ryder'},
{type:'pubh',text:'George J. Stolnitz'},
{type:'sociology',text:'Reynolds Farley'},
{type:'sociology',text:'J. Richard Udry'},
{type:'sociology',text:'William Fielding Ogburn'}
];
var authors = 152;
 var density = 0.03;
 var components = 10;
-->