var cauths = [
{type:'name',url:'',color:'info',text:'Pascal K. Whelpton'},
{type:'article',url:'http://www.jstor.org/stable/3348307',color:'pubh',text:'1955 Social And Psychological Factors Affecting Fertility. Xxix. Interest In And, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2773574',color:'sociology',text:'1956 A Study Of The Growth Of American Families, AJS'},
{type:'article',url:'http://www.jstor.org/stable/3348556',color:'pubh',text:'1958 Social And Psychological Factors Affecting Fertility. Xxxiii. Summary Of Chief, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4590304',color:'pubh',text:'1958 Short Range Birth Projections, PHR'},
{type:'article',url:'http://www.jstor.org/stable/2773158',color:'sociology',text:'1960 Size Of Family And Preference For Children Of Each Sex, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2090259',color:'sociology',text:'1961 Socio-Economic Factors In Religious Differentials In Fertility, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2731988',color:'demography',text:'1963 Why Did The United States Crude Birth Rate Decline During, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/3348658',color:'pubh',text:'1964 Appraisal Of Census Data For Latin America, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2060033',color:'demography',text:'1964 Trends And Differentials In The Spacing Of Births, Demography'},
{type:'name',url:'',color:'info',text:'Edward G. Stockwell'},
{type:'article',url:'http://www.jstor.org/stable/1151722',color:'economics',text:'1960 The Measurement Of Economic Development, Econ. Dev.'},
{type:'article',url:'http://www.jstor.org/stable/4591378',color:'pubh',text:'1961 Socioeconomic Status And Mortality In The United States, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3348613',color:'pubh',text:'1962 Infant Mortality And Socio-Economic Status, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2089681',color:'sociology',text:'1962 The Relationship Between Population Growth And Economic Development, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573285',color:'sociology',text:'1963 Fertility, Mortality, And Economic Status Of Underdeveloped Areas, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2283337',color:'statistics',text:'1963 Illustrative Tables Of School Life, JASA'},
{type:'name',url:'',color:'info',text:'Leo F. Schnore'},
{type:'article',url:'http://www.jstor.org/stable/2773903',color:'sociology',text:'1957 Metropolitan Growth And Decentralization, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2088853',color:'sociology',text:'1957 The Growth Of Metropolitan Suburbs, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573846',color:'sociology',text:'1957 Satellites And Suburbs, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2088914',color:'sociology',text:'1958 Components Of Population Change In Large Metropolitan Suburbs, ASR'},
{type:'article',url:'http://www.jstor.org/stable/1031584',color:'general',text:'1958 Urban And Metropolitan Development In The United States And Canada, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2282176',color:'statistics',text:'1960 Three Sources Of Data On Commuting, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2773161',color:'sociology',text:'1960 Metropolitan Growth, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2090668',color:'sociology',text:'1961 Social Mobility In Demographic Perspective, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2774649',color:'sociology',text:'1963 Some Correlates Of Urban Size, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2573166',color:'sociology',text:'1963 Racial Changes In Metropolitan Areas, 1950-1960, Social Forces'},
{type:'name',url:'',color:'info',text:'Kingsley Davis'},
{type:'article',url:'http://www.jstor.org/stable/2772530',color:'sociology',text:'1955 The Origin And Growth Of Urbanization In The World, AJS'},
{type:'article',url:'http://www.jstor.org/stable/1910683',color:'economics',text:'1956 The Amazing Decline Of Mortality In Underdeveloped Areas, AER'},
{type:'article',url:'http://www.jstor.org/stable/1031249',color:'general',text:'1956 The Unpredicted Pattern Of Population Change, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/1151774',color:'economics',text:'1956 Social Structure And Fertility, Econ. Dev.'},
{type:'article',url:'http://www.jstor.org/stable/1031577',color:'general',text:'1958 Recent Population Trends In The New World, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3348657',color:'pubh',text:'1964 The Place Of Latin America In World Demographic History, Milbank'},
{type:'name',url:'',color:'info',text:'Irene B. Taeuber'},
{type:'article',url:'http://www.jstor.org/stable/2730846',color:'demography',text:'1955 The Population Of The Ryukyu Islands, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2731163',color:'demography',text:'1955 Cyprus, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2730685',color:'demography',text:'1955 Some Recent Research On Fertility In Africa And Asia, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2731654',color:'demography',text:'1956 A Note On The Population Statistics Of Communist China, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/3348413',color:'pubh',text:'1956 Fertility And Research On Fertility In Japan, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2731653',color:'demography',text:'1956 Population Policies In Communist China, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/1032191',color:'general',text:'1958 AsiaS Increasing Population, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2731516',color:'demography',text:'1958 Population And Modernization In Turkey, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2731270',color:'demography',text:'1959 The Population Of The Forty-Ninth State, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2172041',color:'demography',text:'1960 JapanS Demographic Transition Re-Examined, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2731735',color:'demography',text:'1960 The Bases Of A Population Problem, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/3348691',color:'pubh',text:'1960 Continuities In The Declining Fertility Of The Japanese, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1151834',color:'economics',text:'1960 Urbanization And Population Change In The Development Of Modern Japan, Econ. Dev.'},
{type:'article',url:'http://www.jstor.org/stable/2731434',color:'demography',text:'1961 Population Growth In A Chinese Microcosm, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2732198',color:'demography',text:'1963 Hong Kong, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2732171',color:'demography',text:'1964 The Great Concentration, Pop. Index'},
{type:'name',url:'',color:'info',text:'Charles F. Westoff'},
{type:'article',url:'http://www.jstor.org/stable/3348521',color:'pubh',text:'1955 Social And Psychological Factors Affecting Fertility. Xxvi. The Prediction Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172273',color:'demography',text:'1956 Development Of Plans For A Social Psychological Study Of The, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348415',color:'pubh',text:'1956 Social And Psychological Factors Affecting Fertility. Xxxi. Fear Of Childlessness, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2773242',color:'sociology',text:'1957 Preferences In Size Of Family And Eventual Fertility Twenty Years, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2088911',color:'sociology',text:'1958 Fertility Through Twenty Years Of Marriage, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2172966',color:'demography',text:'1961 Some Estimates Of The Reliability Of Survey Data On Family, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348610',color:'pubh',text:'1962 Knowledge Of The Ovulatory Cycle And Coital Frequency As Factors, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172731',color:'demography',text:'1962 Contraceptive Effectiveness As A Function Of Desired Family Size, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2173123',color:'demography',text:'1962 Improvement Of Contraception During The Course Of Marriage, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2060039',color:'demography',text:'1964 Some Selected Findings Of The Princeton Fertility Study, Demography'},
{type:'name',url:'',color:'info',text:'Ronald Freedman'},
{type:'article',url:'http://www.jstor.org/stable/3348399',color:'pubh',text:'1955  Ideals  About Family Size In The Detroit Metropolitan, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2773574',color:'sociology',text:'1956 A Study Of The Growth Of American Families, AJS'},
{type:'article',url:'http://www.jstor.org/stable/3348790',color:'pubh',text:'1959 The Stability And Reliability Of Expected Family Size Data, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172406',color:'demography',text:'1959 Expected Family Size And Family Size Values In West Germany, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2773158',color:'sociology',text:'1960 Size Of Family And Preference For Children Of Each Sex, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2173313',color:'demography',text:'1961 Fertility Differentials For The Indigenous Non-Farm Population Of The United, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2090259',color:'sociology',text:'1961 Socio-Economic Factors In Religious Differentials In Fertility, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2732199',color:'demography',text:'1963 Fertility Expectations Of The United States Population, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2172779',color:'demography',text:'1963 Fertility Trends In Taiwan, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2731873',color:'demography',text:'1964 Fertility Expectations In The United States, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/3348664',color:'pubh',text:'1964 Principles And Practices Of Teaching And Training In The Centro, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2775008',color:'sociology',text:'1964 Fertility And Family Planning In Taiwan, AJS'},
{type:'article',url:'http://www.jstor.org/stable/3348661',color:'pubh',text:'1964 Social And Demographic Research In Latin American Universities, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348659',color:'pubh',text:'1964 Appraisal Of Vital Statistics In Latin America, Milbank'},
{type:'name',url:'',color:'info',text:'Sidney Goldstein'},
{type:'article',url:'http://www.jstor.org/stable/2092737',color:'sociology',text:'1955 Migration And Occupational Mobility In Norristown, Pennsylvania, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2574264',color:'sociology',text:'1955 Changing Patterns Of Fertility In Norristown, Pennsylvania, 1920-1950, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2114440',color:'history',text:'1957 Patterns Of Business Growth And Survival In A Medium-Sized Community, JEH'},
{type:'article',url:'http://www.jstor.org/stable/2774607',color:'sociology',text:'1963 Some Economic Consequences Of Suburbanization In The Copenhagen Metropolitan Area, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2574993',color:'sociology',text:'1964 Migration And The Journey To Work, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2094640',color:'sociology',text:'1964 Population Decline And The Social And Demographic Structure Of An, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2090869',color:'sociology',text:'1964 Devolution Of An Empirical Generalization, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2282627',color:'statistics',text:'1964 The Extent Of Repeated Migration, JASA'},
{type:'name',url:'',color:'info',text:'H. Yuan Tien'},
{type:'article',url:'http://www.jstor.org/stable/41449195',color:'eugenics',text:'1958 Changing Trends In The Chinese-American Population, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/3348747',color:'pubh',text:'1959 A Demographic Aspect Of Interstate Variations In American Fertility ,, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2089862',color:'sociology',text:'1961 The Social Mobility/Fertility Hypothesis Reconsidered, ASR'},
{type:'article',url:'http://www.jstor.org/stable/349006',color:'eugenics',text:'1963 Induced Abortion And Population Control In Mainland China, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/3348736',color:'pubh',text:'1963 Birth Control In Mainland China, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2060048',color:'demography',text:'1964 The Demographic Significance Of Organized Population Transfers In Communist China, Demography'},
{type:'name',url:'',color:'info',text:'George J. Stolnitz'},
{type:'article',url:'http://www.jstor.org/stable/2281215',color:'statistics',text:'1955 Uses Of Crude Vital Rates In The Analysis Of Reproductivity, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2172340',color:'demography',text:'1955 A Century Of International Mortality Trends, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2088427',color:'sociology',text:'1956 Population Composition And Fertility Trends, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348416',color:'pubh',text:'1956 Mortality Declines And Age Distribution, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172272',color:'demography',text:'1956 A Century Of International Mortality Trends, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348504',color:'pubh',text:'1957 Vital Trends And Age Distribution, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1031587',color:'general',text:'1958 The Revolution In Death Control In Nonindustrial Countries, AAAPSS'},
{type:'name',url:'',color:'info',text:'Joseph J. Spengler'},
{type:'article',url:'http://www.jstor.org/stable/2172464',color:'demography',text:'1955 Marshall On The Population Question. I, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172341',color:'demography',text:'1955 Marshall On The Population Question. Part Ii, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/1910686',color:'economics',text:'1956 The Population Problem, AER'},
{type:'article',url:'http://www.jstor.org/stable/1031582',color:'general',text:'1958 Issues And Interests In American Immigration Policy, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/1705886',color:'general',text:'1960 Population And World Economic Development, Science'},
{type:'article',url:'http://www.jstor.org/stable/1151798',color:'economics',text:'1961 Population Change, Econ. Dev.'},
{type:'name',url:'',color:'info',text:'David Goldberg'},
{type:'article',url:'http://www.jstor.org/stable/3348399',color:'pubh',text:'1955  Ideals  About Family Size In The Detroit Metropolitan, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2171971',color:'demography',text:'1959 The Fertility Of Two-Generation Urbanites, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348790',color:'pubh',text:'1959 The Stability And Reliability Of Expected Family Size Data, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348618',color:'pubh',text:'1960 Another Look At The Indianapolis Fertility Data, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2732199',color:'demography',text:'1963 Fertility Expectations Of The United States Population, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2731873',color:'demography',text:'1964 Fertility Expectations In The United States, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2060041',color:'demography',text:'1964 Some Observations Of Changes In Metropolitan Population In The United, Demography'},
{type:'name',url:'',color:'info',text:'Monroe G. Sirken'},
{type:'article',url:'http://www.jstor.org/stable/4590176',color:'pubh',text:'1958 Expanding And Improving Vital Statistics, PHR'},
{type:'article',url:'http://www.jstor.org/stable/41448394',color:'eugenics',text:'1959 Bias In Poliomyelitis Rates Based On Exposed-To-Risk Formulas, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/3348617',color:'pubh',text:'1960 Residence Histories Of Deceased Persons, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2281997',color:'statistics',text:'1961 Residence Histories And Exposure Residences For The United States Population, JASA'},
{type:'article',url:'http://www.jstor.org/stable/3348738',color:'pubh',text:'1963 Research Uses Of Vital Records In Vital Statistics Surveys, Milbank'},
{type:'name',url:'',color:'info',text:'Otis Dudley Duncan'},
{type:'article',url:'http://www.jstor.org/stable/2772537',color:'sociology',text:'1955 Residential Distribution And Occupational Stratification, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2281471',color:'statistics',text:'1956 Research On Metropolitan Population, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2172508',color:'demography',text:'1957 The Measurement Of Population Distribution, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2731681',color:'demography',text:'1957 Report Of The Committee On The 1960 Census Population Association, Pop. Index'},
{type:'name',url:'',color:'info',text:'William Petersen'},
{type:'article',url:'http://www.jstor.org/stable/2172462',color:'demography',text:'1955 John Maynard KeynesS Theories Of Population And The Concept Of, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/346858',color:'eugenics',text:'1955 Family Subsidies In The Netherlands, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/1031583',color:'general',text:'1958 Internal Migration And Economic Development In Northern America, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2089239',color:'sociology',text:'1958 A General Typology Of Migration, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2092079',color:'sociology',text:'1960 The Demographic Transition In The Netherlands, ASR'},
{type:'name',url:'',color:'info',text:'Conrad Taeuber'},
{type:'article',url:'http://www.jstor.org/stable/1031748',color:'general',text:'1957 Population Changes To 1975, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/348461',color:'eugenics',text:'1958 Contributions Of The Census To Family Statistics And Analysis, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/2732171',color:'demography',text:'1964 The Great Concentration, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2060028',color:'demography',text:'1964 A Preliminary Evaluation Of The 1960 Censuses Of Population And, Demography'},
{type:'name',url:'',color:'info',text:'Paul C. Glick'},
{type:'article',url:'http://www.jstor.org/stable/346771',color:'eugenics',text:'1955 The Life Cycle Of The Family, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/2088321',color:'sociology',text:'1955 Some Demographic Characteristics Of Recently Married Persons, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2089243',color:'sociology',text:'1958 Marriage Patterns And Educational Level, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2731190',color:'demography',text:'1959 Plans For The 1960 Census Of Population, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/3348748',color:'pubh',text:'1959 Demographic And Social Aspects Of Childlessness, Milbank'},
{type:'name',url:'',color:'info',text:'Philip C. Sagi'},
{type:'article',url:'http://www.jstor.org/stable/2088911',color:'sociology',text:'1958 Fertility Through Twenty Years Of Marriage, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2172966',color:'demography',text:'1961 Some Estimates Of The Reliability Of Survey Data On Family, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348610',color:'pubh',text:'1962 Knowledge Of The Ovulatory Cycle And Coital Frequency As Factors, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172731',color:'demography',text:'1962 Contraceptive Effectiveness As A Function Of Desired Family Size, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2173123',color:'demography',text:'1962 Improvement Of Contraception During The Course Of Marriage, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2060039',color:'demography',text:'1964 Some Selected Findings Of The Princeton Fertility Study, Demography'},
{type:'name',url:'',color:'info',text:'James D. Tarver'},
{type:'article',url:'http://www.jstor.org/stable/3348589',color:'pubh',text:'1959 Projections Of Mortality In The United States To 1970, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2573210',color:'sociology',text:'1961 Predicting Migration, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2281814',color:'statistics',text:'1962 Evaluation Of Census Survival Rates In Estimating Intercensal State Net, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2090357',color:'sociology',text:'1963 Interstate Migration Differentials, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2574337',color:'sociology',text:'1964 Occupational Migration Differentials, Social Forces'},
{type:'name',url:'',color:'info',text:'T. Lynn Smith'},
{type:'article',url:'http://www.jstor.org/stable/2772881',color:'sociology',text:'1957 Current Population Trends In Latin America, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2172209',color:'demography',text:'1958 The Reproduction Rate In Latin America, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2574087',color:'sociology',text:'1960 A Comparative Study Of The Age Distributions Of The Populations, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/29787445',color:'eugenics',text:'1960 Rural-Urban Demographic Differences In Latin America, Genus'},
{type:'name',url:'',color:'info',text:'Charles B. Nam'},
{type:'article',url:'http://www.jstor.org/stable/2574181',color:'sociology',text:'1959 Nationality Groups And Social Stratification In America, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/3348590',color:'pubh',text:'1959 Census-Novs Study Of Death Certificates Matched To Census Records, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2283337',color:'statistics',text:'1963 Illustrative Tables Of School Life, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2060051',color:'demography',text:'1964 Educational Trends From Census Data, Demography'},
{type:'name',url:'',color:'info',text:'Ansley J. Coale'},
{type:'article',url:'http://www.jstor.org/stable/2281097',color:'statistics',text:'1955 The Population Of The United States In 1950 Classified By, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2730689',color:'demography',text:'1955 The Calculation Of Approximate Intrinsic Rates, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/3348332',color:'pubh',text:'1956 The Effects Of Changes In Mortality And Fertility On Age, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172513',color:'demography',text:'1957 A New Method For Calculating LotkaS R -- The Intrinsic, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348701',color:'pubh',text:'1961 The Significance Of Age-Patterns Of Fertility In High Fertility Populations, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2281643',color:'statistics',text:'1962 The Case Of The Indians And The Teen-Age Widows, JASA'},
{type:'name',url:'',color:'info',text:'Alfred Yankauer'},
{type:'article',url:'http://www.jstor.org/stable/2088915',color:'sociology',text:'1958 The Relation Of Indices Of Fetal And Infant Loss To, ASR'},
{type:'article',url:'http://www.jstor.org/stable/348254',color:'eugenics',text:'1958 Social Class And Child Care Practices, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/1036650',color:'general',text:'1964 Maternal And Child Health Problems, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/4592279',color:'pubh',text:'1964 Diarrheal Disease And Health Services In Latin America, PHR'},
{type:'name',url:'',color:'info',text:'Robert C. Schmitt'},
{type:'article',url:'http://www.jstor.org/stable/2089100',color:'sociology',text:'1956 Intercorrelations Of Social Problem Rates In Honolulu, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2281470',color:'statistics',text:'1956 A Method Of Estimating The Intercensal Population Of Counties, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2773492',color:'sociology',text:'1956 Illegitimate Birth Rates In An Atypical Community, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2574044',color:'sociology',text:'1956 Research Note On Components Of Change In Marital Status On, Social Forces'},
{type:'name',url:'',color:'info',text:'Philip M. Hauser'},
{type:'article',url:'http://www.jstor.org/stable/2773024',color:'sociology',text:'1959 Demography In Relation To Sociology, AJS'},
{type:'article',url:'http://www.jstor.org/stable/1152002',color:'economics',text:'1959 Demographic Indicators Of Economic Development, Econ. Dev.'},
{type:'article',url:'http://www.jstor.org/stable/1705080',color:'general',text:'1960 Demographic Dimensions Of World Politics, Science'},
{type:'article',url:'http://www.jstor.org/stable/2282951',color:'statistics',text:'1963 Statistics And Society, JASA'},
{type:'name',url:'',color:'info',text:'George C. Myers'},
{type:'article',url:'http://www.jstor.org/stable/2172727',color:'demography',text:'1962 Population Dynamics Of An Atoll Community, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2573893',color:'sociology',text:'1962 Patterns Of Church Distribution And Movement, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/3348663',color:'pubh',text:'1964 The Cornell International Population Program, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2060042',color:'demography',text:'1964 Variations In Urban Population Structure, Demography'},
{type:'article',url:'http://www.jstor.org/stable/2575534',color:'sociology',text:'1964 Metropolitan Area Mobility, Social Forces'},
{type:'name',url:'',color:'info',text:'J. Mayone Stycos'},
{type:'article',url:'http://www.jstor.org/stable/2092744',color:'sociology',text:'1955 Interviewer Effect On Scale Reproducibility, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348414',color:'pubh',text:'1956 Contraception And Catholicism In Puerto Rico, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/347203',color:'eugenics',text:'1956 The Dynamics Of Family Planning, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/3348430',color:'pubh',text:'1958 Some Directions For Research On Fertility Control, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/349002',color:'eugenics',text:'1963 Obstacles To Programs Of Population Control-Facts And Fancies, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/2172781',color:'demography',text:'1963 Culture And Differential Fertility In Peru, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348663',color:'pubh',text:'1964 The Cornell International Population Program, Milbank'},
{type:'name',url:'',color:'info',text:'Karl E. Taeuber'},
{type:'article',url:'http://www.jstor.org/stable/2281997',color:'statistics',text:'1961 Residence Histories And Exposure Residences For The United States Population, JASA'},
{type:'article',url:'http://www.jstor.org/stable/3348638',color:'pubh',text:'1961 Duration-Of-Residence Analysis Of Internal Migration In The United States, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2775107',color:'sociology',text:'1964 The Negro As An Immigrant Group, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2091422',color:'sociology',text:'1964 White Migration And Socio-Economic Differences Between Cities And Suburbs, ASR'},
{type:'name',url:'',color:'info',text:'C. Horace Hamilton'},
{type:'article',url:'http://www.jstor.org/stable/2573771',color:'sociology',text:'1958 The Sociology Of A Changing Agriculture, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2574014',color:'sociology',text:'1959 Educational Selectivity Of Net Migration From The South, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2573432',color:'sociology',text:'1961 Sources Of Variation In The Level Of Living Of Farm, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2731789',color:'demography',text:'1961 Some Problems Of Method In Internal Migration Research, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2573607',color:'sociology',text:'1962 A Short Method For Projecting Population By Age From One, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2574947',color:'sociology',text:'1963 Current Population Trends In The South, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2060054',color:'demography',text:'1964 The Negro Leaves The South, Demography'},
{type:'name',url:'',color:'info',text:'Kurt Mayer'},
{type:'article',url:'http://www.jstor.org/stable/2114440',color:'history',text:'1957 Patterns Of Business Growth And Survival In A Medium-Sized Community, JEH'},
{type:'article',url:'http://www.jstor.org/stable/2574993',color:'sociology',text:'1964 Migration And The Journey To Work, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2094640',color:'sociology',text:'1964 Population Decline And The Social And Demographic Structure Of An, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2090869',color:'sociology',text:'1964 Devolution Of An Empirical Generalization, ASR'},
{type:'name',url:'',color:'info',text:'Maurice D. Van Arsdol Jr.'},
{type:'article',url:'http://www.jstor.org/stable/2088802',color:'sociology',text:'1958 The Ecology Of The American City, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573775',color:'sociology',text:'1958 An Application Of The Shevky Social Area Indexes To A, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2089241',color:'sociology',text:'1958 The Generality Of Urban Social Area Indexes, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2775141',color:'sociology',text:'1962 Patterns Of City Growth, AJS'},
{type:'name',url:'',color:'info',text:'Theodore R. Anderson'},
{type:'article',url:'http://www.jstor.org/stable/2087387',color:'sociology',text:'1955 Intermetropolitan Migration, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2773489',color:'sociology',text:'1956 Intermetropolitan Migration, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2574289',color:'sociology',text:'1961 The Shevky-Bell Social Areas, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2090666',color:'sociology',text:'1961 Spatial Aspects Of Social Area Analysis, ASR'},
{type:'name',url:'',color:'info',text:'Lee G. Burchinal'},
{type:'article',url:'http://www.jstor.org/stable/2090035',color:'sociology',text:'1962 Religious Identification And Occupational Status Of Iowa Grooms, 1953-1957, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573892',color:'sociology',text:'1962 Ages At Marriage , Occupations Of Grooms And Interreligious Marriage, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/349343',color:'demography',text:'1964 Rural Poverty, JMF'},
{type:'name',url:'',color:'info',text:'N. B. Ryder'},
{type:'article',url:'http://www.jstor.org/stable/3348329',color:'pubh',text:'1956 Problems Of Trend Determination During A Transition In Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2774272',color:'sociology',text:'1964 Notes On The Concept Of A Population, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2060032',color:'demography',text:'1964 The Process Of Demographic Translation, Demography'},
{type:'name',url:'',color:'info',text:'Mindel C. Sheps'},
{type:'article',url:'http://www.jstor.org/stable/2172695',color:'demography',text:'1963 Effects On Family Size And Sex Ratio Of Preferences Regarding, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172633',color:'demography',text:'1964 On The Time Required For Conception, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2060036',color:'demography',text:'1964 Pregnancy Wastage As A Factor In The Analysis Of Fertility, Demography'},
{type:'article',url:'http://www.jstor.org/stable/2527616',color:'eugenics',text:'1964 Human Reproduction, Biometrics'},
{type:'article',url:'http://www.jstor.org/stable/2172590',color:'demography',text:'1964 The Distribution Of Birth Intervals Under A Class Of Stochastic, Pop. Studies'},
{type:'name',url:'',color:'info',text:'John Y. Takeshita'},
{type:'article',url:'http://www.jstor.org/stable/2172779',color:'demography',text:'1963 Fertility Trends In Taiwan, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/349007',color:'eugenics',text:'1963 Population Control In Japan, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/2775008',color:'sociology',text:'1964 Fertility And Family Planning In Taiwan, AJS'},
{type:'name',url:'',color:'info',text:'Harry Sharp'},
{type:'article',url:'http://www.jstor.org/stable/3348399',color:'pubh',text:'1955  Ideals  About Family Size In The Detroit Metropolitan, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348790',color:'pubh',text:'1959 The Stability And Reliability Of Expected Family Size Data, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2096156',color:'sociology',text:'1959 Some Factors In A Probability Sample Survey Of A Metropolitan, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573166',color:'sociology',text:'1963 Racial Changes In Metropolitan Areas, 1950-1960, Social Forces'},
{type:'name',url:'',color:'info',text:'Clyde V. Kiser'},
{type:'article',url:'http://www.jstor.org/stable/3348306',color:'pubh',text:'1955 Changes In Fertility By Socio-Economic Status During 1940-1950, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/347203',color:'eugenics',text:'1956 The Dynamics Of Family Planning, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/3348529',color:'pubh',text:'1956 Social And Psychological Factors Affecting Fertility. Xxxii. The Number Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172273',color:'demography',text:'1956 Development Of Plans For A Social Psychological Study Of The, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348556',color:'pubh',text:'1958 Social And Psychological Factors Affecting Fertility. Xxxiii. Summary Of Chief, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348431',color:'pubh',text:'1958 Fertility Trends And Differentials Among Nonwhites In The United States, Milbank'},
{type:'name',url:'',color:'info',text:'Bernard Lazerwitz'},
{type:'article',url:'http://www.jstor.org/stable/2092630',color:'sociology',text:'1960 Metropolitan Community Residential Belts, 1950 And 1956, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2282080',color:'statistics',text:'1961 A Comparison Of Major United States Religious Groups, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2774279',color:'sociology',text:'1964 The Three-Generations Hypothesis, AJS'},
{type:'name',url:'',color:'info',text:'Henry S. Shryock Jr.'},
{type:'article',url:'http://www.jstor.org/stable/2573363',color:'sociology',text:'1956 Population Redistribution Within Metropolitan Areas, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2731546',color:'demography',text:'1959 Annotated List Of Estimates Of Net Migration , 1940 To, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2060049',color:'demography',text:'1964 Accuracy Of Methods Of Preparing Postcensal Population Estimates For States, Demography'},
{type:'name',url:'',color:'info',text:'Donald J. Bogue'},
{type:'article',url:'http://www.jstor.org/stable/2772535',color:'sociology',text:'1955 Urbanism In The United States, 1950, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2732225',color:'demography',text:'1964 The Demographic Breakthrough, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2060056',color:'demography',text:'1964 Some Empirical And Analytic Relations Among Demographic Fertility Measures ,, Demography'},
{type:'article',url:'http://www.jstor.org/stable/2060057',color:'demography',text:'1964 A New Estimate Of The Negro Population And Negro Vital, Demography'},
{type:'name',url:'',color:'info',text:'Bert F. Hoselitz'},
{type:'article',url:'http://www.jstor.org/stable/1823550',color:'economics',text:'1955 The City, The Factory, And Economic Growth, AER'},
{type:'article',url:'http://www.jstor.org/stable/1151711',color:'economics',text:'1955 Generative And Parasitic Cities, Econ. Dev.'},
{type:'article',url:'http://www.jstor.org/stable/2172108',color:'demography',text:'1957 Population Pressure, Industrialization And Social Mobility, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/1151680',color:'economics',text:'1957 Urbanization And Economic Growth In Asia, Econ. Dev.'},
{type:'name',url:'',color:'info',text:'Calvin F. Schmid'},
{type:'article',url:'http://www.jstor.org/stable/2088802',color:'sociology',text:'1958 The Ecology Of The American City, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573775',color:'sociology',text:'1958 An Application Of The Shevky Social Area Indexes To A, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2089241',color:'sociology',text:'1958 The Generality Of Urban Social Area Indexes, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2060046',color:'demography',text:'1964 Ecological And Demographic Indices, Demography'},
{type:'name',url:'',color:'info',text:'Reuben Hill'},
{type:'article',url:'http://www.jstor.org/stable/2092744',color:'sociology',text:'1955 Interviewer Effect On Scale Reproducibility, ASR'},
{type:'article',url:'http://www.jstor.org/stable/346776',color:'eugenics',text:'1955 Courtship In Puerto Rico, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/3348414',color:'pubh',text:'1956 Contraception And Catholicism In Puerto Rico, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/347203',color:'eugenics',text:'1956 The Dynamics Of Family Planning, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/347079',color:'eugenics',text:'1957 Research On The Puerto Rican Family In The United States, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/347359',color:'eugenics',text:'1958 Residential Propinquity And Marital Selection, Fam. Living'},
{type:'name',url:'',color:'info',text:'G. W. Roberts'},
{type:'article',url:'http://www.jstor.org/stable/2172461',color:'demography',text:'1955 Some Aspects Of Mating And Fertility In The West Indies, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/1031591',color:'general',text:'1958 The Caribbean Islands, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2173329',color:'demography',text:'1961 A Gross Mating Table For A West Indian Population, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348657',color:'pubh',text:'1964 The Place Of Latin America In World Demographic History, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348662',color:'pubh',text:'1964 The Census Research Program For The West Indies, Milbank'},
{type:'name',url:'',color:'info',text:'Lincoln H. Day'},
{type:'article',url:'http://www.jstor.org/stable/4590173',color:'pubh',text:'1958 Age Of Women At Completion Of Childbearing, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3348716',color:'pubh',text:'1964 Fertility Differentials Among Catholics In Australia, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2091200',color:'sociology',text:'1964 Patterns Of Divorce In Australia And The United States, ASR'},
{type:'name',url:'',color:'info',text:'Robert Gutman'},
{type:'article',url:'http://www.jstor.org/stable/2172275',color:'demography',text:'1956 The Birth Statistics Of Massachusetts During The Nineteenth Century, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348502',color:'pubh',text:'1957 Some Sources Of Variation In The Family Size Of College, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348478',color:'pubh',text:'1958 Birth And Death Registration In Massachusetts, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348791',color:'pubh',text:'1959 Birth And Death Registration In Massachusetts. Iv. The System Attains, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348771',color:'pubh',text:'1959 Birth And Death Registration In Massachusetts. Iii. The System Achieves, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2092078',color:'sociology',text:'1960 In Defense Of Population Theory, ASR'},
{type:'name',url:'',color:'info',text:'Warren C. Robinson'},
{type:'article',url:'http://www.jstor.org/stable/2088951',color:'sociology',text:'1960 Rural-Urban Fertility Differentials In Mexico, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2173330',color:'demography',text:'1961 Urban-Rural Differences In Indian Fertility, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348737',color:'pubh',text:'1963 Urbanization And Fertility, Milbank'},
{type:'name',url:'',color:'info',text:'Judah Matras'},
{type:'article',url:'http://www.jstor.org/stable/2172012',color:'demography',text:'1960 Comparison Of Intergenerational Occupational Mobility Patterns, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2173315',color:'demography',text:'1961 Differential Fertility , Intergenerational Occupational Mobility , And Change In, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348649',color:'pubh',text:'1962 Contraception And Induced Abortions Among Jewish Maternity Cases In Israel, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348812',color:'pubh',text:'1962 On Rationalization Of Family Formation In Israel, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172845',color:'demography',text:'1963 Some Data On Intergenerational Occupational Mobility In Israel, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2774273',color:'sociology',text:'1964 Religious Observance And Family Formation In Israel, AJS'},
{type:'article',url:'http://www.jstor.org/stable/3348715',color:'pubh',text:'1964 Family Size Preferences Of Jewish Maternity Cases In Israel, Milbank'},
{type:'name',url:'',color:'info',text:'Jack P. Gibbs'},
{type:'article',url:'http://www.jstor.org/stable/2089240',color:'sociology',text:'1958 Urbanization And Natural Resources, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2773161',color:'sociology',text:'1960 Metropolitan Growth, AJS'},
{type:'article',url:'http://www.jstor.org/stable/142505',color:'geography',text:'1963 The Evolution Of Population Concentration, Econ. Geo.'},
{type:'article',url:'http://www.jstor.org/stable/2092128',color:'sociology',text:'1964 Social Differentiation And Status Interrelations, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2092129',color:'sociology',text:'1964 A Note On Industry Changes And Migration, ASR'},
{type:'name',url:'',color:'info',text:'Robert G. Potter Jr.'},
{type:'article',url:'http://www.jstor.org/stable/2730686',color:'demography',text:'1955 The British Family Census Of 1946, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/3348292',color:'pubh',text:'1955 Social And Psychological Factors Affecting Fertility. Xxviii. The Influence Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172143',color:'demography',text:'1956 A Critique Of The Glass-Grebenik Model For Indirectly Estimating Desired, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172273',color:'demography',text:'1956 Development Of Plans For A Social Psychological Study Of The, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348690',color:'pubh',text:'1960 Some Relationships Between Short Range And Long Range Risks Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172042',color:'demography',text:'1960 Some Comments On The Evidence Pertaining To Family Limitation In, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348639',color:'pubh',text:'1961 Length Of The Fertile Period, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172966',color:'demography',text:'1961 Some Estimates Of The Reliability Of Survey Data On Family, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348610',color:'pubh',text:'1962 Knowledge Of The Ovulatory Cycle And Coital Frequency As Factors, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172731',color:'demography',text:'1962 Contraceptive Effectiveness As A Function Of Desired Family Size, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2173123',color:'demography',text:'1962 Improvement Of Contraception During The Course Of Marriage, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172844',color:'demography',text:'1963 Birth Intervals, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348799',color:'pubh',text:'1963 Additional Measures Of Use-Effectiveness Of Contraception, Milbank'},
{type:'name',url:'',color:'info',text:'John D. Durand'},
{type:'article',url:'http://www.jstor.org/stable/2774113',color:'sociology',text:'1960 Mortality Estimates From Roman Tombstone Inscriptions, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2172247',color:'demography',text:'1960 The Population Statistics Of China, A.D. 2-1953, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348666',color:'pubh',text:'1964 The Teaching Of Statistics And Demography In Central America, Milbank'},
{type:'name',url:'',color:'info',text:'Beverly Duncan'},
{type:'article',url:'http://www.jstor.org/stable/2772537',color:'sociology',text:'1955 Residential Distribution And Occupational Stratification, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2775141',color:'sociology',text:'1962 Patterns Of City Growth, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2090868',color:'sociology',text:'1964 Devolution Of An Empirical Generalization, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2060041',color:'demography',text:'1964 Some Observations Of Changes In Metropolitan Population In The United, Demography'},
{type:'name',url:'',color:'info',text:'Lillian Guralnick'},
{type:'article',url:'http://www.jstor.org/stable/3348590',color:'pubh',text:'1959 Census-Novs Study Of Death Certificates Matched To Census Records, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2282496',color:'statistics',text:'1959 Analysis Of Vital Statistics By Census Tract, JASA'},
{type:'article',url:'http://www.jstor.org/stable/4591288',color:'pubh',text:'1961 Occupations Of Men Dying From Accidents In The United States, PHR'},
{type:'name',url:'',color:'info',text:'James G. Maddox'},
{type:'article',url:'http://www.jstor.org/stable/1034501',color:'general',text:'1960 Toward Better Use Of Human Resources In Agriculture, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/1815042',color:'economics',text:'1960 Private And Social Costs Of The Movement Of People Out, AER'},
{type:'name',url:'',color:'info',text:'Charles V. Willie'},
{type:'article',url:'http://www.jstor.org/stable/2572966',color:'sociology',text:'1959 A Research Note On The Changing Association Between Infant Mortality, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2090034',color:'sociology',text:'1962 Racial , Ethnic , And Income Factors In The Epidemiology, ASR'},
{type:'name',url:'',color:'info',text:'David M. Heer'},
{type:'article',url:'http://www.jstor.org/stable/2089680',color:'sociology',text:'1962 The Trend Of Interfaith Marriages In Canada, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2090464',color:'sociology',text:'1963 The Attractiveness Of The South To Whites And Nonwhites, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2172632',color:'demography',text:'1964 Fertility Differences Between Indian And Spanish-Speaking Parts Of Andean Countries, Pop. Studies'},
{type:'name',url:'',color:'info',text:'George L. Wilber'},
{type:'article',url:'http://www.jstor.org/stable/2283278',color:'statistics',text:'1963 Migration Expectancy In The United States, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2574995',color:'sociology',text:'1964 Growth Of Metropolitan Areas In The South, Social Forces'},
{type:'name',url:'',color:'info',text:'Stanley Lieberson'},
{type:'article',url:'http://www.jstor.org/stable/2088910',color:'sociology',text:'1958 Ethnic Groups And The Practice Of Medicine, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573470',color:'sociology',text:'1961 The Impact Of Residential Segregation On Ethnic Assimilation, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2090575',color:'sociology',text:'1961 A Societal Theory Of Race And Ethnic Relations, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2090071',color:'sociology',text:'1963 The Old-New Distinction And Immigrants In Australia, ASR'},
{type:'name',url:'',color:'info',text:'Calvin L. Beale'},
{type:'article',url:'http://www.jstor.org/stable/2575540',color:'sociology',text:'1964 Socioeconomic Differences Between White And Nonwhite Farm Populations Of The, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2060053',color:'demography',text:'1964 Rural Depopulation In The United States, Demography'},
{type:'name',url:'',color:'info',text:'E. P. Hutchinson'},
{type:'article',url:'http://www.jstor.org/stable/2281963',color:'statistics',text:'1958 Notes On Immigration Statistics Of The United States, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2172071',color:'demography',text:'1959 Swedish Population Thought In The Eighteenth Century, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Yoshio Koya'},
{type:'article',url:'http://www.jstor.org/stable/3348305',color:'pubh',text:'1955 A Survey Of Health And Demographic Aspects Of Reported Female, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348477',color:'pubh',text:'1958 Seven Years Of A Family Planning Program In Three Typical, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172408',color:'demography',text:'1959 Five-Year Experiment On Family Planning Among Coal Miners In Joban, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Everett S. Lee'},
{type:'article',url:'http://www.jstor.org/stable/2281590',color:'statistics',text:'1960 Internal Migration Statistics For The United States, JASA'},
{type:'article',url:'http://www.jstor.org/stable/3348735',color:'pubh',text:'1963 Socio-Economic And Migration Differentials In Mental Disease , New York, Milbank'},
{type:'name',url:'',color:'info',text:'Robert J. Myers'},
{type:'article',url:'http://www.jstor.org/stable/4590645',color:'pubh',text:'1959 Analysis Of Mortality And Fertility Data Of The Soviet Union, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4591445',color:'pubh',text:'1962 Further Analysis Of Soviet Data On Mortality And Fertility, PHR'},
{type:'article',url:'http://www.jstor.org/stable/2527539',color:'eugenics',text:'1963 An Instance Of The Pitfalls Prevalent In Graveyard Research, Biometrics'},
{type:'name',url:'',color:'info',text:'Christopher Tietze'},
{type:'article',url:'http://www.jstor.org/stable/2172165',color:'demography',text:'1955 Age At Marriage And Educational Attainment In The United States, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172112',color:'demography',text:'1957 Foetal Deaths , Spontaneous And Induced , In The Urban, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/1031586',color:'general',text:'1958 Human Fertility In Latin America, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2172863',color:'demography',text:'1962 Pregnancy Rates And Birth Rates, Pop. Studies'},
{type:'name',url:'',color:'info',text:'S. H. Cousens'},
{type:'article',url:'http://www.jstor.org/stable/2172043',color:'demography',text:'1960 Regional Death Rates In Ireland During The Great Famine ,, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2593008',color:'history',text:'1964 The Regional Variations In Population Changes In Ireland, 1861-1881, EHR'},
{type:'name',url:'',color:'info',text:'Joseph Schachter'},
{type:'article',url:'http://www.jstor.org/stable/3348376',color:'pubh',text:'1958 Child Spacing As Measured From The Ages Of Children In, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4590304',color:'pubh',text:'1958 Short Range Birth Projections, PHR'},
{type:'name',url:'',color:'info',text:'Scott Greer'},
{type:'article',url:'http://www.jstor.org/stable/2092936',color:'sociology',text:'1960 The Social Structure And Political Process Of Suburbia, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2574082',color:'sociology',text:'1960 Voting In A Metropolitan Community, Social Forces'},
{type:'name',url:'',color:'info',text:'A. J. Jaffe'},
{type:'article',url:'http://www.jstor.org/stable/1151922',color:'economics',text:'1960 The Birth Rate And Cottage Industries In Underdeveloped Countries, Econ. Dev.'},
{type:'article',url:'http://www.jstor.org/stable/3348648',color:'pubh',text:'1962 Notes On The Population Theory Of Eugene M. Kulischer, Milbank'},
{type:'name',url:'',color:'info',text:'S. N. Agarwala'},
{type:'article',url:'http://www.jstor.org/stable/2731762',color:'demography',text:'1957 The Age At Marriage In India, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2173311',color:'demography',text:'1961 A Family Planning Survey In Four Delhi Villages, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Peter M. Blau'},
{type:'article',url:'http://www.jstor.org/stable/2089282',color:'sociology',text:'1956 Social Mobility And Interpersonal Relations, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2172867',color:'demography',text:'1962 Inferring Mobility Trends From A Single Study, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Earl Siegel'},
{type:'article',url:'http://www.jstor.org/stable/349057',color:'eugenics',text:'1963 The Medical Problems Of The Teenage Mother, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/4591959',color:'pubh',text:'1963 The Community Impact Of Handicaps Of Prenatal Or Natal Origin, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4592263',color:'pubh',text:'1964 Health And Day Care For Children Of Migrant Workers, PHR'},
{type:'name',url:'',color:'info',text:'Basil G. Zimmer'},
{type:'article',url:'http://www.jstor.org/stable/2088329',color:'sociology',text:'1955 Participation Of Migrants In Urban Structures, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2773491',color:'sociology',text:'1956 Farm Background And Urban Participation, AJS'},
{type:'name',url:'',color:'info',text:'Amos H. Hawley'},
{type:'article',url:'http://www.jstor.org/stable/2088195',color:'sociology',text:'1955 Rural Fertility In Central Luzon, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2060041',color:'demography',text:'1964 Some Observations Of Changes In Metropolitan Population In The United, Demography'},
{type:'name',url:'',color:'info',text:'Charles M. Grigg'},
{type:'article',url:'http://www.jstor.org/stable/2089052',color:'sociology',text:'1958 Patterns Of Mobility Among A Group Of Families Of College, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573038',color:'sociology',text:'1960 Community Of Orientation And Occupational Aspirations Of Ninth Grade Students, Social Forces'},
{type:'name',url:'',color:'info',text:'D. F. Roberts'},
{type:'article',url:'http://www.jstor.org/stable/41449096',color:'eugenics',text:'1956 A Demographic Study Of A Dinka Village, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2172070',color:'demography',text:'1959 A Demographic Study In An Area Of Low Fertility In, Pop. Studies'},
{type:'name',url:'',color:'info',text:'W. Parker Mauldin'},
{type:'article',url:'http://www.jstor.org/stable/349009',color:'eugenics',text:'1963 Population And Population Policy In Pakistan, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/1965180',color:'famplan',text:'1963 Tunisia, Studies in FP'},
{type:'name',url:'',color:'info',text:'Richard A. Easterlin'},
{type:'article',url:'http://www.jstor.org/stable/1813841',color:'economics',text:'1961 The American Baby Boom In Historical Perspective, AER'},
{type:'article',url:'http://www.jstor.org/stable/1151803',color:'economics',text:'1961 Influences In European Overseas Emigration Before World War I, Econ. Dev.'},
{type:'name',url:'',color:'info',text:'Janet Abu-Lughod'},
{type:'article',url:'http://www.jstor.org/stable/347726',color:'eugenics',text:'1961 Egyptian Marriage Advertisements, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/2772954',color:'sociology',text:'1961 Migrant Adjustment To City Life, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2774274',color:'sociology',text:'1964 Urban-Rural Differences As A Function Of The Demographic Transition, AJS'},
{type:'name',url:'',color:'info',text:'Albert J. Mayer'},
{type:'article',url:'http://www.jstor.org/stable/41448141',color:'eugenics',text:'1955 Life Expectancy In The City Of Chicago 1880-1950, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2772879',color:'sociology',text:'1957 Social Change, Religion, And Birth Rates, AJS'},
{type:'name',url:'',color:'info',text:'Brian Macmahon'},
{type:'article',url:'http://www.jstor.org/stable/4589683',color:'pubh',text:'1957 Geographic Variation In Leukemia Mortality In The United States, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3348636',color:'pubh',text:'1961 Physical Damage To The Fetus, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4591780',color:'pubh',text:'1963 Relation Of Suicide Rates To Social Conditions, PHR'},
{type:'name',url:'',color:'info',text:'Lee Rainwater'},
{type:'article',url:'http://www.jstor.org/stable/347644',color:'eugenics',text:'1960 A Qualitative Exploration Of Family Planning And Contraception In The, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/349355',color:'demography',text:'1964 Marital Sexuality In Four Cultures Of Poverty, JMF'},
{type:'name',url:'',color:'info',text:'William A. Lessa'},
{type:'article',url:'http://www.jstor.org/stable/41448138',color:'eugenics',text:'1955 Depopulation On Ulithi, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2172727',color:'demography',text:'1962 Population Dynamics Of An Atoll Community, Pop. Studies'},
{type:'name',url:'',color:'info',text:'C. L. Gregory'},
{type:'article',url:'http://www.jstor.org/stable/2089342',color:'sociology',text:'1956 Occupational Selection And Intelligence In Rural Communities And Small Towns, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573747',color:'sociology',text:'1957 Occupation And Patterns Of Migration, Social Forces'},
{type:'name',url:'',color:'info',text:'Melvin Zelnik'},
{type:'article',url:'http://www.jstor.org/stable/3348729',color:'pubh',text:'1961 Age Heaping In The United States Census, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2282998',color:'statistics',text:'1964 Errors In The 1960 Census Enumeration Of Native Whites, JASA'},
{type:'name',url:'',color:'info',text:'G. E. Hutchinson'},
{type:'article',url:'http://www.jstor.org/stable/41448590',color:'eugenics',text:'1963 Sex-Ratio In Childhood And The Depopulation Of The PetÉN ,, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/71585',color:'general',text:'1963 Differential Mortality Among The Sexes In Childhood And Its Possible, PNAS'},
{type:'name',url:'',color:'info',text:'Philip E. Enterline'},
{type:'article',url:'http://www.jstor.org/stable/4590913',color:'pubh',text:'1960 Death Rates For Coronary Heart Disease In Metropolitan And Other, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4591036',color:'pubh',text:'1960 Estimated Morbidity In The United States Based On Monthly Labor, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3348603',color:'pubh',text:'1961 Causes Of Death Responsible For Recent Increases In Sex Mortality, Milbank'},
{type:'name',url:'',color:'info',text:'Octavio Cabello'},
{type:'article',url:'http://www.jstor.org/stable/2172142',color:'demography',text:'1956 The Demography Of Chile, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2281908',color:'statistics',text:'1960 The Use Of Statistics In The Formulation And Evaluation Of, JASA'},
{type:'name',url:'',color:'info',text:'T. H. Sun'},
{type:'article',url:'http://www.jstor.org/stable/2172779',color:'demography',text:'1963 Fertility Trends In Taiwan, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2775008',color:'sociology',text:'1964 Fertility And Family Planning In Taiwan, AJS'},
{type:'name',url:'',color:'info',text:'Santo F. Camilleri'},
{type:'article',url:'http://www.jstor.org/stable/2573775',color:'sociology',text:'1958 An Application Of The Shevky Social Area Indexes To A, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2089241',color:'sociology',text:'1958 The Generality Of Urban Social Area Indexes, ASR'},
{type:'name',url:'',color:'info',text:'Gerald R. Leslie'},
{type:'article',url:'http://www.jstor.org/stable/2574265',color:'sociology',text:'1955 Studies In Child Spacing, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2090574',color:'sociology',text:'1961 Life-Cycle, Career Pattern, And The Decision To Move, ASR'},
{type:'name',url:'',color:'info',text:'N. Keyfitz'},
{type:'article',url:'http://www.jstor.org/stable/3348664',color:'pubh',text:'1964 Principles And Practices Of Teaching And Training In The Centro, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348665',color:'pubh',text:'1964 Assessment Of Teaching And Training Programs In The Universities Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2060031',color:'demography',text:'1964 The Population Projection As A Matrix Operator, Demography'},
{type:'article',url:'http://www.jstor.org/stable/3348661',color:'pubh',text:'1964 Social And Demographic Research In Latin American Universities, Milbank'},
{type:'name',url:'',color:'info',text:'John F. Kantner'},
{type:'article',url:'http://www.jstor.org/stable/3348292',color:'pubh',text:'1955 Social And Psychological Factors Affecting Fertility. Xxviii. The Influence Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1965032',color:'famplan',text:'1964 Pakistan, Studies in FP'},
{type:'name',url:'',color:'info',text:'E. Lowell Kelly'},
{type:'article',url:'http://www.jstor.org/stable/2773242',color:'sociology',text:'1957 Preferences In Size Of Family And Eventual Fertility Twenty Years, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2088911',color:'sociology',text:'1958 Fertility Through Twenty Years Of Marriage, ASR'},
{type:'name',url:'',color:'info',text:'Benjamin Pasamanick'},
{type:'article',url:'http://www.jstor.org/stable/4590786',color:'pubh',text:'1960 Immigration And Insanity, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3348689',color:'pubh',text:'1960 Socio-Economic And Seasonal Variations In Birth Rates, Milbank'},
{type:'name',url:'',color:'info',text:'George A. Hillery Jr.'},
{type:'article',url:'http://www.jstor.org/stable/2088855',color:'sociology',text:'1957 The Negro In New Orleans, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573778',color:'sociology',text:'1958 Toward A Conceptualization Of Demography, Social Forces'},
{type:'name',url:'',color:'info',text:'H. V. Muhsam'},
{type:'article',url:'http://www.jstor.org/stable/3348529',color:'pubh',text:'1956 Social And Psychological Factors Affecting Fertility. Xxxii. The Number Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172271',color:'demography',text:'1956 Fertility Of Polygamous Marriages, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Francis C. Madigan'},
{type:'article',url:'http://www.jstor.org/stable/2573501',color:'sociology',text:'1957 Differential Sex Mortality, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/3348366',color:'pubh',text:'1957 Are Sex Mortality Differentials Biologically Caused?, Milbank'},
{type:'name',url:'',color:'info',text:'William A. Morrison'},
{type:'article',url:'http://www.jstor.org/stable/3348528',color:'pubh',text:'1956 Attitudes Of Males Toward Family Planning In A Western Indian, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2173331',color:'demography',text:'1961 Family Planning Attitudes Of Industrial Workers Of Ambarnath , A, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Andrew Collver'},
{type:'article',url:'http://www.jstor.org/stable/1151764',color:'economics',text:'1962 The Female Labor Force In Metropolitan Areas, Econ. Dev.'},
{type:'article',url:'http://www.jstor.org/stable/2090462',color:'sociology',text:'1963 The Family Cycle In India And The United States, ASR'},
{type:'name',url:'',color:'info',text:'William H. Nicholls'},
{type:'article',url:'http://www.jstor.org/stable/1151730',color:'economics',text:'1957 Relative Economic Development Of The Upper East Tennessee Valley ,, Econ. Dev.'},
{type:'article',url:'http://www.jstor.org/stable/1815068',color:'economics',text:'1960 Research On Agriculture And Economic Development, AER'},
{type:'name',url:'',color:'info',text:'Dennis C. Mcelrath'},
{type:'article',url:'http://www.jstor.org/stable/2089799',color:'sociology',text:'1962 The Social Areas Of Rome, ASR'},
{type:'article',url:'http://www.jstor.org/stable/1035410',color:'general',text:'1964 Urban Social Differentiation And The Allocation Of Resources, AAAPSS'},
{type:'name',url:'',color:'info',text:'Thomas R. Ford'},
{type:'article',url:'http://www.jstor.org/stable/41448128',color:'eugenics',text:'1955 Longevity Of Retired Army And Air Force Officers, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2574948',color:'sociology',text:'1963 The Decline Of Fertility In The Southern Appalachian Mountain Region, Social Forces'},
{type:'name',url:'',color:'info',text:'Deborah S. Freedman'},
{type:'article',url:'http://www.jstor.org/stable/2773158',color:'sociology',text:'1960 Size Of Family And Preference For Children Of Each Sex, AJS'},
{type:'article',url:'http://www.jstor.org/stable/1809165',color:'economics',text:'1963 The Relation Of Economic Status To Fertility, AER'},
{type:'name',url:'',color:'info',text:'Charles T. Stewart Jr.'},
{type:'article',url:'http://www.jstor.org/stable/2773684',color:'sociology',text:'1958 The Urban-Rural Dichotomy, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2092080',color:'sociology',text:'1960 Migration As A Function Of Population And Distance, ASR'},
{type:'name',url:'',color:'info',text:'William Haenszel'},
{type:'article',url:'http://www.jstor.org/stable/3348617',color:'pubh',text:'1960 Residence Histories Of Deceased Persons, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2281997',color:'statistics',text:'1961 Residence Histories And Exposure Residences For The United States Population, JASA'},
{type:'name',url:'',color:'info',text:'Alma F. Taeuber'},
{type:'article',url:'http://www.jstor.org/stable/2775107',color:'sociology',text:'1964 The Negro As An Immigrant Group, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2091422',color:'sociology',text:'1964 White Migration And Socio-Economic Differences Between Cities And Suburbs, ASR'},
{type:'name',url:'',color:'info',text:'Richard F. Tomasson'},
{type:'article',url:'http://www.jstor.org/stable/3348709',color:'pubh',text:'1960 Patterns In Negro-White Differential Mortality, 1930-1957, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2282329',color:'statistics',text:'1961 Bias In Estimates Of The U.S. Nonwhite Population As Indicated, JASA'},
{type:'name',url:'',color:'info',text:'David Yaukey'},
{type:'article',url:'http://www.jstor.org/stable/349005',color:'eugenics',text:'1963 Some Immediate Determinants Of Fertility Differences In Lebanon, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/1964925',color:'famplan',text:'1964 Pakistan, Studies in FP'},
{type:'name',url:'',color:'info',text:'Leighton Van Nort'},
{type:'article',url:'http://www.jstor.org/stable/2092558',color:'sociology',text:'1955 Demographic Transition Re-Examined, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348710',color:'pubh',text:'1960 On Values In Population Theory, Milbank'},
{type:'name',url:'',color:'info',text:'Guillermo Arbona'},
{type:'article',url:'http://www.jstor.org/stable/3348670',color:'pubh',text:'1964 The Place Of Demography In Health And Welfare Planning In, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4592048',color:'pubh',text:'1964 Public Health Progress In Puerto Rico, PHR'},
{type:'name',url:'',color:'info',text:'Edgar F. Borgatta'},
{type:'article',url:'http://www.jstor.org/stable/3348521',color:'pubh',text:'1955 Social And Psychological Factors Affecting Fertility. Xxvi. The Prediction Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/349106',color:'eugenics',text:'1962 Family Growth In Metropolitan America, Fam. Living'},
{type:'name',url:'',color:'info',text:'Edward B. Perrin'},
{type:'article',url:'http://www.jstor.org/stable/2527616',color:'eugenics',text:'1964 Human Reproduction, Biometrics'},
{type:'article',url:'http://www.jstor.org/stable/2172590',color:'demography',text:'1964 The Distribution Of Birth Intervals Under A Class Of Stochastic, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Constantine A. Yeracaris'},
{type:'article',url:'http://www.jstor.org/stable/2281216',color:'statistics',text:'1955 Differential Mortality, General And Cause-Specific In Buffalo, 1939-41, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2573936',color:'sociology',text:'1959 Differentials In The Relationship Between Values And Practices In Fertility, Social Forces'},
{type:'name',url:'',color:'info',text:'Thomas Mckeown'},
{type:'article',url:'http://www.jstor.org/stable/2172162',color:'demography',text:'1955 Medical Evidence Related To English Population Changes In The Eighteenth, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348700',color:'pubh',text:'1961 The Next Forty Years In Public Health, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2173119',color:'demography',text:'1962 Reasons For The Decline Of Mortality In England And Wales, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172587',color:'demography',text:'1964 The Next Forty Years In Public Health, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Georges Sabagh'},
{type:'article',url:'http://www.jstor.org/stable/2775141',color:'sociology',text:'1962 Patterns Of City Growth, AJS'},
{type:'article',url:'http://www.jstor.org/stable/3348801',color:'pubh',text:'1963 Social Status And Family Size Of Iranian Industrial Employees, Milbank'},
{type:'name',url:'',color:'info',text:'Thomas P. Monahan'},
{type:'article',url:'http://www.jstor.org/stable/2092745',color:'sociology',text:'1955 Is Childlessness Related To Family Stability?, ASR'},
{type:'article',url:'http://www.jstor.org/stable/347204',color:'eugenics',text:'1956 The Number Of Children In American Families And The Sharing, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/2089094',color:'sociology',text:'1956 Some Characteristics Of American Negro Leaders, ASR'},
{type:'article',url:'http://www.jstor.org/stable/348105',color:'eugenics',text:'1959 The Duration Of Marriage To Divorce, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/2089620',color:'sociology',text:'1962 When Married Couples Part, ASR'},
{type:'name',url:'',color:'info',text:'Eugene M. Kulischer'},
{type:'article',url:'http://www.jstor.org/stable/2089281',color:'sociology',text:'1956 A New Look At The Soviet Population Structure Of 1939, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348648',color:'pubh',text:'1962 Notes On The Population Theory Of Eugene M. Kulischer, Milbank'},
{type:'name',url:'',color:'info',text:'Michael K. Roof'},
{type:'article',url:'http://www.jstor.org/stable/2089281',color:'sociology',text:'1956 A New Look At The Soviet Population Structure Of 1939, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2172039',color:'demography',text:'1960 The Russian Population Enigma Reconsidered, Pop. Studies'},
{type:'name',url:'',color:'info',text:'C. Arnold Anderson'},
{type:'article',url:'http://www.jstor.org/stable/2771965',color:'sociology',text:'1955 Inequalities In Schooling In The South, AJS'},
{type:'article',url:'http://www.jstor.org/stable/29787306',color:'eugenics',text:'1956 A Footnote To The Social History Of Modern Russia , Genus'},
{type:'name',url:'',color:'info',text:'William J. Schull'},
{type:'article',url:'http://www.jstor.org/stable/71149',color:'general',text:'1962 The Effect Of Inbreeding On Mortality And Morbidity In Two, PNAS'},
{type:'article',url:'http://www.jstor.org/stable/41448577',color:'eugenics',text:'1962 Kuroshima, Human Biology'},
{type:'name',url:'',color:'info',text:'Kurt W. Back'},
{type:'article',url:'http://www.jstor.org/stable/2092744',color:'sociology',text:'1955 Interviewer Effect On Scale Reproducibility, ASR'},
{type:'article',url:'http://www.jstor.org/stable/347203',color:'eugenics',text:'1956 The Dynamics Of Family Planning, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/349003',color:'eugenics',text:'1963 A Model Of Family Planning Experiments, Fam. Living'},
{type:'name',url:'',color:'info',text:'Harold T. Christensen'},
{type:'article',url:'http://www.jstor.org/stable/2574265',color:'sociology',text:'1955 Studies In Child Spacing, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/349070',color:'eugenics',text:'1963 Child Spacing Analysis Via Record Linkage, Fam. Living'},
{type:'name',url:'',color:'info',text:'J. William Leasure'},
{type:'article',url:'http://www.jstor.org/stable/2172782',color:'demography',text:'1963 Factors Involved In The Decline Of Fertility In Spain 1900-1950, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348800',color:'pubh',text:'1963 Malthus, Marriage And Multiplication, Milbank'},
{type:'name',url:'',color:'info',text:'William F. Kenkel'},
{type:'article',url:'http://www.jstor.org/stable/347105',color:'eugenics',text:'1959 Traditional Family Ideology And Spousal Roles In Decision Making, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/2090035',color:'sociology',text:'1962 Religious Identification And Occupational Status Of Iowa Grooms, 1953-1957, ASR'},
{type:'name',url:'',color:'info',text:'Judith Blake'},
{type:'article',url:'http://www.jstor.org/stable/1151774',color:'economics',text:'1956 Social Structure And Fertility, Econ. Dev.'},
{type:'article',url:'http://www.jstor.org/stable/2060052',color:'demography',text:'1964 Issues In The Training And Recruitment Of Demographers, Demography'},
{type:'name',url:'',color:'info',text:'Ursula M. Cowgill'},
{type:'article',url:'http://www.jstor.org/stable/41448590',color:'eugenics',text:'1963 Sex-Ratio In Childhood And The Depopulation Of The PetÉN ,, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/71585',color:'general',text:'1963 Differential Mortality Among The Sexes In Childhood And Its Possible, PNAS'},
{type:'name',url:'',color:'info',text:'M. C. Balfour'},
{type:'article',url:'http://www.jstor.org/stable/2173310',color:'demography',text:'1961 Family Planning In Asia, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/1965031',color:'famplan',text:'1964 National Seminar On Population Problems Of Thailand, Studies in FP'},
{type:'name',url:'',color:'info',text:'Simon Kuznets'},
{type:'article',url:'http://www.jstor.org/stable/1811581',color:'economics',text:'1955 Economic Growth And Income Inequality, AER'},
{type:'article',url:'http://www.jstor.org/stable/1151820',color:'economics',text:'1956 Quantitative Aspects Of The Economic Growth Of Nations, Econ. Dev.'},
{type:'article',url:'http://www.jstor.org/stable/1152605',color:'economics',text:'1963 Quantitative Aspects Of The Economic Growth Of Nations, Econ. Dev.'},
{type:'name',url:'',color:'info',text:'Dudley Kirk'},
{type:'article',url:'http://www.jstor.org/stable/2731243',color:'demography',text:'1958 Economic And Demographic Developments In Western Germany, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2731350',color:'demography',text:'1960 Some Reflections On American Demography In The Nineteen Sixties, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/1033881',color:'general',text:'1961 Anticipating The Health Needs Of Americans, AAAPSS'},
{type:'name',url:'',color:'info',text:'Mortimer Spiegelman'},
{type:'article',url:'http://www.jstor.org/stable/3348535',color:'pubh',text:'1957 New Frontiers In Medical Statistics, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1031580',color:'general',text:'1958 Mortality Trends And Prospects And Their Implications, AAAPSS'},
{type:'name',url:'',color:'info',text:'John C. Bailar Iii'},
{type:'article',url:'http://www.jstor.org/stable/4591440',color:'pubh',text:'1962 Geographic Variation In Uterine Cancer Incidence In Connecticut, PHR'},
{type:'article',url:'http://www.jstor.org/stable/2528501',color:'eugenics',text:'1964 202. Note, Biometrics'},
{type:'name',url:'',color:'info',text:'Walter E. Boek'},
{type:'article',url:'http://www.jstor.org/stable/348254',color:'eugenics',text:'1958 Social Class And Child Care Practices, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/2574153',color:'sociology',text:'1960 Correlations Of Indexes Of Families Socio-Economic Status, Social Forces'},
{type:'name',url:'',color:'info',text:'Ben Z. Locke'},
{type:'article',url:'http://www.jstor.org/stable/4590786',color:'pubh',text:'1960 Immigration And Insanity, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3348756',color:'pubh',text:'1963 Marital Status, Education And Occupational Differentials In Mental Disease, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348678',color:'pubh',text:'1963 Migration Differentials In Mental Disease, Milbank'},
{type:'name',url:'',color:'info',text:'Ralph Thomlinson'},
{type:'article',url:'http://www.jstor.org/stable/2282088',color:'statistics',text:'1961 A Model For Migration Analysis, JASA'},
{type:'article',url:'http://www.jstor.org/stable/3348576',color:'pubh',text:'1962 The Determination Of A Base Population For Computing Migration Rates, Milbank'},
{type:'name',url:'',color:'info',text:'Joseph A. Cavanaugh'},
{type:'article',url:'http://www.jstor.org/stable/3348624',color:'pubh',text:'1964 The Social And Behavioral Scientist In Latin American Assistance Programs, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4592277',color:'pubh',text:'1964 Future Health Manpower Needs In Latin America, PHR'},
{type:'name',url:'',color:'info',text:'W. D. Borrie'},
{type:'article',url:'http://www.jstor.org/stable/2172099',color:'demography',text:'1957 The Population Of Tikopia, 1929 And 1952, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172065',color:'demography',text:'1959 The Growth Of The Australian Population With Particular Reference To, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2731489',color:'demography',text:'1960 Demographic Cycles And Economic Development, Pop. Index'},
{type:'name',url:'',color:'info',text:'C. A. Mcmahan'},
{type:'article',url:'http://www.jstor.org/stable/41448128',color:'eugenics',text:'1955 Longevity Of Retired Army And Air Force Officers, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/3348788',color:'pubh',text:'1959 The Lower Limit Of The Infant Mortality Rate In The, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/41448440',color:'eugenics',text:'1960 Demographic Aspects Of The Population Of Human Autopsied Cases As, Human Biology'},
{type:'name',url:'',color:'info',text:'Morris H. Hansen'},
{type:'article',url:'http://www.jstor.org/stable/2281161',color:'statistics',text:'1955 The Redesign Of The Census Current Population Survey, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2060028',color:'demography',text:'1964 A Preliminary Evaluation Of The 1960 Censuses Of Population And, Demography'},
{type:'name',url:'',color:'info',text:'Norman C. Allaway'},
{type:'article',url:'http://www.jstor.org/stable/2088915',color:'sociology',text:'1958 The Relation Of Indices Of Fetal And Infant Loss To, ASR'},
{type:'article',url:'http://www.jstor.org/stable/4590691',color:'pubh',text:'1959 Fetal And Early Neonatal Deaths In Onondaga County , New, PHR'},
{type:'name',url:'',color:'info',text:'Harry T. Oshima'},
{type:'article',url:'http://www.jstor.org/stable/2280842',color:'statistics',text:'1957 National Income Statistics Of Underdeveloped Countries, JASA'},
{type:'article',url:'http://www.jstor.org/stable/1151980',color:'economics',text:'1962 A Strategy For Asian Development, Econ. Dev.'},
{type:'name',url:'',color:'info',text:'Lee N. Robins'},
{type:'article',url:'http://www.jstor.org/stable/2090029',color:'sociology',text:'1962 The Interaction Of Social Class And Deviant Behavior, ASR'},
{type:'article',url:'http://www.jstor.org/stable/349103',color:'eugenics',text:'1962 Closeness To Blood Relatives Outside The Immediate Family, Fam. Living'},
{type:'name',url:'',color:'info',text:'Elliot G. Mishler'},
{type:'article',url:'http://www.jstor.org/stable/2172273',color:'demography',text:'1956 Development Of Plans For A Social Psychological Study Of The, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2773242',color:'sociology',text:'1957 Preferences In Size Of Family And Eventual Fertility Twenty Years, AJS'},
{type:'name',url:'',color:'info',text:'J. R. Rele'},
{type:'article',url:'http://www.jstor.org/stable/2172729',color:'demography',text:'1962 Some Aspects Of Family And Fertility In India, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348758',color:'pubh',text:'1963 Fertility Differentials In India, Milbank'},
{type:'name',url:'',color:'info',text:'Bernard Berelson'},
{type:'article',url:'http://www.jstor.org/stable/1965180',color:'famplan',text:'1963 Tunisia, Studies in FP'},
{type:'article',url:'http://www.jstor.org/stable/2060034',color:'demography',text:'1964 On Family Planning Communication, Demography'},
{type:'article',url:'http://www.jstor.org/stable/1964924',color:'famplan',text:'1964 Turkey, Studies in FP'},
{type:'article',url:'http://www.jstor.org/stable/1965309',color:'famplan',text:'1964 National Family Planning Programs, Studies in FP'},
{type:'name',url:'',color:'info',text:'Vasilios G. Valaoras'},
{type:'article',url:'http://www.jstor.org/stable/1031585',color:'general',text:'1958 Young And Aged Populations, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3348777',color:'pubh',text:'1960 A Reconstruction Of The Demographic History Of Modern Greece, Milbank'},
{type:'name',url:'',color:'info',text:'John K. Folger'},
{type:'article',url:'http://www.jstor.org/stable/41448128',color:'eugenics',text:'1955 Longevity Of Retired Army And Air Force Officers, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2060051',color:'demography',text:'1964 Educational Trends From Census Data, Demography'},
{type:'name',url:'',color:'info',text:'Walter T. Martin'},
{type:'article',url:'http://www.jstor.org/stable/2772926',color:'sociology',text:'1956 Continuing Urbanization On The Pacific Coast, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2088712',color:'sociology',text:'1956 The Structuring Of Social Relationships Engendered By Suburban Residence, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2088854',color:'sociology',text:'1957 Ecological Change In Satellite Rural Areas, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2089240',color:'sociology',text:'1958 Urbanization And Natural Resources, ASR'},
{type:'name',url:'',color:'info',text:'Evelyn M. Kitagawa'},
{type:'article',url:'http://www.jstor.org/stable/2281213',color:'statistics',text:'1955 Components Of A Difference Between Two Rates, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2060055',color:'demography',text:'1964 Standardized Comparisons In Population Research, Demography'},
{type:'name',url:'',color:'info',text:'J. N. Sinha'},
{type:'article',url:'http://www.jstor.org/stable/2172111',color:'demography',text:'1957 Differential Fertility And Family Limitation In An Urban Community Of, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/1151632',color:'economics',text:'1959 Population Growth And Balance In Economic Development, Econ. Dev.'},
{type:'name',url:'',color:'info',text:'Eugene Litwak'},
{type:'article',url:'http://www.jstor.org/stable/2773536',color:'sociology',text:'1956 Group Pressure And Family Breakup, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2088943',color:'sociology',text:'1960 Occupational Mobility And Extended Family Cohension, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2092085',color:'sociology',text:'1960 Geographic Mobility And Extended Family Cohesion, ASR'},
{type:'name',url:'',color:'info',text:'C. T. Pihlblad'},
{type:'article',url:'http://www.jstor.org/stable/2089342',color:'sociology',text:'1956 Occupational Selection And Intelligence In Rural Communities And Small Towns, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573747',color:'sociology',text:'1957 Occupation And Patterns Of Migration, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2092083',color:'sociology',text:'1960 Residential And Occupational Mobility In An Area Of Rapid Industrialization, ASR'},
{type:'name',url:'',color:'info',text:'M. A. El-Badry'},
{type:'article',url:'http://www.jstor.org/stable/3348293',color:'pubh',text:'1955 Some Demographic Measurements For Egypt Based On The Stability Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348330',color:'pubh',text:'1956 Some Aspects Of Fertility In Egypt, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2282003',color:'statistics',text:'1961 Failure Of Enumerators To Make Entries Of Zero, JASA'},
{type:'article',url:'http://www.jstor.org/stable/3348575',color:'pubh',text:'1962 An Evaluation Of The Parity Data Collected On Birth Certificates, Milbank'},
{type:'name',url:'',color:'info',text:'James V. Neel'},
{type:'article',url:'http://www.jstor.org/stable/41449171',color:'eugenics',text:'1958 The Study Of Natural Selection In Primitive And Civilized Human, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/71149',color:'general',text:'1962 The Effect Of Inbreeding On Mortality And Morbidity In Two, PNAS'}
];
 var articles = 1051;
 var journals = 24;
 var authors = 1454;
 var density = 0.38;
 var cjournals = [
{title:'AJS',field: 'sociology',centrality:0.74},
{title:'Pop. Studies',field: 'demography',centrality:0.74},
{title:'Social Forces',field: 'sociology',centrality:0.65},
{title:'ASR',field: 'sociology',centrality:0.65},
{title:'Demography',field: 'demography',centrality:0.61},
{title:'Milbank',field: 'pubh',centrality:0.61},
{title:'AAAPSS',field: 'general',centrality:0.57},
{title:'JASA',field: 'statistics',centrality:0.57},
{title:'PHR',field: 'pubh',centrality:0.52},
{title:'Fam. Living',field: 'eugenics',centrality:0.52},
{title:'Econ. Dev.',field: 'economics',centrality:0.52},
{title:'Pop. Index',field: 'demography',centrality:0.48},
{title:'Human Biology',field: 'eugenics',centrality:0.43},
{title:'Science',field: 'general',centrality:0.26},
{title:'AER',field: 'economics',centrality:0.26},
{title:'Studies in FP',field: 'famplan',centrality:0.17},
{title:'JEH',field: 'history',centrality:0.17},
{title:'Genus',field: 'eugenics',centrality:0.13},
{title:'JMF',field: 'demography',centrality:0.13},
{title:'Biometrics',field: 'eugenics',centrality:0.13},
{title:'Econ. Geo.',field: 'geography',centrality:0.09},
{title:'PNAS',field: 'general',centrality:0.04},
{title:'EHR',field: 'history',centrality:0.04},
{title:'Actuaries',field: 'statistics',centrality:0.0}
];