var cauths = [
{type:'name',url:'',color:'info',text:'Irene B. Taeuber'},
{type:'article',url:'http://www.jstor.org/stable/2280451',color:'statistics',text:'1945 The Demographic Statistics Of Southern And Eastern Asia, JASA'},
{type:'article',url:'http://www.jstor.org/stable/1025496',color:'general',text:'1945 The Demographic Heritage Of The Japanese Empire, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2730487',color:'demography',text:'1947 Population Association Meeting May 17 - 18, 1947, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2172201',color:'demography',text:'1947 The Changing Fertility Of The Japanese, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3347982',color:'pubh',text:'1947 Migration And The Population Potential Of Monsoon Asia, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1024876',color:'general',text:'1947 Some Demographic Aspects Of The Changing Role Of Women, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2730431',color:'demography',text:'1949 Literature On Future Populations, 1943-1948, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2730390',color:'demography',text:'1949 Ceylon As A Demographic Laboratory, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/1026977',color:'general',text:'1949 Postwar Emigration From Germany And Italy, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2731083',color:'demography',text:'1950 Micronesian Islands Under United States Trusteeship, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2730665',color:'demography',text:'1950 Korea And The Koreans In The Northeast Asian Region, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/3348137',color:'pubh',text:'1950 Population Increase And Manpower Utilization In Imperial Japan, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2113697',color:'history',text:'1951 Population, JEH'},
{type:'article',url:'http://www.jstor.org/stable/2087687',color:'sociology',text:'1951 Family, Migration, And Industrialization In Japan, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2730647',color:'demography',text:'1952 British Guiana, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2730956',color:'demography',text:'1952 The Expansion Of The Chinese, Pop. Index'},
{type:'name',url:'',color:'info',text:'Ronald Freedman'},
{type:'article',url:'http://www.jstor.org/stable/2086735',color:'sociology',text:'1947 Health Differentials For Rural-Urban Migration, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2086570',color:'sociology',text:'1948 Distribution Of Migrant Population In Chicago, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2280598',color:'statistics',text:'1949 Unemployment And Migration In The Depression (1930-1935), JASA'},
{type:'article',url:'http://www.jstor.org/stable/2770895',color:'sociology',text:'1949 Migration And Occupational Mobility In The Depression, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2772165',color:'sociology',text:'1950 Education And Occupation Of Migrants In The Depression, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2772105',color:'sociology',text:'1950 Incomplete Matching In Ex Post Facto Studies, AJS'},
{type:'article',url:'http://www.jstor.org/stable/3348138',color:'pubh',text:'1950 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348457',color:'pubh',text:'1951 Social And Psychological Factors Affecting Fertility. Xii. The Relationship Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2730919',color:'demography',text:'1953 The 1953 Meeting Of The Population Association, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2172562',color:'demography',text:'1954 Correlates Of Values About Ideal Family Size In The Detroit, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Clyde V. Kiser'},
{type:'article',url:'http://www.jstor.org/stable/1025501',color:'general',text:'1945 Trends, Determinants, And Control In Human Fertility, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3348257',color:'pubh',text:'1945 Social And Psychological Factors Affecting Fertility. Part Iii. The Completeness, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348190',color:'pubh',text:'1945 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348172',color:'pubh',text:'1946 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2086983',color:'sociology',text:'1947 Progress Report On The Study Of Social And Psychological Factors, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3347984',color:'pubh',text:'1947 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348022',color:'pubh',text:'1948 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348104',color:'pubh',text:'1949 Demographic Characteristics Of Women In "WhoS Who", Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348166',color:'pubh',text:'1949 Social And Psychological Factors Affecting Fertility. Ix. Fertility Planning And, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1026981',color:'general',text:'1949 Cultural Pluralism, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2730719',color:'demography',text:'1950 The 1949 Assembly Of The International Union For The Scientific, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/3348409',color:'pubh',text:'1951 Social And Psychological Factors Affecting Fertility. Xiii. Fertility In Relation, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348512',color:'pubh',text:'1951 Social And Psychological Factors Affecting Fertility. Xi. The Interrelation Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348274',color:'pubh',text:'1951 Social And Psychological Factors Affecting Fertility. Xiv. Preference For Children, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2279976',color:'statistics',text:'1952 Fertility Trends And Differentials In The United States, JASA'},
{type:'article',url:'http://www.jstor.org/stable/3348265',color:'pubh',text:'1952 Social And Psychological Factors Affecting Fertility. Xvii. The Interrelation Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172027',color:'demography',text:'1953 Resume Of The Indianapolis Study Of Social And Psychological Factors, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348447',color:'pubh',text:'1953 Exploration Of Possibilities For New Studies Of Factors Affecting Size, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348424',color:'pubh',text:'1953 Social And Psychological Factors Affecting Fertility. Xviii. The Interrelation Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348550',color:'pubh',text:'1953 Social And Psychological Factors Affecting Fertility. Xix. Fear Of Pregnancy, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348466',color:'pubh',text:'1954 Social And Psychological Factors Affecting Fertility. Xxii. The Interrelation Of, Milbank'},
{type:'name',url:'',color:'info',text:'Pascal K. Whelpton'},
{type:'article',url:'http://www.jstor.org/stable/1025501',color:'general',text:'1945 Trends, Determinants, And Control In Human Fertility, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3348257',color:'pubh',text:'1945 Social And Psychological Factors Affecting Fertility. Part Iii. The Completeness, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348190',color:'pubh',text:'1945 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348172',color:'pubh',text:'1946 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2280571',color:'statistics',text:'1946 Reproduction Rates Adjusted For Age , Parity , Fecundity ,, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2086983',color:'sociology',text:'1947 Progress Report On The Study Of Social And Psychological Factors, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3347984',color:'pubh',text:'1947 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348022',color:'pubh',text:'1948 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348166',color:'pubh',text:'1949 Social And Psychological Factors Affecting Fertility. Ix. Fertility Planning And, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2086675',color:'sociology',text:'1949 Cohort Analysis Of Fertility, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2280435',color:'statistics',text:'1950 Comments On Mr. KarmelS Note, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2086397',color:'sociology',text:'1950 The Outlook For The Control Of Human Fertility In Japan, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348138',color:'pubh',text:'1950 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348457',color:'pubh',text:'1951 Social And Psychological Factors Affecting Fertility. Xii. The Relationship Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348512',color:'pubh',text:'1951 Social And Psychological Factors Affecting Fertility. Xi. The Interrelation Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348320',color:'pubh',text:'1952 Social And Psychological Factors Affecting Fertility. Xvi. Fertility Rates And, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348492',color:'pubh',text:'1953 Social And Psychological Factors Affecting Fertility. Xx. The Use ,, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172027',color:'demography',text:'1953 Resume Of The Indianapolis Study Of Social And Psychological Factors, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Kingsley Davis'},
{type:'article',url:'http://www.jstor.org/stable/1025490',color:'general',text:'1945 The World Demographic Transition, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3348228',color:'pubh',text:'1946 Urbanization In Latin America, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348114',color:'pubh',text:'1946 Urbanization In Latin America, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2771069',color:'sociology',text:'1946 Human Fertility In India, AJS'},
{type:'article',url:'http://www.jstor.org/stable/3347983',color:'pubh',text:'1947 Future Migration Into Latin America, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348239',color:'pubh',text:'1948 Puerto RicoS Population Problem, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1026976',color:'general',text:'1949 Immigration From The Western Hemisphere, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/1026822',color:'general',text:'1950 Statistical Perspective On Marriage And Divorce, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2172175',color:'demography',text:'1951 Differential Fertility In Puerto Rico, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172389',color:'demography',text:'1951 The Pattern Of Puerto Rican Fertility, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/1029123',color:'general',text:'1953 Puerto Rico, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/1151656',color:'economics',text:'1954 Urbanization And The Development Of Pre-Industrial Areas, Econ. Dev.'},
{type:'name',url:'',color:'info',text:'Hope T. Eldridge'},
{type:'article',url:'http://www.jstor.org/stable/2571516',color:'sociology',text:'1945 Problems And Methods Of Estimating Postcensal Population, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/1025492',color:'general',text:'1945 Demographic Status Of South America, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2771067',color:'sociology',text:'1946 The Changing Sex Ratio In The United States, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2086487',color:'sociology',text:'1947 Internal Migration In Peace And War, ASR'},
{type:'article',url:'http://www.jstor.org/stable/1024876',color:'general',text:'1947 Some Demographic Aspects Of The Changing Role Of Women, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3348014',color:'pubh',text:'1947 Projection Of Urban Growth And Migration To Cities In The, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2087186',color:'sociology',text:'1950 Social Research Opportunities In The 1950 World Census Of Agriculture, ASR'},
{type:'name',url:'',color:'info',text:'Warren S. Thompson'},
{type:'article',url:'http://www.jstor.org/stable/2771387',color:'sociology',text:'1945 Population Studies, AJS'},
{type:'article',url:'http://www.jstor.org/stable/1025497',color:'general',text:'1945 Population Prospects For China And Southeastern Asia, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3348179',color:'pubh',text:'1947 The Demographic And Economic Implications Of Larger Immigration, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2087143',color:'sociology',text:'1948 Differentials In Fertility And Levels Of Living In The Rural, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2572492',color:'sociology',text:'1949 Subregional Migration As An Area Of Research, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2086856',color:'sociology',text:'1949 Migration And Distance, ASR'},
{type:'article',url:'http://www.jstor.org/stable/1026975',color:'general',text:'1949 The Demographic Revolution In The United States, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2086396',color:'sociology',text:'1950 The Need For A Population Policy In Japan, ASR'},
{type:'name',url:'',color:'info',text:'Philip M. Hauser'},
{type:'article',url:'http://www.jstor.org/stable/1025491',color:'general',text:'1945 The Changing Population Of The United States, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2085632',color:'sociology',text:'1945 Wartime Developments In Census Statistics, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348014',color:'pubh',text:'1947 Projection Of Urban Growth And Migration To Cities In The, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2770654',color:'sociology',text:'1949 The Labor Force And Gainful Workers-Concept , Measurement , And, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2088286',color:'sociology',text:'1951 The Labor Force As A Field Of Interest For The, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2731066',color:'demography',text:'1953 Research Potentialities In Burma, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2772385',color:'sociology',text:'1954 Changes In The Labor-Force Participation Of The Older Worker, AJS'},
{type:'name',url:'',color:'info',text:'Donald J. Bogue'},
{type:'article',url:'http://www.jstor.org/stable/2572492',color:'sociology',text:'1949 Subregional Migration As An Area Of Research, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2086856',color:'sociology',text:'1949 Migration And Distance, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2087184',color:'sociology',text:'1950 Economic Areas As A Tool For Research And Planning, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2280675',color:'statistics',text:'1950 A Technique For Making Extensive Population Estimates, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2772416',color:'sociology',text:'1950 Changes In Population Distribution Since 1940, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2772218',color:'sociology',text:'1952 The Quantitative Study Of Social Dynamics And Social Change, AJS'},
{type:'name',url:'',color:'info',text:'T. J. Woofter'},
{type:'article',url:'http://www.jstor.org/stable/2572301',color:'sociology',text:'1945 Southern Children And Family Security, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/41447905',color:'eugenics',text:'1946 Probabilities Of Death In Closed Population Groups Illustrated By Probabilities, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2087286',color:'sociology',text:'1947 Saving The Lives Of Good Neighbors, ASR'},
{type:'article',url:'http://www.jstor.org/stable/41447920',color:'eugenics',text:'1947 Completed Generation Reproduction Rates, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2279902',color:'statistics',text:'1949 The Relation Of The Net Reproduction Rate To Other Fertility, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2086883',color:'sociology',text:'1949 Factors Sustaining The Birth Rate, ASR'},
{type:'name',url:'',color:'info',text:'Dudley Kirk'},
{type:'article',url:'http://www.jstor.org/stable/1025494',color:'general',text:'1945 Population Trends In Postwar Europe, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3348176',color:'pubh',text:'1947 European Migrations, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1026973',color:'general',text:'1949 Demographic Trends In Europe, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2731101',color:'demography',text:'1951 United Nations Population Commission Sixth Session, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2087465',color:'sociology',text:'1954 Overseas Migration From Europe Since World War Ii, ASR'},
{type:'name',url:'',color:'info',text:'Conrad Taeuber'},
{type:'article',url:'http://www.jstor.org/stable/1025491',color:'general',text:'1945 The Changing Population Of The United States, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2085633',color:'sociology',text:'1945 Some Recent Developments In Sociological Work In The Department Of, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348112',color:'pubh',text:'1946 Wartime Population Changes In The United States, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348181',color:'pubh',text:'1947 Recent Trends Of Rural-Urban Migration In The United States, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2280187',color:'statistics',text:'1947 Some Aspects Of The Statistics Program In The Department Of, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2086818',color:'sociology',text:'1948 Some Sociological Problems In The Work Of Fao, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348223',color:'pubh',text:'1950 Utilization Of Human Resources In Agriculture, Milbank'},
{type:'name',url:'',color:'info',text:'Wilbert E. Moore'},
{type:'article',url:'http://www.jstor.org/stable/1025506',color:'general',text:'1945 Pressures And Barriers In Future Migration, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2085646',color:'sociology',text:'1945 Economic Limits Of International Resettlement, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348199',color:'pubh',text:'1946 The Migration Of Native Laborers In South Africa, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1026971',color:'general',text:'1949 AmericaS Migration Treaties During World War Ii, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2730268',color:'demography',text:'1949 Flora, Fauna, Land, And People, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2730781',color:'demography',text:'1951 Persistent Problems Of Labor Force Analysis, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2087851',color:'sociology',text:'1953 The Exportability Of The "Labor Force" Concept, ASR'},
{type:'name',url:'',color:'info',text:'Frank W. Notestein'},
{type:'article',url:'http://www.jstor.org/stable/3348188',color:'pubh',text:'1945 Population Problems Of Palestine, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2172201',color:'demography',text:'1947 The Changing Fertility Of The Japanese, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348232',color:'pubh',text:'1948 Summary Of The Demographic Background Of Problems Of Undeveloped Areas, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2730391',color:'demography',text:'1949 Notes On The Report Of The Royal Commission On Population, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2172574',color:'demography',text:'1949 The Report Of The Royal Commission On Population, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2280291',color:'statistics',text:'1950 The Population Of The World In The Year 2000, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2730608',color:'demography',text:'1950 Demographic Work Of The United Nations, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2280292',color:'statistics',text:'1950 Population And Resources, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2730939',color:'demography',text:'1951 Policy Of The Indian Government On Family Limitation, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2731020',color:'demography',text:'1954 World Population Conference Rome, August 31 - September 10, Pop. Index'},
{type:'name',url:'',color:'info',text:'Henry S. Shryock Jr.'},
{type:'article',url:'http://www.jstor.org/stable/2086487',color:'sociology',text:'1947 Internal Migration In Peace And War, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2280594',color:'statistics',text:'1949 The Current Status Of State And Local Population Estimates In, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2087185',color:'sociology',text:'1950 Opportunities For Social Research In The 1950 U.S. Census Of, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2172503',color:'demography',text:'1950 Forecasts Of Population In The United States, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2730718',color:'demography',text:'1950 Plans For The 1950 Census, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2280393',color:'statistics',text:'1951 Redistribution Of Population, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2087464',color:'sociology',text:'1954 Accuracy Of Postcensal Estimates Of Population For States And Cities, ASR'},
{type:'name',url:'',color:'info',text:'John D. Durand'},
{type:'article',url:'http://www.jstor.org/stable/1025504',color:'general',text:'1945 The Trend Toward An Older Population, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/1025279',color:'general',text:'1945 Veterans And War Workers In The Postwar Labor Force, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2771066',color:'sociology',text:'1946 Married Women In The Labor Force, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2172134',color:'demography',text:'1950 Adequacy Of Existing Census Statistics For Basic Demographic Research, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Thomas P. Monahan'},
{type:'article',url:'http://www.jstor.org/stable/41447986',color:'eugenics',text:'1950 Marriage Fertility By Ages Of Couples, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2772471',color:'sociology',text:'1951 One Hundred Years Of Marriages In Massachusetts, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2771838',color:'sociology',text:'1952 How Stable Are Remarriages?, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2572864',color:'sociology',text:'1953 Does Age At Marriage Matter In Divorce?, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2772247',color:'sociology',text:'1954 Divorce And Desertion By Religious And Mixed-Religious Groups, AJS'},
{type:'name',url:'',color:'info',text:'Nathan Keyfitz'},
{type:'article',url:'http://www.jstor.org/stable/1025976',color:'general',text:'1947 Ethnic Groups And Their Behavior, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2172240',color:'demography',text:'1950 The Growth Of Canadian Population, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2772508',color:'sociology',text:'1953 A Factorial Arrangement Of Comparisons Of Family Size, AJS'},
{type:'name',url:'',color:'info',text:'Christopher Tietze'},
{type:'article',url:'http://www.jstor.org/stable/2770625',color:'sociology',text:'1947 Human Fertility In Puerto Rico, AJS'},
{type:'article',url:'http://www.jstor.org/stable/41447948',color:'eugenics',text:'1949 Report On A Series Of Illegal Abortions Induced By Physicians, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2087441',color:'sociology',text:'1953 Patterns Of Family Limitation In A Rural Negro Community, ASR'},
{type:'name',url:'',color:'info',text:'A. J. Jaffe'},
{type:'article',url:'http://www.jstor.org/stable/2965629',color:'statistics',text:'1945 Internal Migration And Full Employment In The U. S., JASA'},
{type:'article',url:'http://www.jstor.org/stable/2087333',color:'sociology',text:'1946 Demographic Factors In Labor Force Growth, ASR'},
{type:'article',url:'http://www.jstor.org/stable/41449039',color:'eugenics',text:'1947 Notes On The Rate Of Growth Of The Chinese Population, Human Biology'},
{type:'name',url:'',color:'info',text:'Halbert L. Dunn'},
{type:'article',url:'http://www.jstor.org/stable/1025492',color:'general',text:'1945 Demographic Status Of South America, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2280783',color:'statistics',text:'1952 Evolving Mechanisms For The Production Of International Health Statistics, JASA'},
{type:'article',url:'http://www.jstor.org/stable/4588552',color:'pubh',text:'1953 Elements Of A Coordinated System Of Vital Records And Statistics, PHR'},
{type:'name',url:'',color:'info',text:'Otis Dudley Duncan'},
{type:'article',url:'http://www.jstor.org/stable/2572015',color:'sociology',text:'1950 Fertility Of The Village Population In Pennsylvania, 1940, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2087995',color:'sociology',text:'1952 Is The Intelligence Of The General Population Declining?, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2730741',color:'demography',text:'1952 Annual Meeting Of The Population Association, Pop. Index'},
{type:'name',url:'',color:'info',text:'William M. Kephart'},
{type:'article',url:'http://www.jstor.org/stable/347765',color:'eugenics',text:'1954 Marriage And Family Patterns Of An Academic Group, Fam. Living'},
{type:'article',url:'http://www.jstor.org/stable/2772247',color:'sociology',text:'1954 Divorce And Desertion By Religious And Mixed-Religious Groups, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2087759',color:'sociology',text:'1954 The Duration Of Marriage, ASR'},
{type:'name',url:'',color:'info',text:'W. Parker Mauldin'},
{type:'article',url:'http://www.jstor.org/stable/2280297',color:'statistics',text:'1950 Response Errors In Census Research, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2086919',color:'sociology',text:'1950 Problems Of Response In Enumerative Surveys, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2731100',color:'demography',text:'1951 Annual Meeting Of The Population Association, Pop. Index'},
{type:'name',url:'',color:'info',text:'Jacob S. Siegel'},
{type:'article',url:'http://www.jstor.org/stable/2771067',color:'sociology',text:'1946 The Changing Sex Ratio In The United States, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2281317',color:'statistics',text:'1952 Some Considerations In The Use Of The Residual Method Of, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2281320',color:'statistics',text:'1952 Population Projections For Sales Forecasting, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2087464',color:'sociology',text:'1954 Accuracy Of Postcensal Estimates Of Population For States And Cities, ASR'},
{type:'name',url:'',color:'info',text:'Seymour L. Wolfbein'},
{type:'article',url:'http://www.jstor.org/stable/1025278',color:'general',text:'1945 Postwar Migration Plans Of Army Enlisted Men, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2965629',color:'statistics',text:'1945 Internal Migration And Full Employment In The U. S., JASA'},
{type:'article',url:'http://www.jstor.org/stable/2172578',color:'demography',text:'1949 The Length Of Working Life, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Paul C. Glick'},
{type:'article',url:'http://www.jstor.org/stable/2086982',color:'sociology',text:'1947 The Family Cycle, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2770788',color:'sociology',text:'1949 Family Life And Full Employment, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2086674',color:'sociology',text:'1949 First Marriages And Remarriages, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2087311',color:'sociology',text:'1950 Age As A Factor In Marriage, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2731120',color:'demography',text:'1951 The 1950 Census Of Population, Pop. Index'},
{type:'name',url:'',color:'info',text:'John Hajnal'},
{type:'article',url:'http://www.jstor.org/stable/2730761',color:'demography',text:'1953 The Marriage Boom, Pop. Index'},
{type:'article',url:'http://www.jstor.org/stable/2172028',color:'demography',text:'1953 Age At Marriage And Proportions Marrying, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2088396',color:'sociology',text:'1954 Differential Changes In Marriage Patterns, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2087760',color:'sociology',text:'1954 Analysis Of Changes In The Marriage Pattern By Economic Groups, ASR'},
{type:'name',url:'',color:'info',text:'Ralph H. Turner'},
{type:'article',url:'http://www.jstor.org/stable/2770892',color:'sociology',text:'1949 The Expected-Cases Method Applied To The Nonwhite Male Labor Force, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2772804',color:'sociology',text:'1951 The Nonwhite Female In The Labor Force, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2088285',color:'sociology',text:'1951 The Relative Position Of The Negro Male In The Labor, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2572857',color:'sociology',text:'1953 Negro Job Status And Education, Social Forces'},
{type:'name',url:'',color:'info',text:'Harold T. Christensen'},
{type:'article',url:'http://www.jstor.org/stable/2771219',color:'sociology',text:'1948 Mormon Fertility, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2088076',color:'sociology',text:'1952 Family Size As A Factor In The Marital Adjustments Of, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573070',color:'sociology',text:'1953 Studies In Child Spacing, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2088118',color:'sociology',text:'1953 Studies In Child Spacing, ASR'},
{type:'name',url:'',color:'info',text:'Daniel O. Price'},
{type:'article',url:'http://www.jstor.org/stable/2086489',color:'sociology',text:'1947 A Check On Underenumeration In The 1940 Census, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2770545',color:'sociology',text:'1948 Nonwhite Migrants To And From Selected Cities, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2572459',color:'sociology',text:'1948 Distance And Direction As Vectors Of Internal Migration , 1935, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2572719',color:'sociology',text:'1951 Some Socio-Economic Factors In Internal Migration, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2087846',color:'sociology',text:'1953 Estimates Of Net Migration In The United States, 1870-1940, ASR'},
{type:'name',url:'',color:'info',text:'Harold F. Dorn'},
{type:'article',url:'http://www.jstor.org/stable/3348042',color:'pubh',text:'1947 Genetic And Social Significance Of Differential Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2280290',color:'statistics',text:'1950 Pitfalls In Population Forecasts And Projections, JASA'},
{type:'article',url:'http://www.jstor.org/stable/41448030',color:'eugenics',text:'1952 Prospects Of Further Decline In Mortality Rates, Human Biology'},
{type:'name',url:'',color:'info',text:'Jacob Yerushalmy'},
{type:'article',url:'http://www.jstor.org/stable/1025503',color:'general',text:'1945 Infant And Maternal Mortality In The Modern World, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/4585618',color:'pubh',text:'1946 Tuberculosis Mortality In The United States And In Each State, PHR'},
{type:'name',url:'',color:'info',text:'Ruth R. Puffer'},
{type:'article',url:'http://www.jstor.org/stable/3348154',color:'pubh',text:'1948 Industrial And Occupational Environment And Health, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4588186',color:'pubh',text:'1952 Application Of Statistical Analysis In A Health Program, PHR'},
{type:'name',url:'',color:'info',text:'Iwao M. Moriyama'},
{type:'article',url:'http://www.jstor.org/stable/2279921',color:'statistics',text:'1951 Recent Mortality Trends And Differentials, JASA'},
{type:'article',url:'http://www.jstor.org/stable/4588219',color:'pubh',text:'1952 Needed Improvements In Mortality Data, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4588932',color:'pubh',text:'1954 Recent Mortality Trends In Areas Of Low Mortality, PHR'},
{type:'name',url:'',color:'info',text:'Paul H. Landis'},
{type:'article',url:'http://www.jstor.org/stable/2086704',color:'sociology',text:'1946 Rural-Urban Migration And The Marriage Rate--An Hypothesis, ASR'},
{type:'article',url:'http://www.jstor.org/stable/348545',color:'eugenics',text:'1954 The Marriage And Family Studytour, Fam. Living'},
{type:'name',url:'',color:'info',text:'Harvey S. Perloff'},
{type:'article',url:'http://www.jstor.org/stable/2112904',color:'history',text:'1952 The United States And The Economic Development Of Puerto Rico, JEH'},
{type:'article',url:'http://www.jstor.org/stable/1029113',color:'general',text:'1953 Transforming The Economy, AAAPSS'},
{type:'name',url:'',color:'info',text:'W. P. D. Logan'},
{type:'article',url:'http://www.jstor.org/stable/2172133',color:'demography',text:'1950 Mortality In England And Wales From 1848 To 1947, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/4588994',color:'pubh',text:'1954 Social Class Variations In Mortality, PHR'},
{type:'name',url:'',color:'info',text:'Sam Shapiro'},
{type:'article',url:'http://www.jstor.org/stable/4588130',color:'pubh',text:'1952 Birth Registration Completeness United States, 1950, PHR'},
{type:'article',url:'http://www.jstor.org/stable/2172560',color:'demography',text:'1954 Recent Testing Of Birth Registration Completeness In The United States, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Lillian Guralnick'},
{type:'article',url:'http://www.jstor.org/stable/3348144',color:'pubh',text:'1950 Family Studies In The Eastern Health District. V. Job Stability, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4587301',color:'pubh',text:'1950 Tuberculosis Mortality In The United States, 1948, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4588878',color:'pubh',text:'1954 Population Losses Through Death, 1941-51, PHR'},
{type:'name',url:'',color:'info',text:'C. Horace Hamilton'},
{type:'article',url:'http://www.jstor.org/stable/2571634',color:'sociology',text:'1951 Population Pressure And Other Factors Affecting Net Rural-Urban Migration, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2281317',color:'statistics',text:'1952 Some Considerations In The Use Of The Residual Method Of, JASA'},
{type:'name',url:'',color:'info',text:'Joseph J. Spengler'},
{type:'article',url:'http://www.jstor.org/stable/2113696',color:'history',text:'1951 Population, JEH'},
{type:'article',url:'http://www.jstor.org/stable/1910809',color:'economics',text:'1951 The Population Obstacle To Economic Betterment, AER'},
{type:'name',url:'',color:'info',text:'M. F. Nimkoff'},
{type:'article',url:'http://www.jstor.org/stable/2772739',color:'sociology',text:'1951 Technology, Biology, And The Changing Family, AJS'},
{type:'article',url:'http://www.jstor.org/stable/348545',color:'eugenics',text:'1954 The Marriage And Family Studytour, Fam. Living'},
{type:'name',url:'',color:'info',text:'Theodore Caplow'},
{type:'article',url:'http://www.jstor.org/stable/2572495',color:'sociology',text:'1949 Incidence And Direction Of Residential Mobility In A Minneapolis Sample, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2088220',color:'sociology',text:'1952 Urban Structure In France, ASR'},
{type:'name',url:'',color:'info',text:'P. H. Karmel'},
{type:'article',url:'http://www.jstor.org/stable/2172302',color:'demography',text:'1947 The Relations Between Male And Female Reproduction Rates, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172129',color:'demography',text:'1948 A Rejoinder To Mr HajnalS Comments, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172331',color:'demography',text:'1948 The Relations Between Male And Female Nuptiality In A Stable, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2171994',color:'demography',text:'1948 An Analysis Of The Sources And Magnitudes Of Inconsistencies Between, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2280434',color:'statistics',text:'1950 A Note On P. K. WhelptonS Calculation Of Parity Adjusted, JASA'},
{type:'name',url:'',color:'info',text:'Robert J. Myers'},
{type:'article',url:'http://www.jstor.org/stable/2280237',color:'statistics',text:'1949 Beneficiary Statistics Under The Old-Age And Survivors Insurance Program And, JASA'},
{type:'article',url:'http://www.jstor.org/stable/1680332',color:'general',text:'1952 Vitality Of The Aged, Science'},
{type:'article',url:'http://www.jstor.org/stable/2281126',color:'statistics',text:'1954 Factors In Interpreting Mortality After Retirement, JASA'},
{type:'name',url:'',color:'info',text:'Ta Chen'},
{type:'article',url:'http://www.jstor.org/stable/2771184',color:'sociology',text:'1947 Migration, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2771181',color:'sociology',text:'1947 Sex , Age , Size Of Family , And Density, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2771182',color:'sociology',text:'1947 Births, Deaths, And Marriages, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2771180',color:'sociology',text:'1947 The Beginnings Of Modern Demography, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2771179',color:'sociology',text:'1947 An Appraisal Of ChinaS Historical Population Data, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2771185',color:'sociology',text:'1947 Population Policy, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2771186',color:'sociology',text:'1947 Appendix, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2172330',color:'demography',text:'1948 The Need Of Population Research In China, Pop. Studies'},
{type:'name',url:'',color:'info',text:'Robert C. Schmitt'},
{type:'article',url:'http://www.jstor.org/stable/2571595',color:'sociology',text:'1952 Demography And City Planning, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2280747',color:'statistics',text:'1952 Short-Cut Methods Of Estimating County Population, JASA'},
{type:'name',url:'',color:'info',text:'Daniel G. Horvitz'},
{type:'article',url:'http://www.jstor.org/stable/4588276',color:'pubh',text:'1952 Sampling And Field Procedures Of The Pittsburgh Morbidity Survey, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3348491',color:'pubh',text:'1953 On The Association Between Health And Social Problems In The, Milbank'},
{type:'name',url:'',color:'info',text:'Amos H. Hawley'},
{type:'article',url:'http://www.jstor.org/stable/2280598',color:'statistics',text:'1949 Unemployment And Migration In The Depression (1930-1935), JASA'},
{type:'article',url:'http://www.jstor.org/stable/2770895',color:'sociology',text:'1949 Migration And Occupational Mobility In The Depression, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2772165',color:'sociology',text:'1950 Education And Occupation Of Migrants In The Depression, AJS'},
{type:'name',url:'',color:'info',text:'Sidney Goldstein'},
{type:'article',url:'http://www.jstor.org/stable/2771902',color:'sociology',text:'1954 City Directories As Sources Of Migration Data, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2087791',color:'sociology',text:'1954 Repeated Migration As A Factor In High Mobility Rates, ASR'},
{type:'name',url:'',color:'info',text:'Vincent Heath Whitney'},
{type:'article',url:'http://www.jstor.org/stable/2770598',color:'sociology',text:'1948 Rural-Urban People, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2730741',color:'demography',text:'1952 Annual Meeting Of The Population Association, Pop. Index'},
{type:'name',url:'',color:'info',text:'Ernest Jurkat'},
{type:'article',url:'http://www.jstor.org/stable/3348188',color:'pubh',text:'1945 Population Problems Of Palestine, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1025499',color:'general',text:'1945 The Peoples Of The Mohammedan World, AAAPSS'},
{type:'name',url:'',color:'info',text:'Paul H. Jacobson'},
{type:'article',url:'http://www.jstor.org/stable/3348220',color:'pubh',text:'1950 Marital Dissolutions In New York State In Relation To Their, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2086788',color:'sociology',text:'1950 Differentials In Divorce By Duration Of Marriage And Size Of, ASR'},
{type:'name',url:'',color:'info',text:'J. R. H. Shaul'},
{type:'article',url:'http://www.jstor.org/stable/2172127',color:'demography',text:'1948 A Sample Survey Of The African Population Of Southern Rhodesia, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172577',color:'demography',text:'1949 Provisional Results Of The Sample Survey Of The African Population, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2172393',color:'demography',text:'1951 Vital Statistics Of The African Population Of Southern Rhodesia In, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2280748',color:'statistics',text:'1952 Sampling Surveys In Central Africa, JASA'},
{type:'name',url:'',color:'info',text:'Charles F. Westoff'},
{type:'article',url:'http://www.jstor.org/stable/3348265',color:'pubh',text:'1952 Social And Psychological Factors Affecting Fertility. Xvii. The Interrelation Of, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348492',color:'pubh',text:'1953 Social And Psychological Factors Affecting Fertility. Xx. The Use ,, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348422',color:'pubh',text:'1953 The Changing Focus Of Differential Fertility Research, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2087793',color:'sociology',text:'1954 Differential Fertility In The United States, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348437',color:'pubh',text:'1954 Social And Psychological Factors Affecting Fertility. Xxv. The Prediction Of, Milbank'},
{type:'name',url:'',color:'info',text:'John Folger'},
{type:'article',url:'http://www.jstor.org/stable/2087879',color:'sociology',text:'1953 Some Aspects Of Migration In The Tennessee Valley, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2573717',color:'sociology',text:'1953 Migration And Marital Status In Ten Southeastern Cities, Social Forces'},
{type:'name',url:'',color:'info',text:'C. Chandra Sekar'},
{type:'article',url:'http://www.jstor.org/stable/41447932',color:'eugenics',text:'1948 Some Aspects Of Parsi Demography, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447946',color:'eugenics',text:'1949 The Effect Of The Change In Mortality Conditions In An, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2280353',color:'statistics',text:'1949 On A Method Of Estimating Birth And Death Rates And, JASA'},
{type:'name',url:'',color:'info',text:'Eli S. Marks'},
{type:'article',url:'http://www.jstor.org/stable/2280297',color:'statistics',text:'1950 Response Errors In Census Research, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2086919',color:'sociology',text:'1950 Problems Of Response In Enumerative Surveys, ASR'},
{type:'name',url:'',color:'info',text:'Margaret Merrell'},
{type:'article',url:'http://www.jstor.org/stable/3001948',color:'eugenics',text:'1947 Time-Specific Life Tables Contrasted With Observed Survivorship, Biometrics'},
{type:'article',url:'http://www.jstor.org/stable/41448011',color:'eugenics',text:'1952 The Family As A Unit In Public Health Research, Human Biology'},
{type:'name',url:'',color:'info',text:'Joseph W. Eaton'},
{type:'article',url:'http://www.jstor.org/stable/2088079',color:'sociology',text:'1952 Controlled Acculturation, ASR'},
{type:'article',url:'http://www.jstor.org/stable/41449079',color:'eugenics',text:'1953 The Social Biology Of Very High Fertility Among The Hutterites, Human Biology'},
{type:'name',url:'',color:'info',text:'E. J. Buckatzsch'},
{type:'article',url:'http://www.jstor.org/stable/2172301',color:'demography',text:'1947 The Influence Of Social Conditions On Mortality Rates, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2589829',color:'history',text:'1949 Occupations In The Parish Registers Of Sheffield, 1655-1719, EHR'},
{type:'article',url:'http://www.jstor.org/stable/2590126',color:'history',text:'1950 Places Of Origin Of A Group Of Immigrants Into Sheffield, EHR'},
{type:'article',url:'http://www.jstor.org/stable/2172234',color:'demography',text:'1951 The Constancy Of Local Populations And Migration In England Before, Pop. Studies'},
{type:'name',url:'',color:'info',text:'S. Chandrasekhar'},
{type:'article',url:'http://www.jstor.org/stable/2572530',color:'sociology',text:'1945 The Emigration And Status Of Indians In The British Empire, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/348439',color:'eugenics',text:'1954 The Family In India, Fam. Living'},
{type:'name',url:'',color:'info',text:'Milton L. Barron'},
{type:'article',url:'http://www.jstor.org/stable/2085270',color:'sociology',text:'1946 The Incidence Of Jewish Intermarriage In Europe And America, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2572175',color:'sociology',text:'1949 Intermediacy, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2088005',color:'sociology',text:'1952 Research On The Social Disorganization Of Retirement, ASR'},
{type:'name',url:'',color:'info',text:'Frank Lorimer'},
{type:'article',url:'http://www.jstor.org/stable/1025509',color:'general',text:'1945 Issues Of Population Policy, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2086731',color:'sociology',text:'1947 The Differentiation Of Logical Levels In Social Inquiry, ASR'},
{type:'article',url:'http://www.jstor.org/stable/1026974',color:'general',text:'1949 European Governmental Action Regarding Population, AAAPSS'},
{type:'name',url:'',color:'info',text:'Margaret J. Hagood'},
{type:'article',url:'http://www.jstor.org/stable/2087263',color:'sociology',text:'1946 Some Measurement And Research Problems Arising From Sociological Aspects Of, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2281320',color:'statistics',text:'1952 Population Projections For Sales Forecasting, JASA'},
{type:'name',url:'',color:'info',text:'John H. Burma'},
{type:'article',url:'http://www.jstor.org/stable/2771506',color:'sociology',text:'1946 The Measurement Of Negro "Passing", AJS'},
{type:'article',url:'http://www.jstor.org/stable/2571739',color:'sociology',text:'1951 The Background Of The Current Situation Of Filipino-Americans, Social Forces'},
{type:'name',url:'',color:'info',text:'Alfred Sauvy'},
{type:'article',url:'http://www.jstor.org/stable/2172372',color:'demography',text:'1948 Social And Economic Consequences Of The Ageing Of Western European, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/1026970',color:'general',text:'1949 European Migrations, AAAPSS'},
{type:'name',url:'',color:'info',text:'Enid Charles'},
{type:'article',url:'http://www.jstor.org/stable/1025498',color:'general',text:'1945 Population Problems In The British Overseas Dominions, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2087266',color:'sociology',text:'1946 Post-War Demographic Problems In Britain, ASR'},
{type:'name',url:'',color:'info',text:'Marcus S. Goldstein'},
{type:'article',url:'http://www.jstor.org/stable/4587719',color:'pubh',text:'1951 Physical Status Of Men Examined Through Selective Service In World, PHR'},
{type:'article',url:'http://www.jstor.org/stable/41449065',color:'eugenics',text:'1953 Some Vital Statistics Based On Skeletal Material, Human Biology'},
{type:'name',url:'',color:'info',text:'Lewis M. Killian'},
{type:'article',url:'http://www.jstor.org/stable/2088078',color:'sociology',text:'1952 The Effects Of Southern White Workers On Race Relations In, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2572861',color:'sociology',text:'1953 The Adjustment Of Southern White Migrants To Northern Urban Norms, Social Forces'},
{type:'name',url:'',color:'info',text:'Jerzy Berent'},
{type:'article',url:'http://www.jstor.org/stable/2172429',color:'demography',text:'1952 Fertility And Social Mobility, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/3348423',color:'pubh',text:'1953 Relationship Between Family Sizes Of Two Successive Generations, Milbank'},
{type:'name',url:'',color:'info',text:'T. Lynn Smith'},
{type:'article',url:'http://www.jstor.org/stable/2572303',color:'sociology',text:'1945 A Demographic Study Of The American Negro, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2085589',color:'sociology',text:'1945 The Recent Increase Of Persons In The Social Security Ages, ASR'},
{type:'name',url:'',color:'info',text:'Chia-Lin Pan'},
{type:'article',url:'http://www.jstor.org/stable/2172494',color:'demography',text:'1949 The Population Of Libya, Pop. Studies'},
{type:'article',url:'http://www.jstor.org/stable/2730956',color:'demography',text:'1952 The Expansion Of The Chinese, Pop. Index'},
{type:'name',url:'',color:'info',text:'Evelyn M. Kitagawa'},
{type:'article',url:'http://www.jstor.org/stable/2572862',color:'sociology',text:'1953 Demographic Characteristics And Job Mobility Of Migrants In Six Cities, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2772509',color:'sociology',text:'1953 Differential Fertility In Chicago, 1920-40, AJS'},
{type:'name',url:'',color:'info',text:'A. Ross Eckler'},
{type:'article',url:'http://www.jstor.org/stable/2280124',color:'statistics',text:'1945 The Revised Census Series Of Current Employment Estimates, JASA'},
{type:'article',url:'http://www.jstor.org/stable/1026978',color:'general',text:'1949 Immigration And The Labor Force, AAAPSS'},
{type:'name',url:'',color:'info',text:'Selwyn D. Collins'},
{type:'article',url:'http://www.jstor.org/stable/4585326',color:'pubh',text:'1945 Influenza And Pneumonia Excess Mortality At Specific Ages In The, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4585317',color:'pubh',text:'1945 Influenza And Pneumonia Excess Mortality At Specific Ages In The, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4585562',color:'pubh',text:'1946 Diphtheria Incidence And Trends In Relation To Artificial Immunization ,, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4585588',color:'pubh',text:'1946 The Incidence Of Poliomyelitis And Its Crippling Effects , As, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4586552',color:'pubh',text:'1948 Illness Among Infants, With Comparative Mortality Data, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3348069',color:'pubh',text:'1949 Characteristics Of Stable And Non-Stable Families In The Morbidity Study, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4587153',color:'pubh',text:'1949 Statistical Studies Of Heart Disease, PHR'},
{type:'name',url:'',color:'info',text:'J. Mayone Stycos'},
{type:'article',url:'http://www.jstor.org/stable/2088224',color:'sociology',text:'1952 Family And Fertility In Puerto Rico, ASR'},
{type:'article',url:'http://www.jstor.org/stable/1029126',color:'general',text:'1953 The Prospects Of Birth Control In Puerto Rico, AAAPSS'},
{type:'name',url:'',color:'info',text:'Joseph S. Davis'},
{type:'article',url:'http://www.jstor.org/stable/2280292',color:'statistics',text:'1950 Population And Resources, JASA'},
{type:'article',url:'http://www.jstor.org/stable/1810382',color:'economics',text:'1952 Our Changed Population Outlook And Its Significance, AER'},
{type:'name',url:'',color:'info',text:'Noel P. Gist'},
{type:'article',url:'http://www.jstor.org/stable/2571590',color:'sociology',text:'1952 I. Directions In Urban Development. Developing Patterns Of Urban Decentralization, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2573536',color:'sociology',text:'1954 Occupational Differentiation In South India, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2088393',color:'sociology',text:'1954 Caste Differentials In South India, ASR'}
];
 var articles = 782;
 var journals = 20;
 var authors = 904;
 var density = 0.29;
 var cjournals = [
{title:'JASA',field: 'statistics',centrality:0.63},
{title:'Milbank',field: 'pubh',centrality:0.58},
{title:'AAAPSS',field: 'general',centrality:0.53},
{title:'ASR',field: 'sociology',centrality:0.53},
{title:'AJS',field: 'sociology',centrality:0.53},
{title:'Pop. Studies',field: 'demography',centrality:0.53},
{title:'Social Forces',field: 'sociology',centrality:0.42},
{title:'Pop. Index',field: 'demography',centrality:0.42},
{title:'JEH',field: 'history',centrality:0.37},
{title:'Human Biology',field: 'eugenics',centrality:0.37},
{title:'PHR',field: 'pubh',centrality:0.26},
{title:'Econ. Dev.',field: 'economics',centrality:0.21},
{title:'Fam. Living',field: 'eugenics',centrality:0.16},
{title:'AER',field: 'economics',centrality:0.11},
{title:'Science',field: 'general',centrality:0.05},
{title:'EHR',field: 'history',centrality:0.05},
{title:'Biometrics',field: 'eugenics',centrality:0.05},
{title:'Actuaries',field: 'statistics',centrality:0.0},
{title:'Econ. Geo.',field: 'geography',centrality:0.0},
{title:'WMQ',field: 'history',centrality:0.0}
];