var cauths = [
{type:'name',url:'',color:'info',text:'Harold F. Dorn'},
{type:'article',url:'http://www.jstor.org/stable/1020380',color:'general',text:'1936 Migration, Reproduction, And Population Adjustment, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/4582385',color:'pubh',text:'1937 The Increase In Average Length Of Life, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4582704',color:'pubh',text:'1938 The Incidence And Future Expectancy Of Mental Disease, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4582596',color:'pubh',text:'1938 The Relative Amount Of Ill-Health In Rural And Urban Communities, PHR'},
{type:'article',url:'http://www.jstor.org/stable/2570804',color:'sociology',text:'1938 Migration And The Growth Of Cities, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2084210',color:'sociology',text:'1939 The Relationship Of Fertility And Longevity, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2279168',color:'statistics',text:'1939 The Natural Decrease Of Population In Certain American Communities, JASA'},
{type:'article',url:'http://www.jstor.org/stable/4582865',color:'pubh',text:'1939 Maternal Mortality In Rural And Urban Areas, PHR'},
{type:'article',url:'http://www.jstor.org/stable/1024420',color:'general',text:'1940 Changes In Infant And Child Mortality Rates, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/4583141',color:'pubh',text:'1940 Mortality Rates And Economic Status In Rural Areas, PHR'},
{type:'article',url:'http://www.jstor.org/stable/2769614',color:'sociology',text:'1942 The Potential Rate Of Increase Of The Population Of The, AJS'},
{type:'article',url:'http://www.jstor.org/stable/4584297',color:'pubh',text:'1942 Changes In Mortality Rates, 1930 To 1940, PHR'},
{type:'name',url:'',color:'info',text:'Irene B. Taeuber'},
{type:'article',url:'http://www.jstor.org/stable/2279062',color:'statistics',text:'1938 Measures Of Changes In Fertility In Germany, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2571084',color:'sociology',text:'1938 Short Distance Interstate Migrations, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2769448',color:'sociology',text:'1940 German Fertility Trends, 1933-39, AJS'},
{type:'article',url:'http://www.jstor.org/stable/1024496',color:'general',text:'1944 Population Displacements In Europe, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3348029',color:'pubh',text:'1944 The Dynamics Of Population In Japan, Milbank'},
{type:'name',url:'',color:'info',text:'Raymond Pearl'},
{type:'article',url:'http://www.jstor.org/stable/3347915',color:'pubh',text:'1936 Third Progress Report On A Study Of Family Limitation, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1020356',color:'general',text:'1936 Biological Factors In Fertility, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/41447296',color:'eugenics',text:'1936 Potential And Actual Reproductive Performance In Man, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/1661752',color:'general',text:'1936 Fertility And Contraception In Urban Whites And Negroes, Science'},
{type:'article',url:'http://www.jstor.org/stable/41447687',color:'eugenics',text:'1937 Variation In Parity Of Women Bearing Children In The U., Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447320',color:'eugenics',text:'1937 Variation In Parity Of Women Bearing Children In The U., Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447408',color:'eugenics',text:'1939 Records Of Total Reproduction, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447458',color:'eugenics',text:'1940 A Comparative Examination Of Certain Aspects Of The Populations Of, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2279474',color:'statistics',text:'1940 The Aging Of Populations, JASA'},
{type:'article',url:'http://www.jstor.org/stable/41447468',color:'eugenics',text:'1940 Pregnancy Rates And Coitus Rates, Human Biology'},
{type:'name',url:'',color:'info',text:'Bernard D. Karpinos'},
{type:'article',url:'http://www.jstor.org/stable/2571253',color:'sociology',text:'1935 The Implications Of Certain Population Concepts, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/41447254',color:'eugenics',text:'1935 A Stationary Population (A Study Of Iowa Population), Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2768960',color:'sociology',text:'1936 The Length Of Time Required For The Stabilization Of A, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2768731',color:'sociology',text:'1938 The Differential True Rates Of Growth Of The White Population, AJS'},
{type:'article',url:'http://www.jstor.org/stable/3347944',color:'pubh',text:'1939 The Differential Fertility And Potential Rates Of Growth Of Various, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4583047',color:'pubh',text:'1939 Stabilized Method Of Forecasting Population, PHR'},
{type:'article',url:'http://www.jstor.org/stable/2769535',color:'sociology',text:'1942 Use Of Nuptial Reproduction Rates In Population Analysis, AJS'},
{type:'name',url:'',color:'info',text:'Dorothy Swaine Thomas'},
{type:'article',url:'http://www.jstor.org/stable/2768001',color:'sociology',text:'1936 Internal Migrations In Sweden, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2279871',color:'statistics',text:'1937 The Analysis Of Internal Migration In The Swedish Census Of, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2084691',color:'sociology',text:'1938 Utilization Of Social Security Data For Sociological Research, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2571333',color:'sociology',text:'1941 Differential Fertility In California In 1930, Social Forces'},
{type:'name',url:'',color:'info',text:'Pascal K. Whelpton'},
{type:'article',url:'http://www.jstor.org/stable/3347962',color:'pubh',text:'1935 Causes Of The Decline In Birth Rates, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1020358',color:'general',text:'1936 Geographic And Economic Differentials In Fertility, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2278370',color:'statistics',text:'1936 An Empirical Method Of Calculating Future Population, JASA'},
{type:'article',url:'http://www.jstor.org/stable/1020382',color:'general',text:'1936 Population Policies Of European Countries, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/1021205',color:'general',text:'1938 Levels Of Living And Population Pressure, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2084526',color:'sociology',text:'1940 Changes In Regional And Urban Patterns Of Population Growth, ASR'},
{type:'article',url:'http://www.jstor.org/stable/1024419',color:'general',text:'1940 Birth Rate Trends And Child Welfare, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3348058',color:'pubh',text:'1943 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348215',color:'pubh',text:'1944 Social And Psychological Factors Affecting Fertility. Part Ii. Variations In, Milbank'},
{type:'name',url:'',color:'info',text:'Conrad Taeuber'},
{type:'article',url:'http://www.jstor.org/stable/3347658',color:'pubh',text:'1938 Constructive Rural Farm Population Policies, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2279062',color:'statistics',text:'1938 Measures Of Changes In Fertility In Germany, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2571084',color:'sociology',text:'1938 Short Distance Interstate Migrations, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2769448',color:'sociology',text:'1940 German Fertility Trends, 1933-39, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2571172',color:'sociology',text:'1943 Effects Of The War On The Agricultural Working Force And, Social Forces'},
{type:'name',url:'',color:'info',text:'Warren S. Thompson'},
{type:'article',url:'http://www.jstor.org/stable/2768338',color:'sociology',text:'1935 Movements Of Population, AJS'},
{type:'article',url:'http://www.jstor.org/stable/1020382',color:'general',text:'1936 Population Policies Of European Countries, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/1021205',color:'general',text:'1938 Levels Of Living And Population Pressure, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2769808',color:'sociology',text:'1939 Some Factors Influencing The Ratios Of Children To Women In, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2084526',color:'sociology',text:'1940 Changes In Regional And Urban Patterns Of Population Growth, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3347878',color:'pubh',text:'1940 Outstanding Population Trends Affecting Problems Of Social Welfare, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1025189',color:'general',text:'1944 Adolescents According To The Census, AAAPSS'},
{type:'name',url:'',color:'info',text:'T. J. Woofter Jr.'},
{type:'article',url:'http://www.jstor.org/stable/2569977',color:'sociology',text:'1935 Southern Population And Social Planning, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/3347856',color:'pubh',text:'1935 The Natural Increase Of The Rural Non-Farm Population, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2571276',color:'sociology',text:'1936 Rural Relief And The Back-To-The-Farm Movement, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/3347761',color:'pubh',text:'1937 Replacement Rates In The Productive Ages, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2279028',color:'statistics',text:'1942 Preliminary Population Estimates Based On Ration Book Applications, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2085132',color:'sociology',text:'1944 Size Of Family In Relation To Family Income And Age, ASR'},
{type:'name',url:'',color:'info',text:'Frederick Osborn'},
{type:'article',url:'http://www.jstor.org/stable/2569978',color:'sociology',text:'1935 Significance Of Differential Reproduction For American Educational Policy, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/1020372',color:'general',text:'1936 Measures Of Quality In The Study Of Population, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2084871',color:'sociology',text:'1937 Development Of A Eugenic Philosophy, ASR'},
{type:'name',url:'',color:'info',text:'Mortimer Spiegelman'},
{type:'article',url:'http://www.jstor.org/stable/1020365',color:'general',text:'1936 The Broken Family-Widowhood And Orphanhood, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2279249',color:'statistics',text:'1940 The Trend Of The Birth Rate By Age Of Mother, JASA'},
{type:'article',url:'http://www.jstor.org/stable/41447514',color:'eugenics',text:'1941 Current Versus Generation Life Tables, Human Biology'},
{type:'name',url:'',color:'info',text:'Robert J. Myers'},
{type:'article',url:'http://www.jstor.org/stable/3347879',color:'pubh',text:'1940 Population Trends And Future Problems Of Child Welfare, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2279748',color:'statistics',text:'1941 The Validity And Significance Of Male Net Reproduction Rates, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2279539',color:'statistics',text:'1943 Comparison Of Demographic Rates Assumed By The National Resources Committee, JASA'},
{type:'article',url:'http://www.jstor.org/stable/41447574',color:'eugenics',text:'1943 Further Note On The Death Rate Among Old-Age Assistance Recipients, Human Biology'},
{type:'name',url:'',color:'info',text:'A. J. Jaffe'},
{type:'article',url:'http://www.jstor.org/stable/2278855',color:'statistics',text:'1939 Religious Differentials In The Net Reproduction Rate, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2769336',color:'sociology',text:'1939 Economic Differentials In The Probability Of Insanity, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2769969',color:'sociology',text:'1942 Urbanization And Fertility, AJS'},
{type:'article',url:'http://www.jstor.org/stable/41447546',color:'eugenics',text:'1942 An Abridged Life Table For The White Population Of The, Human Biology'},
{type:'name',url:'',color:'info',text:'Philip M. Hauser'},
{type:'article',url:'http://www.jstor.org/stable/2279611',color:'statistics',text:'1941 The Use Of Sampling In The Census, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2085929',color:'sociology',text:'1941 Research Possibilities In The 1940 Census, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2279433',color:'statistics',text:'1942 Proposed Annual Sample Census Of Population, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2770088',color:'sociology',text:'1942 Population, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2769089',color:'sociology',text:'1942 Population And Vital Phenomena, AJS'},
{type:'name',url:'',color:'info',text:'Frank Lorimer'},
{type:'article',url:'http://www.jstor.org/stable/1020380',color:'general',text:'1936 Migration, Reproduction, And Population Adjustment, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3347931',color:'pubh',text:'1937 The Significance Of Imminent Population Changes In The United States, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2086072',color:'sociology',text:'1944 Recent Population Trends In The Soviet Union, ASR'},
{type:'name',url:'',color:'info',text:'O. E. Baker'},
{type:'article',url:'http://www.jstor.org/stable/1020379',color:'general',text:'1936 Rural And Urban Distribution Of The Population In The United, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3347717',color:'pubh',text:'1937 Significance Of Population Trends To American Agriculture, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/1814516',color:'economics',text:'1940 Round Table On Population Problems, AER'},
{type:'name',url:'',color:'info',text:'Leon E. Truesdell'},
{type:'article',url:'http://www.jstor.org/stable/1020385',color:'general',text:'1936 Value Of The Population Census For Research, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2767713',color:'sociology',text:'1937 Specimens Of Unpublished Census Data On Fertility, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2278913',color:'statistics',text:'1938 Residual Relationships And Velocity Of Change As Pitfalls In The, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2279610',color:'statistics',text:'1941 New Features Of The 1940 Population Census, JASA'},
{type:'name',url:'',color:'info',text:'Selwyn D. Collins'},
{type:'article',url:'http://www.jstor.org/stable/4581514',color:'pubh',text:'1935 Age Incidence Of Illness And Death Considered In Broad Disease, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4581530',color:'pubh',text:'1935 Relation Of Sickness To Income And Income Change In 10, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3347857',color:'pubh',text:'1935 The Incidence And Causes Of Illness At Specific Ages, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4581474',color:'pubh',text:'1935 A General View Of The Causes Of Illness And Death, PHR'},
{type:'article',url:'http://www.jstor.org/stable/1019539',color:'general',text:'1936 The Health Of The Worker, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/4581808',color:'pubh',text:'1936 History And Frequency Of Smallpox Vaccinations And Cases In 9,000, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4581886',color:'pubh',text:'1936 History And Frequency Of Typhoid Fever Immunizations And Cases In, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4582031',color:'pubh',text:'1936 History And Frequency Of Diphtheria Immunizations And Cases In 9,000, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3347720',color:'pubh',text:'1937 Frequency Of Immunizing And Related Procedures In Nine Thousand Surveyed, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4582485',color:'pubh',text:'1938 History And Frequency Of Clinical Scarlet Fever Cases And Of, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3347649',color:'pubh',text:'1940 A Study Of Illness Among Families In The Eastern Health, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4584222',color:'pubh',text:'1942 Frequency And Volume Of Hospital Care For Specific Diseases In, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4584540',color:'pubh',text:'1943 Extent Of Immunization And Case Histories For Diphtheria , Smallpox, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4585095',color:'pubh',text:'1944 Age And Sex Incidence Of Influenza In The Epidemic Of, PHR'},
{type:'name',url:'',color:'info',text:'Frank W. Notestein'},
{type:'article',url:'http://www.jstor.org/stable/3347626',color:'pubh',text:'1935 Effectiveness Of Birth Control, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2569979',color:'sociology',text:'1935 Factors Affecting Variations In Human Fertility, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/1020357',color:'general',text:'1936 Class Differences In Fertility, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3347823',color:'pubh',text:'1936 The Fertility Of Populations Supported By Public Relief, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347973',color:'pubh',text:'1938 A Demographic Study Of 38,256 Rural Families In China, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347871',color:'pubh',text:'1938 Differential Fertility In The East North Central States, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348055',color:'pubh',text:'1944 Problems Of Policy In Relation To Areas Of Heavy Population, Milbank'},
{type:'name',url:'',color:'info',text:'Joseph J. Spengler'},
{type:'article',url:'http://www.jstor.org/stable/1807805',color:'economics',text:'1935 Malthusianism In Late Eighteenth Century America, AER'},
{type:'article',url:'http://www.jstor.org/stable/2084616',color:'sociology',text:'1936 Population Prediction In Nineteenth Century America, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2571203',color:'sociology',text:'1941 Population Trends And The Future Demand For Teachers, Social Forces'},
{type:'name',url:'',color:'info',text:'Alfred J. Lotka'},
{type:'article',url:'http://www.jstor.org/stable/2278558',color:'statistics',text:'1936 The Geographic Distribution Of Intrinsic Natural Increase In The United, JASA'},
{type:'article',url:'http://www.jstor.org/stable/1020355',color:'general',text:'1936 Modern Trends In The Birth Rate, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/41447689',color:'eugenics',text:'1937 A Historical Error Corrected, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2279123',color:'statistics',text:'1938 Some Recent Results In Population Analysis, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2279249',color:'statistics',text:'1940 The Trend Of The Birth Rate By Age Of Mother, JASA'},
{type:'name',url:'',color:'info',text:'Henry S. Shryock Jr.'},
{type:'article',url:'http://www.jstor.org/stable/1020369',color:'general',text:'1936 Population Estimates In Postcensal Years, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2279612',color:'statistics',text:'1941 General Population Statistics, JASA'},
{type:'article',url:'http://www.jstor.org/stable/3347839',color:'pubh',text:'1942 1940 Census Data On Number Of Years Of School Completed, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2279309',color:'statistics',text:'1943 Internal Migration And The War, JASA'},
{type:'name',url:'',color:'info',text:'E. Franklin Frazier'},
{type:'article',url:'http://www.jstor.org/stable/2768234',color:'sociology',text:'1937 Negro Harlem, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2083813',color:'sociology',text:'1937 The Impact Of Urban Civilization Upon Negro Family Life, ASR'},
{type:'name',url:'',color:'info',text:'Thomas C. Mccormick'},
{type:'article',url:'http://www.jstor.org/stable/2770130',color:'sociology',text:'1938 Fertility-Rates In Wisconsin, 1920-35, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2085761',color:'sociology',text:'1941 Occupational Birth And Marriage Rates, Wisconsin, 1920-1936, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2769054',color:'sociology',text:'1942 Marriage And Divorce Rates In Wisconsin, 1920-35, AJS'},
{type:'name',url:'',color:'info',text:'Edgar M. Hoover Jr.'},
{type:'article',url:'http://www.jstor.org/stable/1019702',color:'general',text:'1937 Industrial Location And The Housing Market, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2113473',color:'history',text:'1941 Interstate Redistribution Of Population, 1850-1940, JEH'},
{type:'name',url:'',color:'info',text:'Paul H. Landis'},
{type:'article',url:'http://www.jstor.org/stable/2768180',color:'sociology',text:'1935 Social Change And Social Interaction As Factors In Culture Change, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2572686',color:'sociology',text:'1943 Internal Migration By Subsidy, Social Forces'},
{type:'name',url:'',color:'info',text:'E. P. Hutchinson'},
{type:'article',url:'http://www.jstor.org/stable/3347916',color:'pubh',text:'1936 Education And Intramarital Fertility In Stockholm, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2084487',color:'sociology',text:'1936 Internal Migration And Tuberculosis Mortality In Sweden, ASR'},
{type:'name',url:'',color:'info',text:'John D. Black'},
{type:'article',url:'http://www.jstor.org/stable/1020373',color:'general',text:'1936 Agricultural Population In Relation To Agricultural Resources, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2278764',color:'statistics',text:'1937 The Counting Of Farms In The United States, JASA'},
{type:'name',url:'',color:'info',text:'Louis J. Ducoff'},
{type:'article',url:'http://www.jstor.org/stable/2571172',color:'sociology',text:'1943 Effects Of The War On The Agricultural Working Force And, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2086026',color:'sociology',text:'1944 What Level Of Living Indexes Measure, ASR'},
{type:'name',url:'',color:'info',text:'Christopher Tietze'},
{type:'article',url:'http://www.jstor.org/stable/3347733',color:'pubh',text:'1939 Differential Reproduction In England, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2769967',color:'sociology',text:'1942 Personality Disorder And Spatial Mobility, AJS'},
{type:'article',url:'http://www.jstor.org/stable/3348129',color:'pubh',text:'1943 Life Tables For Social Classes In England, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2771250',color:'sociology',text:'1943 Differential Reproduction In The United States, AJS'},
{type:'name',url:'',color:'info',text:'Josiah Cox Russell'},
{type:'article',url:'http://www.jstor.org/stable/41447339',color:'eugenics',text:'1937 Length Of Life In England, 1250-1348, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/2571421',color:'sociology',text:'1937 Medieval Population, Social Forces'},
{type:'name',url:'',color:'info',text:'Isidore Altman'},
{type:'article',url:'http://www.jstor.org/stable/3347809',color:'pubh',text:'1940 Certain Characteristics Of Urban Housing And Their Relation To Illness, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4583673',color:'pubh',text:'1941 Illness And Accidents Among Persons Living Under Different Housing Conditions, PHR'},
{type:'name',url:'',color:'info',text:'Robert E. Chaddock'},
{type:'article',url:'http://www.jstor.org/stable/1020371',color:'general',text:'1936 Age And Sex In Population Analysis, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2084872',color:'sociology',text:'1937 Methods Of Estimating Proportional Frequencies Of Divorce, ASR'},
{type:'name',url:'',color:'info',text:'Gilbert W. Beebe'},
{type:'article',url:'http://www.jstor.org/stable/41447370',color:'eugenics',text:'1938 The Effect Of Contraception Upon Human Fertility, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/3347849',color:'pubh',text:'1941 Differential Fertility By Color For Coal Miners In Logan County, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/41447525',color:'eugenics',text:'1942 Control Of Conception In A Selected Rural Sample, Human Biology'},
{type:'name',url:'',color:'info',text:'Halbert L. Dunn'},
{type:'article',url:'http://www.jstor.org/stable/1020386',color:'general',text:'1936 Vital Statistics Collected By The Government, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2279658',color:'statistics',text:'1940 Plans For Vital Statistics In 1940, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2279469',color:'statistics',text:'1940 Census--Past And Future, JASA'},
{type:'article',url:'http://www.jstor.org/stable/2279744',color:'statistics',text:'1941 Problems Concerning The Availability Of Census Data, JASA'},
{type:'name',url:'',color:'info',text:'Dorothy S. Thomas'},
{type:'article',url:'http://www.jstor.org/stable/2085758',color:'sociology',text:'1941 Interstate Migration And Intervening Opportunities, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2278953',color:'statistics',text:'1941 Birth Rates And The Interwar Business Cycles, JASA'},
{type:'name',url:'',color:'info',text:'Regine K. Stix'},
{type:'article',url:'http://www.jstor.org/stable/3347626',color:'pubh',text:'1935 Effectiveness Of Birth Control, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347859',color:'pubh',text:'1935 A Study Of Pregnancy Wastage, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2083819',color:'sociology',text:'1937 Research In Causes Of Variations In Fertility, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3347945',color:'pubh',text:'1939 Birth Control In A Midwestern City, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347642',color:'pubh',text:'1939 Birth Control In A Midwestern City, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347773',color:'pubh',text:'1939 Birth Control In A Midwestern City, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347882',color:'pubh',text:'1940 Factors Underlying Individual And Group Differences In Uncontrolled Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347848',color:'pubh',text:'1941 Contraceptive Service In Three Areas, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347636',color:'pubh',text:'1941 Contraceptive Service In Three Areas, Milbank'},
{type:'name',url:'',color:'info',text:'Bruno Lasker'},
{type:'article',url:'http://www.jstor.org/stable/2572679',color:'sociology',text:'1943 Post-War Migration Problems, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/1024497',color:'general',text:'1944 Displacement Of Population In Eastern Asia, AAAPSS'},
{type:'name',url:'',color:'info',text:'W. L. Holland'},
{type:'article',url:'http://www.jstor.org/stable/1020383',color:'general',text:'1936 Population Problems And Policies In The Far East, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/1818708',color:'economics',text:'1944 Postwar Political Economy Of The Far East And The Pacific, AER'},
{type:'name',url:'',color:'info',text:'Jacob Yerushalmy'},
{type:'article',url:'http://www.jstor.org/stable/4583317',color:'pubh',text:'1940 Studies In Childbirth Mortality, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4583352',color:'pubh',text:'1940 Studies In Childbirth Mortality, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3348206',color:'pubh',text:'1943 The Age-Sex Composition Of The Population Resulting From Natality And, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4584624',color:'pubh',text:'1943 Tuberculosis Mortality In The United States, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4584928',color:'pubh',text:'1944 Births , Infant Mortality , And Maternal Mortality In The, PHR'},
{type:'name',url:'',color:'info',text:'Harold T. Christensen'},
{type:'article',url:'http://www.jstor.org/stable/2769334',color:'sociology',text:'1939 The Time-Interval Between Marriage Of Parents And The Birth Of, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2085044',color:'sociology',text:'1942 Some Factors In Family Fertility Among Selected Wisconsin Farmers, ASR'},
{type:'name',url:'',color:'info',text:'Oliver C. Cox'},
{type:'article',url:'http://www.jstor.org/stable/2084528',color:'sociology',text:'1940 Sex Ratio And Marital Status Among Negroes, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2570846',color:'sociology',text:'1940 Farm Tenancy And Marital Status, Social Forces'},
{type:'name',url:'',color:'info',text:'W. Parker Mauldin'},
{type:'article',url:'http://www.jstor.org/stable/2570980',color:'sociology',text:'1940 A Sample Study Of Migration To Knoxville, Tennessee, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2083697',color:'sociology',text:'1940 Selective Migration From Small Towns, ASR'},
{type:'name',url:'',color:'info',text:'Howard B. Myers'},
{type:'article',url:'http://www.jstor.org/stable/2767710',color:'sociology',text:'1937 Another Census Of Unemployment?, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2279431',color:'statistics',text:'1942 Defense Migration And Labor Supply, JASA'},
{type:'name',url:'',color:'info',text:'C. E. Lively'},
{type:'article',url:'http://www.jstor.org/stable/2768235',color:'sociology',text:'1937 Spatial Mobility Of The Rural Population With Respect To Local, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2570601',color:'sociology',text:'1937 Spatial And Occupational Changes Of Particular Significance To The Student, Social Forces'},
{type:'name',url:'',color:'info',text:'Henry Pratt Fairchild'},
{type:'article',url:'http://www.jstor.org/stable/1020381',color:'general',text:'1936 International Migration, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/1023069',color:'general',text:'1943 Family Limitation And The War, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2572372',color:'sociology',text:'1944 Postwar Population Problems, Social Forces'},
{type:'name',url:'',color:'info',text:'Dudley Kirk'},
{type:'article',url:'http://www.jstor.org/stable/3347751',color:'pubh',text:'1942 The Relation Of Employment Levels To Births In Germany, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2086020',color:'sociology',text:'1944 Population Changes And The Postwar World, ASR'},
{type:'name',url:'',color:'info',text:'Samuel A. Stouffer'},
{type:'article',url:'http://www.jstor.org/stable/2767871',color:'sociology',text:'1935 Trends In The Fertility Of Catholics And Non-Catholics, AJS'},
{type:'article',url:'http://www.jstor.org/stable/1020359',color:'general',text:'1936 Marriage And Divorce In Recent Years, AAAPSS'},
{type:'name',url:'',color:'info',text:'John N. Webb'},
{type:'article',url:'http://www.jstor.org/stable/2767710',color:'sociology',text:'1937 Another Census Of Unemployment?, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2279314',color:'statistics',text:'1943 Practical Applications Of Theoretical Sampling Methods, JASA'},
{type:'name',url:'',color:'info',text:'G. St. J. Perrott'},
{type:'article',url:'http://www.jstor.org/stable/4581530',color:'pubh',text:'1935 Relation Of Sickness To Income And Income Change In 10, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3347671',color:'pubh',text:'1937 Urban Differential Fertility During The Depression, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4584644',color:'pubh',text:'1943 The War And The Distribution Of Physicians, PHR'},
{type:'name',url:'',color:'info',text:'Horace Miner'},
{type:'article',url:'http://www.jstor.org/stable/2770127',color:'sociology',text:'1938 Changes In Rural French-Canadian Culture, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2084689',color:'sociology',text:'1938 The French-Canadian Family Cycle, ASR'},
{type:'name',url:'',color:'info',text:'Antonio Ciocco'},
{type:'article',url:'http://www.jstor.org/stable/41447350',color:'eugenics',text:'1938 Variation In The Sex Ratio At Birth In The United, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447361',color:'eugenics',text:'1938 The Masculinity Of Stillbirths And Abortions In Relation To The, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447693',color:'eugenics',text:'1940 The Trend In The Proportional Contribution Of The Socio-Economic Groups, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447466',color:'eugenics',text:'1940 On The Mortality In Husbands And Wives, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447440',color:'eugenics',text:'1940 Studies On The Biological Factors In Public Health, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447496',color:'eugenics',text:'1941 On The Mortality In Brother-Sister And Husband-Wife Pairings, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447506',color:'eugenics',text:'1941 Cardiovascular Diseases Mortality In A Sample Of White Males And, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447517',color:'eugenics',text:'1941 On The Interdependence Of The Length Of Life Of Husband, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/41447477',color:'eugenics',text:'1941 Parity Order Of Birth , Age Of Mother , And, Human Biology'},
{type:'article',url:'http://www.jstor.org/stable/4584207',color:'pubh',text:'1942 Data On The Concurrence Of Death From Tuberculosis , Influenza, PHR'},
{type:'name',url:'',color:'info',text:'Newton Edwards'},
{type:'article',url:'http://www.jstor.org/stable/1022136',color:'general',text:'1937 Youth As A Population Element, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/3347880',color:'pubh',text:'1940 Population Trends And Problems Of Education, Milbank'},
{type:'name',url:'',color:'info',text:'Paul C. Glick'},
{type:'article',url:'http://www.jstor.org/stable/2770130',color:'sociology',text:'1938 Fertility-Rates In Wisconsin, 1920-35, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2085763',color:'sociology',text:'1941 Types Of Families, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2085045',color:'sociology',text:'1942 Family Trends In The United States, 1890 To 1940, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2085880',color:'sociology',text:'1943 Family Status Of Men Of Military Age, ASR'},
{type:'name',url:'',color:'info',text:'Elbridge Sibley'},
{type:'article',url:'http://www.jstor.org/stable/2085361',color:'sociology',text:'1942 Some Demographic Clues To Stratification, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2570883',color:'sociology',text:'1942 Fertility In A Greenbelt Community, Social Forces'},
{type:'name',url:'',color:'info',text:'Bruce L. Melvin'},
{type:'article',url:'http://www.jstor.org/stable/2571273',color:'sociology',text:'1936 Extension In Relation To Research In Rural Sociology, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/1022138',color:'general',text:'1937 The Special Problems Of Rural Youth, AAAPSS'},
{type:'article',url:'http://www.jstor.org/stable/2570920',color:'sociology',text:'1938 Taking Stock Of Rural Youth, Social Forces'},
{type:'name',url:'',color:'info',text:'Rollo H. Britten'},
{type:'article',url:'http://www.jstor.org/stable/4583023',color:'pubh',text:'1939 The National Health Survey, PHR'},
{type:'article',url:'http://www.jstor.org/stable/3347809',color:'pubh',text:'1940 Certain Characteristics Of Urban Housing And Their Relation To Illness, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/4583673',color:'pubh',text:'1941 Illness And Accidents Among Persons Living Under Different Housing Conditions, PHR'},
{type:'article',url:'http://www.jstor.org/stable/4584234',color:'pubh',text:'1942 The Incidence Of Pneumonia As Recorded In The National Health, PHR'},
{type:'name',url:'',color:'info',text:'Alexander Stevenson'},
{type:'article',url:'http://www.jstor.org/stable/2085041',color:'sociology',text:'1942 Some Aspects Of Fertility And Population Growth In Vienna, ASR'},
{type:'article',url:'http://www.jstor.org/stable/3348060',color:'pubh',text:'1943 Maternal Mortality And Length Of Life, Milbank'},
{type:'name',url:'',color:'info',text:'Charles S. Johnson'},
{type:'article',url:'http://www.jstor.org/stable/2571016',color:'sociology',text:'1941 The Place And Importance Of Population Studies In Relation To, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/1023779',color:'general',text:'1942 The Negro Minority, AAAPSS'},
{type:'name',url:'',color:'info',text:'Willystine Goodsell'},
{type:'article',url:'http://www.jstor.org/stable/2767666',color:'sociology',text:'1936 The Size Of Families Of College And Non-College Women, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2084872',color:'sociology',text:'1937 Methods Of Estimating Proportional Frequencies Of Divorce, ASR'},
{type:'name',url:'',color:'info',text:'Rupert B. Vance'},
{type:'article',url:'http://www.jstor.org/stable/2570769',color:'sociology',text:'1939 The Geography Of Distinction, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/3347794',color:'pubh',text:'1941 The Regional Approach To The Study Of High Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2571446',color:'sociology',text:'1943 Human Resources And Public Policy, Social Forces'},
{type:'name',url:'',color:'info',text:'Sanford Winston'},
{type:'article',url:'http://www.jstor.org/stable/2767922',color:'sociology',text:'1935 Cultural Participation And The Negro, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2767669',color:'sociology',text:'1936 The Mobility Of Eminent Americans, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2084363',color:'sociology',text:'1937 Bio-Social Characteristics Of American Inventors, ASR'},
{type:'name',url:'',color:'info',text:'Jitsuichi Masuoka'},
{type:'article',url:'http://www.jstor.org/stable/2769449',color:'sociology',text:'1940 The Structure Of The Japanese Family In Hawaii, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2572383',color:'sociology',text:'1944 The Life Cycle Of An Immigrant Institution In Hawaii, Social Forces'},
{type:'name',url:'',color:'info',text:'Radhakamal Mukerjee'},
{type:'article',url:'http://www.jstor.org/stable/2085759',color:'sociology',text:'1941 Population Theory And Politics, ASR'},
{type:'article',url:'http://www.jstor.org/stable/2571332',color:'sociology',text:'1941 New Approaches To Population, Social Forces'},
{type:'name',url:'',color:'info',text:'Clyde V. Kiser'},
{type:'article',url:'http://www.jstor.org/stable/3347964',color:'pubh',text:'1935 Fertility Of Harlem Negroes, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/2569979',color:'sociology',text:'1935 Factors Affecting Variations In Human Fertility, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/3347784',color:'pubh',text:'1936 Recent Trends In Birth Rates Among Foreign And Native-White Married, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347935',color:'pubh',text:'1937 Recent Analyses Of Marriage Rates, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347670',color:'pubh',text:'1937 Trends In Annual Birth Rates Among Married Women In Selected, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347952',color:'pubh',text:'1938 Birth Rates Among Rural Migrants In Cities, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347972',color:'pubh',text:'1938 Variations In Birth Rates According To Occupational Status , Family, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347772',color:'pubh',text:'1939 Voluntary And Involuntary Aspects Of Childlessness, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347944',color:'pubh',text:'1939 The Differential Fertility And Potential Rates Of Growth Of Various, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347641',color:'pubh',text:'1939 Birth Rates And Socio-Economic Attributes In 1935, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347900',color:'pubh',text:'1941 Social Implications Of The Under-Developed Family, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347847',color:'pubh',text:'1941 Intra-Group Differences In Birth Rates Of Married Women, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347852',color:'pubh',text:'1941 Net Reproduction Rates, 1930-1940, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348058',color:'pubh',text:'1943 Social And Psychological Factors Affecting Fertility, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3347987',color:'pubh',text:'1944 Implications Of Population Trends For Postwar Policy, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348215',color:'pubh',text:'1944 Social And Psychological Factors Affecting Fertility. Part Ii. Variations In, Milbank'},
{type:'article',url:'http://www.jstor.org/stable/3348053',color:'pubh',text:'1944 The Demographic Position Of Egypt, Milbank'},
{type:'name',url:'',color:'info',text:'Margaret J. Hagood'},
{type:'article',url:'http://www.jstor.org/stable/2570700',color:'sociology',text:'1939 An Examination Of Regional Differentials In Fertility By Analysis Of, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2571172',color:'sociology',text:'1943 Effects Of The War On The Agricultural Working Force And, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2086026',color:'sociology',text:'1944 What Level Of Living Indexes Measure, ASR'},
{type:'name',url:'',color:'info',text:'Lowry Nelson'},
{type:'article',url:'http://www.jstor.org/stable/2570770',color:'sociology',text:'1939 Distribution And Extent Of Unemployment Among Farm Laborers In The, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2085404',color:'sociology',text:'1942 Distribution , Age , And Mobility Of Minnesota Physicians ,, ASR'},
{type:'name',url:'',color:'info',text:'William F. Ogburn'},
{type:'article',url:'http://www.jstor.org/stable/2768365',color:'sociology',text:'1935 Recent Changes In Marriage, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2768784',color:'sociology',text:'1936 Independent Voting In Presidential Elections, AJS'},
{type:'article',url:'http://www.jstor.org/stable/2570461',color:'sociology',text:'1936 Regions, Social Forces'},
{type:'name',url:'',color:'info',text:'Mapheus Smith'},
{type:'article',url:'http://www.jstor.org/stable/2570774',color:'sociology',text:'1939 An Examination Of Some Of A. G. SüNdbäRgS Hypotheses Of, Social Forces'},
{type:'article',url:'http://www.jstor.org/stable/2085226',color:'sociology',text:'1943 Some Relationships Between Intelligence And Geographical Mobility, ASR'}
];
 var articles = 702;
 var journals = 19;
 var authors = 657;
 var density = 0.21;
 var cjournals = [
{title:'AAAPSS',field: 'general',centrality:0.56},
{title:'Milbank',field: 'pubh',centrality:0.5},
{title:'JASA',field: 'statistics',centrality:0.44},
{title:'Social Forces',field: 'sociology',centrality:0.44},
{title:'PHR',field: 'pubh',centrality:0.39},
{title:'Human Biology',field: 'eugenics',centrality:0.39},
{title:'ASR',field: 'sociology',centrality:0.39},
{title:'AJS',field: 'sociology',centrality:0.39},
{title:'Science',field: 'general',centrality:0.22},
{title:'AER',field: 'economics',centrality:0.22},
{title:'JEH',field: 'history',centrality:0.06},
{title:'Actuaries',field: 'statistics',centrality:0.0},
{title:'Living',field: 'eugenics',centrality:0.0},
{title:'Fam. Living',field: 'eugenics',centrality:0.0},
{title:'Pop. Index',field: 'demography',centrality:0.0},
{title:'EHR',field: 'history',centrality:0.0},
{title:'Econ. Geo.',field: 'geography',centrality:0.0},
{title:'Biometrika',field: 'eugenics',centrality:0.0},
{title:'Genus',field: 'eugenics',centrality:0.0}
];