<!--

document.getElementById("pcontent")
.innerHTML =
'The network diagrams reveal the contours of the field of population studies during the twentieth century. As with all of the other visualizations presented in this website, however, they obscure (at least) as much as they reveal. First, the limitation of the analysis to networks that include at least one PAA president means that we are considering only the field of demography as defined by the <a class="content" href="../paa/paa.html">Population Association of America</a>, and as practiced by its most prominent members. Including other prominent figures in public and scholarly discussion of population, such as biologists Paul Ehrlich and Garrett Hardin, allows me to examine their connections to the field of demography as the field was institutionalized during the twentieth century, though I find that they are always on the margins of the network, if they appear at all, suggesting that, although they were talking about human population growth, they were participating in a very different conversation. The division of the century into decades is an arbitrary choice; the networks would certainly look very different with an alternate periodization. The following briefly describes the journal and author networks by decade.\
<dl>\
<dt>1925-1934</dt>\
<dd>\
<dl>\
<dt><a class="content" href="jnet1925.html">Journal Networks</a></dt>\
<dd>Between 1925 and 1934, most of the existing journals in the sample are linked to one another. Only <i>Science</i>, <i>Biometrika</i>, and <i>Transactions of the Faculty of Actuaries (TFA)</i> are separate. The majority of population articles are published in <i>Public Health Reports (PHR)</i>, which shares authors with <i>Human Biology</i>, a journal established in 1929 by biologist and eugenicist Raymond Pearl, with the <i>Milbank Memorial Fund Quarterly (MMFQ)</i>, a public-health oriented philanthropy in New York that established a population program within its research division in 1928, and with the <i>Journal of the American Statistical Association (JASA)</i>. <i>JASA</i> is at the center of the network of population studies publications in this decade, reflecting the fact that both mathematical statistics and demography grew out of the older discipline of statistics (state-istics), which focused on collecting information about states and their inhabitants. The <i>American Journal of Sociology (AJS)</i> and <i>Social Forces</i> have many common authors, as expected, and these journals also share authors with the journals discussed above. They also have ties to the <i>Annals of the American Academy of Political and Social Sciences (AAAPS)</i>, as do <i>JASA</i> and <i>Human Biology</i>, and this general, interdisciplinary journal may have provided a forum for scholars from different disciplines to read one another\'s work on population and as an outlet for population science to reach a broader audience.</dd>\
<dt><a class="content" href="anet1925.html">Author Networks</a></dt>\
<dd>The small size of the author network between 1925 and 1934 does not necessarily indicate that the field was small, but does indicate that the field was not tightly connected around those who would become president of PAA. Nonetheless, it does show that some future presidents of PAA (established 1931) were already connected with one another.  Here we see two small groups forming. The first, centered on Louis Dublin, also includes his Metropolitan Life Insurance colleague Alfred J. Lotka; Frank Lorimer, then a student at Columbia University; and Pascal K. Whelpton of the Scripps Foundation for Research in Population Problems at Miami University in Ohio. The other group centers on Frank Notestein, then a researcher at the Milbank Memorial Fund, and includes his Milbank colleagues Clyde V. Kiser and Edgar Sydenstricker. While the work of Dublin\'s cluster focused on population accounting, including work by Dublin and Lotka on the stable population model and by Whelpton on population projection, Notestein\'s focused on the social correlates of fertility and on the prevalence and efficacy of birth control.</dd>\
</dl>\
<dt>1935-1944</dt>\
<dd>\
<dl>\
<dt><a class="content" href="jnet1935.html">Journal Networks</a></dt>\
<dd>In 1935-1944, the same strong links are apparent between the </i>AAAPS</i>, <i>AJS</i>, <i>Social Forces</i>, <i>MMFQ</i>, and <i>JASA</i>, now with the new <i>American Sociological Review (ASR)</i> also part of this tight cluster. These journals are still connected to <i>Human Biology</i> and <i>PHR</i>. <i>TFA</i> remains unconnected, as does <i>Biometrika</i>, the British journal of eugenics directed by Karl Pearson. Two new eugenics journals also appear, unconnected to any others: <i>Genus</i>, established by Corrado Gini, and <i>Living/Family Living</i>, established by Paul Popenoe. We also see the first demography journal, <i>Population Index</i>, the organ of the PAA</i>, published by Princeton University\'s new Office of Population Research (OPR). <i>Population Index</i> is unconnected, largely because it was mainly a bibliography and had few research articles. Those it did have were unsigned, but most were authored by the journal\'s editor, OPR research associate Irene Taeuber. <i>Science</i> is now connected to some of the other journals, suggesting a wider audience for the work of demography.</dd>\
<dt><a class="content" href="anet1935.html">Author Networks</a></dt>\
<dd>In 1935-1944, elements from the two clusters in the previous decade have now merged into a single cluster centered on Kiser at Milbank. This cluster includes Whelpton and his Scripps colleague Warren S. Thompson, as well as Notestein, who became director of OPR on its establishment in 1936. Lotka and Dublin have split off from this cluster, as has Lorimer, who is now connected to Harold Dorn. The largest component in this decade, however, is focused on Conrad Taeuber, Irene\'s husband, who worked at the Census Bureau. He is connected to Irene, but the two have no mutual co-authors, with Conrad connected to other Census people and Irene to other academic people.</dd>\
</dl>\
<dt>1945-1954</dt>\
<dd>\
<dl>\
<dt><a class="content" href="jnet1945.html">Journal Networks</a></dt>\
<dd>In 1945-1954, <i>JASA</i>, <i>AAAPSS</i>, and the sociology journals (<i>AJS</i>, <i>ASR</i>, and <i>Social Forces</i>) are still at the center of the field, but have now been joined by <i>Population Index</i> and the new <i>Population Studies</i> (established 1947), suggesting that scholarship in these demography journals was in conversation with that previously published in the sociology, statistics, and public health journals. <i>Human Biology</i> is still connected to this cluster, and <i>Family Living</i> is now connected as well. During this decade, Irene Taeuber is one of the most central authors, publishing in <i>JASA</i>, <i>AAAPS</i>, <i>MMFQ</i>, <i>Population Index</i>, <i>Population Studies</i>, <i>ASR</i>, and the <i>Journal of Economic History (JEH).</i></dd>\
<dt><a class="content" href="anet1945.html">Author Networks</a></dt>\
<dd>Irene Taeuber also appears at the center of the author network in 1945-1954, connected to Notestein at OPR and to Hope Eldridge at the Census, who ties Taeuber to several other Census figures, including Conrad Taeuber, Philip Hauser, Henry Shryock, Jacob Siegel, Margaret Hagood, and Horace Hamilton. We also see a cluster forming around Kiser and Whelpton, who published several articles, together and separately, analyzing the results of the 1941 Indianapolis Fertility Survey. This group includes Ronald Freedman, who worked with Whelpton at Scripps, Charles Westoff, who had joined OPR, and Amos Hawley, of the University of Michigan.</dd>\
</dl>\
<dt>1955-1964</dt>\
<dd>\
<dl>\
<dt><a class="content" href="jnet1955.html">Journal Networks</a></dt>\
<dd>In 1955-1964, we see the same tight cluster of journals at the center of the field, now with <i>Population Studies</i> equaling <i>AJS</i> in centrality. The new journal <i>Demography</i> (established 1964) has appeared, and is already quite central to the field, despite arriving on the scene only at the end of this decade. <i>Family Living</i> is now much more tightly connected to the other journals, as is the new <i>Economic Development and Cultural Change</i>. <i>Genus</i> is now connected as well. We also see the first family planning journal, <i>Studies in Family Planning</i>, published by the Population Council, which is connected to several other journals in the network.</dd>\
<dt><a class="content" href="anet1955.html">Author Networks</a></dt>\
<dd>The author network for 1955-1964 looks very different than in earlier decades. It now has a very prominent central component, which is markedly larger (106 nodes as compared with 8 nodes for the next largest component), and much less dense than the other components. This large component, centered around fertility researchers associated with the Population Council (such as Ronald Freedman, J. Mayone Stycos, Carmen Miro, Pascal Whelpton, and Donald Bogue) and publishing mainly in demography journals, signals the centrality of fertility to the field. This component also includes Kingsley Davis and Judith Blake, then at Berkeley, who would, in the next decade, become openly critical of the Population Council\'s fertility research and intervention programs.</dd>\
</dl>\
<dt>1965-1974</dt>\
<dd>\
<dl>\
<dt><a class="content" href="jnet1965.html">Journal Networks</a></dt>\
<dd>Between 1965 and 1974, <i>Population Studies</i> and <i>Demography</i> are at the center of the network, with continued strong ties to the sociology and public health journals, but weakening ties with <i>Human Biology</i> and <i>JASA</i>, reflecting the establishment of population studies centers at U.S. universities, themselves with strong ties to departments of sociology and schools of public health. <i>Economic Development and Cultural Change</i> remains closely tied to the journals at the center, and <i>Science</i> is much more central than it previously had been, reflecting public debates between Kingsley Davis and the demographers more closely aligned with the Population Council, and reflecting increased interest among the public and among other scientists in population. In this decade, we see the emergence of the field of historical demography, with the journals <i>Social History</i>, <i>Economic History Review</i>, <i>Journal of Interdisciplinary History</i>, and <i>Journal of Economic History</i> appearing on the edges of the network. <i>Studies in Family Planning</i> is now very central in the field, and has been joined by another family planning journal, <i>Family Planning Perspectives</i>, published by the Guttmacher Institute. The centrality of these journals reflects the fact that many of the same people were writing for both these journals and the demography journals, and the fact that funding for demography and family planning research largely came from the same sources. <i>Family Living</i> has become the <i>Journal of Marriage and Family (JMF)</i>, and is now more closely aligned with demography than with eugenics. The journal <i>International Migration Review</i> has appeared at the edge of the demography cluster, reflecting both the marginality of migration in the field of demography and the fact that its publisher, the <a class="content" href="http://cmsny.org">Center for Migration Studies</a> had a very different political orientation than did the <a class="content" href="http://www.popcouncil.org">Population Council</a>, publisher of <i>Studies in Family Planning</i>, and the <a class="content" href="http://www.fordfoundation.org">Ford Foundation</a>, publisher of <i>Demography</i>. </dd>\
<dt><a class="content" href="anet1965.html">Author Networks</a></dt>\
<dd>In 1965-1974, we see the same large low-density cluster at the center of the network that we saw in the previous decade, though it has now more than tripled in size. At the center of this cluster are several PAA presidents, including Donald J. Bogue, Ronald Freedman, Philip M. Hauser, Reynolds Farley, Charles f. Westoff, Paul C. Glick, Norman B. Ryder, Frank W. Notestein, Irene B. Taeuber, and Arthur A. Campbell, reflecting the tight connections at the core of this newly-established discipline. The network still includes Kingsley Davis and Judith Blake, despite their harsh criticism of mainstream demography and family planning toward the end of the decade. The majority of members of this cluster publish in demography and family planning journals, reflecting the prevalence of co-authorship in these fields and the overlap of these fields with one another. Those who publish primarily in demography journals are closer to the center of the cluster and those who publish primarily in family planning journals farther to the edges, reflecting the higher prestige of demography.</dd>\
</dl>\
<dt>1975-1984</dt>\
<dd>\
<dl>\
<dt><a class="content" href="jnet1975.html">Journal Networks</a></dt>\
<dd>Between 1975 and 1984, demography journals and family planning journals are clearly at the center of the network, reflecting the growth of demography and its continued close ties with family planning research. Two new demography journals in this decade are <i>Population and Development Review</i>, published by the Population Council beginning in 1975, and <i>Population Research and Policy Review</i>. Also central are <i>Economic Development and Cultural Change</i>, reflecting demography\'s orientation toward economic development, and <i>ASR</i>, reflecting the field\'s continued close ties to the discipline of sociology. <i>Human Biology</i> and <i>Genus</i> are still closely connected to the center of the network. Historical demography is larger and more clustered within itself, and two new journals have joined the field: <i>William and Mary Quarterly</i> and <i>Social Science History</i>.</dd>\
<dt><a class="content" href="anet1975.html">Author Networks</a></dt>\
<dd>In 1975-1984 the cluster of fertility scholars at the center of the field has grown even larger and less dense, and the field of family planning is more strongly represented, reflecting the same trends seen in the previous decade. Some figures who had been part of that cluster in the past have now moved into smaller clusters or are on their own, including Davis, who had begun to turn toward environmental issues; Blake, who turned toward health; Nathan Keyfitz, who focused on formal demography; and Douglas Massey, who focused on immigration. Notestein is now unconnected on the edge of the network, likely reflecting his retirement.</dd>\
</dl>\
<dt>1985-1994</dt>\
<dd>\
<dl>\
<dt><a class="content" href="jnet1985.html">Journal Networks</a></dt>\
<dd>In 1985-1994 the demography journals are still at the center of the network, but the field has begun to diversify, as indicated by more specialized population journals, such as <i>Population Economics</i> and <i>Population and Environment</i>. <i>Genus</i> and <i>Human Biology</i> are still central, reflecting the field\'s continued ties to eugenics. The sociology journals are also still central and, in this period, demography became more closely aligned with sociology, as reflected in the disciplinary orientations of PAA presidents. Historical demography still has a presence, though it is still on the edge of the network.</dd>\
<dt><a class="content" href="anet1985.html">Author Networks</a></dt>\
<dd>The diversification of the field represented in the journal network for this decade is not apparent in the author network, where the central component has grown to over 1400 members and no other component has more than three. However, this large cluster is very diffuse, and perhaps reflects the field as a whole rather than a faction within it.</dd>\
</dl>\
<dt>1995-2004</dt>\
<dd>\
<dl>\
<dt><a class="content" href="jnet1995.html">Journal Networks</a></dt>\
<dd>The final decade of this analysis exhibits the same trends as the previous decade. The demography journals now comprise the bulk of the field and its center, but are still tightly tied to family planning journals and sociology journals. Public health journals are much less central to the field than they were at its beginning: <i>MMFQ</i> stopped publishing on demography after Clyde Kiser\'s retirement in 1971, and the marginality of <i>Public Health Reports</i> in the network indicates weakened ties between scholars in public health and those in mainstream demography, though public health scholars continue to use demographic methods and attend PAA meetings. The general journals are still quite central, reflecting continued interest among scientists more broadly in population, and the historical demography journals continue their presence on the edge of the field.</dd>\
<dt><a class="content" href="anet1995.html">Author Networks</a></dt>\
<dd>In this final decade, the author network also shows a continuation of earlier trends, with the central component growing larger and more diffuse and the other components growing smaller in both number and size. In contrast to the 1965-1974 network, where PAA presidents were at the center of the cluster, in the 1995-2004 network, PAA presidents are dispersed throughout the cluster, with smaller clusters forming around them. This pattern suggests both the diversification of the field and the persistence of tight connections within it.</dd>\
</dl>\
</dl>\
What we see in these networks is the establishment of an interdiscipline, or possibly two interdisciplines if we consider family planning studies as a separate field. At the beginning of the period, individual scholars and small groups published population-oriented research in a number of different disciplinary journals, all in conversation with one another. Over the period, with strong encouragement and funding from such organizations as the Population Council and the Ford Foundation, specifically population-oriented and family-planning-oriented journals came to occupy the center of this conversation, and the scholars publishing in those journals clustered together and then spread out again, forming a diffuse interdisciplinary network.'
    
-->