var paapres = [{name:'Henry Pratt Fairchild',field:'sociology',syear:1931,eyear:1935,affil:'other'},
{name:'Louis Dublin',field:'statistics',syear:1935,eyear:1936,affil:'industry'},
{name:'Warren Thompson',field:'sociology',syear:1936,eyear:1938,affil:'foundation'},
{name:'Alfred J. Lotka',field:'biology',syear:1938,eyear:1939,affil:'industry'},
{name:'Leon Truesdell',field:'statistics',syear:1939,eyear:1940,affil:'government'},
{name:'T.J. Woofter Jr.',field:'sociology',syear:1940,eyear:1941,affil:'government'},
{name:'Pascal Whelpton',field:'economics',syear:1941,eyear:1942,affil:'foundation'},
{name:'Lowell J. Reed',field:'biology',syear:1942,eyear:1945,affil:'popcent'},
{name:'Frank Hankins',field:'sociology',syear:1945,eyear:1946,affil:'other'},
{name:'Frank Lorimer',field:'sociology',syear:1946,eyear:1947,affil:'other'},
{name:'Frank W. Notestein',field:'statistics',syear:1947,eyear:1948,affil:'popcent'},
{name:'Conrad Taeuber',field:'sociology',syear:1948,eyear:1949,affil:'government'},
{name:'Frederick Osborn',field:'none',syear:1949,eyear:1950,affil:'foundation'},
{name:'Philip M. Hauser',field:'sociology',syear:1950,eyear:1951,affil:'popcent'},
{name:'Rupert Vance',field:'economics',syear:1951,eyear:1952,affil:'popcent'},
{name:'Clyde Kiser',field:'sociology',syear:1952,eyear:1953,affil:'foundation'},
{name:'Irene Taeuber',field:'sociology',syear:1953,eyear:1954,affil:'popcent'},
{name:'Margaret J. Hagood',field:'sociology',syear:1954,eyear:1955,affil:'government'},
{name:'Henry Shryock Jr.',field:'sociology',syear:1955,eyear:1956,affil:'government'},
{name:'Joseph J. Spengler',field:'economics',syear:1956,eyear:1957,affil:'other'},
{name:'Harold F. Dorn',field:'sociology',syear:1957,eyear:1958,affil:'government'},
{name:'Dorothy S. Thomas',field:'economics',syear:1958,eyear:1959,affil:'popcent'},
{name:'Dudley Kirk',field:'sociology',syear:1959,eyear:1960,affil:'foundation'},
{name:'C. Horace Hamilton',field:'sociology',syear:1960,eyear:1961,affil:'popcent'},
{name:'John D. Durand',field:'economics',syear:1961,eyear:1962,affil:'popcent'},
{name:'Kingsley Davis',field:'sociology',syear:1962,eyear:1963,affil:'popcent'},
{name:'Donald J. Bogue',field:'sociology',syear:1963,eyear:1964,affil:'popcent'},
{name:'Ronald Freedman',field:'sociology',syear:1964,eyear:1965,affil:'popcent'},
{name:'Calvin F. Schmid',field:'sociology',syear:1965,eyear:1966,affil:'government'},
{name:'Paul Glick',field:'sociology',syear:1966,eyear:1967,affil:'government'},
{name:'Ansley J. Coale',field:'economics',syear:1967,eyear:1968,affil:'popcent'},
{name:'Otis Dudley Duncan',field:'sociology',syear:1968,eyear:1969,affil:'popcent'},
{name:'Everett S. Lee',field:'sociology',syear:1969,eyear:1970,affil:'other'},
{name:'Nathan Keyfitz',field:'sociology',syear:1970,eyear:1971,affil:'popcent'},
{name:'Amos H. Hawley',field:'sociology',syear:1971,eyear:1972,affil:'popcent'},
{name:'Norman B. Ryder',field:'sociology',syear:1972,eyear:1973,affil:'popcent'},
{name:'Arthur A. Campbell',field:'sociology',syear:1973,eyear:1974,affil:'government'},
{name:'Charles F. Westoff',field:'sociology',syear:1974,eyear:1975,affil:'popcent'},
{name:'Sidney Goldstein',field:'sociology',syear:1975,eyear:1976,affil:'popcent'},
{name:'Evelyn Kitagawa',field:'sociology',syear:1976,eyear:1977,affil:'popcent'},
{name:'Richard Easterlin',field:'economics',syear:1977,eyear:1978,affil:'popcent'},
{name:'Charles B. Nam',field:'sociology',syear:1978,eyear:1979,affil:'other'},
{name:'Jacob S. Siegel',field:'sociology',syear:1979,eyear:1980,affil:'government'},
{name:'Judith Blake',field:'sociology',syear:1980,eyear:1981,affil:'popcent'},
{name:'John F. Kantner',field:'sociology',syear:1981,eyear:1982,affil:'popcent'},
{name:'George J. Stolnitz',field:'economics',syear:1982,eyear:1983,affil:'government'},
{name:'Samuel H. Preston',field:'economics',syear:1983,eyear:1984,affil:'popcent'},
{name:'Jane A. Menken',field:'sociology',syear:1984,eyear:1985,affil:'popcent'},
{name:'Paul Demeny',field:'economics',syear:1985,eyear:1986,affil:'foundation'},
{name:'Ronald Lee',field:'economics',syear:1986,eyear:1987,affil:'popcent'},
{name:'Reynolds Farley',field:'sociology',syear:1987,eyear:1988,affil:'popcent'},
{name:'Harriet B. Presser',field:'sociology',syear:1988,eyear:1989,affil:'popcent'},
{name:'Larry L. Bumpass',field:'sociology',syear:1989,eyear:1990,affil:'popcent'},
{name:'Ronald R. Rindfuss',field:'sociology',syear:1990,eyear:1991,affil:'popcent'},
{name:'Etienne Van de Walle',field:'sociology',syear:1991,eyear:1992,affil:'popcent'},
{name:'Albert I. Hermalin',field:'sociology',syear:1992,eyear:1993,affil:'popcent'},
{name:'J. Richard Udry',field:'sociology',syear:1993,eyear:1994,affil:'popcent'},
{name:'Linda J. Waite',field:'sociology',syear:1994,eyear:1995,affil:'popcent'},
{name:'Douglas S. Massey',field:'sociology',syear:1995,eyear:1996,affil:'popcent'},
{name:'Karen O. Mason',field:'sociology',syear:1996,eyear:1997,affil:'popcent'},
{name:'Anne R. Pebley',field:'sociology',syear:1997,eyear:1998,affil:'popcent'},
{name:'Andrew J. Cherlin',field:'sociology',syear:1998,eyear:1999,affil:'popcent'},
{name:'Suzanne M. Bianchi',field:'sociology',syear:1999,eyear:2000,affil:'popcent'},
{name:'Arland Thornton',field:'sociology',syear:2000,eyear:2001,affil:'popcent'},
{name:'Marta Tienda',field:'sociology',syear:2001,eyear:2002,affil:'popcent'},
{name:'S. Philip Morgan',field:'sociology',syear:2002,eyear:2003,affil:'popcent'},
{name:'Sara McLanahan',field:'sociology',syear:2003,eyear:2004,affil:'popcent'},
{name:'Charles Hirschman',field:'sociology',syear:2004,eyear:2005,affil:'popcent'},
{name:'Alberto Palloni',field:'sociology',syear:2005,eyear:2006,affil:'popcent'}
];